### ISSUE TITLE
Add TokenScript branding to bottom of Settings screen

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1053]
Notice the extra empty vertical margin at the bottom

<img src="https://user-images.githubusercontent.com/56189/71233002-2508f300-232f-11ea-9f57-37a9a32e7753.png"  width=200>

Applicable for forks too.

**Comment by JamesSmartCell** [comment]
It won't look like this in the initial version, but will show the right information. We are refactoring this view.

**Comment by hboon** [comment]
@JamesSmartCell yeah, sorry, should have pointed it out. iOS doesn't look like that yet too. Just a reference from the "footer".

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/alpha-wallet-android/pull/1055
