### ISSUE TITLE
Tokens auto-detected from transactions shouldn't always be treated as ERC20 because BlockScout returns ERC721 too

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1054]
Refer to https://github.com/AlphaWallet/alpha-wallet-ios/pull/1622

Not sure if it affects Android version.

**Comment by JamesSmartCell** [comment]
Android uses several steps to determine the contract type when it picks it up from transactions. The possible outcomes are erc721/ticket/legacy, erc875/legacy, erc20.

**Comment by JamesSmartCell** [comment]
Closing due to no longer an issue.
