### ISSUE TITLE
/v1/verifyXMLDSig is pretty slow

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1062]
```
$ curl -X POST -F file=@0x0F43923667843BCCAfD12a5c001A7838Fa5fC8AB.tsml  https://aw.app/api/v1/verifyXMLDSig | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 83190  100   153  100 83037      6   3265  0:00:25  0:00:25 --:--:--    37
{
   "result" : "pass",
   "keyName" : "AlphaWallet",
   "keyType" : "SHA256withRSA",
   "issuer" : "CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US",
   "subject" : "CN=*.aw.app"
}

$ curl -X POST -F file=@0x0F43923667843BCCAfD12a5c001A7838Fa5fC8AB.tsml  https://aw.app/api/v1/verifyXMLDSig | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 83190  100   153  100 83037      8   4601  0:00:19  0:00:18  0:00:01    31
{
   "issuer" : "CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US",
   "keyType" : "SHA256withRSA",
   "result" : "pass",
   "subject" : "CN=*.aw.app",
   "keyName" : "AlphaWallet"
}
```

**Comment by colourful-land** [comment]
What a revelation! That the lambda I wrote was never used (since clearly you are calling  https://aw.app/api/v1/verifyXMLDSig ) Could have saved the work to make the lambda in the first place.

**Comment by colourful-land** [comment]
That's definitely too slow since Sangalli and I moved the aw.app server to China. I previously didn't know the service is still at use (I thought we moved to labmda a few months ago so this migration to China shouldn't have any effect on  αWallet daily use - although lambda wouldn't be any faster in this case, but I thought it worked for a few months so it should be fine).

I'm afraid we should reverse our migration until we have a solution for this. I have a few workarounds in my head but all requires new iOS αWallet releases.

**Comment by James-Sangalli** [comment]
> That's definitely too slow since Sangalli and I moved the aw.app server to China.
> 
> I previously didn't know the service is still at use (I thought we moved this xmldsig verification to lambda a few months ago so this migration to China shouldn't have any effect on αWallet daily use - although lambda wouldn't be any faster in this case, but I thought since it worked for a few months it should be fine).
> 
> I'm afraid we should reverse our migration until we have a solution for this. I have a few workarounds in my head but all requires new iOS αWallet releases.

Lambda integration was never complete in the apps. Also doesn't solve the issues for aw.app as that is a web renderer via thymeleaf, fixing that will require it to be rewritten to be compatible.

**Comment by James-Sangalli** [comment]
Reverted to AWS US
