### ISSUE TITLE
Contract address does not contain checksum (upper/lower case)

### ISSUE THREAD

**Issue by jzaki** [AlphaWallet/alpha-wallet-android#1070]
- Click on an nft
- Click on QR code (top-right)
- copy address
- pasted address does not contain checksum
- Expect: address contains upper/lower case for checksum (as in iOS)

Same for all addresses copied in the app, eg wallet address

**Comment by JamesSmartCell** [comment]
NB This is a big project.

**Comment by ronakdave195** [comment]
@JamesSmartCell May I kindly request you to confirm if the checksum present in QR code? If not, can you provide us logic for checksum placement?

**Comment by James-Sangalli** [comment]
@ronakdave195 checksum was fixed for address qr's and all my wallet addresses but it still uses the class ContractAddress which gives back an unchecksumed address

**Comment by James-Sangalli** [comment]
#1109

**Comment by James-Sangalli** [comment]
this is no longer an issue
