### ISSUE TITLE
Copy transaction to clipboard does not contain transaction details.

### ISSUE THREAD

**Issue by jzaki** [AlphaWallet/alpha-wallet-android#1071]
- import a ticket
- click to copy to clipboard
- copied text pasted as: "Transaction accepted by server."
- Expect: link to the transaction

**Comment by James-Sangalli** [comment]
@jzaki do you mean a link to etherscan rather than just the tx id?

**Comment by jzaki** [comment]
It contained neither. It instead copied: "Transaction accepted by server."
