### ISSUE TITLE
Update Settings Tab Icons [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1080]
Sketch Cloud:
https://sketch.cloud/s/jDODG/p/settings
https://sketch.cloud/s/jDODG/a/Jd5OMr
https://sketch.cloud/s/jDODG/a/4nLd9d
https://sketch.cloud/s/jDODG/a/en9Moq
https://sketch.cloud/s/jDODG/a/0MqWx2
https://sketch.cloud/s/jDODG/a/GW548b

Zeplin:
(app link) zpl://project?pid=5d088205bff2d15de6a4397b&seid=5e21dc3812814e6dc6319fb5
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/dashboard?seid=5e21dc3812814e6dc6319fb5
https://zpl.io/awX04Lg
https://zpl.io/VY7JKYk
https://zpl.io/aR7N1M0
https://zpl.io/251gOEW
https://zpl.io/bzXYN83

There are three types of components

- 60pt high with an icon
- 80pt high with an icon and secondary line
- 60pt high with an icon and toggle

Additional screens

- Advanced and Support will open another screen
- Advanced
- Support
- Modals (Back up my wallet, lock phrase)

**Comment by tomekalphawallet** [comment]
![modals](https://user-images.githubusercontent.com/51817359/72661419-21be6100-39da-11ea-8dfc-839c245f407d.png)
![settings_icons](https://user-images.githubusercontent.com/51817359/72661420-21be6100-39da-11ea-9343-e04a77b73444.png)

**Comment by JamesSmartCell** [comment]
Complete
