### ISSUE TITLE
Update Change Language screen [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1082]
Sketch Cloud:
https://sketch.cloud/s/jDODG/v/eKjDAx/a/oQZJ1Q

Zeplin:
(app link) zpl://screen?sid=5e21dbe34c4d006aceda121e&pid=5d088205bff2d15de6a4397b
https://zpl.io/2vkB7Mr

- use radio button (for single choice lists)
- no need to click any save button, simply make changes and hit back to save

**Comment by tomekalphawallet** [comment]
![change_language](https://user-images.githubusercontent.com/51817359/72661589-1cfaac80-39dc-11ea-9bc9-e64672cffc07.png)

**Comment by JamesSmartCell** [comment]
closed in #1231
