### ISSUE TITLE
Update Active Networks screen [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1083]
Sketch Cloud:
https://sketch.cloud/s/jDODG/v/eKjDAx/a/kn9jrZ

Zeplin:
https://zpl.io/aNM4PEZ

- use checkmark (rounded, blue with white checkbox) for the multiple-choice lists

**Comment by tomekalphawallet** [comment]
![active_networks](https://user-images.githubusercontent.com/51817359/72661602-6b0fb000-39dc-11ea-970d-ff70da8aee04.png)

**Comment by JamesSmartCell** [comment]
@tomekalphawallet this breaks UX convention as the round radio button on android is meant to be a single select. If you have multi-select it should be a checkbox which is square. Not sure if this is still the case though, but it was a couple of years ago.

**Comment by tomekalphawallet** [comment]
You are right. Updated.

https://www.dropbox.com/s/2pvq8efc7wx6vwc/Screenshot%202020-03-20%2008.51.52.png?dl=0

<img width="736" alt="Screenshot 2020-03-20 08 51 52" src="https://user-images.githubusercontent.com/51817359/77145172-13e39580-6a88-11ea-82dc-e5feace758d2.png">

**Comment by tomekalphawallet** [comment]
@JamesSmartCell

**Comment by JamesSmartCell** [comment]
completed in #1247
