### ISSUE TITLE
Update My Wallet Address screen [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1084]
Sketch Cloud:
https://sketch.cloud/s/jDODG/v/eKjDAx/a/W0Oyb0

Zeplin:
https://zpl.io/VQ7WkR4

- Add Smart QR Code Scanner icon in the top right to quickly switch to camera
- clicking "tomek.eth" copies to clipboard
- display ENS + address below

**Comment by tomekalphawallet** [comment]
![my_wallet_address](https://user-images.githubusercontent.com/51817359/72661682-7f07e180-39dd-11ea-9d55-1e127afad3b5.png)

**Comment by hboon** [comment]
@JamesSmartCell tweaked so the Ethereum address wraps with the same font size: https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfaf2cf2149329a03c7b760

**Comment by JamesSmartCell** [comment]
@ChintanRathod this one is not as trivial as it seems. You may need to extend the ENSHandler class to do a reverse-ENS lookup. Currently I don't think it has that ability. The reverse ENS lookup is operational elsewhere in the wallet, on the walletActivity page to detect ENS names for each wallet. If you want extra info please msg me.

**Comment by JamesSmartCell** [comment]
Also see resolveWalletEns(Wallet wallet) in AWEnsResolver, it takes a Wallet and returns any ENS name.
ENS name in Ethereum is like DNS - you can assign a name which represents an address (as opposed to a name that represents an IP address).  

There is also a convenience method provided by ENS that checks if there's any ENS name given an address (similar to whois). This is great for wallets.

**Comment by ChintanRathod** [comment]
OK> Clear. I will start on this issue.

**Comment by ChintanRathod** [comment]
@JamesSmartCell In title, it is mentioned "Fiji" so should this changes applied to "Fiji-implementation" branch? 

I checkout from master branch for now, but if we need to checkout from "Fiji-implementation" let me know. I did my work done for My wallet screen changes. 

There are two screens I can see on Zeplin. 
![image](https://user-images.githubusercontent.com/4371780/78828538-7b935d80-7a02-11ea-888b-a01bc39c2070.png)

Below is current implementation in application (only left side screen from Zeplin)
![image](https://user-images.githubusercontent.com/4371780/78828630-9fef3a00-7a02-11ea-8ad5-403738df517d.png)

So right side view of Camera is pending. Will that change be in this issue or will be a separate one? 
If we need to implement then I am unaware about the functionality of Camera view, so if you can shade of the purpose.

**Comment by ChintanRathod** [comment]
@JamesSmartCell Shall this ticket be closed as PR is merged.

**Comment by AW-STJ** [comment]
Closed, based on confirmation from @JamesSmartCell  over phone.
