### ISSUE TITLE
Update Segmented Controls look [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1085]
Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5dfc12e12ec4d6975469c160

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5dfc1338bdb90d17d2aa628c

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/styleguide/components?cseid=5dfc1308cb89a49855c3063e

- They are part of Master library (common for iOS and Android)
- Please pay attention to the details. It took me a while to set up spacing, color, fonts.

**Comment by tomekalphawallet** [comment]
![segmented_controls](https://user-images.githubusercontent.com/51817359/72661714-eaea4a00-39dd-11ea-97fb-5d7cfe9fd248.png)

**Comment by JamesSmartCell** [comment]
closed with #1225
