### ISSUE TITLE
Update token icons in Wallet tab [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1086]
We will have rounded icons 40x40. It's easy to generate for coins, more difficult for tokens without graphics. For those ones, use colors (Emerald, Indigo, Radical, Pumpkin, Cerulean, Azure, Mine) and up to 4 characters inside (ENS, SFPF, DEFI, DAO). Use the Tokenary app for inspiration.

If AlphaWallet wants to be the best wallet to hold tokens, we need to make it attractive. In the future, I will provide few more designs how you can manage your tokens quickly (by holding and swiping left to reveal hidden menu)

Sketch Cloud:
https://sketch.cloud/s/jDODG/v/093zrA/a/gPjRJM/r/eKjJOp

Zeplin:
https://zpl.io/bzXyMyM

- We are using the same component as we used in "Settings", so we have an icon 40x40, then the same Headline, secondary line (in terms of font). 
https://zpl.io/VkordBg

**Comment by tomekalphawallet** [comment]
![Screenshot 2020-01-18 11 48 35](https://user-images.githubusercontent.com/51817359/72662514-78cb3280-39e8-11ea-9e8c-cc42b9c6dc63.png)

**Comment by jzaki** [comment]
@tomekalphawallet  Where is the ability to add tokens? Previously `+`
Is it in `Manage Tokens` ?

**Comment by tomekalphawallet** [comment]
You can find this inside "Manage Tokens". It was not sent to development yet. In most cases you will use a QR code camera.

**Comment by jzaki** [comment]
Most regular users wont be adding tokens manually (contract address, decimals, etc). But I noticed the `+` in the designs now (and the new `Add/Hide`).

**Comment by JamesSmartCell** [comment]
We'll implement this by using the token graphic if available otherwise use the symbol inside a coloured ring. I'll make an algorithm that converts the token address to a colour. Is that how you expect it? Maybe also have an address -> colour table so this can be overriden.

**Comment by tomekalphawallet** [comment]
> We'll implement this by using the token graphic if available otherwise use the symbol inside a coloured ring. I'll make an algorithm that converts the token address to a colour. Is that how you expect it? Maybe also have an address -> colour table so this can be overriden.

https://play.google.com/store/apps/details?id=com.jufy.tokenary&hl=en

@JamesSmartCell Please download and try to figure out how they made it.

**Comment by tomekalphawallet** [comment]
![tokenary](https://user-images.githubusercontent.com/51817359/76399554-1276e680-637f-11ea-9d31-0d6a72e73343.jpg)

**Comment by tomekalphawallet** [comment]
in our case, those are acceptable colors for tokens without symbols: Mine, Radical, Emerald, Pumpkin, Cerulean, Indigo, Azure

<img width="1055" alt="Screenshot 2020-03-11 10 06 24" src="https://user-images.githubusercontent.com/51817359/76400130-1820fc00-6380-11ea-9ffc-1041a149686f.png">

I created a quite big library of tokens:

https://app.zeplin.io/styleguide/5e0b15e46049c216fb7ab4d5/components?cseid=5e0b16e4ce5cf519870b0316

**Comment by JamesSmartCell** [comment]
I will use this repo:

https://github.com/ethereum-lists/tokens/tree/master/tokens/eth

build a simple tool that creates a mapping between token addr and icon and embed this in the app.

**Comment by tomekalphawallet** [comment]
Along with this change, we need to update font and spacing on wallet tab:

- native crypto where fiat value is available
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?coid=5e96e1bf41b00851c1fb454a
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?coid=5e96e1bea5ea847f77c9ca27
<img width="879" alt="Screenshot 2020-07-03 11 08 08" src="https://user-images.githubusercontent.com/51817359/86453059-7c940c80-bd1d-11ea-8750-03a26700f661.png">

In this example, Ether market price is $226 USD

- native crypto where fiat value is not available
- tokens, not fiat value
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?coid=5e20c0a5535db07d236ab315

<img width="805" alt="Screenshot 2020-07-03 11 14 51" src="https://user-images.githubusercontent.com/51817359/86453652-6d618e80-bd1e-11ea-8725-1c648379cbf8.png">
<img width="796" alt="Screenshot 2020-07-03 11 14 06" src="https://user-images.githubusercontent.com/51817359/86453660-705c7f00-bd1e-11ea-8bf5-3049accc3fc8.png">


- native crypto or tokens for testnets
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?coid=5efc3d791b4d9162739cd42f
<img width="446" alt="Screenshot 2020-07-03 at 11 12 33" src="https://user-images.githubusercontent.com/51817359/86453462-19ef4080-bd1e-11ea-9fd5-9bb74b7db0ac.png">

**Comment by JamesSmartCell** [comment]
@ChintanRathod The work for this is mostly complete. It is lower priority than the universal icon class (#1550 )

Summary of total change:

- Don't display value for testnet.
- Re-add the old testnet label at the far end if the token is testnet. Use the 'hasRealValue' in class EthereumNetworkRepository to determine if testnet token or not.
