### ISSUE TITLE
not asking for authentication when a private key (not a keystore or HD key) is imported

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#1091]
In the codebase, the app won't ask for authentication if a private key was imported and will ask for authentication if it is a keystore or HD key.

This doesn't make sense as the key type is irrelevant, what determines whether authentication is required is determined by whether the user has locked the key on the device or not. 

Furthermore, because of this issue, users are unable to send transactions if they have a keystore but haven't locked it with a PIN.

**Comment by colourful-land** [comment]
![Screenshot_20200126-153229](https://user-images.githubusercontent.com/548435/73130725-fb3f9c00-4051-11ea-89f6-1be5c3447632.jpg)

Tested. Can't reproduce the problem (app does ask for authentication)
