### ISSUE TITLE
Use API key for accessing Etherscan by Feb 15

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1100]
I thought this was done by @colourful-land recently, but I can't find it. So just to be safe.

Refer to: https://github.com/AlphaWallet/alpha-wallet-ios/issues/1677

**Comment by hboon** [comment]
Ah, probably #1077

**Comment by JamesSmartCell** [comment]
Confirmed this was done by @colourful-land in class TransactionsNetworkClient.
