### ISSUE TITLE
Gas limit too low on TokenScript transactions (SAI to DAI conversion)

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#1102]

**Comment by jzaki** [comment]
![Screenshot_20200130-131718_AlphaWallet](https://user-images.githubusercontent.com/939603/73416238-64802180-4368-11ea-8a87-48cab6ca657e.jpg)

**Comment by jzaki** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/7941 ?
