### ISSUE TITLE
Keypad "Go" button on tokenscript numerical input does not do anything

### ISSUE THREAD

**Issue by jzaki** [AlphaWallet/alpha-wallet-android#1104]
Version: 2.21.0

- In the Sai tokenscript, after enabling migration, attempt to convert sai to dai.
- Copy/paste amount into numerical field (keypad shown)
- click "Go" on keypad, nothing happens, Expect: keyboard to hide, or conversion to begin
- edit number on keypad and click "Go", nothing happens.

![Screenshot_20200130-131657_AlphaWallet](https://user-images.githubusercontent.com/939603/73415174-3816d600-4365-11ea-985b-35599fc751f4.jpg)

**Comment by JamesSmartCell** [comment]
Good catch I'll update
