### ISSUE TITLE
Clicking on local .tsml file doesn't open with AlphaWallet

### ISSUE THREAD

**Issue by jzaki** [AlphaWallet/alpha-wallet-android#1113]
Click on local .tsml file in "My Files" (file explorer), Result (image below)
Expect: should open, or suggest to open, with AlphaWallet.

![photo_2020-01-30 16 50 28](https://user-images.githubusercontent.com/939603/73423693-001d8c00-4381-11ea-884f-066f725c4f62.jpeg)

**Comment by JamesSmartCell** [comment]
Unable to reproduce. .tsml asks for AlphaWallet to be opened. Tested on Google Pixel, Xiaomi and Huawei all open AlphaWallet - Google Pixel even puts AlphaWallet as the preferred app.

**Comment by JamesSmartCell** [comment]
Note: tested from telegram, so it could be the file explorer app you're using. Can you re-rest using telegram? I sent you a .tsml

**Comment by JamesSmartCell** [comment]
Appears to be an issue with the file manager rather than with AlphaWallet. Perhaps the file manager is trying to protect users?

**Comment by JamesSmartCell** [comment]
closing due to not an issue we can do anything about.
