### ISSUE TITLE
Low severity low skill vulnerability

### ISSUE THREAD

**Issue by 0xfool** [AlphaWallet/alpha-wallet-android#1119]
I found a low severity security issue in a number of Android wallets.

Google keyboard suggests what word to use based on what I'm typing. In past tests Google keyboard will remember and suggest words from backup phrases in order. This is especially prevalent when seed phrases include words like "october" spelled with a lowercase"o".

It's a low skill attack. While there are a number of ways to stop it (turn off autocorrect and suggest next word) I feel an encrypted keyboard would be better because average users might be unaware.

I'm currently researching ways one could pull info off gboard storage located on a single phone, remotely or otherwise (info stealing USB charger, ECT...).

I suggest an update to add an encrypted keyboard.

**Comment by 0xfool** [comment]
The issue may be more serious than I thought.

Apparently there is a remote hack for Android. I'm not able to verify it as my coding skills are lacking and my knowledge of Linux is non existent.

metasploit in Kali Linux.
https://youtu.be/VaXi5rqeWx0

I'm still not sure how to get at data from gboard cashe. Sources I'm reading seem to think the data is stored on the device (with some exceptions like searches in Google search engine, obviously).

**Comment by JamesSmartCell** [comment]
Hi @0xfool yes this is indeed a potential vulnerability. We are currently finalising a PR which switches off the suggestions while entering seeds; replacing them with an internal class that only suggests from the standard BIP39 seed words. This class doesn't cache any words. Because the OS suggestion system is switched off, it's not aware of the words typed, which effectively solves the issue.

**Comment by 0xfool** [comment]
Much respect for the Alpha wallet team for handling it super quick and openly. This is all very new software, all software can have issues and Alpha wallet team gets things done.

**Comment by JamesSmartCell** [comment]
fixed in #1090 . Thankyou for reporting, The issue is solved by switching off suggestions and programmatically adding suggestions from BIP39. The filter is local and doesn't persist any data.
