### ISSUE TITLE
Add Localised currency

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1136]
This is a mini project which lets users switch their local currency eg AUD, GBP, INR, CNY etc.

It will need: 
- new item in settings for major currencies (at minimum add GBP, AUD, INR, EUR and CNY).
- Create new display class to show currency which automatically converts currency.
- Replace all instances of currency display and usage to use new class.

There is an API in 'TickerService' which converts currencies. All fiat currency values are received in USD; this shouldn't change - just apply local conversion in the new class.

**Comment by ChintanRathod** [comment]
![image](https://user-images.githubusercontent.com/4371780/73836508-6e58c780-4835-11ea-9454-fcefde03bc00.png)

For now implemented necessary currency list into settings. 
@tomekalphawallet Kindly review the design if we need to apply some changes for this issue.

**Comment by tomekalphawallet** [comment]
@ChintanRathod This is a great start. Please keep in mind that we have a new design system. So as long you tried to mimic the current design, really soon we will have a new one, where all fonts, colors, input types are aligned. 

Note: 

a) I added "FIAT" to the title. 
b) We won't have a Confirm button. You confirm by hitting the back button. 
c) I updated the design to be aligned with the new design system (we use checkmark for multiple choices)

Do you have an access to Zeplin libraries? 

Updated design:
![Select_FIAT_Currency](https://user-images.githubusercontent.com/51817359/73918571-28961080-48c2-11ea-99cf-a2b441de3bec.png)

**Comment by JamesSmartCell** [comment]
[flags_svg.zip](https://github.com/AlphaWallet/alpha-wallet-android/files/4301269/flags_svg.zip)

@ChintanRathod here are the round flag SVG assets from the above screen

**Comment by JamesSmartCell** [comment]
Complete
