### ISSUE TITLE
Long delays in User balance & Transaction screen updating after each Transaction

### ISSUE THREAD

**Issue by hellolucas** [AlphaWallet/alpha-wallet-android#1138]
User reports long/"seemingly arbitrary" delays in the wallet updating after each transaction.

These delays affect both user’s balance and transaction screen.

OS: Android (no further given)

**Comment by JamesSmartCell** [comment]
This is related to the update cycle. For non testnet chains this isn't an issue as the balances are checked frequently but could be for testnet.

We are transitioning to an event/action based system where changes in balance on mainnet and Rinkeby will be reported as soon as the transaction is finalised on chain (ie the event is issued).
