### ISSUE TITLE
Update Back up with Seed illustration

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1147]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1700

**Comment by tomekalphawallet** [comment]
I have just updated this illustration. Please overwrite the existing one.

**Comment by justindg** [comment]
@tomekalphawallet the last update in Zeplin (Android) was 27 days ago. Is that the correct one?

**Comment by tomekalphawallet** [comment]
@justindg Check out now

**Comment by JamesSmartCell** [comment]
Fixed in #1258
