### ISSUE TITLE
Update TS Buttons

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1149]
Sketch Cloud:
- https://sketch.cloud/s/jDODG/a/nn1YDz
- https://sketch.cloud/s/jDODG/a/QG9g17
- https://sketch.cloud/s/jDODG/a/xn98Qv
- https://sketch.cloud/s/jDODG/a/EMo1G2
- https://sketch.cloud/s/jDODG/a/jElRrz

and few more if you switch to next to the right.. (Function 3,4,5,6)

Zeplin:
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/dashboard?seid=5e41333605a98088a65653b4

**Comment by tomekalphawallet** [comment]
![Screenshot 2020-02-10 11 45 21](https://user-images.githubusercontent.com/51817359/74143282-d4a96580-4bfa-11ea-849c-5fc510a767e6.png)

**Comment by tomekalphawallet** [comment]
@colourful-land wants to outsource this part to new developers on Upwork - and hire the one who provided the highest quality.

**Comment by JamesSmartCell** [comment]
This doesn't look Android native. The way shown above doesn't appear as a design pattern on Android interfaces.

Instead when pressing the hamburger button potentially extra buttons should appear in a panel; possibly with some sort of priority so the TokenScript developer can supply hints as to how the buttons should appear. We can see what our outsourcers do with this; it's actually a good first issue.

**Comment by tomekalphawallet** [comment]
https://material.io/components/sheets-bottom/#usage

Check Modal Sheet Bottom. Because TS limitations, we can't support icons. So I removed them. 

If you want, we can also remove "More options" from the top.

<img width="1225" alt="Screenshot 2020-03-03 13 12 58" src="https://user-images.githubusercontent.com/51817359/75774692-c3aec880-5d50-11ea-83c8-500b09a0adac.png">

https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1xY0fPveXIEcZrtyPbRtnDDEcn1IOJTch%2Fmodal-usage-overflow.mp4

**Comment by JamesSmartCell** [comment]
Agree this should be implemented on Android in the modal bottom sheet style. We further discussed the possibility of button weighting or priority in the meeting today. Being able to create a button with higher priority than the intrinsic buttons is also worthwhile.

**Comment by JamesSmartCell** [comment]
Closed by #1250
