### ISSUE TITLE
Fiji all-encompassing issue

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1156]
Mainly a FYI and also for both @JamesSmartCell and @jzaki benefit.

I've created this for iOS https://github.com/AlphaWallet/alpha-wallet-ios/pull/1672 as a checklist for myself. The first 4 items forms most of the foundation for Fiji for iOS:

* https://github.com/AlphaWallet/alpha-wallet-ios/pull/1686
* https://github.com/AlphaWallet/alpha-wallet-ios/issues/1673
* https://github.com/AlphaWallet/alpha-wallet-ios/issues/1633
* https://github.com/AlphaWallet/alpha-wallet-ios/issues/1634

So an Android equivalent could form a good foundation if we want to ship Fiji without working on specific screens.

Feel free to close this or modify this issue for tracking

**Comment by JamesSmartCell** [comment]
Closed in Qoin repo and complete in Fiji-Implementation branch.
