### ISSUE TITLE
Advanced transaction details screen 

### ISSUE THREAD

**Issue by jzaki** [AlphaWallet/alpha-wallet-android#1158]
On transaction confirmation page, able to tap on section beneath addresses (left screen), and be presented with advanced options (right screen): gas price/limit, and transaction data.

iOS screenshots...
<img src="https://user-images.githubusercontent.com/939603/74284249-7655c180-4d77-11ea-98de-94d37566bf5e.PNG" alt="iPhone_e990a_IMG_0022" width="300">  <img src="https://user-images.githubusercontent.com/939603/74284255-7950b200-4d77-11ea-8f7a-ff747a7cb3d3.PNG" alt="iPhone_e990a_IMG_0021" width="300">

**Comment by hboon** [comment]
We have a design for actionsheet transaction confirmation. So have to weigh how much work to put into tweaking this existing version switching to actionsheet.

**Comment by JamesSmartCell** [comment]
Note 1: DO NOT LABEL WITH 'GOOD FIRST ISSUE'.
Note 2: The screen is there but due to colour changes the icon isn't visible.
Will be fixed in UX upgrade

**Comment by jzaki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[__] As a user, I want understanding/control over transaction processing time, so that I can transact with confidence](https://trello.com/c/26MTjbSU/70-as-a-user-i-want-understanding-control-over-transaction-processing-time-so-that-i-can-transact-with-confidence)

**Comment by JamesSmartCell** [comment]
This has been addressed to a certain extent in PR #1172
