### ISSUE TITLE
Android adding ASNX module parsing capacity (only used for events now)

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#1183]
It means iOS should be aware of this file's line 26 to line 34

https://github.com/AlphaWallet/TokenScript-Examples/blob/27ffe6a83a7c41631ebfe22e262e21850f234327/examples/ENS/ENS.xml#L26-L34

**Comment by JamesSmartCell** [comment]
Solved within the script by passing the ```xmlns:asnx="urn:ietf:params:xml:ns:asnx"``` directive.
