### ISSUE TITLE
Add ability to retrieve events inside TokenScript

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#1194]
https://gist.github.com/James-Sangalli/0509258f3d56b66b68bfd6d51a10639a

**Comment by James-Sangalli** [comment]
@JamesSmartCell I'll add the function and a test to retrieve the events and then you can integrate it in

**Comment by James-Sangalli** [comment]
@JamesSmartCell as discussed, here is a code snippet for retrieving filtered events in Web3J with sample output: https://gist.github.com/James-Sangalli/4d1f031d5cf6ac724e7946b48f1cf44c

**Comment by JamesSmartCell** [comment]
Can now access events.
