### ISSUE TITLE
Enable Currency Selection in Fiji

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1219]
Just did a re-sync of the Fiji branch with all the fixes/improvements that have gone into the repo since we branched the Fiji work.

The Currency selection screen isn't re-enabled - but everything else is there, the selection activity etc. I left a //TODO in the new class AdvancedSettingsActivity where the currency selection should go.

Could you resolve this TODO and add the selection screen back in and connect it up? You may have to modify the viewModel etc and do a little wiring elsewhere I'll leave that to you.

Submit the PR to the Fiji-Implementation branch.

The refactor makes the code here a lot less messy!

**Comment by ChintanRathod** [comment]
@JamesSmartCell Implemented in Fiji branch. Can you please review and close this ticket if done?

**Comment by JamesSmartCell** [comment]
Completed by remote PR.
