### ISSUE TITLE
Jump to 'Backup your key' screen when user has assets in wallet

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#122]
App should display the 'backup your key' screen when the user finally has eth or ticket assets.

The screen should advise user on where to put the data, and that it's locked with a password.

**Comment by James-Sangalli** [comment]
@JamesSmartCell bump

**Comment by miang719** [comment]
@JamesSmartCell bump

**Comment by James-Sangalli** [comment]
@JamesSmartCell is this done?

**Comment by James-Sangalli** [comment]
No longer relevant since UI keystore implementation #770
