### ISSUE TITLE
Implement browser string change

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1245]
I'm assigning this to Boon and Brown for comments.

Consider a website which would render this screen if opened with αWallet (pic1):

![Screenshot_2020-03-20 Log In ‹ bitflynn — WordPress](https://user-images.githubusercontent.com/548435/77137529-76f21e00-6ac2-11ea-87c5-053ec851a352.png)

And if not, this (pic2):

![Screenshot_2020-03-20 Log In ‹ bitflynn — WordPress(1)](https://user-images.githubusercontent.com/548435/77137598-aacd4380-6ac2-11ea-9247-e8ef68efc9b0.png)

## Traditional implementation

Traditionally, this is achieved by rendering both login dialogue with Javascript. That is, it starts with this screen:

![Screenshot_2020-03-20 Log In ‹ bitflynn — WordPress(2)](https://user-images.githubusercontent.com/548435/77137668-f54ec000-6ac2-11ea-8383-32153bdd94e8.png)

Then, JavaScript kicks in, replacing the message by either pic1 or pic2.

## Proposed implementation

I propose that we return a User-Agent string that contains the word AlphaWallet.

This way the server can choice to offer between pic1 and pic2 without using JavaScript to detect the user-agent with a web3 object, giving additional flexibility to the web developer.

**Comment by hboon** [comment]
> I propose that we return a User-Agent string that contains the word AlphaWallet.

Modern web frameworks make it easy to get the headers.

Sounds like it should work and is clean, and should be easily implemented in other dapp browsers too.

**Comment by colourful-land** [comment]
@hboon can you propose what the new User-Agent string is and I'll file another issue under iOS asking that to be implemented. Quoin can pull that change in and release before αWallet.

**Comment by hboon** [comment]
How about we append the "AlphaWallet/<app version>" to it?

Eg. on iPhone, it is:

> Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

Make it:

> Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 AlphaWallet/2.30

If they like, Qoin can append an additional value "Qoin/<app version>" for their tracking via server logs

**Comment by colourful-land** [comment]
@hboon Assigned to JB now. Yours is https://github.com/AlphaWallet/alpha-wallet-ios/issues/1758

@JamesSmartCell I don't think Qoin should add their own value in the Browser String, cautious of over-designing.

**Comment by JamesSmartCell** [comment]
We already have this in both the Dapp and TokenScript injector:
```
webSettings.setUserAgentString(webSettings.getUserAgentString()
                                               + "AlphaWallet(Platform=Android&AppVersion=" + BuildConfig.VERSION_NAME + ")");
```

Which I think is similar to what is being proposed. I think @hboon proposed it some time ago.

**Comment by JamesSmartCell** [comment]
I will update it with the proposed mod above.
