### ISSUE TITLE
the QR code scanner on browser tab doesn't recognise URLs

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1253]
Reproduce.

1. On your PC, go to https://www.qrcode-monkey.com/
2. Use your mobile to scan the QR code there.
3. get the message "Invalid scan result"

Expected:

3. The browser launches the website  https://www.qrcode-monkey.com/

**Comment by JamesSmartCell** [comment]
It has been fixed in the past. But possible PR didn't go through and got closed.

**Comment by JamesSmartCell** [comment]
Works on latest master branch

**Comment by James-Sangalli** [comment]
Works in iOS

**Comment by James-Sangalli** [comment]
Duplicate of https://github.com/AlphaWallet/alpha-wallet-android/issues/1177
