### ISSUE TITLE
Hide Wallet Tabs & Add / Hide Tokens

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1254]
When scrolling the token list, we should hide the Title, Add / Hide Token bar and the filter tabs.

Check Twitter how, when the first thing to scroll off the top of the screen is the title bar. 

As you scroll down the token list, the three title areas should disappear until you only see the thin OS details bar right at the top.

**Comment by justindg** [comment]
Is there any way we could utilise a **Floating Action Button** for the **Add / Hide Token** bar?

**Comment by tomekalphawallet** [comment]
@justindg We have to stay consistent between iOS and Android. So even if we ever add a **Floating Action Button**, the **Add/Hide Tokens** is not that important to stand out.

**Comment by tomekalphawallet** [comment]
This can be helpful:

https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1584058305895%2Fassets%2F1cx_CQC_pYOeAxmJAoEIjGnZNAWQzz-O1%2Ftabs-scrolling-1.mp4

**Comment by JamesSmartCell** [comment]
closed in #1257
