### ISSUE TITLE
warn android 6.x users that their devices are planned to be obsoleted

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1264]
If a user is using android < 8.0 they should see a message that their device is to be obsoleted with a link to a blog post why we decided so.

**Comment by JamesSmartCell** [comment]
Actually doesn't need to be Android 8. We can start with removing Android 6 support which would allow us to consolidate some source into the 'lib' project.

**Comment by colourful-land** [comment]
> Actually doesn't need to include 7. We can start with removing Android 6 support which would allow us to consolidate some source into the 'lib' project.

We need to warn them that even 7 will be dropped at certain point. Still warn 7 users, but less sense of urgency.

**Comment by justindg** [comment]
> If a user is using android < 8.0 they should see a message that their device is to be obsoleted with a link to a blog post why we decided so.

Is the blog link available?

**Comment by AW-STJ** [comment]
Talked to Weiwu and confirmed that we don't need a blog as we are only dropping support for Android 6 now. We might do a blog if and when we decide to stop Android 7.

**Comment by AW-STJ** [comment]
> > If a user is using android < 8.0 they should see a message that their device is to be obsoleted with a link to a blog post why we decided so.
> 
> Is the blog link available?

Talked to Weiwu and confirmed that we don't need a blog as we are only dropping support for Android 6 now. We might do a blog if and when we decide to stop Android 7.

**Comment by colourful-land** [comment]
When android 8 is actually obsoleted, we should revert the PR 1400
https://github.com/AlphaWallet/alpha-wallet-android/pull/1400#pullrequestreview-410900597
