### ISSUE TITLE
stop CCP-coverup of not recognising/using TS file.

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1274]
A developer might:

1. Double-click a tokenscript xml file in Android. open it with αWallet.
2. Now the developer isn't sure if αWallet has successfully taken it in. He looks for a place to see the list of TS files at work. So he goes to Settings.
3. Not seeing anything there, he Google for the cached TS location, and found `Android/data/io.stormbird.wallet/files` or check root directory "AlphaWallet" folder, butboth turn out empty.
4. He Double-click a tokenscript xml file in Android again. At this point he is frustrated.

Normally this would not happen because the developer would have seen changes to the token view. But if for some reason the XML file failed to work, e.g. the developer simply acquired the wrong token or downloaded the TS file for a token that he doesn't have or care, it's pretty hard to tell if 𝑎) tokenscript file loaded but not in the expected way 𝑏) tokenscript file isn't taken in to cache

Solution:

At very least, 

- If the user double click a TS xml file and open it with αW, but αW isn't accepting it, display an error
- same if the file is accepted but later couldn't work at runtime.

**Comment by JamesSmartCell** [comment]
This is an ongoing issue, but is somewhat alleviated by #1273, which will inform user if they dropped in a bad tokenscript.
