### ISSUE TITLE
Add Analytics screen

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1280]
In the Settings -> Advanced we can add one more screen where users can turn on/off analytics. It should be on by default (as other wallets do).

@jzaki can provide a better copy

Sketch Cloud:
https://sketch.cloud/s/jDODG/a/en9Moq
https://sketch.cloud/s/jDODG/a/m2YKAP
https://sketch.cloud/s/jDODG/a/7QPAY8

Zeplin:
https://zpl.io/2j0XM4q

<img width="1242" alt="Screenshot 2020-04-07 at 15 26 00" src="https://user-images.githubusercontent.com/51817359/78674674-40027180-78e4-11ea-9a44-63f848501daf.png">

**Comment by JamesSmartCell** [comment]
Suggestion: link to GitHub source code so more curious users can see we're really sharing only anonymous data.

**Comment by colourfreak** [comment]
@colourfreak Improve this and apply to iOS

**Comment by hboon** [comment]
Skip the "what data do we collect?" screen.
