### ISSUE TITLE
Error in TokenScript element: Add subdomain

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#1282]
This could be an error in the ENS tokenscript but I get this using the latest ENS version in the latest event support branch

![Screenshot_2020-04-08-10-47-35-877_io stormbird wallet](https://user-images.githubusercontent.com/16630514/78739320-56b5d080-7997-11ea-9ed1-2b1d254ec873.png)

**Comment by JamesSmartCell** [comment]
Yes I've seen it, fixing before release

**Comment by James-Sangalli** [comment]
This has caused a botched transaction:

Correct transaction: https://etherscan.io/tx/0xec92a480ecef2ca9a82d7420bd0df6cf4d12fcc3e14ab721025660c96e37d1c0

Botched transaction: https://etherscan.io/tx/0x9b9e6885275bd711884cb18d2e45fb68e7fe777c07afb863c917dcd94ec64f1b
