### ISSUE TITLE
Update collectibles tab to match iOS

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1283]
Here's what the collectibles tab looks like on iOS:

![collectibles](https://user-images.githubusercontent.com/12689544/78741660-456fc280-799d-11ea-88d6-154ab9e1a494.jpg)

Android should be updated to look like this, as it's pretty cool.

**Comment by colourfreak** [comment]
Hold your horses here. We are going to update this tab anyway.
