### ISSUE TITLE
Misc Improvements to last Fiji build

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1290]
1. My Wallet Address is broken

![2020-04-10 09 33 30](https://user-images.githubusercontent.com/51817359/78974697-d4eab200-7b12-11ea-9cfa-4bbf453c5852.jpg)

---

2. To copy an address, extend the area where you can tap. Right now, only the icon lets you copy the address (green). Please make it larger, so the whole gray background is a button (red). 

![Zrzut ekranu 2020-04-10 10 09 47](https://user-images.githubusercontent.com/51817359/78974984-740fa980-7b13-11ea-839e-b6d0ef753d45.png)

---

3. Change font when importing a wallet

![2020-04-10 09 37 31](https://user-images.githubusercontent.com/51817359/78975413-55f67900-7b14-11ea-9935-7007c8f59e3e.jpg)

https://zpl.io/2yZ15MG

---

4. Manage Tokens - if a button says "Add/Hide Tokens" then it should have the same title in the following screen. Otherwise, people have to think if they are in the right place. 

![Zrzut ekranu 2020-04-10 10 24 21](https://user-images.githubusercontent.com/51817359/78977018-ae7b4580-7b17-11ea-8710-c234d017713a.png)

---

5. Manage Tokens  - the design is different, but having the functionality ready (it works well), it should be easier to just adjust the design. "Apply Filters" is not necessary. It should be saved the moment you hit the back button. 

https://zpl.io/2Glzlrm

![Zrzut ekranu 2020-04-10 10 42 14](https://user-images.githubusercontent.com/51817359/78977214-0d40bf00-7b18-11ea-8136-3e0c2ebc7dda.png)

---

6. Watch Wallet does not work with ENS addresses. 

![2020-04-10 10 43 54](https://user-images.githubusercontent.com/51817359/78977390-598bff00-7b18-11ea-98a6-b63f52b6d756.jpg)

**Comment by tomekalphawallet** [comment]
7. Make it in 2 lines

"Write down seed phrase
on paper"

https://zpl.io/bJ4AMLW

![2020-04-10 10 23 03](https://user-images.githubusercontent.com/51817359/78977804-08c8d600-7b19-11ea-8dfb-2689b8036009.png)

---

8. Look at the bottom part - they button overlays the lowest row of mnemonics. "Garage" "Detect"

https://zpl.io/bLAL8O7

![2020-04-10 10 19 51](https://user-images.githubusercontent.com/51817359/78978007-5ba28d80-7b19-11ea-9b61-6aa92d76c651.jpg)

**Comment by JamesSmartCell** [comment]
@justindg you broke my nice calculated layout for that seed phrase entry! Actually your code looks a lot nicer, but could you sort out the above issue, looks like a job for coordinator layout maybe?

**Comment by JamesSmartCell** [comment]
My wallet address was broken by me - not sure how but there you go.
