### ISSUE TITLE
Unified function name， Networks

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1308]
![photo_2020-04-14 11 09 28](https://user-images.githubusercontent.com/33795543/79175473-28297100-7e41-11ea-845a-299654496543.jpeg)

Change 'Networks' to'Select Active Networks'

**Comment by colourful-land** [comment]
I solved it on Android. Victor check if iOS needs the same to be done to it.

**Comment by zhangzhongnan928** [comment]
> I solved it on Android. Victor check if iOS needs the same to be done to it.

Yes, I have an issue for iOS as well.
