### ISSUE TITLE
Add TokenScript Management Page

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1315]
Page that matches iOS TokenScript management page which displays a list of Tokens that have a tokenscript.

Once we have a basic list of tokens we will expand on it to show warnings/errors and allow users to remove and otherwise manage scripts.

Add the page into the settings like this (@hboon can you please add iOS settings page screen shot with TokenScript management entry and another showing the script page):

TokenScript Management

You will be able to get a list of the scripts from assetDefinitionService using a method that traverses the ```assetDefinitions``` SparseArray/Mapping, making a list of holding contract tokens vs Filename. See method 'addContractAddresses' to see how to extract the holding contracts from each definition. Most scripts have only one holding contract token (eg Karma - ```0x75cb...```).

I'm thinking initially we want to see something like a list like this:

```
Script Name                 Filename                        
   - token address
```
eg
```
Car Ownership Token                 karma.canonicalized.xml (small font)
0x75cb...  (small font)
```

We may want to change this in future but for now this will be fine

**Comment by hboon** [comment]
@JamesSmartCell are you referring to these 2 screens?

TokenScript overrides | Console
-|-
<img width=300 src="https://user-images.githubusercontent.com/56189/79237817-30b19400-7ea1-11ea-9795-712a5f64c188.jpg">|<img width=300 src="https://user-images.githubusercontent.com/56189/79237826-327b5780-7ea1-11ea-91b2-1dcf49683bf4.jpg">

The Console screen was initially added to help with debugging. I was thinking it can log all kinds of errors. But never had the chance to go further with it.

**Comment by JamesSmartCell** [comment]
Yes, thankyou. I had exactly the same thought, we can add some additional debugging information for developers in here, based on feedback from @James-Sangalli's interviews with developers trying to use TS, it should be very useful.

**Comment by JamesSmartCell** [comment]
What is the 'Console' screen? Is it related to the Management screen or does it just display all the TS errors like 'Console' JS view in the browser?

**Comment by hboon** [comment]
Related because it displays validation errors and when two or more files are in conflict. I was hoping it can display additional errors and messages that help TokenScript authors but that isn’t relevant to users. Console output is a good candidate too.

**Comment by ChintanRathod** [comment]
@JamesSmartCell Could you please close this ticket as PR is merged.

**Comment by JamesSmartCell** [comment]
Completed
