### ISSUE TITLE
QR Scan icon

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#132]
![whatsapp image 2018-05-07 at 12 29 45 1](https://user-images.githubusercontent.com/33795543/39685233-a5e7ea6c-51f3-11e8-8642-17bbf1c61ca6.jpeg)
![whatsapp image 2018-05-07 at 12 29 45](https://user-images.githubusercontent.com/33795543/39685234-a61c3fa6-51f3-11e8-9748-8639c0ab8714.jpeg)

Many users told me this icon is confusing, 
1. they don't, it is a button 
2. it doesn't look like a scan button

I suggest that we change it to a camera icon

**Comment by James-Sangalli** [comment]
Has been done.
