### ISSUE TITLE
Add 'What is TokenScript' to the Help & FAQ page

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1321]
Add a brief introduction to TS, what it is and why it's there - no more than a single paragraph! Should also have a link to the community section and paper.

**Comment by AW-STJ** [comment]
Community page is https://tokenscript.org/community/

**Comment by ChintanRathod** [comment]
@AW-STJ What should be the content to show.

**Comment by JamesSmartCell** [comment]
Use this text for now:

"TokenScript is a markup language which aims to provide a enhanced experience for token users and owners. The experience is enhanced with a cryptographic trust model and consistent user interface. A TokenScript associated with a token provides a user with a trusted and private way to use more advanced features; for example 'approve' on ERC20 or 'breedWithAuto' on Cryptokitties."

**Comment by ChintanRathod** [comment]
Is this the correct flow?
![ezgif-1-28b8e381aefa](https://user-images.githubusercontent.com/4371780/80936678-ce88e680-8def-11ea-8711-f64249c0a078.gif)
