### ISSUE TITLE
Custom tokenscript not loading in wallet

### ISSUE THREAD

**Issue by jzaki** [AlphaWallet/alpha-wallet-android#1352]
- Had existing wallets before adding custom tokenscript file
- could see token, but not additional actions from file
- changed wallets
- could see token (perhaps manually added address?), but still no additional actions from file
- Expected: additional actions on token visible, and custom action in each wallet (also irrespective of balance)

[spec ref](https://github.com/AlphaWallet/internal-alpha-wallet/wiki/TokenScript-in-the-Wallet#rendering-tokenscript-files)

**Comment by JamesSmartCell** [comment]
@jzaki can you attach the script that isn't working

**Comment by jzaki** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE token  [
    <!ENTITY style SYSTEM "app.css">
    <!ENTITY mint.en SYSTEM "mint.shtml">
    ]>
<ts:token xmlns:ts="http://tokenscript.org/2019/10/tokenscript"
          xmlns="http://www.w3.org/1999/xhtml"
          xmlns:xml="http://www.w3.org/XML/1998/namespace"
          xsi:schemaLocation="http://tokenscript.org/2019/10/tokenscript http://tokenscript.org/2019/10/tokenscript/tokenscript.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          custodian="false"
>
    <ts:name>
        <ts:string xml:lang="en">Coin</ts:string>
    </ts:name>
    <ts:contract name="Coin" interface="erc20">
        <ts:address network="3">0x9E9002A92e91f66fe7F94D2394B3AF68eb886f39</ts:address>
    </ts:contract>
    <ts:origins>
        <ts:ethereum contract="Coin"></ts:ethereum>
    </ts:origins>
    <ts:cards>
        <ts:action>
            <ts:name>
                <ts:string xml:lang="en">Mint</ts:string>
            </ts:name>
            <ts:attribute-type id="amount" syntax="1.3.6.1.4.1.1466.115.121.1.36">
                <ts:name>
                    <ts:string xml:lang="en">Amount to create</ts:string>
                </ts:name>
                <ts:origins>
                    <!-- e18 is a hard coded multiplier.
                    rationale for hardcoding: avoiding over-design -->
                    <ts:user-entry as="e18"/>
                </ts:origins>
            </ts:attribute-type>
            <ts:transaction>
                <ts:ethereum function="mint" contract="DAI">
                    <ts:data>
                        <ts:address ref="recipient"/>
                        <ts:uint256 ref="amount"/>
                    </ts:data>
                </ts:ethereum>
            </ts:transaction>
            <style type="text/css">&style;</style>
            <ts:view>&mint.en;</ts:view>
        </ts:action>
    </ts:cards>
    <ts:attribute-types>
        <ts:attribute-type id="balance" syntax="1.3.6.1.4.1.1466.115.121.1.36">
            <ts:name>
                <ts:string xml:lang="en">Balance</ts:string>
            </ts:name>
            <ts:origins>
                <ts:ethereum function="balanceOf" contract="Coin" as="uint">
                    <ts:data>
                        <ts:address ref="ownerAddress"/>
                    </ts:data>
                </ts:ethereum>
            </ts:origins>
        </ts:attribute-type>
    </ts:attribute-types>
</ts:token>
```

**Comment by JamesSmartCell** [comment]
Where are app.css and mint.shtml?

If these are placed in the directory alongside this script, it won't work on Android. Google took the decision to remove the ability of the Android XML parser to resolve references. 

Either - include the references using xmlstarlet or manually add them, or if these are resolved already could you include the full script?

**Comment by jzaki** [comment]
@JamesSmartCell I had tested with the canonicalized file. XML above updated accordingly.

**Comment by JamesSmartCell** [comment]
Specifically what isn't working. I'm seeing this:

![ad7eda0a-81fa-4145-a7ed-908d851e0588](https://user-images.githubusercontent.com/12689544/80444140-42d90b00-8954-11ea-95b8-e7d0cc17129b.jpg)

You do have to click on the new Fiji controls here:

![bf05ba74-9591-4f48-9c7e-cb5dbdbf0bff_LI](https://user-images.githubusercontent.com/12689544/80444192-71ef7c80-8954-11ea-98e7-61ad45d495f7.jpg)

Also to load into AW either send it to yourself in telegram and click or drop into the AlphaWallet directory. If AlphaWallet directory doesn't exist then use the TokenScript Override button in advanced settings.

If this is the issue then it's a UX fail, if even internally we missed the hamburger menu extension queue!

**Comment by jzaki** [comment]
Mint shouldn't work for you, but good you can see the tokenscript.
I've been using custom tokenscripts before by opening with the app (sometimes works and puts a file in the AlphaWallet directory), and also directly putting the canonicalized file in the AW directory.

Certainly wouldn't have missed the action if it was there. It worked a treat in iOS. Will try again with latest PlayStore version.

Which version are you using?

**Comment by jzaki** [comment]
Update, due to the amount of installs/reinstalls between apks and playstore version, I suspect I had not turned on "TokenScript Overrides" at that time. Latest playstore build works.
The AlphaWallet directory still existed, but the app didn't have access.
