### ISSUE TITLE
Prevent sending of 0 Fiat transaction

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1358]
Go to Send activity, switch to fiat send using up/down arrow control:

![signal-attachment-2020-04-26-132534_002_LI](https://user-images.githubusercontent.com/12689544/80296866-b26ac100-87c1-11ea-9f60-302af0037681.jpg)

Leave the amount blank and press send. App will allow you to send zero amount.

Fix: App shouldn't allow you to send zero fiat amount.

**Comment by ChintanRathod** [comment]
PR merged. Closing the issue.
