### ISSUE TITLE
XMLDSig server verification fails with 2020/03 TSML

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#1362]
{"result":"fail","failureReason":null}

**Comment by James-Sangalli** [comment]
Problem found, no keyinfo name like "AlphaWallet" was set. This is easy to fall for @colourful-land

**Comment by James-Sangalli** [comment]
Another issue is found:

ENS verification fails but DAI verification passes, both signed with the same key and params

**Comment by colourful-land** [comment]
Can you provide the steps to reproduce the issue?

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript-Repo/tree/master/aw.app/2020/03

Try with these two files

**Comment by James-Sangalli** [comment]
@colourful-land narrowed down the problem, the namehash dependency is causing the signature to be invalidated

**Comment by James-Sangalli** [comment]
@colourful-land observe with the following diff: https://www.diffchecker.com/502ao2II

The left side has the releaseBundle.js file which has namehash wrapped into it and the other does not. The right side passes and the left does not.

**Comment by James-Sangalli** [comment]
@colourful-land offending string here: https://github.com/AlphaWallet/TokenScript-Examples/blob/upgrade-schema-2020-03/examples/ENS/recordsBundle.en.js#L3249

**Comment by James-Sangalli** [comment]
https://stackoverflow.com/questions/61472667/xmlsignature-fails-to-validate-with-special-string

**Comment by James-Sangalli** [comment]
@colourful-land test case is here: https://github.com/AlphaWallet/alpha-wallet-android/commit/ac45eb4de44d15c57b32a42eed51b40da04597d0#diff-d6fbb474a42c3b56427ec830bfb0aa6fR50
