### ISSUE TITLE
Add copy-to-clipboard button to Transaction Details

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1377]
Visual (by Tomek, if in question, ask him)
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e170e6ef7b0f25419ad8e00

iOS: https://github.com/AlphaWallet/alpha-wallet-ios/issues/1792

**Comment by ChintanRathod** [comment]
@tomekalphawallet There are some parameters not mentioned in the Zeplin design. Below is difference between previous and current zeplin screen.

![image](https://user-images.githubusercontent.com/4371780/82583033-7a804f00-9bb0-11ea-8b31-9c568b24b3e2.png)

Missing parameters are

- Crypto received 
- Confirmation

Could you please confirm whether we are not expecting to have this details on the "Transaction Details" screen?

**Comment by ChintanRathod** [comment]
@JamesSmartCell In this Zeplin design, there is new parameter added to display "Transaction Initiated" which we are not getting in "Transaction". Should we show it or only "Transaction Time" is sufficient?

**Comment by JamesSmartCell** [comment]
Hi @ChintanRathod , can you add the confirmations in a bracket after the block number. So it should look something like this:
```
Block
0x9843f3f3  (4192 Confirmations)
```

We may want to change this later, but the confirmation depth is useful information.

**Comment by ChintanRathod** [comment]
@JamesSmartCell OK Sure. Should we also keep "Received" amount information on top too? It is valuable too.

**Comment by tomekalphawallet** [comment]
@ChintanRathod Yes, you can. This is mentioned already in the previous screen. But you can add "Amount" at the top of the Transaction Details screen.

<img width="1362" alt="Screenshot 2020-05-25 09 31 04" src="https://user-images.githubusercontent.com/51817359/82789489-aa5a7b80-9e6a-11ea-956a-5fabf771ff89.png">
