### ISSUE TITLE
Add 'Universal Scan' button

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1388]
On the wallet front page there should be a scan button next to 'add token' which looks like this [+] (see zeplin for asset - use SVG asset - don't generate many PNG's).

The result should be passed through the QRUrlDecoder and then the app assigns where to go based on the result.

There should only be three actions - if the EIP681Type is URL then open it in Dapp browser, if OTHER then fail, if anything else then jump to 'SendActivity' and handle appropriately.

**Comment by ChintanRathod** [comment]
@JamesSmartCell Are we referring to below screens?

![image](https://user-images.githubusercontent.com/4371780/82975527-58e0f680-9ffa-11ea-9d9f-a58138b13d0f.png)

https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e6f655d83d042179a137405
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e6f64f0de850113ba37080a

**Comment by JamesSmartCell** [comment]
Yes
