### ISSUE TITLE
Check existing ENS sends when using reverse resolve

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1404]
When we reverse resolve ENS (ie look up an address to see if it has an ENS name associated) using:
```resolveEnsName(String address)```, if we don't get any result from the ```reverseResolve``` method we should also check the previously used ENS names which are retrieved here: ```getENSHistoryFromPrefs();``` in ```class AutoCompleteUrlAdapter```.

If we resolve the address for those (using ```resolveENSAddress(String name)```, and it matches the address we're looking up then we found a hit. This way a user can discover their own wallet names for the wallets list, if they haven't (or don't know how to) set the reverse resolver contract.

```class AutoCompleteUrlAdapter``` should probably also be renamed to ```class AutoCompleteAddressAdapter```, it no longer has anything to do with URLs.

**Comment by ChintanRathod** [comment]
@JamesSmartCell When I check "getENSHistoryFromPrefs" below is the output. In this preferences, we are not storing, key-value information. Like this is only ENS name, how to compare with Address? Shall I extend this with Address-ENS name pair value storing? 

**Current**
historyJson : ["jsbrown.eth"]

**Improvement** 
historyJson : ["jsbrown.eth|0xC067A53c91258ba513059919E03B81CF93f57Ac7"]

In this way, we can compare the stored history.

**Comment by JamesSmartCell** [comment]
That sounds like a good solution.
