### ISSUE TITLE
need a <speed up pending transaction> function

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1412]
one transaction sends with lower gas will block all the other transaction.
speed up pending transaction function can be quite useful: resend the same transaction with same Nonce but higher gas.
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1809

**Comment by hellolucas** [comment]
@all-contributors please add @zhangzhongnan928 for ideas

**Comment by JamesSmartCell** [comment]
Nice idea! @tomekalphawallet let me know when you have a flow for this.

**Comment by JamesSmartCell** [comment]
I added a 'speedup' button to the transaction detail view if the transaction is pending. This button sends you to the confirmation page with the gas fee bumped by 1 Gwei. With the modification outlined in a different issue it should be very obvious how to choose the new speed.
