### ISSUE TITLE
Gas price +1

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1430]
Can we be a bit more aggressive with the gas price? If the node returns with a gas price n, then we should use n+1 as the gas price.

**Comment by JamesSmartCell** [comment]
Make the gas price slightly higher than the recommended? This could be done in conjunction with making the fact you can change the gas price more obvious, since one person couldn't work it out.

**Comment by zhangzhongnan928** [comment]
> Make the gas price slightly higher than the recommended? This could be done in conjunction with making the fact you can change the gas price more obvious, since one person couldn't work it out.

Yes, just 1 gwei higher as default
