### ISSUE TITLE
Chinese Translation Incorrect

### ISSUE THREAD

**Issue by whtyfhas** [AlphaWallet/alpha-wallet-android#1434]
Hi Dear AlphaWallet members

We added support in your system for our token. We installed an Android version of your wallet. When we ran that version and intended to transfer a token of ours we found that the Chinese translation might not be that appropriate. 

The Chinese translation for “MagicLink for picking up” was "通过MagicLink导出门票". A better translation might be "通过MagicLink转出通证"

The Chinese translation for “transfer now” was "现在直接转让门票". A better translation might be "直接转出通证"
 
Thank you and best regards

Yuefei

**Comment by colourful-land** [comment]
This issue was filed in Feb in the wrong repository that's why it took so long.

**Comment by zhangzhongnan928** [comment]
> This issue was filed in Feb in the wrong repository that's why it took so long.

currently, these are in wallet code, but should they be in TokenScript?
@colourful-land

**Comment by zhangzhongnan928** [comment]
Thanks for the suggestions @whtyfhas 
close to https://github.com/AlphaWallet/alpha-wallet-android/pull/1436
