### ISSUE TITLE
About rounding the balance number

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1446]
For example, if the real balance is 1.537356754, the display balance should be 1.5373 instead of 1.5374

reason:
1. don't set a wrong expectation, users will expect they can get the full display balance available to use   
2. since we don't have a "send maximum balance" function, users may manually key in the number display in balance, they will key in 1.5374 which will trigger "insufficient balance" or if it is a contract call, will result in transaction fail (I did many times😢）

**Comment by JamesSmartCell** [comment]
@zhangzhongnan928 can you check the latest build to see if this is now fixed?

**Comment by zhangzhongnan928** [comment]
fixed
