### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1452]
![WechatIMG1889](https://user-images.githubusercontent.com/33795543/84091074-ce0aed80-aa36-11ea-9bab-f07171fd9fdc.jpeg)

Where can I find the translation repo for this page?

**Comment by JamesSmartCell** [comment]
Here:

https://github.com/AlphaWallet/alpha-wallet-android/blob/master/app/src/main/res/values-zh/strings.xml

**Comment by zhangzhongnan928** [comment]
updated.
