### ISSUE TITLE
Remove issuer: AlphaWallet

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1453]
![photo_2020-06-09 09 58 17](https://user-images.githubusercontent.com/33795543/84091473-d0ba1280-aa37-11ea-8d13-52516d03afc9.jpeg)
As those tokens are not issued by AlphaWallet, and we cannot get all of the token issuers to sign a TS file.

**Comment by James-Sangalli** [comment]
> ![photo_2020-06-09 09 58 17](https://user-images.githubusercontent.com/33795543/84091473-d0ba1280-aa37-11ea-8d13-52516d03afc9.jpeg)
> As those tokens are not issued by AlphaWallet, and we cannot get all of the token issuers to sign a TS file.

@zhangzhongnan928 the wallet is ready from the signer details (when the TokenScript is signed) therefore we are labelled as the issuer for that

**Comment by zhangzhongnan928** [comment]
> > ![photo_2020-06-09 09 58 17](https://user-images.githubusercontent.com/33795543/84091473-d0ba1280-aa37-11ea-8d13-52516d03afc9.jpeg)
> > As those tokens are not issued by AlphaWallet, and we cannot get all of the token issuers to sign a TS file.
> 
> @zhangzhongnan928 the wallet is ready from the signer details (when the TokenScript is signed) therefore we are labelled as the issuer for that

I understand, but to avoid confusion, we should remove it. As inside the token page, we already have Verified by xxx(iOS) and Green Lock(Andriod)

Today some new users ask me, why DAI and USDC's issuer is AlphaWallet....
