### ISSUE TITLE
Refactor to reduce the intermediary classes that just passes signable messages (12 layers to ~ 9 levels?)

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1454]
I copied the layers analysis from issue #1556 so we can just talk about simplifying it. This issue is about reducing the layered complexity in passing Signable data within the user-agent (the part programmed in Java), that is, simplify the passage of data from Layer 5 to Layer 12

--

# Layers inside WebView (before entering Java)

## Layer 1

The web page calls `eth.personal.sign()`

## Layer 2

At certain point in the `app/src/main/res/raw/alphawallet_min.js` this call is captured in a switch-case like this:

````
HookedWalletSubprovider.prototype.handleRequest = function(payload, next, end){
    …
    case 'eth_sign':
      // process normally
      address = payload.params[0]
      message = payload.params[1]
      …
      return

    case 'personal_sign':
      // process normally
      const first = payload.params[0]
      const second = payload.params[1]
      …
      msgParams.chainType = "ETH"
      waterfall([
        // (cb) => self.validatePersonalMessage(msgParams, cb),
        (cb) => self.processPersonalMessage(msgParams, cb),
      ], end)
````

This code is squeezed into `app/src/main/res/raw/alphawallet_min.js` so I can't just paste a link reference. (By the way why do we minify it in the first place? There is no bandwidth saving here since it's local to local).

## Layer 3

In the same file (`app/src/main/res/raw/alphawallet_min.js`) we have this:

````
HookedWalletSubprovider.prototype.processPersonalMessage = function(msgParams, cb) {
  const self = this
  waterfall([
    (cb) => self.approvePersonalMessage(msgParams, cb),
    (didApprove, cb) => self.checkApproval('message', didApprove, cb),
    (cb) => self.signPersonalMessage(msgParams, cb),
  ], cb)
}
````

## Layer 4

This time the call leaves `alphawallet_min.js` and enters `init.js`:

https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/res/raw/init.js#L29

# Layers in the user-agent (not accessible by WebView)

## Layer 5

Which is called from `SignCallbackJSInterface.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/web3/SignCallbackJSInterface.java#L67-L78

## Layer 6

The call is passed to here:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/ui/DappBrowserFragment.java#L846
And when the user confirms, here:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/ui/DappBrowserFragment.java#L1519-L1525

## Layer 7

Which is called from `DappBrowserViewModel.java `:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/viewmodel/DappBrowserViewModel.java#L181-L187

## Layer 8

Which is called from `TransactionRepository.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/repository/TransactionRepository.java#L249-L257

## Layer 9

Which is called from `KeystoreAccountService.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/service/KeystoreAccountService.java#L226

## Layer 10

Which is called from the same file:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/service/KeyService.java#L322

## Layer 11

It's called from `KeyService.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/service/KeyService.java#L1073

## Layer 12

Which is called from `CreateTransactionInteract.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/interact/CreateTransactionInteract.java#L27-L37

**Comment by JamesSmartCell** [comment]
@colourful-land we can add an extra path into the web3 inject callbacks for this, and then implement the code within the java wallet. You have access to sha3 via spongy castle. The web3j implementation of sha3 uses keccak at the backend.

**Comment by JamesSmartCell** [comment]
Closing.

It is indeed tempting to gaze from outside at the code and imagine that it could be done better. The world where this pipe dream happens hasn't yet collided with the reality of 1000's of models of Android phones and handling of flavours of Android libraries.

NB: 
1. Android key handling needs to deal with legacy libraries that behave differently from the contemporary ones.
2. Abstraction avoids code duplication, but adds layers.

Besides recent refactors have simplified this a little, but only as far as it is possible. My prediction for anyone attempting to refactor this would be: 

- Initial results would be good, code will be cleaner and some layers of abstraction can be removed!
- When I try to sign with my Android 9 device, or some Android 10 devices that use a PIN code or gesture it will fail.
- Roll back to previous existing code seeing that it actually was required after all, and curse that you wasted a few days of development time.
