### ISSUE TITLE
Allow user to set nonce in transaction advanced page

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1466]
![image](https://user-images.githubusercontent.com/33795543/84771985-a19a3700-b01d-11ea-8cd6-1f1c18d77a09.png)

Since we won’t implement “speed up” and “cancel” transaction features any time soon, we should at least provide a “manual” way to do it. Otherwise, user will stuck with the pending transaction and there is no easy way to solve it.

**Comment by JamesSmartCell** [comment]
We have implemented 'speedup' in the wallet now. Cancel has been written but not implemented as we are designing the UX for it, the process for which is only intuitive for an ethereum developer.

Not sure which circumstances that change nonce will be used for.

**Comment by zhangzhongnan928** [comment]
have speedup already
