### ISSUE TITLE
Analytics for AlphaWallet

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1476]
Apply Firebase analytics to base AlphaWallet.

Duplicate the work done for the Qoin fork on the main repo.

You will need to liase with @hboon to ensure only the features agreed upon for the main branch are implemented.

Specifically:

- Events need to be anonymous - no addresses, transaction hashes etc.

**Comment by ChintanRathod** [comment]
@hboon Do we have similar implementation like Qoin in iOS AlphaWallet or we have lower down the events?
Could you please address which events are integrated in iOS app? 
Link to the issue and output would be great if we have.

**Comment by hboon** [comment]
@ChintanRathod we haven’t settled on the list of events yet so the PR I have created doesn’t log any events. I have created some scaffolding for a different (but currently empty) set of events so it’s easier to keep the 2 iOS repos in sync. If we still don’t have a list of events after a while, we can probably just ship it without any events being logged. It still automatically logs sessions etc, which is still useful.

**Comment by hboon** [comment]
The iOS PR: https://github.com/AlphaWallet/alpha-wallet-ios/pull/1864

**Comment by ChintanRathod** [comment]
@hboon I understand. I will look after your given PR and implement in Android accordingly.

**Comment by ChintanRathod** [comment]
@hboon I checked given PR and it has MixPanel integration and no Firebase (I couldn't find any GoogleService-Info.plist file).
So are we integrating MixPanel for iOS and Firebase in Android? 
cc @JamesSmartCell

**Comment by hboon** [comment]
@ChintanRathod Mixpanel requires Firebase to send remote notifications for Android, but Mixpanel sends them iOS devices directly.

So for Android, you'll want Mixpanel + Firebase. If the Firebase SDK wasn't integrated previously (I thought it was). You'll need to check with James (or figure out yourself) that it doesn't pose a problem for China. It used to be that just including the Firebase (or was it Fabric) SDK would caused the app to crash when connected to China ISPs.

**Comment by hboon** [comment]
@ChintanRathod I wouldn't worry too much about how iOS implements analytics internally (other than to look for events to log, which we don't have yet). I suppose you'll want to structure or restructure the code as close to what was done for our other Android fork so it's easier to merge and maintain.
