### ISSUE TITLE
Get rid of two "+" buttons from the wallet tab 

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1485]
@ChintanRathod 

We need a quick change. 
Currently, we have two "plus" icons in the Wallet tab. This is very confusing, but we can fix this quite easy and quickly. 

![2020-06-26 12 24 27](https://user-images.githubusercontent.com/51817359/85848778-071ebe00-b7aa-11ea-99eb-1ac30fffe7a9.jpg)

So we need to change what follows:

1. Take out the very top + button and replace it by QR icon https://zpl.io/VYvX6Ge
2. This QR code icon will open "My Wallet Address". We already have this screen in Settings tab. So now, we will have two ways to access the same screen. First is QR Code icon in the Wallet tab, second is "My wallet Address" item in the Settings tab.
3. Currently, to add a Custom Token you can click very top "+" button. Now, you can open "Add /Hide Tokens" and there you will find + icon. 
4. Change text from "Show / Hide Tokens" to "Add / Hide Tokens"

![Plus](https://user-images.githubusercontent.com/51817359/85849125-a9d73c80-b7aa-11ea-823f-d397c0db2fa0.png)

**Comment by colourful-land** [comment]
@ChintanRathod I second this, this fix should be quickly done and released!

**Comment by ChintanRathod** [comment]
@colourful-land Generated PR, could you please check.
