### ISSUE TITLE
Update Input Fields look [Fiji]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1486]
Zeplin:

Blank
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?cseid=5e218a805b5b617d8eec7aef

Entering:
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?cseid=5e218c6773e393a79c640116

Entered:
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?cseid=5e218cbacf6a85ab00ee4d3b

Error:
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?cseid=5e218d1b0f5ab5ab7cdca668

![input-fields-android](https://user-images.githubusercontent.com/51817359/85870009-cab08980-b7cc-11ea-8bac-84d9a90bd8ed.jpg)

**Comment by tomekalphawallet** [comment]
You can pay a special attention to numeric keyboard (when entering amount)

a) dai/xdai bridge
<img width="810" alt="Screenshot 2020-06-26 at 16 49 51" src="https://user-images.githubusercontent.com/51817359/85870218-1105e880-b7cd-11ea-88ea-09729473c460.png">

b) send coin
<img width="814" alt="Screenshot 2020-06-26 at 16 50 16" src="https://user-images.githubusercontent.com/51817359/85870262-1ebb6e00-b7cd-11ea-98a5-dc0771587c52.png">

c) supply to defi
<img width="705" alt="Screenshot 2020-06-26 at 16 50 39" src="https://user-images.githubusercontent.com/51817359/85870330-2c70f380-b7cd-11ea-85b0-a83dbb1e05c0.png">

d) fiat on-ramp
<img width="831" alt="Screenshot 2020-06-26 at 16 51 35" src="https://user-images.githubusercontent.com/51817359/85870449-4dd1df80-b7cd-11ea-830c-7ce75db2d555.png">

**Comment by tomekalphawallet** [comment]
There was a very similar issue on iOS https://github.com/AlphaWallet/alpha-wallet-ios/issues/1742

**Comment by tomekalphawallet** [comment]
https://zpl.io/awRP9yN
https://zpl.io/aNg1d4D
https://zpl.io/VqqnGxJ

**Comment by tomekalphawallet** [comment]
<img width="583" alt="Screenshot 2020-06-26 16 59 03" src="https://user-images.githubusercontent.com/51817359/85871374-98a02700-b7ce-11ea-8a10-76d373410de6.png">

**Comment by JamesSmartCell** [comment]
@ChintanRathod address book can go in on a different PR, make this PR only about the appearance.
