### ISSUE TITLE
Update "Add / Hide Tokens" screen

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1487]
Zeplin:
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e209479cbb745a93fbda293/

This is how it looks now:
![2020-06-26 14 51 28](https://user-images.githubusercontent.com/51817359/85871563-dd2bc280-b7ce-11ea-87df-6d21b9d64681.jpg)

---

And this is how it should look like

<img width="413" alt="Screenshot 2020-06-26 17 03 40" src="https://user-images.githubusercontent.com/51817359/85871643-ffbddb80-b7ce-11ea-8454-8afd04fcaa89.png">

**Comment by JamesSmartCell** [comment]
@ChintanRathod use the 'glide' method in class TokenHolder, in method displayTokenIcon().

Move the iconCheck map into the assetDefinition service and have your new method check it so we only check for the icon once per app session (that boolean mapping links to the 'onlyRetrieveFromCache' which tells the glide library not to try downloading the icon again. Without this, the app checks the URL every time if no icon is found which is a waste of network bandwidth.

**Comment by tomekalphawallet** [comment]
We don't need QR Scanner icon in there. 
![2020-07-02 09 29 34](https://user-images.githubusercontent.com/51817359/86330511-138e9500-bc48-11ea-8276-2765798561de.jpg)

**Comment by ChintanRathod** [comment]
> @ChintanRathod use the 'glide' method in class TokenHolder, in method displayTokenIcon().
> 
> Move the iconCheck map into the assetDefinition service and have your new method check it so we only check for the icon once per app session - that boolean mapping links to the 'onlyRetrieveFromCache' which tells the glide library not to try downloading the icon again. Without this, the app checks the URL every time if no icon is found which is a waste of network bandwidth.

For Glide, it is providing temporary/permanent caching in memory. I will check if we are using that feature or not. I would say temporary download and reusing it is a good idea. 

Another question is in my mind like, how to bifurcate the list with 3 categories. 
- XX New token found 
- Displayed Tokens
- Hidden Tokens. 

I check response from service and could find matching criteria. Could you share idea how are we planning to handle it? 
![image](https://user-images.githubusercontent.com/4371780/86438517-59209000-bd24-11ea-99cf-b9b46268cacb.png)

**Comment by JamesSmartCell** [comment]
> > @ChintanRathod use the 'glide' method in class TokenHolder, in method displayTokenIcon().
> > Move the iconCheck map into the assetDefinition service and have your new method check it so we only check for the icon once per app session - that boolean mapping links to the 'onlyRetrieveFromCache' which tells the glide library not to try downloading the icon again. Without this, the app checks the URL every time if no icon is found which is a waste of network bandwidth.
> 
> @JamesSmartCell
> For Glide, it is providing temporary/permanent caching in memory. I will check if we are using that feature or not. I would say temporary download and reusing it is a good idea.

No need to check - we're already using it extensively and this is how we handle token icons.

> 
> Another question is in my mind like, how to bifurcate the list with 3 categories.
> 
> * XX New token found
> * Displayed Tokens
> * Hidden Tokens.
> 
> I check response from service and could find matching criteria. Could you share idea how are we planning to handle it?
> ![image](https://user-images.githubusercontent.com/4371780/86438517-59209000-bd24-11ea-99cf-b9b46268cacb.png)

I'm going to move handling this into a separate PR. For now, just show displayed tokens and hidden tokens. Displayed or hidden is based on the position of the switch.
