### ISSUE TITLE
Add Androad apk and iOS TestFlight download link in MagicLink landing page

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1488]
Please add Androad apk and Apple TestFlight download link in MagicLink landing page 
https://alphawallet.com/apk/Release-v3.00.2.apk
https://testflight.apple.com/join/HRsmubhS

![Screen Shot 2020-06-25 at 11 43 34 am](https://user-images.githubusercontent.com/33795543/85644086-52b56700-b6d9-11ea-9019-0b68c015ad99.png)

**Comment by colourful-land** [comment]
I think the magiclink landing page is currently still served by the code in the android-repo right?

**Comment by zhangzhongnan928** [comment]
> I think the magiclink landing page is currently still served by the code in the android-repo right?

Who should I assign this issue to?

**Comment by JamesSmartCell** [comment]
Can we have a fixed APK link? eg

https://alphawallet.com/apk/Android-Release.apk

This way we don't need to keep updating the APK link for each release. For legacy APK we could rename each one with its version number.

**Comment by zhangzhongnan928** [comment]
> Can we have a fixed APK link? eg
> 
> https://alphawallet.com/apk/Android-Release.apk
> 
> This way we don't need to keep updating the APK link for each release. For legacy APK we could rename each one with its version number.

Yes make sense 
https://alphawallet.com/apk/Android-Release.apk
Done, currently, it is the v3.00.2
