### ISSUE TITLE
Update Light, My QR Code, Browse buttons in Scan QR Code screen

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1495]
**Current:**

![2020-07-03 10 18 00](https://user-images.githubusercontent.com/51817359/86450122-5a988b00-bd19-11ea-9cfa-65a9a7084390.jpg)

**We need:** 
a) Light - tour on the light in your camera
b) My QR Code - switches to "My Wallet Address" screen
c) Browse - to select images from your Camera Roll

<img width="412" alt="Screenshot 2020-07-03 10 36 30" src="https://user-images.githubusercontent.com/51817359/86450329-a3504400-bd19-11ea-9716-e51bcd232425.png">

**Comment by JamesSmartCell** [comment]
Hi @ChintanRathod can you complete the controls? Browse may be more tricky to implement; there should be part of the existing QR scanner that parses images though; let's see if we can achieve this without needing additional libraries.

**Comment by tomekalphawallet** [comment]
@ChintanRathod You can take a look at how WeChat did this. Their scanner Is very good.

**Comment by ChintanRathod** [comment]
> @ChintanRathod You can take a look at how WeChat did this. Their scanner Is very good.

Sure. I will compare it.

**Comment by ChintanRathod** [comment]
> Hi @ChintanRathod can you complete the controls? Browse may be more tricky to implement; there should be part of the existing QR scanner that parses images though; let's see if we can achieve this without needing additional libraries.

OK. I will check for existing one and implement accordingly

**Comment by tomekalphawallet** [comment]
@ChintanRathod Chintan, to make it easier, let's make a version without a "Browse" for now. So only the light and switch to My Wallet Address. Can we release that this week? 
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5f040d37b4215b7cddae21f6/

**Comment by tomekalphawallet** [comment]
<img width="573" alt="Screenshot 2020-07-07 at 08 05 06" src="https://user-images.githubusercontent.com/51817359/86723863-93da3f00-c028-11ea-8ff5-6268742c84f1.png">

**Comment by ChintanRathod** [comment]
@tomekalphawallet Could you please help me to have a "Flash Off" icon? I temporary used from Android Assets but if you can would be great.

**Comment by JamesSmartCell** [comment]
> > Hi @ChintanRathod can you complete the controls? Browse may be more tricky to implement; there should be part of the existing QR scanner that parses images though; let's see if we can achieve this without needing additional libraries.
> 
> OK. I will check for existing one and implement accordingly

Let's see if we can use the existing library - not sure how difficult it will be to hook between the code that scans images and the camera image update. Hopefully we can pass the images in the format the scanner likes. Looks like this area of the source would be the useful code - we might be able to pass the image if we can convert to a 'BinaryBitmap':

```
if (source != null) {
                BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
                try {
                    rawResult = mMultiFormatReader.decodeWithState(bitmap);
                } catch (ReaderException re) {
                    // continue
                } catch (NullPointerException npe) {
                    // This is terrible
                } catch (ArrayIndexOutOfBoundsException aoe) {

                } finally {
                    mMultiFormatReader.reset();
                }
```

**Comment by ChintanRathod** [comment]
I have same implementation which converts the Bitmap into BinaryBitmap like below. 

![image](https://user-images.githubusercontent.com/4371780/86876599-b50f5e00-c102-11ea-9423-9e1467cd2470.png)

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet Could you please help me to have a "Flash Off" icon? I temporary used from Android Assets but if you can would be great.

https://zpl.io/bzg4vg4
