### ISSUE TITLE
Speed up transaction 

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1496]
Not sure if this function works. I speeded up the transaction, but this is still pending for about 8 minutes now. 
0x252d576642029b9e4651a21007fffa0a77679046b7a4da5368736eecef027d30
![2020-07-03 11 29 56](https://user-images.githubusercontent.com/51817359/86455243-9f73f000-bd20-11ea-97b7-372a448ec8c6.jpg)

Anyway, for better UI, you can use this:
<img width="684" alt="Screenshot 2020-07-03 11 26 18" src="https://user-images.githubusercontent.com/51817359/86454968-44da9400-bd20-11ea-8cbd-52537609eb69.png">
https://zpl.io/anqglkJ

**Comment by JamesSmartCell** [comment]
Hi @ChintanRathod can you update the app to reflect the spec?

@tomekalphawallet yes it works - the suggested increase is only 1 Gwei each time though, pending more investigation. I also added a touch sensor to the values as even frequent users didn't realise you can change the gas settings. I like the bubble that draws attention to the control.

**Comment by tomekalphawallet** [comment]
All good. Just keep in mind guys, that at one point we will also have a confirmation action sheet. So the flow would look slightly different (you can set speed by expanding a tab).

![send-eth-android-flow](https://user-images.githubusercontent.com/51817359/86566822-99714f80-bf6a-11ea-8987-f8efab2470e4.jpg)

**Comment by JamesSmartCell** [comment]
@ChintanRathod note that the above spec "Sent ETH" is outside the scope of this issue, this is a separate body of work on its own.
