### ISSUE TITLE
Preset gas limit for common transactions

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1497]
Like ETH transfer and standard ERC20 transfer. 
Currently, it is using a very high default gas limit. 
due to the high gas limit and gas price, users are not able to submit a transaction, as their wallet balance is lower than the estimate max gas fee.

**Comment by JamesSmartCell** [comment]
Does the recent enhancement which shows gas estimate and gas estimate cost help here? Try the latest release.

**Comment by zhangzhongnan928** [comment]
> Does the recent enhancement which shows gas estimate and gas estimate cost help here? Try the latest release.
different issue,
For example, 
The currently default gas limit in Android for an eth transfer is 90,000, the real usage is 21,000, if gas price is 1, 
with a gas limit at 21,000, I only need to have at least 21,000 Gwei to submit a transaction
If the gas limit is at 90,000, and my balance is below 90,000 Gwei, I won't be able to submit a transaction.

Users asked why they can submit an erc20 transfer in other wallets, but not AlphaWallet, although they have the same eth balance.

**Comment by JamesSmartCell** [comment]
Ah ok. I don't think the gas fee is factored in until the node call; but we can drop the limit for standard calls that we know in advance the exact gas fee. The gas estimate will catch and compensate for any token that appears to be ERC20 but which has a modified Transfer which has extra components and higher gas fee, so it's now safe to implement.
