### ISSUE TITLE
Scan QR Code in Build 3.00.4(117)

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1498]
![photo_2020-07-07 17 46 41](https://user-images.githubusercontent.com/33795543/86740347-ec85f800-c079-11ea-88ea-0f478e00da85.jpeg)

These 3 buttons have the same name, and none of them has any functions

**Comment by JamesSmartCell** [comment]
This is in known and a fix is in progress I think.

**Comment by ChintanRathod** [comment]
Issue is fixed in #1495
