### ISSUE TITLE
Ethereum card disappeared

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1507]
Add contract 0x26EaC4b2080C343621c9792C0F27EDD25E2c3197 as watch wallet

Manually add token 0x26EaC4b2080C343621c9792C0F27EDD25E2c3197

Then Ethereum card disappeared

![Screenshot_20200713-215339.png](https://user-images.githubusercontent.com/33795543/87302165-3bd59800-c554-11ea-8d0e-6e2ff8d48348.png)

**Comment by JamesSmartCell** [comment]
Fixed within #1520
