### ISSUE TITLE
face ID doesn't work (Galaxy Tab)

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1515]
Reproduce:

1) import wallet -> json
2) type password
3) system prompt "Provide authentication to create key" but nothing happens.

![IMAG1269](https://user-images.githubusercontent.com/548435/87635308-28a80f80-c782-11ea-9312-50346e4452b3.jpg)

**Comment by JamesSmartCell** [comment]
Yes the now deprecated authentication code needs to be bought up to date

**Comment by JamesSmartCell** [comment]
Note - this will be addressed when the updated Fiji security flow is implemented.

**Comment by JamesSmartCell** [comment]
@colourful-land Please test once more. It should be working now, close the issue if all good or bump it otherwise.
