### ISSUE TITLE
alphawallet flips upside down when user click "import"

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1522]
Reproduce:

1. Put the device side way.
2. Do the import. See this video
(If you can't reproduce the issue, rotate the device 180 degrees then start again. It seems "Import" always makes the app goes to one specific side).

![screenrecord](https://user-images.githubusercontent.com/548435/87996056-8ba7f680-cb34-11ea-9806-1370b2f08d1e.gif)

**Comment by JamesSmartCell** [comment]
Closed by #1530
