### ISSUE TITLE
Re-add the gradle switch for removing analytics

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1532]
Previously you added code for a switch in gradle to be able to not add the firebase libraries if switched off in the build.

In the new PR these weren't implemented.

Can you re-implement the gradle switch, as it was a good idea to easily switch between firebase and non-firebase builds.

**Comment by ChintanRathod** [comment]
@JamesSmartCell Till my knowledge, due to Product Flavor and different directories we need to create, we have dropped to include that into PR. 
Could you please clarify on this part? As if we want to achieve that, we need to go with 2 product flavors
- AlphaWallet
- NoAnalytics

And below code will help to import dependency but it is purely depend upon the flavor. 

```
def task = gradle.startParameter.taskNames[0] ?: ""

afterEvaluate { Project project ->

	if (!task.toLowerCase().contains("noanalytics")) {
		apply plugin: 'com.google.gms.google-services'

		dependencies {
			implementation 'com.google.firebase:firebase-analytics:16.5.0'
		}
	}
}
```

**Comment by JamesSmartCell** [comment]
I have re-visited this. We need to remove the current implementation of flavours which is completely incorrect and is causing a lot of issues. If we re-target the wallet we can do it in situ.

Once we have removed the current badly implemented flavour system it will be simple to implement this correctly.

Please put this issue on hold until we've done this.

**Comment by ChintanRathod** [comment]
@JamesSmartCell we did this flavoring in #1591 issue. This issue can be closed.

**Comment by colourful-land** [comment]
@ChintanRathod next time, just close the issue and if you want to be polite you can say "reöpen it if I was wrong". seeking permission took too much of our resources
