### ISSUE TITLE
Update WalletConnect icon

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#1534]
Zeplin:
https://zpl.io/VY7JKYk

<img width="392" alt="Screenshot 2020-07-27 12 01 48" src="https://user-images.githubusercontent.com/51817359/88530015-0f645600-d001-11ea-88a6-783a5267a4a8.png">

**Comment by ChintanRathod** [comment]
PR is merged so closing this ticket.
