### ISSUE TITLE
Gas limit is different than estimation

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1540]
Android 3.0.8 (Playstore version) shows a gas limit that equals to gas estimation.
Beta shows a gas limit that is different than the estimation.

Both screenshots were taken no more than 5 minutes apart.

| Official 3.0.8| Beta 3.1.1 |
| --- | --- |
| ![imagen](https://user-images.githubusercontent.com/548435/88813089-d512d880-d1fb-11ea-9149-bb66ef172cdc.png)|![imagen](https://user-images.githubusercontent.com/548435/88813139-e5c34e80-d1fb-11ea-9d1f-056631f3867e.png)|

**Comment by colourful-land** [comment]
Issue closed because I forgot to notice that the gas limit is actually 4 times not 4/1

**Comment by AW-STJ** [comment]
Issue is fixed in 3.11.0-beta (123)
