### ISSUE TITLE
Bad first impression

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1546]
![Screenshot_2020-08-01-00-15-12](https://user-images.githubusercontent.com/548435/89043749-5305e980-d38c-11ea-8deb-8832f6eaed15.png)
Manage the space a bit better by moving CREATE A NEW WALLET to the centre.

**Comment by ChintanRathod** [comment]
@colourful-land Could you please let me know what's the resolution of the device you did test? 
I checked for other "landscape" views in devices and it seems good to me.
