### ISSUE TITLE
hitting browser shouldn't take the user back to the home page

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1547]
Reproduce:

1. go to work in a dapp for 10 mins
2. hit "Browser"
3. the current page is now the home page
4. hit back 
5. user goes back to wallet instead of the dapp that user worked with for 10 mins. (issue #1516 - this issue is about **the user surprise at step 3.**

Expected: (@tomekalphawallet what do you think?)

- go to work in a dapp for 10 mins
- hit "Browser"
- nothing happens
- hit "Browser" again
- the current page is now the home page

Argument:
- Why would anyone want to hit "Browser"?

Answer:
- I was wanting to check Transactions to see the one I just sent in DAPP, and go back to Browsing but because I was thinking "I need to go back to browser" I hit browser.

Assigning to @tomekalphawallet might this be done in two OSs

**Comment by hboon** [comment]
For context, hitting a tab button on iOS pops the entire stack. It’s default functionality. We could disable it. BC does.

I suppose Android complicates this a bit more with the concept of a, sometimes, ambiguous but system-wide back button.

**Comment by colourful-land** [comment]
> For context, hitting a tab button on iOS pops the entire stack. It’s default functionality. We could disable it. BC does.
> 
> I suppose Android complicates this a bit more with the concept of a, sometimes, ambiguous but system-wide back button.

I think that comment is more appropriate on https://github.com/AlphaWallet/alpha-wallet-android/issues/1516 because back button only has a cameo appearance  in this issue.

**Comment by JamesSmartCell** [comment]
> Reproduce:
> 
> 1. go to work in a dapp for 10 mins
> 2. hit "Browser"
> 3. the current page is now the home page
> 4. hit back
> 5. user goes back to wallet instead of the dapp that user worked with for 10 mins. (issue #1516 - this issue is about **the user surprise at step 3.**
> 

This was the behaviour designed into the origin UX.

Because we didn't have a 'home' button, pressing the browser tab while on the browser screen will take you back home.

This may not be a good design, because I suspect impatient users will do multi-tapping of the browser button.

It looks like what you're experiencing is the unexpected intersection of two separate systems that both work correctly in their own place but combined in unexpected ways don't work intuitively.

Suggestion - have an actual 'home' button, or dispense with it altogether, and just keep the back/forward buttons.

**Comment by JamesSmartCell** [comment]
Since the Activity overhaul the wallet is more responsive but you will be using a pre-activity overhaul app version.

Probably - hitting the browser tab button repeatedly is a consequence of a not-so-responsive app.

**Comment by AW-STJ** [comment]
@tomekalphawallet: As a designed what is your thinking on creating a dedicated home button for Browser on Android?
