### ISSUE TITLE
v3.00.10 hotfix (unreleased thanks to this): transaction displayed as rejected but is pending according to Etherscan

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1548]
1. Send a tx with low fee (0.0126ETH)
2. It is displayed as "Successful" then if you observe "Transactions" it is displayed as "Rejected"
(this seem to suggest that αW knows the tx is not successful - otherwise it should display this as rejected after a few days)
3. such a "Rejected" transaction can still be viewed on Etherscan and is  displayed as pending.

I'm going to leave it for 8 hours to see if (in the unlikely case it is accepted) will this update the states from Rejected to "accepted".

**Comment by JamesSmartCell** [comment]
@colourful-land Can you show the TX hash?

If AW lists the tx as rejected then the node can no longer see the transaction in the pool, and it wasn't written to the chain.

What could be happening here:

1. Most likely! There is an issue with AW's detection of the tx.
2. Etherscan has a time delay with noticing that the TX has been dropped.

Note that, I adapted the AW code that it will still scan etherscan for the transaction, and that if a transaction should ever appear then it will appear in the transaction page.

Let's keep a watch on the transaction.

**Comment by colourful-land** [comment]
> @colourful-land Can you show the TX hash?

https://etherscan.io/tx/0xba57597c9182b72d2b3fcd094bdbc0f0df47425279f5a7f15a22955a22769eb0

It is still displayed as pending but αW displayed it as rejected 𝑜𝑢𝑡𝑟𝑖𝑔ℎ𝑡. that is, I have never seen it been displayed as penidng in alphawallet - it has been rejected since its appearance

**Comment by colourful-land** [comment]
It's even worse - now the transaction disappeared from the "Transactions" tab.

**Comment by JamesSmartCell** [comment]
Checked the transaction pool, the tx is no longer in the pool (dropped), so Etherscan has a slow update to detect pool rejection.

Other than somehow deleting your old rejection notification AW is behaving correctly. I will investigate how a transaction could have been deleted.

**Comment by colourful-land** [comment]
@AW-STJ can you build from the 3.00.10 hotfix branch?

Then:
1. Send tx with 50% to 70% of the average fee.
2. Observe if it is rejected in the Transaction tab.
3. If it is, observe if the same TX is not found in Etherscan and EthExporer.

You can also do it with, say, 10% of the average fee, which should guarantee and share what you see.

**Comment by colourful-land** [comment]
> Other than somehow deleting your old rejection notification AW is behaving correctly. I will investigate how a transaction could have been deleted.

Asking Sunil to verify that with comparison to EthExplorer. Maybe it's not Etherscan drops too slowly, but we drops too quickly. Communist survival skill - behave like thy neighbour.

**Comment by AW-STJ** [comment]
Looks like the transaction is pending in Etherscan but not found on Ethplorer or Ether chain
