### ISSUE TITLE
trivial issues on browser url bar

### ISSUE THREAD

**Issue by lyhistory** [AlphaWallet/alpha-wallet-android#1549]
this is more of a improvement, not a serious issue but impact on the user experience a lot,
when I use the browser module, each time I want to search something, I'll tap on the url bar,
and just like the screenshots in below, sometimes it will expand a bit, still ok for me to click on the 'close' icon to clear the url,
but sometimes it won't expand, so I have to scroll to the end to find the 'close' icon,
![image](https://user-images.githubusercontent.com/1522513/89103110-fbc25080-d441-11ea-9dbd-5bd9138e14f1.png)

![image](https://user-images.githubusercontent.com/1522513/89103101-f402ac00-d441-11ea-8777-c1a1dd0a2287.png)

based on experience on other similar browser app, my suggestion is that it will be better if you  can just clear out the url bar automatically, if user want to copy the url, you can put it in the dotdotdot tray

**Comment by JamesSmartCell** [comment]
Thanks, I also have noticed this but not sure what's causing it. I'll assign.

This control doesn't always work as expected - sometimes it expands when you click on it, sometimes it doesn't.

Can you change the following:

1. Consistently expand the search bar when clicked on.
2. Ensure the 'x' clear button always appears when you click on the search bar.
3. If the bar is empty, display a 'paste' button on the end similar to how the address input bar works.

**Comment by lyhistory** [comment]
by the way, I noticed another related issue:
when I am at https://kyberswap.com/swap,
the browser tab button stop working, I try to get back to the dapp home page, but no response when I tap on the 'browser'
