### ISSUE TITLE
Add custom linking to Uniswap to tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1564]
So for all major ER20 tokens + Ether we are adding custom links, that will allow users to access Uniswap quickly. Remember that with custom linking you can have already preselected coin. So when you are starting with USDC, it should be already preselected in Uniswap.

https://uniswap.org/docs/v1/frontend-integration/custom-linking/

Ethereum:
https://app.uniswap.org/#/swap?use=v1&create-exchange?tokenAddress=0x0F5D2fB29fb7d3CFeE444a200298f468908cC942

Zeplin:
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/dashboard?seid=5f368622f1e73c2976900afb

![Zrzut ekranu 2020-08-14 o 14 46 23](https://user-images.githubusercontent.com/51817359/90250811-ff3fd980-de3c-11ea-9c65-57590d23e0ed.png)

**Comment by JamesSmartCell** [comment]
@tomekalphawallet So this is adding a default action on the function bar for any erc20 supported by Uniswap?

Is there a definitive list of supported tokens somewhere or would someone need to go onto Uniswap to list all the supported tokens by hand?

**Comment by tomekalphawallet** [comment]
> @tomekalphawallet So this is adding a default action on the function bar for any erc20 supported by Uniswap?

yes

https://github.com/MyEtherWallet/etherwallet/blob/mercury/app/scripts/tokens/ethTokens.json

**Comment by hboon** [comment]
So to sum it up:

Add a TokenScript action for a subset of ERC20 tokens, when launched, it opens Uniswap with the current token.

Longer:

* Add a TokenScript action for a subset of ERC20 tokens. This action is called "Exchange with Uniswap".
* When the action is launched, pop the navigation stack and switch to the browser tab, loading the URL as described by https://uniswap.org/docs/v1/frontend-integration/custom-linking/ with the token as the `inputCurrency`.
* The list of tokens is at https://github.com/AlphaWallet/alpha-wallet-android/issues/1564#issuecomment-677485732
* Probably look at `TokenInstanceAction.ActionType.erc20Send` to see how it's added

@tomekalphawallet that page may be outdated (since it's archived), and it seems like an attempt to list every ERC20 token rather than the list supported by Uniswap. Is that the correct list?

**Comment by hboon** [comment]
@tomekalphawallet that page may be outdated (since it's archived), and it seems like an attempt to list every ERC20 token rather than the list supported by Uniswap. Is that the correct list?

**Comment by tomekalphawallet** [comment]
<img width="995" alt="Screenshot 2020-08-20 at 13 26 14" src="https://user-images.githubusercontent.com/51817359/90764568-c4c8b780-e2e8-11ea-99c1-6fbbb7bcbead.png">
https://github.com/trustwallet/assets

**Comment by tomekalphawallet** [comment]
if you want, I can make you a list. But I assume it can be found online.

**Comment by hboon** [comment]
@tomekalphawallet it’s alright, we’ll ask Vlad to grab it. Should be easier for him to inspect the page. Thanks.

**Comment by hboon** [comment]
Will ask him to post back when he has the list.

**Comment by tomekalphawallet** [comment]
https://etherscan.io/tokens

I even started entering the list, but I think it's not faster than going one by one from the page above. 

[ERC20 Tokens.xlsx](https://github.com/AlphaWallet/alpha-wallet-android/files/5102948/ERC20.Tokens.xlsx)

**Comment by vladyslav-iosdev** [comment]
> https://etherscan.io/tokens
> 
> I even started entering the list, but I think it's not faster than going one by one from the page above.
> 
> [ERC20 Tokens.xlsx](https://github.com/AlphaWallet/alpha-wallet-android/files/5102948/ERC20.Tokens.xlsx)[![](chrome-extension://gmpljdlgcdkljlppaekciacdmdlhfeon/images/beside-link-icon.svg)](https://docs.google.com/viewer?url=https%3A%2F%2Fgithub.com%2FAlphaWallet%2Falpha-wallet-android%2Ffiles%2F5102948%2FERC20.Tokens.xlsx&embedded=true&chrome=false&dov=1)

<img width="481" alt="Screenshot 2020-08-20 at 15 33 01" src="https://user-images.githubusercontent.com/55975226/90770505-8d630680-e2fa-11ea-9215-4dc2772a9cba.png">
am i understand right, i need to find all these tokens and update doc with their addresses, and other info?

**Comment by hboon** [comment]
Yes. Just those from Uniswap. Just stick it into the PR or make a list here or at the other issue. The list will be outdated and we’ll only maintain the one in the code anyway..

**Comment by vladyslav-iosdev** [comment]
The list of uniswap tokens.
https://docs.google.com/spreadsheets/d/1oWj4gWrII84pP07-A0zn9YHmlkuZy0sKG3f6h_dvHkA/edit?usp=sharing

**Comment by hboon** [comment]
@vladyslav-iosdev works for me. Thanks.

**Comment by JamesSmartCell** [comment]
@ChintanRathod this should be supported by an addition to the FunctionButtonBar class. You might have to make a helper class which handles detecting if it's needed, as we might need to re-use elsewhere (and don't want to make the FunctionButtonBar too much more complicated).

**Comment by colourfreak** [comment]
The only difference is that is has to be linked to 1inch instead of Uniswap https://github.com/AlphaWallet/alpha-wallet-android/issues/1669

**Comment by hboon** [comment]
For reference, the bulk of the details are in https://github.com/AlphaWallet/alpha-wallet-ios/pull/2269/files#diff-80fd5c6670e9a201e0ffb8bf29d27f88f8d9a5730e60df8c39665ba3f298b620 for iOS
