### ISSUE TITLE
Hide console button from the wallet

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1566]
The console button is not working in Android.

@colourful-land & @JamesSmartCell  Do we really need Console button in the first place?

**Comment by JamesSmartCell** [comment]
It's copied from the spec, but don't know what it's for.

**Comment by AW-STJ** [comment]
Since we don't see any functionality for now, let us hide it.

cc: @colourfreak, for your information as well.

**Comment by hboon** [comment]
Hold first, till https://github.com/AlphaWallet/alpha-wallet-ios/issues/2500#issuecomment-774410629 is resolved.

**Comment by ChintanRathod** [comment]
@AW-STJ Should we close this ticket as mentioned ticket in iOS is closed without implementation?

**Comment by AW-STJ** [comment]
Yes.. closing the ticket as we now know that this is for displaying tokenscript errors. TokenScript would have more applications in the coming months, so let us keep it as it is.
