### ISSUE TITLE
Add AlphaWallet to WalletConnect repo

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1572]
Can you please add AlphaWallet information to the WalletConnect repo?
https://github.com/WalletConnect/walletconnect-monorepo/tree/next/packages/helpers/mobile-registry/logos
https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/helpers/mobile-registry/registry.json

and https://walletconnect.org/wallets

**Comment by colourfreak** [comment]
@hboon Shall we transfer this issue to AlphaWallet-web3-provider repo?

**Comment by hboon** [comment]
This one's done. But there might be separate work needed because of https://medium.com/walletconnect/introducing-walletconnect-cloud-registry-c17ac580f33. Will follow up separately.
