### ISSUE TITLE
Wallet Import: ETC address is different to ETH Main address in Metamask. Verify whether this is an issue on our side or not

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1576]
The issue was reported in our support group. Verified that Trust uses a different mechanism for their ETC wallet. 

Need to decide whether this is an issue or not.

Seed Phrase for testing (generated from Trust): vote code smoke muffin jungle panda lyrics glance sister blood spatial stay

![image](https://user-images.githubusercontent.com/61957841/91532161-422ba200-e951-11ea-87fe-9276a8c14943.png)

**Comment by hboon** [comment]
Oh, they use a different derivation path. Ethereum 60, ETC 61 for the coin type. We always use 60.

**Comment by JamesSmartCell** [comment]
> Oh, they use a different derivation path. Ethereum 60, ETC 61 for the coin type. We always use 60.

What does it mean? Is this related to the default 'password salt' for key derivation, that we leave blank.

**Comment by hboon** [comment]
No, it’s in the derivation path. This https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Coin_type

**Comment by JamesSmartCell** [comment]
Ah I see

**Comment by AW-STJ** [comment]
After testing a couple of options, found out that the wallets that use 12 phrase seed phrase derive ETC wallet address similar to the how Trust does it. 

So let us get the implement ETC 61 in our wallets too.

**Comment by hboon** [comment]
This might be tough. Probably have to treat it as a project.

**Comment by zhangzhongnan928** [comment]
> After testing a couple of options, found out that the wallets that use 12 phrase seed phrase derive ETC wallet address similar to the how Trust does it.
> 
> So let us get the implement ETC 61 in our wallets too.

@AW-STJ in the title you says "ETC address is different to ETH Main address in Metamask."
I just add ETC to Metamask, it behaves the same as AlphaWallet.

"found out that the wallets that use 12 phrase seed phrase derive ETC wallet address similar to the how Trust does it."
Coinbase Wallet behaves the same as AlphaWallet.

let's keep it in the current way.
