### ISSUE TITLE
There is no requestAccounts method ,shuold update the js && initJs file  ASAP

### ISSUE THREAD

**Issue by SephirothLT** [AlphaWallet/alpha-wallet-android#1587]
There is no requestAccounts method ,shuold update the js && initJs file  ASAP

**Comment by SephirothLT** [comment]
@corymsmith

**Comment by JamesSmartCell** [comment]
@James-Sangalli Does our web3.js & init code support requestAccounts?

**Comment by James-Sangalli** [comment]
> @James-Sangalli Does our web3.js & init code support requestAccounts?

No, only enable.
