### ISSUE TITLE
crash upon selecting network

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1598]
Reproduce:

![bug_network_select](https://user-images.githubusercontent.com/548435/93064397-d3717700-f6ba-11ea-90ff-f7671ec7aea9.gif)

The logcat might have the error (perhaps around this line:

    ATAL EXCEPTION: RxCachedThreadScheduler-12

[adb_logcat.txt](https://github.com/AlphaWallet/alpha-wallet-android/files/5217206/adb_logcat.txt)

**Comment by JamesSmartCell** [comment]
Note that this is the playstore version. May not be reproducable with current source.
