### ISSUE TITLE
Browser becomes unresponsive

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1621]
This is a issue that is hard to replicate. But the browser gets a dark overlay and becomes unresponsive.

Normally happens when switching between multiple websites. Here is a screen recording of how it starts to happen.

Screen Recoding: https://drive.google.com/file/d/1-lfu6OVH4gggEYamKpACkk0xkidX-N9Q/view?usp=sharing

Build: 3.20.2(130)

**Comment by JamesSmartCell** [comment]
Thanks for reporting, got it fixed.
