### ISSUE TITLE
Support wallet names 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#1624]
like so https://github.com/AlphaWallet/alpha-wallet-ios/pull/2178

**Comment by JamesSmartCell** [comment]
Could you clarify if this is or is not for main AlphaWallet?

This feature was implemented in Android but was explicitly removed by a UX update from @colourfreak in Zeplin , and also was consistently opposed by @hboon previously.

**Comment by JamesSmartCell** [comment]
Requires clarification from @James-Sangalli . Could you link to the Zeplin page which shows how to implement this feature? It was previously in the design but was explicitly removed.

**Comment by James-Sangalli** [comment]
Dropping as per Tomek's design
