### ISSUE TITLE
general dependency upgrade

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1636]
αW started 2 years ago, many libraries have since upgraded. Noticeably:

- com.android.tools.build:gradle is now 4.x.x
- gradle version is 5.x.x 
- Android SDK Build Tools is now 30.x.x  
- We used NDK 21.0.x - currently it's 21.3.x
- some of the build.gradle content isn't compatible with the upcoming gradle-7
- some build.gradle options, AndroidManifest might be deprecated.
- Amazon Mobile SDK is now 2.19 where we used 2.2

---

Note that the BC fork already is using the latest Amazon mobile SDK in `app`; other than that, both should have the same `app/gradle.build` (I think?).

````

    // Amazon Android SDK
    implementation 'com.amazonaws:aws-android-sdk-core:2.2.+'
    implementation 'com.amazonaws:aws-android-sdk-lambda:2.2.+'
    implementation 'com.amazonaws:aws-android-sdk-core:2.19.+'
    implementation 'com.amazonaws:aws-android-sdk-lambda:2.19.+'

````

**Comment by JamesSmartCell** [comment]
Closing for now as this isn't the correct way to handle this.

Work is in progress to upgrade the wallet to the AndroidX libraries which this issue is in conflict with. Once this upgrade takes place we can re-consider this issue.
