### ISSUE TITLE
Add CoFi token icon

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1641]
0x1a23a6BfBAdB59fa563008c0fB7cf96dfCF34Ea1

https://app.zeplin.io/styleguide/5e0b15e46049c216fb7ab4d5/components?coid=5f7f16cde4c19b1204906859

**Comment by JamesSmartCell** [comment]
@hboon I'll add it into our global icon repo so it can be picked up procedurally rather than needing to add it into the bundle.

https://github.com/AlphaWallet/iconassets
