### ISSUE TITLE
Update Xtoken and Cofi tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1645]
Xtoken:
https://zpl.io/25Lk44e

Cofi:
https://zpl.io/anxl33Q

**Comment by JamesSmartCell** [comment]
Best to submit a PR to the repo that we draw these icons from:

https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets

This will fix both iOS and Android in one go (assuming that iOS followed the same spec we laid down).
