### ISSUE TITLE
Show recent transactions, after first install

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1659]
Need to populate the recent transactions fields, after the wallet is imported. Right now only the transactions initiated after importing or creating the wallet is displayed there.

![Screenshot_20201031-195316_AlphaWallet.jpg](https://user-images.githubusercontent.com/61957841/97775232-38255a00-1bb3-11eb-8c23-1af40adc7954.jpg)

The wallet has transactions on this token.

**Comment by AW-STJ** [comment]
@colourfreak - need your guidance here. What should be shown under recent transactions? Once we confirm the thinking will align both Android and iOS to that.

**Comment by colourfreak** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/2157

**Comment by colourfreak** [comment]
This can be a blank canvas even but we need to make this change first. 

https://github.com/AlphaWallet/alpha-wallet-android/issues/1237

**Comment by JamesSmartCell** [comment]
Yes there is an issue here - I need to revisit the filter
