### ISSUE TITLE
optimise the display of the message 'insuffucient fund'

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#166]
Get message 'insufficient funds for gas * price + value' when there are sufficient funds -> Reproduce:

1. Import the wallet `0x71c650d7d5416c6efa31758ff6430ba63629bb0f` (get key from #163)
2. Check the balance is 0.03Eth
3. Click this link*, which asks for 0.01Eth.
4. Choose "Purchase".

* https://app.awallet.io/AAAnEFsBB0Omaj8IBoF06PAFESqLLHpQeoIjNQFdz_0iRbTn97yKTlIlbeCB0pFt9iqY4Yqb_87QlAU_X0QmiB4_nqFeXZpp6ZnkjypD4Mwd5iNF7gfDeoXLm5GFHA==

What happened:
5. get the said error.

What should happen:
5 - we verified that a transaction costs 0.00177 by experiment, therefore the balance should be enough for purchase.

**Comment by colourful-land** [comment]
@farrahfazirah need to integrate this to some of the design docs

**Comment by miang719** [comment]
bump @farrahfazirah

**Comment by James-Sangalli** [comment]
@colourful-land still an issue?

**Comment by James-Sangalli** [comment]
Gas price plus tx cost can override your final balance. closing this
