### ISSUE TITLE
Change the “Exchange with Uniswap” button to 1inch

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1669]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/2265

**Comment by zhangzhongnan928** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/2265#issuecomment-725226630

**Comment by colourfreak** [comment]
What's the status of this change? Why it takes so long?
