### ISSUE TITLE
Improve Recipient input field

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1681]
The Recipient input should be lower. And the empty state looks different. 
1) Move this down by eight points. 
![2020-12-01 09 55 10](https://user-images.githubusercontent.com/51817359/100718205-57362800-33bb-11eb-8525-28f56c1e3bd9.jpg)

2) Improve how it works. As far I know this is a native android behavior. 

So by default you have: 
<img width="417" alt="Screenshot 2020-12-01 at 09 56 05" src="https://user-images.githubusercontent.com/51817359/100718358-8ba9e400-33bb-11eb-8a94-75cd4e9e14b2.png">

Zeplin component:
https://zpl.io/aRZBx0g

----

When you are entering:
<img width="416" alt="Screenshot 2020-12-01 at 09 56 35" src="https://user-images.githubusercontent.com/51817359/100718542-c57aea80-33bb-11eb-8efb-3471a76939f1.png">

Zeplin component:
https://zpl.io/Vqp8Yxl

----

When you entered:
<img width="402" alt="Screenshot 2020-12-01 at 09 56 42" src="https://user-images.githubusercontent.com/51817359/100718700-ed6a4e00-33bb-11eb-8cf9-c28d59353c2d.png">

Zeplin component:
https://zpl.io/awvB6W1

----

Update the bar above. it should be "Recipient" instead of "Recipient's Address"

<img width="417" alt="Screenshot 2020-12-01 at 09 56 05" src="https://user-images.githubusercontent.com/51817359/100719013-59e54d00-33bc-11eb-9c2b-3570201be871.png">

----

Also, make sure that input fields have a 16pt margin on each side.

**Comment by JamesSmartCell** [comment]
We won't be able to do the '...' split in the input pane - I don't think that would be an acceptable practice for Android, in case the user wants to edit one of the digits that are hidden. I'll update the margins - we need to have dynamic margins on android though for different  screen dimensions.

**Comment by colourfreak** [comment]
https://material.io/components/text-fields

<img width="916" alt="Screenshot 2020-12-01 at 11 48 02" src="https://user-images.githubusercontent.com/51817359/100731015-2100a480-33cb-11eb-8b07-75e7e1a4b4fa.png">

**Comment by JamesSmartCell** [comment]
@colourfreak please check the latest version and close if complete.
