### ISSUE TITLE
Improve Amount input field

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1682]
You have all components here: 
https://zpl.io/bJr5dgx
https://zpl.io/2pA7BKy

1) So make sure the spacing from the top to the token symbol is right. 

<img width="998" alt="Screenshot 2020-12-01 at 10 08 48" src="https://user-images.githubusercontent.com/51817359/100719678-3d95e000-33bd-11eb-90bc-011056353713.png">

2) Please stick to the right spacing, sizes, colors, fonts. You have it all in the Zeplin.
3) When you are switching from ETH to USD, the symbol should change to: 

<img width="957" alt="Screenshot 2020-12-01 at 10 13 23" src="https://user-images.githubusercontent.com/51817359/100720135-db89aa80-33bd-11eb-90d9-85aba0f3b646.png">

4) If you want to switch to another coin, you have to be very precise when tapping on the arrow. Make the tappable area wider. So you could tap on "ETH" to switch to USD. So red should be interactive, not just blue.

<img width="549" alt="Screenshot 2020-12-01 at 10 13 42" src="https://user-images.githubusercontent.com/51817359/100720370-2b687180-33be-11eb-9798-c440b99417c5.png">

**Comment by JamesSmartCell** [comment]
If I use the same spacing as Zeplin the control appears incorrect on different platforms; it doesn't look anything like in the zeplin picture.

Will update the click areas.

**Comment by colourfreak** [comment]
> If I use the same spacing as Zeplin the control appears incorrect on different platforms; it doesn't look anything like in the zeplin picture.

What do you mean? I didn't get it.

**Comment by JamesSmartCell** [comment]
I mean, if I use the actual 'dp8' it won't look anything like how it looks in the Zeplin spec. That is, unfortunately how Android works. Justin made a compatibility library that attempts to compensate for this; it's a lot better than before but still not perfect.

**Comment by JamesSmartCell** [comment]
I'll make a new build today and post it on the UI group, you can let me know if it's a lot closer to what you expect.

**Comment by colourfreak** [comment]
> I mean, if I use the actual 'dp8' it won't look anything like how it looks in the Zeplin spec. That is, unfortunately how Android works. Justin made a compatibility library that attempts to compensate for this; it's a lot better than before but still not perfect.

Zeplin is made for this. There must be a way to fully reflect what is in the design. All I need to know from you or Justin it to how to send it right to Zeplin. It has many features and options. And extensions. 

https://extensions.zeplin.io/

**Comment by JamesSmartCell** [comment]
@justindg can you comment on this issue? I think you may have the best info on this for Android.

**Comment by justindg** [comment]
I could do a few improvements, will try to get it as close as possible. @JamesSmartCell @colourfreak

**Comment by justindg** [comment]
Will be solved via #2336

**Comment by justindg** [comment]
Fixed via #2362
