### ISSUE TITLE
Improve Activity design

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1683]
First, take a look at how great it looks on iOS. We need to align the design with Zeplin design:
https://zpl.io/VDevWP3

Component:
https://zpl.io/V0BRJMx
https://zpl.io/257YAmJ
https://zpl.io/2Gr4W59

<img width="1166" alt="Screenshot 2020-12-01 at 10 18 00" src="https://user-images.githubusercontent.com/51817359/100720590-8732fa80-33be-11eb-8dd0-fb5c9eff3676.png">

**Comment by JamesSmartCell** [comment]
OK I see, the elements are spaced further apart and appear the same as the TokenScript events.

**Comment by JamesSmartCell** [comment]
@colourfreak please check the latest version and close if complete.

**Comment by colourfreak** [comment]
Well done
