### ISSUE TITLE
Improve Sending ETH ActionSheet

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1685]
1) Confirm Transaction top bar should be higher. Now this is 50, it should be 60 pt. 
<img width="868" alt="Screenshot 2020-12-01 at 10 30 51" src="https://user-images.githubusercontent.com/51817359/100721936-4a680300-33c0-11eb-9a5f-5f4c22aec97e.png">

https://zpl.io/V0KlpXl

2) Make sure that if you want to expand Recipient, you can click anywhere in the cell, not only the arrow. 

<img width="974" alt="Screenshot 2020-12-01 at 10 32 30" src="https://user-images.githubusercontent.com/51817359/100722218-a92d7c80-33c0-11eb-8c11-5089a7b301e4.png">

3) Delete Ethereum symbol

<img width="435" alt="Screenshot 2020-12-01 at 10 34 12" src="https://user-images.githubusercontent.com/51817359/100722389-dbd77500-33c0-11eb-8bff-a4ee602d0cfb.png">

**Comment by JamesSmartCell** [comment]
@colourfreak What do you think about the chain icon? I added it because sometimes I might have forgotten which chain I'm signing a transaction for. It's a final precaution to check before signing. Although a user could just slide the TX pane down, glimpse and slide it back up.

**Comment by colourfreak** [comment]
Yeah, but when you are sending USDC it will be ETH symbol again. Then you might think that something is wrong. If you are sending an email, you don't care if this is TCP/IP or any other protocol.

**Comment by colourfreak** [comment]
We could inform users only if this is something else than Ethereum mainnet.

**Comment by JamesSmartCell** [comment]
> We could inform users only if this is something else than Ethereum mainnet.

I like this solution. Perhaps we use the colour coded text network name (eg Ropsten)  rather than symbol, as there's less chance to confuse.

**Comment by JamesSmartCell** [comment]
@colourfreak please check the latest version and close if complete.
