### ISSUE TITLE
Add High/Low Fee Warnings

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1691]
1. High Fee Warning caused by a mistake

Zeplin: https://zpl.io/bLypApJ

<img width="2046" alt="Screenshot 2020-12-03 at 12 01 08" src="https://user-images.githubusercontent.com/51817359/101001691-bc2a8300-355f-11eb-8858-1633480ca7cf.png">

----

2. High Fee because the network is congested

Zeplin: https://zpl.io/VDeR0Me

<img width="1552" alt="Screenshot 2020-12-03 at 12 01 14" src="https://user-images.githubusercontent.com/51817359/101001706-c482be00-355f-11eb-995c-436697e947fa.png">

----

3. Fee too Low

Zeplin: https://zpl.io/agwyJEO

<img width="2058" alt="Screenshot 2020-12-03 at 12 01 29" src="https://user-images.githubusercontent.com/51817359/101001726-cba9cc00-355f-11eb-86f7-658e8d72a842.png">

----

4. Note that updated a few components: 

I increased the font size to 15pt for the secondary row.

<img width="929" alt="Screenshot 2020-12-03 at 10 10 59" src="https://user-images.githubusercontent.com/51817359/100988476-115e9880-3550-11eb-906c-245e22c11f11.png">

https://zpl.io/VOZ9w88
https://zpl.io/a8rBoeE
https://zpl.io/a7rL9Nv

**Comment by colourfreak** [comment]
We added a gas price:

https://zpl.io/a8rBoeE

<img width="1004" alt="Screenshot 2020-12-03 at 12 08 30" src="https://user-images.githubusercontent.com/51817359/101002320-4377f680-3560-11eb-94a9-61e687267e87.png">

**Comment by JamesSmartCell** [comment]
Hi @colourfreak, I'll change the layout to match this one. Previously I added it in brackets after the name

**Comment by colourfreak** [comment]
cool
