### ISSUE TITLE
ERC20 tokens balance not Refresh after transaction

### ISSUE THREAD

**Issue by wepobid** [AlphaWallet/alpha-wallet-android#1692]
ERC20 tokens balance not Refresh after receive transaction, first my token was 0 , add funds with metamask, transaction is ok and done in etherscan.io but in my app show 0.

**Comment by wepobid** [comment]
anyone?

**Comment by JamesSmartCell** [comment]
Hi @wepobid this should be fixed in release 3.21 which came out 7th December, same day as your issue. Can you have another look and see if it is now working?

**Comment by wepobid** [comment]
thanks, I will run the new version and let you know!

**Comment by wepobid** [comment]
it's ok
