### ISSUE TITLE
Improve the Activity cell styles

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1697]
This is very, very close to the design. Few, minor changes need to be made and we are good.

Zeplin:
https://zpl.io/V0BRJMx

Right-Semibold-Black, #000000 17pt, Source Sans Pro
Right-Regular-Dove, #727272, 12pt, Source Sans Pro
Left-Regular-Dove, #727272, 12pt, Source Sans Pro

![2020-12-19 14 53 40](https://user-images.githubusercontent.com/51817359/102691179-ec824a80-420a-11eb-8b71-f5cbd0b20c61.jpg)

**Comment by colourfreak** [comment]
Much, much better. Just a quick alignment and we are ready. 

a) The date "11:13" is in the same line as "to: 0x9F...967E". Both are Source Sans Pro, 12 pt, Dove #727272. I think this is 6sp for Android. 

<img width="538" alt="Screenshot 2020-12-20 at 20 49 03" src="https://user-images.githubusercontent.com/51817359/102722976-26377c00-4305-11eb-800e-0bbd1bc480d7.png">
<img width="1038" alt="Screenshot 2020-12-20 at 20 48 51" src="https://user-images.githubusercontent.com/51817359/102723001-5848de00-4305-11eb-8481-5744fc88dafb.png">

b) Please move "Send ETH" and the "-1.503 ETH" a bit lower. They have to start after 7dp. In other words, we need more distance between the gray line at the top and "Send ETH". Everything else is place well. 

<img width="1440" alt="Screenshot 2020-12-20 at 20 55 21" src="https://user-images.githubusercontent.com/51817359/102723154-7fec7600-4306-11eb-9ed5-b291e6f66b11.png">


Sorry for being picky, but paying attention to symmetry is a key for aesthetic look. 

Good job!

**Comment by JamesSmartCell** [comment]
@colourfreak please check the latest version and close if complete.

**Comment by colourfreak** [comment]
"to colourfreak.eth" is not the right color - it should be #727272 and we are good.
![2021-02-01 10 27 43](https://user-images.githubusercontent.com/51817359/106439958-8e3abf80-6478-11eb-94c8-7c471d5866c9.jpg)

**Comment by JamesSmartCell** [comment]
in latest version it's dove / #727272
