### ISSUE TITLE
3.21.2: "Not enough balance" when there are plenty balance

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1698]
Reproduce:

1. Try to send transaction from αW Android 3.21.2 and got this error (balance insufficent)
![Screenshot_20201221-131947.png](https://user-images.githubusercontent.com/548435/102732993-35afd700-4390-11eb-80aa-375eef345270.png)

2. Sending to the same address same amount in MetaMask works perfectly:

`0xdd18e363782479803ba27e29521276e891764bd9118f98462e8b142eb91d8118`

**Comment by JamesSmartCell** [comment]
This issue looks like it's the outlandish European input spec.

**Comment by JamesSmartCell** [comment]
@colourful-land  Can you check the latest build fixes this; if so please close the issue.

**Comment by colourful-land** [comment]
I'll close this first and reöpen if it happens again. Reason being I should chance upon one of such operations.
