### ISSUE TITLE
Hardcode 'Convert xDAI' button to https://bridge.xdaichain.com/

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1707]
Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/2473

Like what we do for swaps (https://1inch.exchange)

**Comment by JamesSmartCell** [comment]
Got it, just use the bridge instead of the script.

**Comment by hboon** [comment]
Yeah. Remember to auto-switch to the xDai chain for the browser.

**Comment by AW-STJ** [comment]
Implemented in v3.24.3.
