### ISSUE TITLE
Please add TaiChi Network

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1709]
https://github.com/Taichi-Network/docs/blob/master/sendPriveteTx_tutorial.md
Please use the RPC address in my private email <About TaiChi Network Fwd: 太极内测邀请邮件(AD)>.
and check out https://github.com/AlphaWallet/alpha-wallet-ios/issues/2489

**Comment by hboon** [comment]
Check https://github.com/AlphaWallet/alpha-wallet-ios/issues/2489 before implementing.

**Comment by hboon** [comment]
Closing since they are sunsetting ref: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3251
