### ISSUE TITLE
Speed-up transaction either crashes app or the flow goes into loop

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1713]
The speed-up transaction does not work as expected. 

The app crashed the first time I tried to open up speed up transactions.

The flow is also weird now. The speed up transaction goes on like this:
1. Click pending transaction
2. Click details button on top right
3. Click 'Speedup Txn' button
4. Cick 'settings' button at top-right corner (Screen is has a dialogue box saying 'Submit replacement txn')
    Go backs back to Step 2.
- OR -
5. Click the blue dialogue box and app crashes

![image](https://user-images.githubusercontent.com/61957841/106688148-ac8fef00-6621-11eb-9020-d22a4ecfcbdf.png)

Video:
https://drive.google.com/file/d/1S9oirBr_APSRD1kwHcVDhCgE2LXRC3KT/view?usp=drivesdk

**Comment by AW-STJ** [comment]
@colourfreak: Should'nt speed-up be more prominent for pending transactions?  Where do you think Speed-up transactions should be placed and what should be the flow?

**Comment by JamesSmartCell** [comment]
Speedup should be using actionsheet ideally.

**Comment by colourfreak** [comment]
![Speedup_Android](https://user-images.githubusercontent.com/51817359/107007229-85a4fa80-6792-11eb-9f3f-863c7d5461f4.jpg)

Zeplin:
https://zpl.io/bP6n6AD

**Comment by colourfreak** [comment]
<img width="1012" alt="Screenshot 2021-02-05 at 09 16 18" src="https://user-images.githubusercontent.com/51817359/107007426-d0267700-6792-11eb-9390-e104fc719596.png">

**Comment by JamesSmartCell** [comment]
@colourfreak I was envisaging exactly something like this. I'll add this part into the PR because as a new user I may not know I need to click on the 3 lines transaction breakdown page.

**Comment by JamesSmartCell** [comment]
#1716 adds the cancel and speedup buttons to the Token Activity view as per the picture above
