### ISSUE TITLE
Support EIP1193 (and hence https://web3modal.com/)

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1714]
https://github.com/Web3Modal

**Comment by hboon** [comment]
Working on EIP1193 support in our web3 provider which is needed here. Will post back when done.

**Comment by hboon** [comment]
Hi @JamesSmartCell 

I have updated our web3 provider to support EIP1193: https://github.com/AlphaWallet/AlphaWallet-web3-provider/tree/master/dist

Most of the changes are already handled by the provider, but our apps needs to install an additional hook for `eth_call`.

These are the relevant code for iOS:

A. Use the updated provider https://github.com/AlphaWallet/alpha-wallet-ios/pull/2509/files#diff-8f7d6adf31268a2d897ee34bd170592648d6e520aa237104395e4a4438af50cb
B. Install the hook: https://github.com/AlphaWallet/alpha-wallet-ios/pull/2509/files#diff-d4f413396ebc9488b81ef23d1f35c3828b7340252b860a8cbfca206d2de295df
C. The arguments in the call: https://github.com/AlphaWallet/alpha-wallet-ios/pull/2509/files#diff-95d3c34707ec63ff68317f0fe33e100ba36bc4253b4b22bd3ca9a7ed7efc4c32
D. The app will have to make the eth_call to the RPC node based on B

**Comment by JamesSmartCell** [comment]
thanks @hboon very useful :)
