### ISSUE TITLE
switch network button in the browser disappeared 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#1718]
reproduce:
1. setting only the ethereum network enabled. 
2. kill and restart the wallet 
3. enable Ropsten
4. the switch network button in the browser won't show up.

**Comment by huweihong** [comment]
I have also encountered this problem. At the same time, after I selected Ropsten(Test), I accessed the page in Browser; later, after I removed Ropsten(Test) from the settings, I accessed the page in Browser and it was still connected to Ropsten(Test).

**Comment by JamesSmartCell** [comment]
Fixed in #1715
