### ISSUE TITLE
Fix wallet connection: https://bridge.xdaichain.com/

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1720]
The connect button does stays irresponsive and does not proceed after the screen below:
![image](https://user-images.githubusercontent.com/61957841/107636431-ba4c1100-6cc0-11eb-9ca6-f4dba2b6cb28.png)

The button works fine to prompt and connect to wallet in web3 browsers of other wallets.

**Comment by colourfreak** [comment]
@AW-STJ This is not about WalletConnect. 

1. You go to Browser.
2. You launch https://bridge.xdaichain.com/
3. You hit "Connect Wallet" and nothing happens.

This is on our side, as I check with Trust and Huobi wallets and it worked fine.

**Comment by JamesSmartCell** [comment]
Fixed by #1730
