### ISSUE TITLE
Scope for 19 Feb

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1726]
Trying to get back to the rhythm of fortnightly releases:

- [x] https://github.com/AlphaWallet/alpha-wallet-android/pull/1716
- [x] https://github.com/AlphaWallet/alpha-wallet-android/pull/1715

Suggestions:
- [x] https://github.com/AlphaWallet/alpha-wallet-android/issues/1720
- [ ] https://github.com/AlphaWallet/alpha-wallet-android/issues/1722
- [x] https://github.com/AlphaWallet/alpha-wallet-android/issues/1717

**Comment by JamesSmartCell** [comment]
@AW-STJ All the topics were covered in release 3.24.2 which went live on the day of this reply. 

#1722 is not fixable by us, it requires Honeyswap to enable WalletConnect for mobile browsers. As a suggestion we could add a 'switch to desktop browser format' in the DappBrowser which would at least give us a workaround.

**Comment by AW-STJ** [comment]
Closing the ticket.. Version 144 (3.24.3) submitted in PlayStore for review, with all items in the scope addressed, except for #1722.

#1722 is moved to scope for  5 March 2020's release.
