### ISSUE TITLE
WalletConnect does not work in Gnosis Safe

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1747]
I started facing this issue on Android, starting only a couple of days ago.

On (Gnosis safe)[https://gnosis-safe.io/] the transactions signed by Android applications creates the error below, even though the transaction is signed successfully. The transactions signed on iOS go through without any problem.

Versions affected: 3.24.3(144) 

Sceenshot: Error on Gnosis Safe:
![image](https://user-images.githubusercontent.com/61957841/109436882-00052980-7a76-11eb-9b62-c6fa61498394.png)

Screenshot: Signed transaction on Application
![image](https://user-images.githubusercontent.com/61957841/109436895-13b09000-7a76-11eb-917a-cfc6bf216249.png)

**Comment by JamesSmartCell** [comment]
@AW-STJ Unable to reproduce ... Sign tests work correctly.

Please create a reproducible sample.

**Comment by colourful-land** [comment]
@AW-STJ said that the test build you shared yesterday already have this problem solved; given the PR was made 22 hours ago, I assume the build @AW-STJ tested does NOT contain this fix, therefore this fix #1763 has nothing to do with this bug.

To be really in the clear, I would 1) reproduce this bug with the playstore version and 2) build a version from #1763 and test it again confirm it's gone.

**Comment by JamesSmartCell** [comment]
@colourful-land Please refer to this issue and related PR.

We follow git convention.

If PR says 'fixes' or 'closes' an issue it is related to that issue.

@AW-STJ has already confirmed the issue is fixed twice.

**Comment by JamesSmartCell** [comment]
https://github.com/web3j/web3j/pull/1382

This is the fix for the above issue, now pushed to web3j repo.
