### ISSUE TITLE
Add "Show Seed Phrase" to Settings tab + Change "Backup Seed Phrase"

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1748]
**Problem:**
Some users find it difficult to access their Seed Phrase. They have to go through "Back up my Wallet" flow, where we tried to warn users about not sharing seed phrases.

**Solution:**
We add one more item to the Settings Menu. We keep "Back up my Wallet". If you open "Back up my Wallet" it goes exactly as it is now, but please remove the addition line in red "Do not share your backup. AlphaWallet team..." as that will be relevant in the "show seed phrase" section.
![2021-03-02 10 36 49](https://user-images.githubusercontent.com/51817359/109628702-58562d00-7b43-11eb-8584-1bf49a8b280c.jpg)

If you select "Show Seed Phrase" you will get into a flow like this:
<img width="1648" alt="Screenshot 2021-03-02 at 10 36 05" src="https://user-images.githubusercontent.com/51817359/109628625-41173f80-7b43-11eb-8de0-a2a5ebbb55dd.png">

**Zeplin:**
https://zpl.io/VkQ8dL5

**Comment by colourful-land** [comment]
I suggest adding the word secret somewhere since the first timer would link the word 'safe' to availability (not lost) instead of confidentiality (not leaked). This happened in the bank, where the user think "safe" means "your money is safe in the bank" or "your investment is safe without fund manager" and went ahead telling other people their safe word thinking it's not confidential - we had to replace it to secret word.

You migh think "who on the earth would think 'safe' as non-confidential"????

Well... I was speechless too.

**Comment by JamesSmartCell** [comment]
@colourfreak can you check @colourful-land's comment above?

**Comment by colourfreak** [comment]
<img width="588" alt="Screenshot 2021-03-16 at 07 22 29" src="https://user-images.githubusercontent.com/51817359/111264744-610d2f80-8628-11eb-84c3-5e6a5566f234.png">

**Comment by colourful-land** [comment]
Will do for me. iOS and Android needs to be aligned @hboon

**Comment by JamesSmartCell** [comment]
@colourful-land can you double check the design above, the screen we get when clicking the 'show seed phrase' button is shown in the 1st entry on this issue, with the heading 'Beware of scammers ...'. It is NOT the original 'Back up your seed phrase' screen.

What I assume has happened is the context has switched to changing the original screen with the 'Backup my seed phrase' title which is accessed via a different path (user clicks 'back up seed phrase' from settings) and would be a different issue. I'm ok to piggy-back this new issue on this one to save time, but technically it's wrong to do so.

Please confirm if you understand the above.

**Comment by JamesSmartCell** [comment]
@colourful-land pushed update based on https://github.com/AlphaWallet/alpha-wallet-android/issues/1748#issuecomment-799988081, please check translations.

**Comment by hboon** [comment]
@colourful-land @colourfreak is the change limited to copy in this screen? https://github.com/AlphaWallet/alpha-wallet-android/issues/1748#issuecomment-799988081

**Comment by colourfreak** [comment]
> @colourful-land @colourfreak is the change limited to copy in this screen? [#1748 (comment)](https://github.com/AlphaWallet/alpha-wallet-android/issues/1748#issuecomment-799988081)

No other changes.
