### ISSUE TITLE
Deeplink FAQ in the Settings to alphawallet.com/faq

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1749]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/2583

**Comment by colourfreak** [comment]
Second task for @mpaschenko @AW-STJ

**Comment by mpaschenko** [comment]
@colourfreak @JamesSmartCell should I use internal browser like for dapps or external would be fine?

**Comment by colourfreak** [comment]
> @colourfreak @JamesSmartCell should I use an internal browser like for dapps or external would be fine?

Please check out how this is implemented on iOS. @hboon

![2021-08-04 06 44 59](https://user-images.githubusercontent.com/51817359/128175605-74c2fafd-ef18-4f16-aa6d-542b5cf25ff5.gif)
