### ISSUE TITLE
Unable to connect to registration server, please try again later

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1751]
The following happened by trying to login as a@colourful.land and using the corresponding password. The wallet is newly installed.

![signal-2021-03-03-120841](https://user-images.githubusercontent.com/548435/109754575-62a62300-7c38-11eb-8149-6386f5ae68a6.png)

**Comment by JamesSmartCell** [comment]
Wrong repo
