### ISSUE TITLE
Make a lighter Status Bar

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1756]
<img width="423" alt="Screenshot 2021-03-05 at 07 59 28" src="https://user-images.githubusercontent.com/51817359/110079034-d9523600-7d88-11eb-81c6-3177409d029f.png">

Take a look at the very top of this screenshot. Our Status bar is black. Can we change it to the lighter, classic version?
![2021-02-26 10 36 29](https://user-images.githubusercontent.com/51817359/110079070-ed963300-7d88-11eb-82f5-7a6f5bdc84f2.jpg)

**Comment by JamesSmartCell** [comment]
Fixed by #1757
