### ISSUE TITLE
Rare Coin in Wrong Dapp Category 

### ISSUE THREAD

**Issue by Affinity-Design** [AlphaWallet/alpha-wallet-android#1759]
Hey, guys when adding my xDai/Defi app to the Dapp list I was hoping to show up in the "xDai" category on the home page, so when I referenced another app in the xDai category, in this case, the xDaiBrdige and figured "tool" would have been the correct pair.  

`{"name": "xDai Bridge", "description": "xDai/Ethereum bridge for self transfers of Dai to xDai", "url": "https://dai-bridge.poa.network/", "category": "Tool"},`

However, after adding this to my app, I am listed in the "Utilities" section on the browser Dapp page, where-as the above app was listed correctly on the "xDai" category, yet they both have the "tool" category in code. Any ideas??? Or is this something that is moved around on the admin side? If so could you move "Rare Coin" to the xDai category?

`[  {"name": "Rare Coin", "description": "Free Crypto Faucet & Yeild Farming", "url": "make.rare.claims", "category": "Tool"},`

**Comment by JamesSmartCell** [comment]
Hi, sorry about that, we weren't sure where to put your dapp, so we just took the Category: Tool to mean utility.

So we add your dapp to the 'xDai' category, right?

**Comment by Affinity-Design** [comment]
@JamesSmartCell Yes please! xDai category is correct. Thank you!

**Comment by colourfreak** [comment]
Done.

**Comment by Affinity-Design** [comment]
Thank you!!
