### ISSUE TITLE
Update Wallet Tab [Samoa]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1768]
<img width="1619" alt="Screenshot 2021-03-10 at 15 24 01" src="https://user-images.githubusercontent.com/51817359/110643685-a65ad880-81b4-11eb-975d-0baaf2310700.png">

https://zpl.io/2vRNpwP

-----

**Ether, ERC20, xDAI.. going up:**
https://zpl.io/addP0yR
<img width="452" alt="Screenshot 2021-03-08 at 10 52 41" src="https://user-images.githubusercontent.com/51817359/110304942-749f1180-7ffc-11eb-9d97-eac051fe33c6.png">

-----

**Ether, ERC20, xDAI.. going down:**
https://zpl.io/VQP9Dyx
<img width="453" alt="Screenshot 2021-03-08 at 10 52 46" src="https://user-images.githubusercontent.com/51817359/110304958-78329880-7ffc-11eb-9cb0-93c1bd0f3184.png">

-----

**Savings, Loans, Debt Obligation, LP tokens:**
https://zpl.io/agxr05D
<img width="460" alt="Screenshot 2020-11-12 at 11 24 29" src="https://user-images.githubusercontent.com/51817359/98928746-70de0100-24da-11eb-9814-180401c779de.png">

-----

**NFTs:**
https://zpl.io/VkordBg
<img width="514" alt="Screenshot 2020-11-12 at 11 40 10" src="https://user-images.githubusercontent.com/51817359/98929709-d41c6300-24db-11eb-8df5-800bc01e4cee.png">

-----
**Large Title**

<img width="620" alt="Screenshot 2021-03-10 at 15 26 05" src="https://user-images.githubusercontent.com/51817359/110643993-f20d8200-81b4-11eb-9686-6871c92e3dde.png">

a) tomek.eth - a name that you can change in the Settings
b) $14,224.76 - how much those assets are worth in USD (you can change it to ETH, AUD, etc. in the Settings)
c) +$405.12 (+2.53%) - Portfolio change in last 24h

-----
**Small Title**, when scrolled down:
https://zpl.io/2Elx85n
<img width="664" alt="Screenshot 2021-03-10 at 15 30 47" src="https://user-images.githubusercontent.com/51817359/110644638-998ab480-81b5-11eb-8bd8-9ff5983f6dcd.png">

**Comment by colourfreak** [comment]
@AW-STJ Assigned the task

**Comment by mpaschenko** [comment]
<img width="377" alt="Screenshot 2021-08-25 at 4 52 00 PM" src="https://user-images.githubusercontent.com/2472117/130803333-e1d1c0c0-d009-44f2-a700-7e8269450c7a.png">
Hi @colourfreak seems like icons for the price go up/down are not marked for export or so - the side properties menu doesn't contain export buttons...

**Comment by mpaschenko** [comment]
![viber_image_2021-08-28_11-40-53-207](https://user-images.githubusercontent.com/2472117/131321411-0ad7334d-e851-4a37-8d08-166787fb0214.jpg)
Hi @colourfreak 
1 should I remove elements marked on picture attached, since there are no such on the new design
2 should split tokens list for sections for savings / nft's ?
3 @JamesSmartCell how can I check if token is: Savings, Loans, Debt Obligation, LP tokens (as it has separate presentation)?
4 As I see there is a favorites tab - should I add that, if so - can I see UI on how tokens can be marked as favorite?
5 there is a search field on top and **Buy ETH** / **Add/HideTokens** buttons on the bottom, should I add that as well?

**Comment by colourfreak** [comment]
1. Yes and no. Take a look at this first.
https://github.com/AlphaWallet/alpha-wallet-android/issues/1890

Ideally, I would like to cut the names of tokens and display only what is in the bracket. So **BNB** should stay in this example. Kick-off **ERC20**, **Network name**, **Issuer**

2. **Attestations** for now, till we come up with something better
3. Since we are no longer aiming for wallets for DEFI, try to put them all in one container called **DEFI** and I think you can manually add them to one of those groups. 
 
We have:
aTokens https://zpl.io/a7XDGKW
pTokens https://zpl.io/bzOkwpM
iTokens https://zpl.io/2ZO5qOl
sTokens https://zpl.io/aNvZEWQ

I only have icons for them, but we need to have all contact addresses. If you have an idea of how to automate this process, maybe we can save time. 

4. We don't have the favorites feature for now. So kick it off. 
5. Yes, please. Please check out https://github.com/AlphaWallet/alpha-wallet-ios/issues/2994

We might be moving towards this design in the future, so you can have a picture of what we are planning next. But this needs to be confirmed. 

![nft-wallet_concept](https://user-images.githubusercontent.com/51817359/131367699-542d38f6-a8e8-4d74-8579-0596547e70aa.jpg)

**Comment by mpaschenko** [comment]
@JamesSmartCell can you tell me what is attestations, by which criteria can I filter them?

**Comment by colourfreak** [comment]
a) Attestations - you asked me "2 should split tokens list for sections for savings / nft's ?", so my answer is: **Attestations**. 

b) Defi

**Comment by mpaschenko** [comment]
@JamesSmartCell do you have thoughts on the best way to implements the groups in the **TokenAdapter** class (**TokenCardMeta** has a pretty tricky way to calculate weight - don't want to change there anything), 
I think - basically split **TokenAdapter.items** into the groups, which order will be controlled by some condition.

**Comment by mpaschenko** [comment]
@JamesSmartCell @colourfreak fond exact list of the 
aTokens - https://docs.aave.com/developers/deployed-contracts/deployed-contracts 
iTokens - https://bzx.network/itokens
for p / s tokens seems there is no exact contacts list (or I'm unable to find it).

should I add that to known tokens list and then group by that contracts?

**Comment by hboon** [comment]
@mpaschenko You can also see if https://github.com/AlphaWallet/alpha-wallet-ios/blob/master/AlphaWallet/UI/AlphaWalletAddress+UI.swift helps for now. There's also https://tokenlists.org. Long term of course we'll want a single list.

**Comment by mpaschenko** [comment]
@JamesSmartCell @colourfreak  basically finished points, mentioned in this ticket. can do PR and proceed with the others.
