### ISSUE TITLE
Add history chart to all ERC20 tokens & Ether [Samoa]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1770]
Zeplin:
https://zpl.io/VKx0yA6

<img width="637" alt="Screenshot 2021-03-10 at 15 34 45" src="https://user-images.githubusercontent.com/51817359/110645311-26ce0900-81b6-11eb-9b74-c63e5352cc61.png">

My suggestions:
- Coingecko API
- Tradingview API

**Comment by JamesSmartCell** [comment]
Hi @colourfreak, how would you get to this screen with the top pager? Is it by clicking the token in the main wallet tab? If so; which one of these has the Send/Receive buttons, or do they all?

**Comment by JamesSmartCell** [comment]
> Hi James, please take look at the prototype. https://invis.io/7TZHRQ8W265

Thanks that's clear
