### ISSUE TITLE
Add Wallet Naming feature in the Settings

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1795]
<img width="1712" alt="Screenshot 2021-03-29 at 15 44 14" src="https://user-images.githubusercontent.com/51817359/112845853-9e9c9e80-90a5-11eb-80c6-43a9d6e714b0.png">

https://zpl.io/b6nndAq

**Comment by JamesSmartCell** [comment]
@colourfreak What do you think of adding a 'Scan ENS' text at the bottom right (where 'Paste' would normally go) that allows user to use their ENS name here?

See the notes on this PR:

https://github.com/AlphaWallet/alpha-wallet-android/pull/1668

**Comment by colourfreak** [comment]
@JamesSmartCell 
I thought about it. And I am fully aware of ENS names holders. But...

On one hand, it helps power users to use their ENS names, but on the other hand, it becomes complicated for beginners. If a random user will enter this screen, he will be concerned about the difference between ENS name and name. And since the majority of users don't have ENS names, I prefer to do not to overcomplicate a simple screen. 

If you have an ENS name, just enter it manually. It's easy.

**Comment by colourfreak** [comment]
"Don't make me think" - and by adding an additional label with ENS name, we make the majority of our users think.

**Comment by JamesSmartCell** [comment]
Ok. How about pre-populating the name with ENS if they have one? That way, it's hidden from users who don't know about it, and for those that have it, they can see it and change it.

**Comment by ChintanRathod** [comment]
> Ok. How about pre-populating the name with ENS if they have one? That way, it's hidden from users who don't know about it, and for those that have it, they can see it and change it.

Do we need to auto populate the ENS name?

**Comment by JamesSmartCell** [comment]
> > Ok. How about pre-populating the name with ENS if they have one? That way, it's hidden from users who don't know about it, and for those that have it, they can see it and change it.
> 
> Do we need to auto populate the ENS name?

Yes, when the page starts, fetch the ENS name.

However, if the name input field has focus when the ENS name is ready then just abort - don't type over what the user is typing.

**Comment by colourfreak** [comment]
@AW-STJ Here is a great task for @mpaschenko

**Comment by mpaschenko** [comment]
@JamesSmartCell 
Ok, so to summarize:
- if there is ENS name for the wallet, make the edit field read-only
- if there is no ENS, update field **name** from **Wallet** class
right?

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell
> Ok, so to summarize:
> 
> * if there is ENS name for the wallet, make the edit field read-only
> * if there is no ENS, update field **name** from **Wallet** class
>   right?

User may still want to rename even if they have ENS. Because, user may have many ENS names and the one that the wallet code picks is usually determined by whichever order the event scanner finds them in.

Instead, do a fetch when the activity/fragment starts, then, once the ENS name is ready, populate the field, but only if it doesn't have focus - that is, the user may already be typing in there.

Because you will be using the Input text widget you have the loading spinner, so switch this on during the fetch, but allow user to gain focus of the field and type. If they start typing then you can cancel the fetch.

**Comment by mpaschenko** [comment]
@JamesSmartCell talked with Vlad, and made as it's implemented on iOS, show ENS name as edit text hint if any.

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell talked with Vlad, and made as it's implemented on iOS, show ENS name as edit text hint if any.

Ok that should also work. So, if I overrode the name previously and want to revert to the ENS name, I just delete the hint and it'll revert?

**Comment by mpaschenko** [comment]
@JamesSmartCell basically yes:
- if there is ENS name for the wallet - it's shown as a hint, which will disappear in the edit box, once you start to type anything (which let the user think that the typed name will be used as the name for the wallet)
- if you will clear the previous typed name - ENS hint will appear, which means this name will be used as well (like default or so).
- if there is no ENS - the edit box will be empty before setting any name.

this is how iOS (and my implementation as well) works

**Comment by JamesSmartCell** [comment]
Ok nice, that sounds like a good way to do it.

**Comment by mpaschenko** [comment]
Think you already added it’s ***@***.*** ***@***.***>
