### ISSUE TITLE
Add SNAFU erc20 token on your token list

### ISSUE THREAD

**Issue by Agilulfo1820** [AlphaWallet/alpha-wallet-android#1816]
Hello, we would like our users to be able to manage their $SNAFU token on your wallet.

Those are the specifics:

Network: xDai
Token Address: 0x27B9C2Bd4BaEa18ABdF49169054c1C1c12af9862
Ticker: SNAFU
Decimals: 18
Logo: https://gateway.pinata.cloud/ipfs/QmYFnC1RxAvNzWFmtR5CQYWBz8pgzDidqQKg8o1WVqppEq

More about SNAFU: https://nftsnafu.org

**Comment by JamesSmartCell** [comment]
@Agilulfo1820  If the wallet user has this token in their wallet, it should automatically be picked up. Can you re-check with the latest version and let us know if it's being picked up. If it is, and the logo isn't correct I can add it into our secondary repo.

**Comment by Agilulfo1820** [comment]
Hi @JamesSmartCell, yes the token is picked up and the logo is displayed correctly. 

Only thing I noticed is that if you tap on the token the logo inside is different (the standard green circle).
