### ISSUE TITLE
Update "Name this Wallet" icon

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1817]
https://zpl.io/Vq3l6yN

The old one was confusing, as it has .ens in it. Users might think this is where they should set on .ens, which is wrong.

<img width="156" alt="Screenshot 2021-04-21 at 12 27 07" src="https://user-images.githubusercontent.com/51817359/115539123-e4abe300-a29c-11eb-94a8-982a7c2ac46e.png">

**Comment by JamesSmartCell** [comment]
Where does this go?

**Comment by ChintanRathod** [comment]
It's icon for "Name the wallet"

**Comment by JamesSmartCell** [comment]
Ok - is it part of an as-yet unimplemented design? I don't recall seeing it.

**Comment by colourfreak** [comment]
> Ok - is it part of an as-yet unimplemented design? I don't recall seeing it.

Yes. But already implemented in iOS.

**Comment by JamesSmartCell** [comment]
Hi @ChintanRathod can you push this update?

**Comment by ChintanRathod** [comment]
> Hi @ChintanRathod can you push this update?

Generated PR
