### ISSUE TITLE
oasis.app Browser ethereum provider and URL network param do not match!

### ISSUE THREAD

**Issue by harold26kim** [AlphaWallet/alpha-wallet-android#1832]
Good day to all,

I got an issue with oasis.app site. Check the screenshot below. How I can fix this issue? Thank you all and have a great day ahead.

![image](https://user-images.githubusercontent.com/8415590/117946929-4f9f8580-b342-11eb-93b6-fbc99665bd25.png)

**Comment by ErwinDecenternet** [comment]
We need to get a feedback from Oasis.app developers themselves since we need to know what specifically they are asking to successfully integrate with a wallet.
