### ISSUE TITLE
AlchemyNFT Twitter verification error in AW Android browser

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1840]
The error only occurs in AlphaWallet Androrid browser during Twitter verification. 

https://user-images.githubusercontent.com/61957841/118580579-78f16300-b7d3-11eb-9d57-222d5795a227.mp4

Expected result is to redirect back to autographnft website connected with Twitter.

**Comment by JamesSmartCell** [comment]
Fixed
