### ISSUE TITLE
Tokens not appearing and BNB price is NULL

### ISSUE THREAD

**Issue by CodahUY** [AlphaWallet/alpha-wallet-android#1842]
Tokens are not appearing in the Manage tokens window and BNB price is empty

**Comment by JamesSmartCell** [comment]
Hi @CodahUY this should be improved now; tokens should automatically appear in the wallet when sent. If this isn't working correctly, could you send a watch wallet address that holds some BNB tokens, we will try to work out what's going on.

**Comment by CodahUY** [comment]
Thanks a lot James! I didnt answer because i losed my github account, sorry. It works now! :)
