### ISSUE TITLE
KNC Token Migration

### ISSUE THREAD

**Issue by ssreelekhya** [AlphaWallet/alpha-wallet-android#1848]
Hello Team,

KNC token is undergoing a migration and upgrade, KNC migration is an important step forward in our Kyber 3.0 journey. 
It would be great if you could support this migration.
New KNC smart contract address: 0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202
For further information, please refer to the following: [KNC Token Migration Guide](https://blog.kyber.network/knc-token-migration-guide-fda08bfe62c2)

**Comment by colourfreak** [comment]
We added a new item to 'Utilities' where you can quickly jump to the Migration Page.

![photo_2021-05-20 11 53 37](https://user-images.githubusercontent.com/51817359/118958835-0f538f00-b962-11eb-8224-1686334ac7b2.jpeg)
![photo_2021-05-20 11 53 39](https://user-images.githubusercontent.com/51817359/118958844-1084bc00-b962-11eb-8a3b-f5191434517f.jpeg)
