### ISSUE TITLE
Make it explict that Binance is BSC

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1849]
There is confusion happening as Binance have BSC and Binance chains. So best to list the chain as 'Binance (BSC)'. I have got a few queries on this already on support.

**Comment by ChintanRathod** [comment]
@AW-STJ Do we need to just show name as "Binance (BSC)"?

**Comment by AW-STJ** [comment]
Yes that is all that is needed.
