### ISSUE TITLE
Unable to connect wallet to Etherscan "revoke feature" to canx ETH Unlimited Contracts

### ISSUE THREAD

**Issue by sharonsylu** [AlphaWallet/alpha-wallet-android#1853]
User reported bug via support: 
Cannot connect to wallet to Etherscan, objective is to revoke Uniswap approval (Unlimited ERC20 allowances!)

Message: 
Hi I have a problem to revoke UNI Swap access to my founds, please help me.
https://etherscan.io/tokenapprovalchecker?search=0x39063c32ebef4b026609ef841b8203e52de68630

Steps to reproduce the behaviour: 

1. Tap Browser
2. Insert Etherscan Contract url:  https://etherscan.io/tokenapprovalchecker?search=0x39063c32ebef4b026609ef841b8203e52de68630
4. Cannot connect wallet ---> cannot show 

My screenshot where I've replicated the UX: 
![Screenshot_20210521-110313_AlphaWallet](https://user-images.githubusercontent.com/15342675/119076905-b99ce680-ba36-11eb-994b-3157a51b81f5.jpeg)

Interim workaround: 

Quick fix for this user to stay inside Alphawallet - 
1. ask user to navigate Browser
2. use this Url Eth Allowance / Revocation tool:   https://james-sangalli.github.io/eth-allowance/
3. Wallet should automatically connect (To be confirmed, waiting for user to respond) 
4. User to click "revoke all allowances" 

![Screenshot_20210521-121252_AlphaWallet](https://user-images.githubusercontent.com/15342675/119077129-17313300-ba37-11eb-8d66-c87202ff780a.jpeg)

Resolution: 
- pending user confirmation that workaround point 3 works
- pending user confirmation iOS / Android (version number) 

Background: 

Etherscan has a new Token Approvals feature released  (2 months).  https://info.etherscan.com/tokenapprovals/
Unproven projects with novel yield farming have reaped more and more token allowances - to the point where they just start stealing user tokens.  Reading: https://kalis.me/unlimited-erc20-allowances/

**Comment by sharonsylu** [comment]
Note: this ticket is replicated in both iOS and Android pending user confirmation of version

**Comment by sharonsylu** [comment]
Closing - duplicate ticket.

**Comment by hboon** [comment]
Duplicate of #1852
