### ISSUE TITLE
Prompt and collect user emails

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1866]
We should collect and maintain a list of users' email. This will help us immensely in announcing new features, doing usability testing etc. 

@colourfreak - can you design how we can do that. Need to consider #1856 as this is another prompt to the users.

**Comment by colourfreak** [comment]
https://zpl.io/brKW40D

See the reference on iOS
https://github.com/AlphaWallet/alpha-wallet-ios/issues/2807

![Email_Request](https://user-images.githubusercontent.com/51817359/132709116-d3e6aaec-8dd1-459f-aa13-092a1f79399e.jpg)

**Comment by JamesSmartCell** [comment]
@colourfreak do you want to re-assign this so it goes into development? 

Do you know if we have a server back end that collects these emails? If not, that part will need to be assigned to the web team.

**Comment by hboon** [comment]
My bad, @JamesSmartCell. I forgot about this. We are using MailChimp.

This is the corresponding PR for iOS https://github.com/AlphaWallet/alpha-wallet-ios/pull/2919

The few lines that really matter for adding to the list is in this file: https://github.com/AlphaWallet/alpha-wallet-ios/blob/b50dd2903294d1ba9838ad946ee5cbfab9d06609/AlphaWallet/Core/EmailList.swift

Kotlin (hah!) version supplied by MailChimp:

```
val sdkKey = "<key>"
val isDebugBuild = BuildConfig.DEBUG
val configuration = MailchimpSdkConfiguration.Builder(context, sdkKey)
    .isDebugModeEnabled(isDebugBuild)
    .isAutoTaggingEnabled(true)
    .build()
val mailchimpSdk = Mailchimp.initialize(configuration)
```

I'll send you the key privately

**Comment by mpaschenko** [comment]
@JamesSmartCell @hboon on which run it should be raised?
