### ISSUE TITLE
Add Custom Linking to Quickswap for tokens on Polygon

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1868]
#2103 - since Quickswap is a for of Uniswap, we can add custom linking for all tokens on Polygon.

![Quickswap_AlphaWallet](https://user-images.githubusercontent.com/51817359/119621863-e79f7380-be06-11eb-8a17-7dd34c0ff951.jpg)

**Comment by colourfreak** [comment]
Third and last task @mpaschenko @AW-STJ

**Comment by mpaschenko** [comment]
@JamesSmartCell @colourfreak just checked the code, but can't find any implementation for that (I mean for the other tokens). But it exists on ios, should I make it from scratch? Or did I miss something?
Also for the iOS for the LINK tokens it redirects to **https://1inch.exchange/#/r/0x98f21584006c79871F176F8D474958a69e04595B/LINK/ETH** should I use quickswap or 1inch as on iOS?

**Comment by JamesSmartCell** [comment]
We have previously added custom functions like this. It should be fairly trivial to extend this, for reference check ```openDapp(C.XDAI_BRIDGE_DAPP);``` in Erc20DetailActivity.

maybe 1inch on Mainnet, quickswap on Polygon?

**Comment by hboon** [comment]
1inch also supports Polygon now. So if it’s good enough, we can avoid QuickSwap entirely (less code to add an maintain). @colourfreak do you know?

**Comment by colourfreak** [comment]
Polygon users use Quickswap a lot. Much more than 1inch.
