### ISSUE TITLE
Set different Home in the Browser after connecting to Polygon

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1872]
When you are in a Browser connected to Mainnet and you switch to Polygon, it resets the browser and starts with a blank page. What we want to do is to loads in https://alphawallet.com/browser-item-category/polygon/ instead. 

<img width="1628" alt="Screenshot 2021-05-27 at 11 40 22" src="https://user-images.githubusercontent.com/51817359/119804102-54d30780-bee0-11eb-98d2-bb82945649a3.png">

**Comment by hboon** [comment]
That means we are displaying an index of dapps, which got us rejected multiple times. They even scanned for words like "crypto kitties" and their URL even when we disabled the functionality but kept the list in the app. Whether the list is loaded from a website by automatically loading the page or whether the list is built into the app shouldn't matter.

Don't think we can do this.

**Comment by hboon** [comment]
(replied to wrong issue, deleted comment)
