### ISSUE TITLE
[Error Message Improvement] Insufficient Funds #2812

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1875]
Mainthread: https://github.com/AlphaWallet/alpha-wallet-ios/issues/2812

Summary:  'Insufficient funds' has been confusing to new users. Proposal to change the dialogue to 'Insufficient ETH', so that it would make it more sense to users.

**Comment by jinkjonks** [comment]
Shall I fix this one? I implemented this under @JamesSmartCell

**Comment by AW-STJ** [comment]
Yes! That would be fantastic.

**Comment by jinkjonks** [comment]
Hey Sunil, just to confirm, this is the warning that pops up when setting the gas settings correct?

**Comment by hboon** [comment]
It's supposed to do this instead [1]:

<img width="200" alt="Screenshot 2021-05-28 at 1 29 23 PM" src="https://user-images.githubusercontent.com/56189/119934746-dbf3ae80-bfb8-11eb-8774-5661b5de2817.png">

[1] https://zpl.io/29RZ0nd

**Comment by AW-STJ** [comment]
This scenario works for ETH, but for other tokens 'Availabe ETH' would not make sense.

**Comment by hboon** [comment]
Yes. Replace the symbol accordingly.
