### ISSUE TITLE
A whole lotta undownloadable artifacts

### ISSUE THREAD

**Issue by bonevays** [AlphaWallet/alpha-wallet-android#1883]
Hi folks, this might be somehow well-known to Android devs but it's my first time trying to debug it. I run Android Studio Canary and tried to build the project, I got errors quite early in the process:

`Could not find com.google.code.gson:gson:2.8.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app > com.google.gms:google-services:4.3.3
         project :app > com.google.firebase:firebase-crashlytics-gradle:2.3.0 > com.google.firebase:firebase-crashlytics-buildtools:2.3.0
   Could not find com.google.guava:guava:27.0.1-jre. ...`

Is it possible that some of these libs have been removed for security vulns? Or is it a POM misconfiguration?
Thanks!

**Comment by JamesSmartCell** [comment]
Maybe try Invalidate caches and restart ? We've never seen any issues like this.

Let us know if you manage to get past this stage, or not.
