### ISSUE TITLE
Update BSC network token icons

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1885]
BUSD
0xe9e7cea3dedca5984780bafc599bd69add087d56
https://zpl.io/a7gZX4E
![BUSD](https://user-images.githubusercontent.com/51817359/120307754-a3fbac80-c2d3-11eb-9ebc-6c2880144312.png)

---

BUSD-T
0x55d398326f99059ff775485246999027b3197955
https://zpl.io/V0rZ80Q
![BUSD-T](https://user-images.githubusercontent.com/51817359/120307764-a6f69d00-c2d3-11eb-9e1d-c0e3b880da54.png)

---

vBUSD
0x95c78222b3d6e262426483d42cfa53685a67ab9d
https://zpl.io/29G5XPy
![vBUSD](https://user-images.githubusercontent.com/51817359/120307779-ab22ba80-c2d3-11eb-8e6c-84a93949267d.png)

---

vUSDT
0xfd5840cd36d94d7229439859c0112a4185bc0255
https://zpl.io/Vqz6DlJ
![vUSDT](https://user-images.githubusercontent.com/51817359/120307925-d1485a80-c2d3-11eb-9a03-96f5e8f32a85.png)

---

BTCB
0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c
https://zpl.io/2jqlAvp
![BTCB](https://user-images.githubusercontent.com/51817359/120308025-efae5600-c2d3-11eb-822c-ef39c6617e27.png)

---

ETH
0x2170ed0880ac9a755fd29b2688956bd959f933f8
https://zpl.io/anBrjKr
![ETH](https://user-images.githubusercontent.com/51817359/120308120-0785da00-c2d4-11eb-9ded-ff4740f86f26.png)

---

USDC
0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d
https://zpl.io/bAxGeZ8
![USDC](https://user-images.githubusercontent.com/51817359/120308286-3c922c80-c2d4-11eb-8b15-16f3cb26ef1e.png)

---

vETH
0xf508fcd89b8bd15579dc79a6827cb4686a3592c8
https://zpl.io/boJkwDX
![vETH](https://user-images.githubusercontent.com/51817359/120308446-651a2680-c2d4-11eb-97ed-a0afc3ee0728.png)

---

vBTC
0x882c173bc7ff3b7786ca16dfed3dfffb9ee7847b
https://zpl.io/VOLBlPr
![vBTC](https://user-images.githubusercontent.com/51817359/120308915-ebcf0380-c2d4-11eb-83b5-f01b658f0da5.png)

---

vUSDC
0xeca88125a5adbe82614ffc12d0db554e2e2867c8
https://zpl.io/VkMrgp5
![vUSDC](https://user-images.githubusercontent.com/51817359/120309005-030df100-c2d5-11eb-9d9a-fd78f785516e.png)

**Comment by colourfreak** [comment]
BETH
0x250632378e573c6be1ac2f97fcdf00515d0aa91b
https://zpl.io/VK7Nz37
![BETH](https://user-images.githubusercontent.com/51817359/120309136-2e90db80-c2d5-11eb-9325-a23c74d7b64b.png)

---

WBNB
0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c
https://zpl.io/a3rzB7N
![WBNB](https://user-images.githubusercontent.com/51817359/120309213-45cfc900-c2d5-11eb-9c1a-09d8afbbace3.png)

---

CAKE
0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
https://zpl.io/2yDBv7L
![CAKE](https://user-images.githubusercontent.com/51817359/120309296-5d0eb680-c2d5-11eb-876c-3f9133728610.png)

---

DAI
0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3
https://zpl.io/brAk5lW
![Dai](https://user-images.githubusercontent.com/51817359/120309421-83345680-c2d5-11eb-9601-1bc7b2a62756.png)

---

vDAI
0x334b3ecb4dca3593bccc3c7ebd1a1c1d1780fbf1
https://zpl.io/2vjB96P
![vDAI](https://user-images.githubusercontent.com/51817359/120309534-a2cb7f00-c2d5-11eb-8036-71a2620ceda1.png)

---

ADA
0x3ee2200efb3400fabb9aacf31297cbdd1d435d47
https://zpl.io/aw50RO1
![ADA](https://user-images.githubusercontent.com/51817359/120310920-2f2a7180-c2d7-11eb-98f2-44f9d7ed2eb7.png)

---

DOT
0x7083609fce4d1d8dc0c979aab8c869ea2c873402
https://zpl.io/bAxGo5P
![DOT](https://user-images.githubusercontent.com/51817359/120311099-6567f100-c2d7-11eb-9cad-26e388c09ccf.png)

---

BAKE
0xe02df9e3e622debdd69fb838bb799e3f168902c5
https://zpl.io/2jql6nx
![BAKE](https://user-images.githubusercontent.com/51817359/120311546-e9ba7400-c2d7-11eb-8106-6cc768c18844.png)

**Comment by colourfreak** [comment]
LINK
0xf8a0bf9cf54bb92f17374d9e9a321e6a111a51bd
https://zpl.io/bPB4ZwL
![Link](https://user-images.githubusercontent.com/51817359/120316669-f5a93480-c2dd-11eb-9d9b-320ac0f939df.png)

---

vADA
0x9a0af7fdb2065ce470d72664de73cae409da28ec7
https://zpl.io/bAxGrKo
![vADA](https://user-images.githubusercontent.com/51817359/120316927-46b92880-c2de-11eb-9b0e-7ef17be785b7.png)

---

vDOT
0x1610bc33319e9398de5f57b33a5b184c806ad217
https://zpl.io/2pRo5N8
![vDOT](https://user-images.githubusercontent.com/51817359/120316981-589acb80-c2de-11eb-92a3-98012b1a4bd7.png)

---

vLINK
0x650b940a1033b8a1b1873f78730fcfc73ec11f1f
https://zpl.io/2GPzr34
![vLINK](https://user-images.githubusercontent.com/51817359/120317039-6fd9b900-c2de-11eb-8b7e-f17fb45ee179.png)

---

XRP
0x1d2f0da169ceb9fc7b3144628db156f3f6c60dbe
https://zpl.io/2GPzr34
![XRP](https://user-images.githubusercontent.com/51817359/120317102-841db600-c2de-11eb-8b79-832fef54d299.png)

---

SXP
0x47bead2563dcbf3bf2c9407fea4dc236faba485a
https://zpl.io/adKAZmp
![SXP](https://user-images.githubusercontent.com/51817359/120317181-9d266700-c2de-11eb-9d46-5c322d32f4c5.png)

---

VAI
0x4bd17003473389a42daf6a0a729f6fdb328bbbd7
https://zpl.io/2jqlzr4
![VAI](https://user-images.githubusercontent.com/51817359/120317239-aa435600-c2de-11eb-9a4d-a76e4a3bbddd.png)

---

XVS
0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63
https://zpl.io/aRRNZLz
![XVS](https://user-images.githubusercontent.com/51817359/120317306-c21ada00-c2de-11eb-8d7a-dc600c8ba06c.png)

---

vXRP
0xb248a295732e0225acd3337607cc01068e3b9c10
https://zpl.io/b6Alq9d
![vXRP](https://user-images.githubusercontent.com/51817359/120317414-e1196c00-c2de-11eb-9287-07b40b0e0ade.png)

---

LTC
0x4338665cbb7b2485a8855a139b75d5e34ab0db94
https://zpl.io/2E4wrDe
![LTC](https://user-images.githubusercontent.com/51817359/120317506-fd1d0d80-c2de-11eb-92a1-feb0fcfedfbe.png)

---

**Comment by hboon** [comment]
Refer https://github.com/AlphaWallet/alpha-wallet-ios/issues/2835#issuecomment-853717366
