### ISSUE TITLE
Do not reset the Browser when you hit on "Browser icon"

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1886]
> "Is it intentional that when you press the Browser/Home button there is no "back button" functionality on the top left corner? The scenario is that I was browsing the AAVE dapp and was pretty deep into some pages and pressed browser by accident while trying to scroll up with my thumb. This sent me to the homepage(as intended), so I had to start my AAVE browsing all over again, which is a little bit frustrating"

**What to do:**
Do not reset the browser when you hit on "browser" icon again.

**Comment by JamesSmartCell** [comment]
Ok, we can remove it - it goes against the design standard but since most people don't seem to know this is how apps with tab bar should work; it should be ok.

Needs to be done together with adding the 'home' button at the top.
