### ISSUE TITLE
Fiat details missing

### ISSUE THREAD

**Issue by splitice** [AlphaWallet/alpha-wallet-android#1897]
Great app. I have a wallet which has been running on my android device for many months. It's running on my android device as a watch only wallet  (public key).

Recently it lost fiat value information. Not a big issue but rather annoying.

I tested changing from AUD to USD to see if it was an issue specific to AUD. It's not.

I suspect it is due to the wallet being watch only as I have noticed other bugs with wallets in a watch only setup (for example that the activity page is missing all transactions).

**Comment by JamesSmartCell** [comment]
Hi @splitice Thanks for reporting! Can you say for which chain you're seeing the activity page is missing transactions? We're aware of an update for xDai API routes which prevented some xDai transactions showing. Also Polygon/Mumbai had similar issues.

These issues should be fixed in the release that's coming this week.

**Comment by JamesSmartCell** [comment]
Could you give some more info about Fiat info loss? We haven't seen this reported from anywhere else and it appears to be correctly on all our builds. Eg do you use VPN, if so which one; our method of fetching API call may be failing over some of these. Did the fiat info come back?

**Comment by splitice** [comment]
No VPN. Just a regular old (IPv4) internet connection. I do not beleive it to be related to connectivity as another device with a full wallet was not affected on the same network.

I ended up resolving the issue (or it resolved itself). I did reinstall the application. So either the API service you run had a period of unavailability or some cache was corrupt.

An Ethereum wallet is my only datapoint.

**Comment by JamesSmartCell** [comment]
Yes, that could well be. We get our price info for ERC20 tokens from coingekko, and our chain price data from CoinMarketCap. Did you notice if there were still prices for tokens, and no chains or vice-versa? Or just no prices for any tokens?

**Comment by JamesSmartCell** [comment]
It could either be something in the app that caused it to lose sync (most likely) to service error (least likely). I can def take a look at how the tickers are stored and see if there's a way for sync to be lost.
