### ISSUE TITLE
Implement EIP3085 wallet_addEthereumChain

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1901]
This is the iOS PR for reference: https://github.com/AlphaWallet/alpha-wallet-ios/pull/2907

A good site for Heco to test against: https://opennft.io. Tap on the hamburger in the top right of the site and tap CONNECT to trigger `wallet_addEthereumChain`.

There are a few cases to handle:

A. Prompted for a chain that is already enabled, but not the current chain in the browser
B. Prompted for a chain that is already supported (either built-in or already added as a custom chain)
C. Prompted for a chain that isn't supported and not added as a custom chain yet
D. Prompted for a chain that is already enabled and is the current chain in the browser

For C, we'll need to develop with the built-in support for Heco disabled in the app.

I don't know if it's common behavior, but on https://opennft.io, once the chain is enabled and active in the browser, if you tap CONNECT, it wouldn't send `wallet_addEthereumChain`. It probably checks for the chainID first. That means you can't test D with the site

On iOS, we share the custom chains added across wallets.

Useful to work on this with #1887 in mind

Our web3 provider (dist/AlphaWallet.js and dist/AlphaWallet-min.js) has been updated in https://github.com/AlphaWallet/AlphaWallet-web3-provider/commit/308dbd3c7f70487b90aabdeef8641b7ad959c26f.

The app-injected JavaScript hook needs to be updated to install a native hook: https://github.com/AlphaWallet/alpha-wallet-ios/blob/49d8f257b128a429276942a1d03dc2b46cf0e558/AlphaWallet/Browser/Factory/WKWebViewConfiguration.swift#L118

The JavaScript payload looks like this:

```
{
   "object" : {
      "nativeCurrency" : {
         "name" : "HT",
         "symbol" : "HT",
         "decimals" : 18
      },
      "blockExplorerUrls" : [
         "https://hecoinfo.com"
      ],
      "chainName" : "HECO",
      "chainId" : "0x80",
      "rpcUrls" : [
         "https://http-mainnet-node.huobichain.com"
      ]
   },
   "name" : "walletAddEthereumChain",
   "id" : 52026
}
```

iOS version (just the object) is defined in: https://github.com/AlphaWallet/alpha-wallet-ios/blob/49d8f257b128a429276942a1d03dc2b46cf0e558/AlphaWallet/Browser/Types/DappCommand.swift#L114 as:

```
struct WalletAddEthereumChainObject: Decodable {
    struct NativeCurrency: Decodable {
        let name: String
        let symbol: String
        let decimals: Int
    }

    let nativeCurrency: NativeCurrency?
    var blockExplorerUrls: [String]?
    let chainName: String?
    let chainType: String? //ignore this
    let chainId: String //this is a hex number with "0x" prefix. On iOS, we relax this a little and if it is without "0x", process it as dec
    let rpcUrls: [String]?
}
```

The `?` represents optionals (i.e. the values can be nil), according to the EIP. But during processing in iOS, we deviate from the spec a little to make life simpler for ourselves by assuming (and enforcing) that both blockExplorerUrls and rpcUrls arrays are present and have 1 element.

Once the payload is read, there are a few auxiliary things to do:

1. Make an RPC call with the provided RPC URL for "eth_chainId" and verify the chain ID matches what's provided in the payload
2. Check if `api.` needs to be prepended to the blockchain explorer domain name (iOS makes a call against `/api?module=account&action=tokentx&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3` and check if `json["result"]` is an array)
3. Check if the blockchain explorer is Etherscan-compatible or Blockscout-compatible (test with call in A, but `action=tokennfttx`. Check result in the same way)

**Comment by JamesSmartCell** [comment]
Note this Issue is partly closed now, it remains to implement the improved UI and custom chains.
