### ISSUE TITLE
Biometrics interferes with wallet import

### ISSUE THREAD

**Issue by roguetr** [AlphaWallet/alpha-wallet-android#1903]
On two separate Android devices, both with version 3.33, importing the wallet using fingerprint on one and facial recognition on the other has failed. I've been required to select "Use Pin" and enter the pattern manually.

**Comment by JamesSmartCell** [comment]
Hi @roguetr , yes we had to pull facial recognition unlock support for now as it's not considered a fully secure unlock on some phones, and wouldn't provide the required unlock event that the keystore needed to unlock the private key.

Perhaps we can support it like this: support a software lock of the key if using facial unlock. The PIN/Fingerprint lock can use the full secure enclave locking.

**Comment by roguetr** [comment]
Hi James,

I'd be happy to use pin only but it seems to attempt facial recognition
with no option to disable it (I use pattern for system unlock but have face
data stored), so currently I just go through the process of clicking "use
pin", which prompts for facial recognition and then clicking "use pattern"
and entering the pattern.

This only seems to be an issue for wallet import. I've been able to
successfully click "use pin" and then facial recognition for transactions
though I'm not sure if that's consistent.

So a hard option for pin only would be good to avoid the double handling 🙏

I know this is unrelated but while I've got your attention, do you know if
there are any plans for dark mode and an activity search?

Thanks!

**Comment by JamesSmartCell** [comment]
Dark mode request @colourfreak is our UX designer. I'm a fan of app skins too.
Activity Search: I believe it's in iOS, so it should be coming. Good idea anyway, that would be useful.

Yes, the key biometrics handling needs updating - we switched to the newer Android API a while back but it just didn't work correctly. By now hopefully they have ironed out the issues.

**Comment by roguetr** [comment]
Awesome, thanks! Looking forward to future updates. This app has by far has
been the most convenient and useful as a daily driver over any others that
I've ... persisted with :D

**Comment by colourfreak** [comment]
> I know this is unrelated but while I've got your attention, do you know if
> there are any plans for dark mode and an activity search?

We haven't thought about the dark mode yet. But we can put this in our backlog. But for the activity search is definitely a good suggestion. We already have it in iOS version of the app, the Android part is in progress. 

@roguetr How do you usually search for activity? Would you rather search for an address, amount... ?

**Comment by roguetr** [comment]
@colourfreak hmmm ... date or date range comes to mind first as I have had to scroll back _a lot_ to find transactions I'm looking for. Token/coin second. Address would certainly be useful but more when scrutinising contract interactions. Amounts above or below a filtered threshold would also be useful.

**Comment by JamesSmartCell** [comment]
@colourfreak this looks like it's a good issue on its own. An Activity sort by date, token name (any interaction with) and possibly token address is something I'd find very useful too. Sort by interaction with token does need extra support as currently we don't store eg the destination address of a token send; we decode this from the transaction input. This would have to be added to the activity database so it can be indexed, or more easily fetched from etherscan API on an ad-hoc basis.

**Comment by colourfreak** [comment]
> @colourfreak this looks like it's a good issue on its own. An Activity sort by date, token name (any interaction with) and possibly token address is something I'd find very useful too. Sort by interaction with token does need extra support as currently we don't store eg the destination address of a token send; we decode this from the transaction input. This would have to be added to the activity database so it can be indexed, or more easily fetched from etherscan API on an ad-hoc basis.

Yeah. Very nice. I am adding this to my to-do list.

**Comment by colourfreak** [comment]
Banking apps should be a reference for us. They have to deal with the same issue. They allow users to search for payments from the past.

**Comment by JamesSmartCell** [comment]
Closing as action looks complete
