### ISSUE TITLE
Make chain ID in `engine.chainId` be hex encoded

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1904]
Refer to https://github.com/AlphaWallet/alpha-wallet-ios/pull/2923/files for implementation.

So it's consistent with:

```
await ethereum.request({method: 'eth_chainId'}) //returns 0x80
```

Note that the value returned by `web3.version.getNetwork()` should still be decimal (empirically determined)

**Comment by JamesSmartCell** [comment]
@hboon I couldn't get this to work, when I changed it nearly all dapps stopped working; they work correctly when value was reverted to decimals. Will revisit when we get more information on it.

Are there any dapps which require the network info to be in hex?

**Comment by hboon** [comment]
Not sure. Let’s just keep it that way first. I’ll take a quick look if I have the chance. But let’s not waste much time on this for now.

**Comment by hboon** [comment]
Closing for now since it seems to break things

**Comment by hboon** [comment]
I finally understand why it didn't work the last time. I wrote the issue wrongly. It was:

> Change `web3.version.getNetwork()` to return a hex

when it should be:

> Change `engine.chainId` to return a hex and note that the value returned by `web3.version.getNetwork()` should still be decimal (empirically determined)

**Comment by hboon** [comment]
Have updated the issue title and 1st comment for posterity
