### ISSUE TITLE
Documentation links are geting  404 Not Found Error

### ISSUE THREAD

**Issue by Teodor-Iancu** [AlphaWallet/alpha-wallet-android#1910]
Documentation links are geting  404 Not Found Error

**Comment by hboon** [comment]
Could you point us to which doc/file you found the broken link in so we can fix it?

**Comment by Teodor-Iancu** [comment]
--> "Find more information in our available documentation."
--> https://github.com/AlphaWallet/alpha-wallet-android/blob/master/docs/desktop/README.md
--> https://github.com/AlphaWallet/alpha-wallet-android/blob/master/docs/lib/README.md
--> https://github.com/AlphaWallet/alpha-wallet-android/blob/master/docs/dmz/README.md

**Comment by hboon** [comment]
Thanks @Teodor-Iancu!
