### ISSUE TITLE
gradle build issue in dmz project

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1925]
observe in which directory is the following command executed:
````
dmz$ gradle build
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/a/IdeaProjects/alpha-wallet-android/dmz/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':dmz'.
> Could not find method testCompile() for arguments [junit:junit] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 56s
````

**Comment by colourful-land** [comment]
Maybe it has something to do with my gradle version?
````
$ gradle --version

------------------------------------------------------------
Gradle 7.0.1
------------------------------------------------------------

Build time:   2021-05-10 16:08:58 UTC
Revision:     67e618faef187783dadd03a34fdab9dc71b85b19

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OS:           Linux 5.4.0-42-generic amd64
a@thinkpad:~/IdeaProjects/alpha-wallet-android/dmz$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
a@thinkpad:~/IdeaProjects/alpha-wallet-android/dmz$ javac -version
javac 11.0.11

````

**Comment by mpaschenko** [comment]
AW doesn't support gradle 7.x yet, please downgrade to 6.9 or so 
cc:@JamesSmartCell

**Comment by colourful-land** [comment]
> AW doesn't support gradle 7.x yet, please downgrade to 6.9 or so
> cc:@JamesSmartCell

Can you make it work with gradle 7? I'm interested to see how you find out the underlying problem between gradle 7 and αW.

**Comment by mpaschenko** [comment]
I saw comment in the code about APK ballooning issue, what is it?

**Comment by mpaschenko** [comment]
@colourful-land please check my commit, basically, I can't see any issues with build & gradle 7, app runs well as I see. Please let me know if you will encounter any further problems

**Comment by colourful-land** [comment]
> I saw comment in the code about APK ballooning issue, what is it?

Can you check it yourself? Build it and check the resulting apk file size before and after

**Comment by mpaschenko** [comment]
@colourful-land pushed fixes, now apk file size remains the same. Actually, it's not the issue, but a new way to keep native libs uncompressed in the apk, so the OS shouldn't uncompress them before run.

**Comment by JamesSmartCell** [comment]
@mpaschenko this fixes the APK ballooning issue? If so, nice work - we haven't had a chance to try to diagnose this issue.

**Comment by mpaschenko** [comment]
@JamesSmartCell yes, the size remains the same as before

**Comment by JamesSmartCell** [comment]
Really good. Finally can update the gradle version.
