### ISSUE TITLE
Optimistic Ethereum not working 

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-android#1930]
After checking the new version of UniSwap on Optimistic Ethereum using the in-app browser, AlphaWallet latest version (19/07/21) on Galaxy S10+ here are the findings. We can split it to different issues after.

1) Unable to connect to Optimistic via WalletConnect in Chrome. Once the QR code is scanned, we are automatically connected to mainnet Ethereum, even though is disabled in active networks in the wallet (on iOS it doesnt work at all) 

2) The wallet detects the tokens twice (same as on iOS):

![Two_optimistic_tokens_Android](https://user-images.githubusercontent.com/84448420/126229561-03ed72bf-26c5-44b4-a2af-8dacd41abeb5.jpg)

3) In Uniswap the token with value is detected but the rest are almost always not, similar to the RPC node issue we had with Polygon

![Android_doesnt_detect_tokens](https://user-images.githubusercontent.com/84448420/126229982-9adf3456-8fc8-4d20-bc80-c890515311a2.jpg)

4) In the rare cases they are detectable and selected we are stuck on this screen, unable to fetch the exchange data.

![Android_unable_to_fetch_values](https://user-images.githubusercontent.com/84448420/126230135-5d8586a3-886e-4246-8236-c92492886847.jpg)

I was unable to proceed further and didn't manage to complete a transaction on neither iOS nor Android.

For a reference, you can see the current iOS issues on OE here: https://github.com/AlphaWallet/alpha-wallet-ios/issues/2979

**Comment by JamesSmartCell** [comment]
thanks @hieronymus4826. Do you have a watch address that has optimistic assets on it we can use for validation? I tried to get Optimistic Kovan tokens but couldn't get anywhere with the conversion dapp.

**Comment by hieronymus4826** [comment]
@JamesSmartCell I've tested it in all four wallets, all have assets on OE mainchain.

AlphaWallet iOS:  0x327FAE26ac2bA0a1C1e9b79663B72Ac139100Bc2 - has ETH

AlphaWallet Android: 0x4091c56F4636e3f4065a060c6765F4AB2890a8ce - has ETH

Metamask: 0xef12a286ab1398D2802401aC9dfCfb1Bd175d371 - Has ETH-xDai LP from UniSwap v3

CoinBaseWallet: 0x857D0Cc397867275110D1bA00bd01f61FE8C9ba0 - Has ETH-xDai LP from UniSwap v3, and xDai and ETH

**Comment by hieronymus4826** [comment]
I can also transfer you some, the fees are $0.30 to $0.50. Ping me on Discord when you need it.
