### ISSUE TITLE
Verify `CRONOS_TEST_URL` is correct

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1941]
From #1938

Verify `CRONOS_TEST_URL` is correct at https://github.com/AlphaWallet/alpha-wallet-android/blob/01dee23cd51871efbba5da45f0be703101222b52/lib/src/main/java/com/alphawallet/ethereum/EthereumNetworkBase.java#L60

There seems to be 2 `EthereumNetworkBase.java` files. The other one seems correct (and different): https://github.com/AlphaWallet/alpha-wallet-android/blob/01dee23cd51871efbba5da45f0be703101222b52/app/src/main/java/com/alphawallet/app/repository/EthereumNetworkBase.java#L125

**Comment by jinkjonks** [comment]
Oops this was my bad! Thanks for pointing it out. I've made a new PR to fix this.

**Comment by hboon** [comment]
@jinkjonks thanks for checking it out
