### ISSUE TITLE
Beefy Finance doesn't detect Polygon

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-android#1945]
Probably related to https://github.com/AlphaWallet/alpha-wallet-android/issues/1944

![Screenshot_20210726-204031_AlphaWallet.jpg](https://user-images.githubusercontent.com/84448420/127034339-907cb809-1405-460e-ba35-9d473bbde36f.jpg)

Does not connect at all using WalletConnect in Chrome on both Android and iOS.

Works properly on iOS (in the wallet browser).

**Comment by JamesSmartCell** [comment]
@hboon seems we do need that upgrade you made; although despite trying for a while, I couldn't get anywhere with it. Could you give me a dump of a page with the provider code filled in; that way by comparing what AW Android is doing I can see exactly what's going wrong with the integration.

**Comment by hboon** [comment]
Maybe you are referring to this injected code?

```
                   walletAddEthereumChain: function (msgParams, cb) {
                       const data = msgParams
                       const { id = Math.floor((Math.random() * 100000) + 1) } = msgParams
                       console.log("walletAddEthereumChain", msgParams)
                       AlphaWallet.addCallback(id, cb)
                       webkit.messageHandlers.walletAddEthereumChain.postMessage({"name": "walletAddEthereumChain", "object": data, id: id})
                   },
```

For context, refer to #1901. It's mentioned under "The app-injected JavaScript hook needs to be updated to install a native hook:".

The error in the screenshot suggests the web provider library isn't updated. You can verify it by looking for "Our web3 provider (dist/AlphaWallet.js and dist/AlphaWallet-min.js) has been updated in" in #1901

**Comment by JamesSmartCell** [comment]
Following the steps exactly it still doesn't work on Android and I have no idea how to proceed to debug why it doesn't work. Can you do a web debug on chrome and copy paste exactly what iOS is giving to the browser? I think I can quickly work out what's going wrong based on this. Thanks.

**Comment by hboon** [comment]
For posterity. Try in the browser:

```
        await window.ethereum.request({
              method: 'wallet_addEthereumChain',
              params: [
                {
                  chainId: '0x61',
                  rpcUrls: ['https://data-seed-prebsc-1-s1.binance.org:8545/'],
                },
              ],
            });
```
