### ISSUE TITLE
Implement designed Prompts for EIP3085 wallet_addEthereumChain support

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1950]
Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/2908

**Comment by JamesSmartCell** [comment]
Actions for this PR:

1. Implement UX as per spec linked above (note use BottomSheetDialog but 'Androidise' the appearance as appropriate ie no bottom bar).
2. Allow custom chains with provided RPC, chain name, decimals etc. (Note that the block explorer part should be done in a different PR - only implement enough to get the chain working, the balance of the display working and name displaying).

**Comment by JamesSmartCell** [comment]
@mpaschenko can you check how much of this is complete based on your PR #1964 ?

**Comment by JamesSmartCell** [comment]
I do not have a good example to test on. It might be straightforward to produce a 'fake' event by using one of the Polygon dapps which produce this network switch, and just change the chainId to an unknown chain.

**Comment by mpaschenko** [comment]
@JamesSmartCell added the basic implementation of the adding the chain from dapp.
please check commit https://github.com/mpaschenko/alpha-wallet-android/commit/fa42575d8f3f66f295d69e6817423ef7cfffee19
WalletAddEthereumChainObject is missing a few fields:
- blockExlorerUrl
- explorerApiUrl
- if it's testnet...
