### ISSUE TITLE
Add 'Rate Me' dialog + button

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1967]
Need to add the 'Rate Me' button as per just about every other app.

Recommend waiting until 5 app opens, and/or completing a successful action like sending a transaction or receiving some funds.

Therefore add a trigger in WalletFragment, and also in SendActivity.

Check with iOS team under what conditions the dialog appears.

Ensure the dialog looks correct, similar to ones used by apps like Twitter/Quora etc.

**Comment by mpaschenko** [comment]
@JamesSmartCell in a side project I did similar, and logic was:
- 1-3 stars - redirect user to mail form or somekind of the report (which is internal)
- 4-5 start - redirect user to google play, 
to avoid bad reviews...
just FYI.

**Comment by JamesSmartCell** [comment]
Thanks, I was hoping you had previous experience with this! Looks good.
