### ISSUE TITLE
Not detecting balances and transfer history on Ethereum Mainnet

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-android#1970]
Two separate users reporting they cannot see their ETH balances (or other tokens on the Ethereum Chain) on Android in the wallet. The balaces are properly read in the Browser and Detected by third party Defi Dapps. Working properly on iOS.

Case 1:
Android:
![Zero_balance_2](https://user-images.githubusercontent.com/84448420/129209885-ede05062-8917-48ed-95b7-ddebeaedccef.jpg)
Same Wallet on iOS:
![iOS1](https://user-images.githubusercontent.com/84448420/129209968-b49619d8-31f7-493e-9b03-5bf058cff62f.JPG)

Case 2:
Android:
![Zero_balance_1](https://user-images.githubusercontent.com/84448420/129210087-9ae1762c-d24e-4504-8279-3d83db1d95c7.jpg)
Same Wallet on iOS:
![iOS2](https://user-images.githubusercontent.com/84448420/129210220-fc8a68e4-08da-4757-bc89-de1103f67458.JPG)

Transaction history on Android (stops in 2019):
![transaction_history_1](https://user-images.githubusercontent.com/84448420/129210297-011774f9-4cf5-4d75-b370-8b2a056ef211.jpg)

Transaction history on iOS (Till July 2021):
![Transaction_history_iOS](https://user-images.githubusercontent.com/84448420/129210409-4643149e-a8bc-4b4d-9441-72281953357e.JPG)

Using the latest Android and iOS versions. I read them both properly as a Watch Wallet on the same version of Android. Both work on iOS.

Case 1 public Address: 0xA2c8f66c4a70DeDdF04C5bbAb71d3A96443F8172
Case 2 public Address: 0x3f17f1962B36e491b30A40b2405849e597Ba5FB5 (legacy wallet)

**Comment by kboyero** [comment]
![Uploading aa.PNG…]()

**Comment by JamesSmartCell** [comment]
@hieronymus4826  I have managed to reproduce this on the released build, but not on a local build. Really confusing and really bad! I will re-release after I find out what the reported crash issue is about.

**Comment by JamesSmartCell** [comment]
@hieronymus4826 This should have been fixed in v3.36.2. Once it has been released on PlayStore please update and close the issue if this is the case.
