### ISSUE TITLE
Will ApphaWallet support  L2 zkSync?

### ISSUE THREAD

**Issue by gosgos11** [AlphaWallet/alpha-wallet-android#1973]
Will ApphaWallet support ETH second-layer networks such as zkSync?

**Comment by JamesSmartCell** [comment]
We so far only support Optimism L2. 

I just took a look at the zkSync explorer, it looks like this is a very popular network. Yes, we'll definitely look into supporting it.

Thanks for bringing this up.

**Comment by gosgos11** [comment]
> We so far only support Optimism L2.
> 
> I just took a look at the zkSync explorer, it looks like this is a very popular network. Yes, we'll definitely look into supporting it.
> 
> Thanks for bringing this up.

Thank you.
