### ISSUE TITLE
Update Dialog

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1974]
Implement a 'A new version of AlphaWallet has been released. Please upgrade in order to ensure issues are fixed' Dialog.

I think the best way to do this is to check github releases which we maintain alongside each PlayStore release:

```https://api.github.com/repos/AlphaWallet/alpha-wallet-android/releases/latest```

You can pull the latest version ID here: 

```
"node_id": "MDc6UmVsZWFzZTQ3MjIwNTA5",
  "tag_name": "v3.36.1",    <-----------------------
  "target_commitish": "master",
  "name": "Provider connection and stability upgrade",
  "draft": false,
  "prerelease": false,
  "created_at": "2021-08-03T12:03:24Z",
  "published_at": "2021-08-03T12:13:39Z",
```

Compare this with the version on ```BuildConfig.VERSION_NAME```

These are kept in step.

**Comment by JamesSmartCell** [comment]
If you can get the version directly from the PlayStore this is better, but I'm not sure if this is API is available.

**Comment by mpaschenko** [comment]
@JamesSmartCell there is In-App Updates api
https://developer.android.com/guide/playcore/in-app-updates
which can even initiate the update...

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell there is In-App Updates api
> https://developer.android.com/guide/playcore/in-app-updates
> which can even initiate the update...

^ can you implement it?

**Comment by mpaschenko** [comment]
Yes, I had a chance to work with it
