### ISSUE TITLE
Why tokens take so much time to load on the list?

### ISSUE THREAD

**Issue by Donnardu** [AlphaWallet/alpha-wallet-android#1981]
Hello, im facing a problem with the android build and project.
Coins and tokens take a lot of time to load in the token manager and sometimes ethereum tokens doesn't load at all for some periods of time. Why is this happening? Thanks.

**Comment by JamesSmartCell** [comment]
The Infura key in gradle.build is provided only as a curtesy to help getting the source built. That key is completely rate limited as it's used by a lot of people making builds. If you create a free Infura account, a new project and take the 'PROJECT ID' from the settings page of your project you'll find the wallet works correctly.

**Comment by JamesSmartCell** [comment]
Project key, not secret.

**Comment by JamesSmartCell** [comment]
Closing this, as dropping in your own Infura key should solve the issue.
