### ISSUE TITLE
App unresponsive when switching to wallet with high activity

### ISSUE THREAD

**Issue by roguetr** [AlphaWallet/alpha-wallet-android#1987]
Sorry if this related to another problem report but it appears to be separate.

When launching the app to my main wallet that has a lot of activity and has had many tokens associated with it (or when switching to that wallet), the app can become unresponsive for up to a minute and sometimes longer.

I love that Alphawallet automatically enumerates all tokens that I use or have had associated with my wallet but I've had to switch back to twallet for now when using Polygon and only endure the delay when on Avalanche.

Maybe an option for manual update is possible? I have to manually add tokens to twallet but when your primary use feature is the DApp browser, that's not really an issue.

**Comment by JamesSmartCell** [comment]
@roguetr Yes I've seen this lately too; esp for wallets with NFT's. Does your wallet have a lot of NFT's or just a lot of ERC20 tokens?

**Comment by roguetr** [comment]
Only two (Polygon) NFTs, primarily just a lot of tokens on Polygon.

**Comment by JamesSmartCell** [comment]
OK thanks for reporting; previously the wallet handled very large token lists perfectly fine, but we've since added better handling for NFT and new tokens so I suspect we need to add some extra rate limiting in the new handling code.

**Comment by roguetr** [comment]
Brilliant, thanks for such quick responses and updating me.

**Comment by JamesSmartCell** [comment]
Hi @roguetr sorry for the delay, can you update from the play store and let us know if this version fixes the issue?

**Comment by roguetr** [comment]
Straight up I was able to scroll the token list without delay, brilliant!
So my first impression is yes. If that changes I'll let you know.

Well done and thank you!

**Comment by JamesSmartCell** [comment]
Thanks for replying :) much appreciated

**Comment by roguetr** [comment]
Tbh, everything seems quicker, there's obviously been some improvement
under the hood. I can now connect to ethermine with wallet connect which is
awesome.

Had a strange glitch after previous update I believe where DApp icons went
to generic images but just edited one and all came back.

So far very impressed with this update.

**Comment by JamesSmartCell** [comment]
Thanks, yes a lot of work went into this update, especially the ERC1155 support. We checked against all the NFT and DeFi whale wallets we could find too.

There's more coming too - we have a big UX update that provides a lot more data for DeFi usage.

**Comment by roguetr** [comment]
That's awesome. I'm really happy that I've been able to switch back to
Alphawallet.

Out of curiosity, what's the best way to report interaction issues,
assuming you want them. Right now I'm not seeing many but for instance,
this morning hitting the approve button for breaking LP tokens on Wault
swap (Polygon) would prompt for signing but not proceed (tried multiple
times, restarted app etc). On TrustW after signing it went straight
through.

I didn't want to go creating tickets for something you're not interested in
or if maybe there's a better channel.

**Comment by roguetr** [comment]
Regarding the example of Wault swap, maybe I should be choosing Wallet
Connect instead Metamask now that that is working ...

What is the recommended option (Wallet Connect/Metamask) to choose when
given the choice? Does it matter?

Sorry for all the questions!

**Comment by JamesSmartCell** [comment]
Argh! We struggle with this. Some apps use a generic Web3 injection and call it MetaMask. If they're doing this, then that's the way I prefer to connect. Sometimes the developer tries to be useful and insists that the MetaMask wallet actually needs to be Metamask and attempts to start it.

Really, if DApp developers just used targetless web3 - like HTML - then it would be much easier; have a web3 icon which would work with MM, Trust, WallETH and AW etc.

The top apps do this, like Uniswap, 1Inch, Quickswap etc. They don't even ask for a connection type if they find web3 hooks - they just go ahead and use it.

So - there's no good answer really. If I'm asked, I try the Metamask option, if that works then all good. Otherwise my second option will be WalletConnect.

**Comment by roguetr** [comment]
Nice, that's exactly what I currently do but good to have it validated.
Thanks for all the prompt responses and assistance btw, you've been very
accommodating and very helpful.

(FYI the Wault LP approve issue is consistent between both the Metamask and
WalletConnect options)

**Comment by JamesSmartCell** [comment]
Hi @roguetr I'll close the issue now, please contact us again if you see anything else or have any ideas.

Thanks again for reporting this; we had noticed it a day or so before you reported it but weren't sure if it was affecting anyone.

Cheers,

James
