### ISSUE TITLE
Icons uploaded to iconssets are not up-to-date in the app

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#1998]
Maybe caching?

It's seems that there is a conflict between an external library and the one we have in iconssets. 

https://github.com/AlphaWallet/iconassets

**Comment by colourfreak** [comment]
ENJ could be a good example here.

**Comment by mpaschenko** [comment]
@colourfreak  trust wallet asset repo has ENJ token, so first it loads from there:
https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xF629cBd94d3791C9250152BD8dfBDF380E2a3B9c/logo.png

**Comment by JamesSmartCell** [comment]
@colourfreak we check the trust repo first (because the initial implementation was only a few testnet tokens, since then we've added a huge number of assets).

Do you prefer now to check our icon repo first? If so, @mpaschenko can you re-order the check in class TokenIcon

**Comment by colourfreak** [comment]
@hboon 

Goal: Load up icons provided by us first, if not exist, load up an external library. I manually created and uploaded 140 HQ icons.

**Comment by colourfreak** [comment]
> Do you prefer now to check our icon repo first? If so, @mpaschenko can you re-order the check in class TokenIcon

Yep. The EJN is a good example of how ugly the external graphic can be. 

Since we are all here, let's discuss how to optimize these images. I usually upload a 512x512 px png graphics. That sounds a bit heavy though. Maybe we can think of webp or avif? We can think of lazy loading as well. So let's get image placeholders first (just a gray circle) + name + prices, then load up asynchronously those icons while you are scrolling. 

Thoughts? @hboon @JamesSmartCell @mpaschenko

**Comment by hboon** [comment]
>@hboon  ...

@colourfreak yes. Should be our repo first then fallback to Trust’s then programmatically generated as fallback.

**Comment by hboon** [comment]
I don’t think size is a major issue though. If we want, we can reduce it so it is the largest possible dimension we use it for, eg on iOS is is 3x of maybe 44px (can’t remember offhand the size).

We shouldn’t use other formats because iOS doesn’t do webp and PNG is very performant.

We also don’t need to worry too much about size actually, since the icons ought to be cached locally for a while.

Not worth over-engineering this unless there’s something really bad happening. But we should make loading order, caching etc correct though.

**Comment by JamesSmartCell** [comment]
> > @hboon  ...
> 
> @colourfreak yes. Should be our repo first then fallback to Trust’s then programmatically generated as fallback.

I agree too. The icon repo was added initially just for odd uses but it's moved way beyond that now. It's a simple mod to reverse the load order.

**Comment by JamesSmartCell** [comment]
Fixed in #2002
