### ISSUE TITLE
Name / Symbol

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2000]
Hi @colourfreak, the new 'using the symbol for the token name' is definitely a step in the right direction, it looks less cluttered.

I would like to propose a slight modification.

Currently the format of the left hand side of the Token cards is like this:

[Icon] [Symbol (*1)]
[Icon] [Balance] [Symbol (*2)]

There's a few edge conditions that don't work like this: 

- Ethereum base tokens. Some of the Testnet and Mainnet tokens have the same symbols. This could be an issue with Android only - perhaps the symbol names are wrong?
- Token name from TokenScript - for attestations the TokenScript name will be the only source for naming. 
- Tokens which have mixed up the symbol and the name (there are a few). 
- Tokens without a symbol eg Enjin token.

I propose this heuristic for filling in fields *1 and *2:

When picking *1 (long name):
1. Use TokenScript name if available.
2. Use Token name if longer than Token symbol.
3. Use Token symbol.

When picking *2 (short name):
1. Use shortest of name and symbol, but abbreviate to 5 characters or less and capitalise.

Here's what the above heuristic looks like for my wallet:

https://user-images.githubusercontent.com/12689544/132428393-9a37cabc-e048-4ba0-8e2a-a53cbd226635.mp4

And previously:

https://user-images.githubusercontent.com/12689544/132429487-34223229-28ee-4b71-b4bb-d615f06ce91b.mp4

We can at minimum do this:

- If TokenScript is available, use TokenScript name.
- If symbol is blank, use shortened name.
- Use chain name for Chain tokens.

Let me know what you think - just need a consensus between everyone.

**Comment by colourfreak** [comment]
I love that @JamesSmartCell Very, very good suggestion.

**Comment by colourfreak** [comment]
@hboon Can you make sure that this applies to iOS as well?

**Comment by JamesSmartCell** [comment]
The code is committed into the working Samoa branch. @hboon can I close this issue now? It'll still be there for your reference.

**Comment by hboon** [comment]
> The code is committed into the working Samoa branch. @hboon can I close this issue now? It'll still be there for your reference.

Yes, of course :)
