### ISSUE TITLE
Filter IME in the #1768 branch

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2001]
Can you check the IME action in the Token filter (SearchTokensHolder)? When I click it there's an app crash with undeliverable focus. Looks like you just need to hook up the IME to bypass the 750 ms delay.

**Comment by mpaschenko** [comment]
@JamesSmartCell not sure I understand what you mean, have never got that, can you send crash log please?

**Comment by JamesSmartCell** [comment]
Go to the search dialog and let the softkeyboard open. Click the -> IME button on the keyboard. Crash. The crash log isn't very useful as it's just a generic 'undeliverable focus' error without saying where it came from.

**Comment by mpaschenko** [comment]
Thanks, just have to change imeOptions to actionSearch, fixed

**Comment by JamesSmartCell** [comment]
I can see the new search icon but it still crashes when I click on it.

```
2021-09-10 12:39:58.568 6290-6290/io.stormbird.wallet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.stormbird.wallet, PID: 6290
    java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
        at android.widget.TextView.onKeyUp(TextView.java:9616)
        at android.view.KeyEvent.dispatch(KeyEvent.java:3648)
        at android.view.View.dispatchKeyEvent(View.java:15050)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
```

I think you need to actually hook up a listener for the IME search event, currently it's still dangling.

**Comment by mpaschenko** [comment]
ok will add that as well, it doesn't crash on my side, checked on Samsung A10 and Pixel, just curious which device do you have as test?

**Comment by JamesSmartCell** [comment]
S20

**Comment by mpaschenko** [comment]
I'm on 11 as well

**Comment by JamesSmartCell** [comment]
Hmm, ok --- see if adding a handler for the IME fixes it, if not maybe it's just happening locally.

**Comment by JamesSmartCell** [comment]
It no longer crashes now that the IME is handled, so that's good.

Before we launch the update though, the search button will need to be connected through to the adapter code:

After I click on the search IME, the soft keyboard should immediately be cleared and the search should start. I use the app full screen, using gesture navigation which makes this issue especially awkward as the search IME often intercepts the gesture and stops me from clearing the keyboard. 

Currently the soft keyboard is stuck visible, the only way to clear it is by clicking on a token and then going back to the wallet page.

**Comment by JamesSmartCell** [comment]
Works perfectly now :)
