### ISSUE TITLE
Make all input fields according to material design

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2005]
We should follow the material design (check our outlined design).
https://material.io/components/text-fields#usage

So, therefore, I propose making all custom fields background white instead of current gray. That will make all labels look better. 

![2021-09-09 09 05 08](https://user-images.githubusercontent.com/51817359/132783325-91bd43b8-8fa5-4f4b-bebc-c9fbfac8152d.jpg)
![2021-09-09 19 15 36](https://user-images.githubusercontent.com/51817359/132783413-85aa2198-ae9e-4314-9d42-42f44c1e8707.jpg)

**Comment by colourfreak** [comment]
The list of all input fields is here:
https://github.com/AlphaWallet/alpha-wallet-android/issues/1486

But you can make a new style in xml. @mpaschenko

**Comment by JamesSmartCell** [comment]
I added the ghosted text there as a hint for the user because it's confusing which URL to add where. Is there a material way to provide an example of what the input is supposed to be? Like the (?) question mark in a circle? I don't know how out of date that design principle is ...

**Comment by mpaschenko** [comment]
@colourfreak should I also implement focused blue state?
@JamesSmartCell think I have to make all the things by the code, instead of using the **com.android.support:design** as the latest version is targeted to AndroidX which we don't support yet

**Comment by JamesSmartCell** [comment]
> @colourfreak should I also implement focused blue state? @JamesSmartCell think I have to make all the things by the code, instead of using the **com.android.support:design** as the latest version is targeted to AndroidX which we don't support yet

Ok, use whichever means you have to to get it as close to the spec as possible.

**Comment by JamesSmartCell** [comment]
@justindg I think this has already been mentioned in the UI umbrella issue
