### ISSUE TITLE
Add 3 items to Browser's menu

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2006]
Add three items to the menu:

1. My Bookmarks
2. History
3. Set as Home Page

if you set a new Home Page, show a navigation bar with a Home icon.
<img width="756" alt="Screenshot 2021-09-09 at 19 44 43" src="https://user-images.githubusercontent.com/51817359/132785457-fb9dc6ae-4e1d-413c-96f4-e3b769d58f95.png">

**Zeplin:**
https://zpl.io/ad6wyr7

**Comment by JamesSmartCell** [comment]
@colourfreak how about also a 'copy wallet' item? Often I need to copy my address into a field for a dapp etc. It would save a little bit of hunting around.

**Comment by mpaschenko** [comment]
@colourfreak on android we already have My Dapps / Add to My DApps, it works like bookmarks, should I rename these menu items?
and History menu item is already there as well.

**Comment by hboon** [comment]
@mpaschenko Tomek might still be travelling. But just so you aren't blocked, you can keep it as "Dapps" instead of changing to "Bookmarks" for now. The reason why they are referred to as "Bookmarks" on iOS is because we had to rename it to go through iOS App store review.

**Comment by mpaschenko** [comment]
@JamesSmartCell we can close it as it's merged already
