### ISSUE TITLE
Fix Token card layout boundaries

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2008]
![Screenshot_20210910-182235_AlphaWallet](https://user-images.githubusercontent.com/12689544/132823913-10d4d0e5-2192-46c9-aa1f-13f919df21ba.jpg)

The layout boundaries for the token name and the value need to be joined.

**Comment by mpaschenko** [comment]
<img width="741" alt="Screenshot 2021-09-10 at 12 23 15 PM" src="https://user-images.githubusercontent.com/2472117/132832097-d2881c26-e13a-423c-b1af-bf85da6fda85.png">

As I see, there are some changes after your merge, which reverted mines. That is what @colourfreak wrote about names
> Ideally, I would like to cut the names of tokens and display only what is in the bracket. So **BNB** should stay in this example. 
>

**Comment by JamesSmartCell** [comment]
Yes, we agreed to change the name display.

Now that there's potential collision the layout needs to be changed so the elements don't overlap for a long name.

**Comment by JamesSmartCell** [comment]
@mpaschenko linked issue: https://github.com/AlphaWallet/alpha-wallet-android/issues/2000

**Comment by JamesSmartCell** [comment]
@mpaschenko confirmed fixed
