### ISSUE TITLE
Grouping tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2013]
I would like to open a discussion about grouping tokens inside AlphaWallet. Ideally, we would like to have the same groups for Android and iOS. So the right coordination is required. 

**My suggestions:**
1. Assets (ERC20 tokens)
2. DEFI (all tokens related to DEFI, such as savings, liquidity pools, debt obligation, loans)
3. NFTs and Collectibles
4. Utilities

Users won't be able to manually move tokens from one group to another. 
Calling all of you guys to participate in the discussion. 

@hboon @JamesSmartCell @mpaschenko @AW-STJ @zhangzhongnan928 I can't call Vlad in this repo.

**Comment by hboon** [comment]
>  I can't call Vlad in this repo.

@vladyslav-iosdev

**Comment by hieronymus4826** [comment]
Is there a way to group these by reading a property in their smart contract? As far as I understand token contracts, function is interpreted at the application level. If there isn't are we gouping them manually?

**Comment by colourfreak** [comment]
> Is there a way to group these by reading a property in their smart contract? As far as I understand token contracts, function is interpreted at the application level. If there isn't are we grouping them manually?

I am trying to scrap this database https://github.com/AlphaWallet/alpha-wallet-ios/issues/2629#issuecomment-917837196
So if we decide to group tokens, I need to know the possible group names. This is the reason behind this task. And alignment between platforms.

**Comment by hboon** [comment]
I think your list looks reasonable. Shall we add a catch-all like “Others”?

**Comment by AW-STJ** [comment]
> 4. Utilities

Are there some examples of such tokens. And would a 'ticket' token be under collectable or utility?

**Comment by JamesSmartCell** [comment]
Also Attestations, later, when we start supporting off-chain assets.

**Comment by zhangzhongnan928** [comment]
> I would like to open a discussion about grouping tokens inside AlphaWallet. Ideally, we would like to have the same groups for Android and iOS. So the right coordination is required.
> 
> **My suggestions:**
> 
> 1. Assets (ERC20 tokens)
> 2. DEFI (all tokens related to DEFI, such as savings, liquidity pools, debt obligation, loans)
> 3. NFTs and Collectibles
> 4. Utilities
> 
> Users won't be able to manually move tokens from one group to another.
> Calling all of you guys to participate in the discussion.
> 
> @hboon @JamesSmartCell @mpaschenko @AW-STJ @zhangzhongnan928 I can't call Vlad in this repo.

What jumped into my mind is:
**Advanced search, filleter VS Group tab**

They provide similar functions, 
but one key difference is "Advanced search, filleter" doesn't change the display layout,  
Group tab can have different display layouts for each group. And Group tab can serve as a promotion page.


So we should utilize both:
**"Advanced search, filter" is for users to quickly categorize or find the right token he needs**
Example filter like:  
- Assets: include everything, all kinds of tradable rights.
- Currencies:  tradable rights accepted everywhere, blockchain native tokens like Eth and different Fiat Tokens like USDT/USDC/DAI
- Identity: all kinds of non-tradable rights

**"Group tab" is for displaying certain tokens in different layouts.** 
Example:
- Tokens with rich visualization.
- Tokens can benefit from a specified layout
- Tokens we want to highlight, a token promotion page.

**Comment by JamesSmartCell** [comment]
@zhangzhongnan928 post covered most bases - other than this my concern is how to fold the NFT display. If we operate a view like OpenSea does, showing all NFTs some wallets are going to be really big. 

Would 3 levels of folding cover this?

1. Show all NFT (like OpenSea). Will be huge for some of the 7000+ NFT wallets.
2. Collapse into collections. For wallets with ERC1155 tokens this will shrink the display quite significantly.
3. Collapse into contracts. The current implementation.

**Comment by colourfreak** [comment]
There is one more design that not sure you had a chance to look at @zhangzhongnan928 
![nft-wallet_concept](https://user-images.githubusercontent.com/51817359/133192954-4e44d356-e2fb-44c4-a364-186afdd187e8.jpg)

**Comment by zhangzhongnan928** [comment]
> There is one more design that not sure you had a chance to look at @zhangzhongnan928
> ![nft-wallet_concept](https://user-images.githubusercontent.com/51817359/133192954-4e44d356-e2fb-44c4-a364-186afdd187e8.jpg)

I saw this before, it is almost the same as rainbow(R), but I'm not a fan of it. Reasons:
1. I have a lot of tokens, it will be very long, unlimited scrolling down. If we fold it, to display only 4, then I need to decide which 4 to display.
2. need extra steps to "switch" between Assets/NFT/Savings/Governance, eg, to go to NFT with 2 networks(Ethereum and polygon) enabled, I have to scroll down several times then click see all NFT. if I need to go to Governance I will need to scroll down many times.
3. with multiple network enabled, there will be groups in groups
4. if Assets, Savings, and Governance have the same layout/display/summary. What is the point to list them in different groups. ( this part is worse than R, at least they use different layouts for different groups) 
P.S. R doesn't even have a search function, which makes it not usable at all. 

Key Question: besides looking better, is this design helping users to get things down easier? if not, it doesn't worth the effort of changing it.
1. Does it provide a better "summary page" for users to quickly see some summary(like different summary based on token type)?
2. Does it provide an easier way for users to find the right token they want to use?
3. Does it provide an easier way for users to filter out the tokens they don't want to see?
4. What else do users want to do? and this design can help?

**Comment by colourfreak** [comment]
@zhangzhongnan928 Victor, I like the idea of Advanced Search, Filters, and Groups. But let's hold on for a while with this. 

The current issue we are working on is how to group tokens within the current long list of tokens we have now. Nothing more. So I am not proposing folding tokens. But simply grouping them. It will be one long list as well, but with separators. For now.

<img width="662" alt="Screenshot 2021-09-15 at 09 30 10" src="https://user-images.githubusercontent.com/51817359/133463427-e5cffaa3-c22c-4cbf-8c46-fc3c1da4ae4c.png">

This is still the Samoa update that I would like to finish it before we jump into NFT wallet changes. So there won't be a big change, except you will have separators for each group (and you will be able to use segmented controls to jump into those groups).

So when the time comes (very soon, after I finish the AutographNFT SEO part and devs will catch up with the Samoa update), I will produce multiple design proposals. And we can discuss the design. And I will make a design with your proposed changes and see how it will work. Sounds good?

**About your idea:**
I like it. What i would suggest is to move the **Filters** and **Advanced search** to "Manage Tokens" screen which is now called "Add/Hide Tokens". So basically it will be a screen, where you can customize a wallet tab that meets your needs. But I would not clutter a wallet tab. 

<img width="712" alt="Screenshot 2021-09-15 at 09 33 53" src="https://user-images.githubusercontent.com/51817359/133463906-0a1178af-b83d-4cab-bc81-c4c803d3b7ed.png">

**Comment by colourfreak** [comment]
https://user-images.githubusercontent.com/51817359/133470943-28eb9462-65a7-4d06-84ff-8bf1556d47d7.mp4

**Comment by colourfreak** [comment]
No longer up to date.
