### ISSUE TITLE
Missing many tokens on Polygon

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2019]
3.4 (169)

I imported a wallet and I see missing many tokens on the Polygon network. I should have total 34 tokens on Polygon.
Watch: t0x80cc263cb3fA1bE2AeC748b3811261c1E2a1ba8d

https://polygonscan.com/address/0x80cc263cb3fA1bE2AeC748b3811261c1E2a1ba8d

<img width="331" alt="Screenshot 2021-09-14 at 08 56 28" src="https://user-images.githubusercontent.com/51817359/133281859-9d0a5163-5a72-42b7-a487-f31ad9ecfc9e.png">
<img width="400" alt="Screenshot 2021-09-14 at 08 56 34" src="https://user-images.githubusercontent.com/51817359/133281871-e297fda7-822b-4e87-8ede-d41fc1786efb.png">
<img width="699" alt="Screenshot 2021-09-14 at 08 57 02" src="https://user-images.githubusercontent.com/51817359/133281874-4322c7c3-f0b8-4da9-aef2-1b4c35d2386c.png">

**Comment by JamesSmartCell** [comment]
Hi @colourfreak this looks like an issue in the Token auto-discovery code that I broke while diagnosing the De-Fi whale freeze issue rather than the token list display filtering. I did a small refactor on this process which should have fixed it.

**Comment by colourfreak** [comment]
The real value of my wallet is about 11k USD vs 3800 USD displayed in AlphaWallet here![Screenshot_20210914-190659_AlphaWallet.jpg](https://user-images.githubusercontent.com/51817359/133353866-1403c56a-fb5e-420d-bc51-3649fb7f707d.jpg)
