### ISSUE TITLE
Enlarge the font for 24H Price change

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2021]
3.4 (169)

Make it 15pt.

![2021-09-14 08 17 50](https://user-images.githubusercontent.com/51817359/133289312-54b3535a-39bf-4154-9f7f-78bf3a7b588b.jpg)

https://zpl.io/addP0yR

**Comment by JamesSmartCell** [comment]
Also change the green value from change in value of 1 unit of the token price to the change in value of the whole balance eg:

If the Eth balance is 100Eth, then the green value should be (current value of 100 eth) - (value of 100 eth 24 hours ago).

**Comment by JamesSmartCell** [comment]
Complete
