### ISSUE TITLE
Vertical alignment of text in Wallet tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2033]
The currency symbol ("USD") and token type ("ERC 20") is vertically off. Annotated with 2 red lines to highlight:

![Screenshot_20210920_171635_io stormbird wallet copy](https://user-images.githubusercontent.com/56189/133982190-3ac18633-4b69-4623-8b75-b1217c389ab7.png)

**Comment by JamesSmartCell** [comment]
Oh my god! I never noticed this before

**Comment by JamesSmartCell** [comment]
The fix is pretty much immaterial because Samoa layout is a fresh start.

**Comment by hboon** [comment]
Still there in the new build downloaded at 20210922 04:31 PM. But like you said Samoa will override this. Feel free to close it if that's the intention.

**Comment by hboon** [comment]
Still there with 3.40.1 RC3. The misalignment is also visit in the screen that appears after tapping a token in the Wallet tab.
