### ISSUE TITLE
Implement RoboElectric (or other framework)

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2042]
Check the RoboElectic testing harness: http://robolectric.org/

What we want to do is, via gradle tests, run a test script that adds a watch wallet (you can try 0xC067A53c91258ba513059919E03B81CF93f57Ac7 to start with) then visits each page in the settings screen.

Once it's set up a further issue will expand this to check some tokens and later import a private key and do sends.

The initial stage should just run the app and open the various pages. We can test the wallet name too, as you can get the title and check it has resolved the ENS name which should be jsbrown.eth

**Comment by JamesSmartCell** [comment]
- [ ] Import a wallet (just create a new wallet and store the seed phrase, or create a new wallet in MetaMask and export the raw key).
- [ ] Check the address of the wallet

Move some testnet balance onto this wallet (any testnet is find, Ropsten is easy to get, as is Mumbai and Goerli).

- [ ] create a new wallet
- [ ] get the address of the new wallet
- [ ] send balance from the first wallet to the second
- [ ] check balance was received

Redo the above but with Android 10 and Android 11 security set up (PIN is fine).

**Comment by AW-STJ** [comment]
Hey @seabornlee - did you get a chance to look at this issue?
