### ISSUE TITLE
Tap blockie on Wallet tab should show Change / Add Wallet screen that is currently (and still will be) available in Settings

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2050]
i.e. show this:

<img width='200' src='https://user-images.githubusercontent.com/56189/134886601-d94f4909-0758-4cd9-a9b7-0571bd93978f.jpg'>

Note that this screen (available from both Wallet and Settings) will look different with Samoa. But flow applies. Might be duplicate of #1769

**Comment by JamesSmartCell** [comment]
Top left blockie in wallet page -> add / change. @mpaschenko can you check if it's been done in the Samoa branch.

**Comment by mpaschenko** [comment]
yes, I added that, the only thing left from the mockups provided - is balance per wallet and total balance (on the wallets screen)

**Comment by JamesSmartCell** [comment]
Closing as now completed
