### ISSUE TITLE
Tweak where and how current wallet Ethereum address and ENS name is displayed in Settings tab

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2053]
Current:

<img width='200' src='https://user-images.githubusercontent.com/56189/135033563-9b35e700-91e0-4753-87ae-2255b8d7d1b7.jpg'>

How it should look like:

https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/60b6299ba3632008a42391c5

Notable change:

* It should be displayed in a different row
* The ENS name isn't displayed (it is available for this address)

**Comment by ChintanRathod** [comment]
@hboon 
Below screen is for the Settings/Add Custom RPC

![image](https://user-images.githubusercontent.com/4371780/135263162-85be43ee-1c86-4b55-aaf7-b8e8d9fd337c.png)

Where as current Android screen follows below settings from Zeplin. (Settings/Export JSON Keystore)

![image](https://user-images.githubusercontent.com/4371780/135263281-855ff3b2-113b-475b-8e2f-542cb323f171.png)

So change required for Android is 
- showing "wallet address" from "Show My Wallet Address" to "Change / Add wallet" section. 
- ENS name above "wallet address" when available
