### ISSUE TITLE
Display ENS name (if available) while setting up a watch wallet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2054]
Current:

<img width='200' src='https://user-images.githubusercontent.com/56189/135034631-ffdd7137-2b41-4347-b9ff-df144dde34ca.JPG'>

How it should be displayed (buzz Tomek if you need an Android variant)

https://zpl.io/aX1rqpX

**Comment by JamesSmartCell** [comment]
Are you using a build installed from PlayStore/APK or building from AndroidStudio?

The behaviour should be different - we allow the ActionSheet if using a debug build, for testing.

**Comment by hboon** [comment]
The RC APK build.

**Comment by JamesSmartCell** [comment]
OK then it's an issue that needs fixing.
