### ISSUE TITLE
Integrate with Oneinch

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2061]
Seems like we missed this.

Main file for iOS: https://github.com/AlphaWallet/alpha-wallet-ios/blob/master/AlphaWallet/Core/SwapToken/Oneinch/Oneinch.swift

Related iOS PRs for reference: https://github.com/AlphaWallet/alpha-wallet-ios/pulls?q=is%3Apr+is%3Aclosed+oneinch

#1803 might not be relevant anymore if it hasn't been implemented yet

Edit: modified the link to list of iOS PRs above.

**Comment by JamesSmartCell** [comment]
Is this providing a link to 1inch on each erc20 token?

**Comment by hboon** [comment]
Yes.

And to be exact ERC20 and the native ETH token. But like a few similar swap services they provide an endpoint to discover which tokens it works against (for Oneinch, this endpoint doesn't list ETH, so you'll have to include it yourself). Look for "/v3.0/1/tokens".

This is the whitelist of tokens to show the Oneinch "Swap" button for.
