### ISSUE TITLE
Scan WalletConnect QR codes (`wc:`) in cameras outside of AlphaWallet should open AlphaWallet and prompt for connection

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2106]
Tried with built-in scanner on my Huawei

**Comment by mpaschenko** [comment]
@hboon @JamesSmartCell can you attach some sample qr codes to test?

**Comment by JamesSmartCell** [comment]
This one should trigger a WalletConnect open:

![image](https://user-images.githubusercontent.com/12689544/137712403-0602fb48-d815-4120-bc05-f3e523a599ce.png)

(or just go to https://example.walletconnect.org/)

This one should trigger an EIP681 open:

![eip681](https://user-images.githubusercontent.com/12689544/137712813-8c98f28d-84c3-4f32-a252-b574efbf45bb.jpg)


These links start with ```wc:``` and ```ethereum:``` respectively. If you check the Manifest you can see I added the "wc" intent. This works if I call the wc: from a browser, but it should also work from scanning from the camera. Might have to register an intent for it to work with the camera.

**Comment by JamesSmartCell** [comment]
You can see it working if you open  https://example.walletconnect.org/ in a phone browser app like Brave etc, then click 'mobile' instead of QR code and it should give you AlphaWallet as an option to open it.

**Comment by hboon** [comment]
@JamesSmartCell, @seabornlee or @justindg would you help re-assign among yourself and close this?

**Comment by hboon** [comment]
(if it's possible)

**Comment by justindg** [comment]
Looking into this

**Comment by justindg** [comment]
I failed to update this thread, but this is not possible at the moment due to the custom URI provided by WalletConnect.
