### ISSUE TITLE
Tapping on Collectibles in Wallet tab shifts the entire "sub-tabs" left

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2116]
Doesn't happen when "Currencies" is tapped

I know the design is going to change, but I suppose the component might still be affected.

All|Collectibles|Overlaid
-|-|-
<img width='200' src='https://user-images.githubusercontent.com/56189/137240853-b9c50d27-69f6-42c2-8261-855819d3cddc.jpg'>| <img width='200' src='https://user-images.githubusercontent.com/56189/137240857-6d33141d-2238-4966-882a-37dbae14328c.jpg'>| <img width='200' src='https://user-images.githubusercontent.com/56189/137241091-0bd23787-3ba7-411f-b696-cf1f44500a7a.png'>

v3.40.2 (171)

**Comment by JamesSmartCell** [comment]
Hi @mpaschenko can you check this in Samoa and fix if required.

**Comment by mpaschenko** [comment]
@hboon @JamesSmartCell it's a stock TabLayout control behavior, the only solution I can suggest is to make all the columns the same size, to avoid shifts, like on the image attached
![viber_image_2021-11-10_15-03-07-216](https://user-images.githubusercontent.com/2472117/141118092-66ed75f6-e8fb-42cf-ba8e-b7708d2edebf.jpg)

**Comment by hboon** [comment]
@mpaschenko not a showstopper for me. Just found it strange. If it’s difficult to fix and is standard behaviour, you don’t have to unless James thinks otherwise.

**Comment by JamesSmartCell** [comment]
It's standard behaviour, and yes I'd agree with @mpaschenko that you can make the tabs all the same width. Let's go with that, and see if there are any issues with it.

**Comment by JamesSmartCell** [comment]
Solved in Samoa
