### ISSUE TITLE
Add an app-enforced timeout for WalletConnect while waiting to make new connections

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2127]
One of the problems with WalletConnect is frequently encountered when making a new connection, the user might be stuck waiting after scanning a QR code. Empirically, successful connections only take 2-3 seconds. Other than fixing the problem at the root, we can improve the user experience by setting a 10 seconds timeout. Upon timing out, inform the user to get a fresh QR code (not to rescan the same one). 

Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/3275#issuecomment-943343738 for UI design.

**Comment by JamesSmartCell** [comment]
Yeah that's a good idea. Currently android just asks them to re-scan, but not to refresh and get a new connection.
