### ISSUE TITLE
Migrate all the Log.(x) instructions to use Timber.(x)

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2138]
Haha, Google! "Use Timber, not Log". So funny, much humour.

Timber is Log, but automatically switches off for release builds, so all the if (BuildConfig.DEBUG) can be removed.

It should also shrink the APK size a fraction too.

**Comment by JamesSmartCell** [comment]
Also migrate all the ```System.out.println(...);``` and if ```(BuildConfig.DEBUG) e.printStackTrace();``` to use ```Timber.e(TAG, e.printMessage());``` as appropriate

**Comment by asif-finimble** [comment]
Task Update Feb 2, 
- Replaced all ```Log.x```, ```System.out.println()``` and ```If (BuildConfig.Debug) e.printStacktrace()``` to use ```Timber.x```.
