### ISSUE TITLE
App crashing when trying to add a token (from an address) on a different chain

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-android#2144]
Reported on Discord, but tested it myself and its the same for me.

Scenario: 

I copy a BSC chain token address in the "add/hide tokens" menu while Ethereum is the selected chain in the drop down. The wallet starts looking endlessly for the token address on Etherscan and eventually the app crashes. Easy to replicate.

**Comment by JamesSmartCell** [comment]
This is based on an old release, and has been fixed. When 3.40.2 is out later today can you check?
