### ISSUE TITLE
Show Wallet Connect as a row at the top of Wallet tab if there are sessions

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2153]
There was an older issue about this. Might have assets there. Otherwise buzz Tomek.

<img width="200" alt="Screenshot 2021-10-19 at 11 17 19 AM" src="https://user-images.githubusercontent.com/56189/137838193-5bdbe4e6-1ffe-46ef-b1b4-add8711511ee.png">

**Comment by hboon** [comment]
@seabornlee bump

**Comment by seabornlee** [comment]
Have this on my list of WalletConnect v2.

**Comment by hboon** [comment]
@JamesSmartCell, @seabornlee or @justindg would you help re-assign among yourself and close this?

**Comment by seabornlee** [comment]
This is done on WC2 branch. Will be merged after migration to WC Beta 100.

**Comment by seabornlee** [comment]
Close since it's done.
