### ISSUE TITLE
Transaction confirmation actionsheet in landscape mode should (almost?) fill the screen upon appearing

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2166]
<img width='200' src='https://user-images.githubusercontent.com/56189/138200735-d54d3275-5982-4c58-a88d-5d6bb0e34995.png'>

Rather than just showing a little bit and expecting the user to pull it up

**Comment by JamesSmartCell** [comment]
Linked to issue #2167
