### ISSUE TITLE
Spinner for resolving ENS text avatar/address overlaps briefly with avatar

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2169]
In the send screen

1. Type or paste ENS name which has an avatar text record configured
2. Little spinner appears
3. Wait

Observed
---
4. ENS avatar appear
5. Spinner still around, but doesn't look nice because it is overlapping the ENS avatar
6. Spinner disappears and address appears

Expected
---
Probably similar to observed, but reposition the spinner maybe?

<img width='200' src='https://user-images.githubusercontent.com/56189/138202357-db1c3df6-6e56-46e8-a8cf-c02f87ddcd41.png'>

**Comment by JamesSmartCell** [comment]
Thanks for spotting this.
