### ISSUE TITLE
Update the top Dapp icon in Active WalletConnect session screen

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2195]
Refer to: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3384#issue-1037359162

Ignore the "Switch Network" button for now (unless we know it's possible then feedback here)

**Comment by JamesSmartCell** [comment]
Ok understood it now, thanks

**Comment by hboon** [comment]
Update. Yes, switching chains for active sessions is possible: #2205
