### ISSUE TITLE
Allow users to import a wallet with 24 seed phrase

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2204]

**Comment by JamesSmartCell** [comment]
@colourfreak should we also allow users to create a seed phrase with 24 words? When users are entering the 24 word seed phrase, would we just allow them to keep entering the words in the import screen, or display some sort of dialog?

**Comment by hboon** [comment]
We can allow users to import, but for creation, can we keep the UI as simple as when it was only 12-word seeds phrases?

**Comment by JamesSmartCell** [comment]
> We can allow users to import, but for creation, can we keep the UI as simple as when it was only 12-word seeds phrases?

Yes, but I'm wondering if there should be a visual que that we now support 24 word phrases, if the user goes past 12 words. The current behaviour is to disable the import button unless there's 12 words. We can now disable the button unless there's 12 or 24 words, but user may not know we support 24 word phrases unless they try.

Maybe something like a counter that would trip to 11 words remaining if they go past 12 and add a 13th word?

**Comment by colourfreak** [comment]
When you enter 12 words it works the same way (changes to import button from suggestions).
When you keep writing another word  (13th), then it comes back to suggestions + the counter changes from .../12 to .../24

https://zpl.io/29pk04e
https://zpl.io/bP6zjqM
https://zpl.io/V1LK9ZX
https://zpl.io/VQ3jQW4

<img width="1672" alt="Screenshot 2021-11-18 at 12 19 33" src="https://user-images.githubusercontent.com/51817359/142406401-eb830d7e-f46f-4042-b28e-2eaffbd25646.png">

**Comment by hboon** [comment]
Yeah, let's do it.

**Comment by hboon** [comment]
- [ ] Also need to check for references to "12 words seed phrases" or similar in the app
- [ ] Also need to check if export functionality needs to be changed
* Let's just not allow user to create them at the moment

**Comment by JamesSmartCell** [comment]
Hi @seabornlee for this one, I believe WalletCore already supports 24 word keys, so supporting the crypto should be straightforward.

You'll have to re-do the limits in the importseedphrase code in line with the above spec.

**Comment by seabornlee** [comment]
Tasks: 

- [ ] should change from 12/12 to 13/24 and disable the import button
- [ ] should change from 13/24 to 12/12 and enable the import button
- [ ] should enable import button when achieve 24/24
- [ ] should import 24 words seed phrase successfully
- [ ] should be noticed that app support 24 words seed phrase
