### ISSUE TITLE
After back up my testnet wallet my erc20 token all disappeared 

### ISSUE THREAD

**Issue by andrewmckenzie123** [AlphaWallet/alpha-wallet-android#2206]
I am requesting help in getting back my missing testnet funds. I only deposit fund before backing up my wallet. After back up and confirm the account. My funds missing.
The funds showing on testnet explorer but not in the account. Very frastrating

**Comment by JamesSmartCell** [comment]
Hi @andrewmckenzie123 can you provide more details; can you say what is your address and which testnet you're using.

The wallet usually picks up all erc20 automatically on the main testnets (Kovan, Ropsten, Rinkeby, Goerli, Mumbai), but it struggles with some testnets like Avalanche Fuji as we haven't yet added token discovery heuristics for this chain.

The testnet tokens are still there, can you give us more details we'll help you find them again.

**Comment by andrewmckenzie123** [comment]
I got it resolved by email assistance. I rate your platform 5 star. Thanks for the readily support ..... keep adding more function to the platform like Venus XVS testnet, then it perfect

**Comment by andrewmckenzie123** [comment]
I got your response and it help 100% thanks but i need Venus XVS testnet wallet! Have any info on Venus XVS testnet?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
