### ISSUE TITLE
Improve the font under "Change / Add Wallet"

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2214]
https://zpl.io/VY7JKYk
https://zpl.io/2pqPx1y
<img width="821" alt="Screenshot 2021-11-09 at 08 19 57" src="https://user-images.githubusercontent.com/51817359/140879818-523f151f-473c-471c-850b-d88ca5e40936.png">

SourceSansPro Regular 12, Dove #727272

**Comment by colourfreak** [comment]
Still exists.

**Comment by colourfreak** [comment]
We need to apply the same to more Settings screen

- Change Language
- Change Currency
- Select Currency screen

![2021-12-14 14 35 53](https://user-images.githubusercontent.com/51817359/146011704-063327fe-3bcf-441d-b177-6c1aaa7385b1.jpg)
![2021-12-14 14 35 08](https://user-images.githubusercontent.com/51817359/146011686-b7be43e8-94b7-4154-be77-31e2a4400178.jpg)

**Comment by colourfreak** [comment]
It was marked as closed but I haven't seen this updated in the design. @seabornlee  Can you take a look, please?

**Comment by seabornlee** [comment]
@colourfreak Sure.
