### ISSUE TITLE
Move the search bar down, move Add/Hide Tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2230]
**Changes:**

- Replace "My Wallet Address" with the additional menu icon
- When revealed additional menu, show three options "Copy Address" "My Wallet Address" and "Add/Hide Tokens"
- Add search bar where "Add/Hide Tokens" was before

https://zpl.io/VqMqYol
https://zpl.io/aXOMol8

![Wallet_Menu](https://user-images.githubusercontent.com/51817359/142405323-96169a59-5f68-4553-bd68-67cdee31f7bf.jpg)
![Wallet](https://user-images.githubusercontent.com/51817359/142405326-cfb65bca-1b0a-4d36-8bb3-5a80d3c6c39d.jpg)

**Comment by JamesSmartCell** [comment]
This is now completed in the Samoa working branch.
