### ISSUE TITLE
Replace Select button in assets with additional menu [ERC1155]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2231]
@JamesSmartCell 

A small change here. Where you have **Assets** tab, you can find the "Select" link in the top right corner 
<img width="750" alt="Screenshot 2021-11-18 at 13 08 02" src="https://user-images.githubusercontent.com/51817359/142412643-7aedbeef-a095-416a-8ac8-8db1326e225e.png">

So we need to change it to a native Android icon for an additional menu. When you reveal this menu, you will see two options
a) Send Multiple Tokens (works the same as the current Select icon)
b) Switch to Grid View

https://zpl.io/bW3ogpk
https://zpl.io/awlRWQD
https://zpl.io/b6Wzjkm

**List**
![ERC-1155-Project-Assets-List](https://user-images.githubusercontent.com/51817359/142413203-e7a3c14a-1efc-41ac-b8e5-2eae5f365ec0.jpg)

**Menu**
![ERC-1155-Project-Assets-Menu](https://user-images.githubusercontent.com/51817359/142413206-63573279-cc46-4616-a2ec-f5073518c1ca.jpg)

**Grid**
![ERC-1155-Project-Assets-Grid](https://user-images.githubusercontent.com/51817359/142413197-c02c9393-ce9b-4f73-8dc8-c7f545336347.jpg)

**Comment by JamesSmartCell** [comment]
Hi @justindg can you resolve this one while you have the relevant code under construction?

**Comment by justindg** [comment]
This should be solved in #2271
