### ISSUE TITLE
Add Search box under the segmented control inside Assets tab [ERC1155]

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2232]
It should work natively. When you tap on it, the search box appears at the very top.
https://zpl.io/bW3ogpk
https://zpl.io/b6Wzjkm
https://zpl.io/293QEpe

![ERC-1155-Project-Assets-Grid](https://user-images.githubusercontent.com/51817359/142417098-a93977f3-7bd4-4084-8609-1f936bc602c6.jpg)

![ERC-1155-Project-Assets-List](https://user-images.githubusercontent.com/51817359/142417100-4f065cb1-5e18-4351-b990-69f929b7c949.jpg)

![ERC-1155-Project-Assets-Search-Results](https://user-images.githubusercontent.com/51817359/142417678-7556ce4b-aecd-47be-86d2-02c6b0d6eb35.jpg)

**Comment by JamesSmartCell** [comment]
@justindg can you add this (After Samoa goes in). I assume the search bar is within a view holder on the TokensAdapter, so it should drop into the 1155/721 view.

This should go in straight after the work to merge the 721 code into 1155.

**Comment by justindg** [comment]
Solved in #2271
