### ISSUE TITLE
Add wallet button content description shows "Add Token", it could be "Add Wallet"

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2236]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/735708/142716224-87c6e3c7-291a-4596-9e90-4e6960e47222.png">

<img width="286" alt="image" src="https://user-images.githubusercontent.com/735708/142716214-f8765c05-310b-4560-be19-928ec2e47b0f.png">

**Comment by JamesSmartCell** [comment]
Hi @seabornlee I see; thanks for the heads up, the 'add token' is indeed incorrect when viewing the full text.

**Comment by vfbiby** [comment]
let me try to fix this issue.
