### ISSUE TITLE
Wallet address not all in upper case

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2237]
It show all upper case in most pages.
<img width="265" alt="image" src="https://user-images.githubusercontent.com/735708/142721696-1451005d-7e89-4175-940f-34957c78e594.png">
<img width="264" alt="image" src="https://user-images.githubusercontent.com/735708/142721699-87e4b3ec-38aa-433e-b76b-c28341f75f6d.png">

But in lower case on the "Change / Add Wallet" page.
<img width="269" alt="image" src="https://user-images.githubusercontent.com/735708/142721706-f3400fe1-ba99-4bd9-942f-7f0d908d4b78.png">

**Comment by JamesSmartCell** [comment]
This is an ethereum standard - it should be consistent as you say - it should show the cheksummed wallet address on the wallet screen. Just wrap the text with ```Keys.toChecksumAddress( ... )```

**Comment by seabornlee** [comment]
Exactly, it's not just all uppercased.
