### ISSUE TITLE
Settings -> Change / Add Wallet page not show correct balance

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2241]
![image](https://user-images.githubusercontent.com/735708/142760567-4f0a299c-46dd-4da8-9807-90d87dd13fd0.png)
![image](https://user-images.githubusercontent.com/735708/142760575-676c43f2-a250-49fe-b09c-23ddb01f2801.png)

**Comment by JamesSmartCell** [comment]
This is expected behaviour - the wallet page shows only main net balance.

**Comment by seabornlee** [comment]
Got it. Thanks for sharing this!
