### ISSUE TITLE
What's new dialog upon 1st launch after app is update

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2247]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/3462

Zeplin:
https://zpl.io/VQ3ZgDx

![Wallet-News](https://user-images.githubusercontent.com/51817359/143022128-c5dc461f-e6ae-442e-989b-c22b2aabde30.jpg)

**Comment by JamesSmartCell** [comment]
Nice, where do we source the data? It can be pulled from the github release point. Or, if the SDK permits from the corresponding Play Store release.

**Comment by hboon** [comment]
This was started on iOS to attempt to surface specific features/experiments as we go along. So it's not intended to duplicate the release notes.

So no rush for Android but you can use it for release notes summary if you like, at your discretion :)

**Comment by JamesSmartCell** [comment]
I will try fetching the notes from the Github release, fetching the number is striaghtforward; fetching the text may also be possible.

**Comment by mpaschenko** [comment]
@JamesSmartCell all the releases could be fetched through 
`curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/alphawallet/alpha-wallet-android/releases`
would you like me to use it?

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell all the releases could be fetched through `curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/alphawallet/alpha-wallet-android/releases` would you like me to use it?

This looks ideal. Can you make it so? Initially let's take the update text from the notes.
