### ISSUE TITLE
Text margins in the wallet pager

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2253]
The words can sometimes go onto two lines; maybe make it singleline and expand the margins slightly?

This is in the 1768_wallet_tab branch

![Screenshot_1638180116](https://user-images.githubusercontent.com/12689544/143847787-092f1812-a1a6-4804-97f5-3be5e7ba4df7.png)

**Comment by colourfreak** [comment]
Make it swipeable https://zpl.io/aXOMol8

<img width="605" alt="Screenshot 2021-11-30 at 09 45 31" src="https://user-images.githubusercontent.com/51817359/144014371-aa83ef99-0696-43a7-93d5-4f1730cf5fdb.png">

**Comment by JamesSmartCell** [comment]
> Make it swipeable https://zpl.io/aXOMol8
> 
> <img alt="Screenshot 2021-11-30 at 09 45 31" width="605" src="https://user-images.githubusercontent.com/51817359/144014371-aa83ef99-0696-43a7-93d5-4f1730cf5fdb.png">

This makes it a lot easier - this style is supported natively on Android, you can just remove the custom tab code in WalletFragment

**Comment by JamesSmartCell** [comment]
Fixed by removing a single line
