### ISSUE TITLE
Implement Price Alerts

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2257]
See https://app.zeplin.io/project/5d088205bff2d15de6a4397b/dashboard?tag=Samoa

<img width="758" alt="image" src="https://user-images.githubusercontent.com/12689544/144508366-009bf643-691a-4559-8de0-9e72973a9946.png">

Add the views for creating price alerts (using InputAmount widget), and swipe out/delete.

**Comment by mpaschenko** [comment]
@colourfreak could you please add me to this zeplin project

**Comment by hboon** [comment]
@mpaschenko you should have access with your gmail account.

**Comment by mpaschenko** [comment]
@hboon yes, it's ok now, had some issues with login, thanks

**Comment by JamesSmartCell** [comment]
@mpaschenko I have done the Samoa merge, so you'll need to branch from Samoa_Update.

**Comment by mpaschenko** [comment]
@JamesSmartCell yes, I'm on samoa_update branch

**Comment by seabornlee** [comment]
@colourfreak Hi Tomek, what do you wish me to do by assigning me on this issue?

**Comment by seabornlee** [comment]
ACs:
- [ ] Add new alert
- [ ] Show alerts list
- [ ] Toggle alert
- [ ] Delete alert
- [ ] Above 
- [ ] Below
- [ ] Different currencies

**Comment by colourfreak** [comment]
> @colourfreak Hi Tomek, what do you wish me to do by assigning me on this issue?

I am trying to assign the old Michael test to you or Justin. But please follow Boon and James' recommendations. I just wanted to make sure that are keep the ball rolling ;)

**Comment by seabornlee** [comment]
Got it, I am working on testing and fixing now.

**Comment by seabornlee** [comment]
![image](https://user-images.githubusercontent.com/735708/149178230-98d6e606-3ed8-4dae-9190-3a1baf764b8e.png)

I am not sure the price format `US$17,703.30` fits all currencies.

![image](https://user-images.githubusercontent.com/735708/149177885-6eb90c51-a92d-46e3-94cf-bb103a2f569f.png)

For example, the last one, according to same rule, it will be `PKRRs 17,703.30`.
How about another way: `17,703.30 USD`?

**Comment by seabornlee** [comment]
![image](https://user-images.githubusercontent.com/735708/149179540-97d4fb6d-0817-43af-a27b-79a0ab75ad36.png)

In the list, how to distinguish USD and SGD. @colourfreak

**Comment by JamesSmartCell** [comment]
I don't think you need to worry about it - the user is probably aware which currency they have selected.

**Comment by seabornlee** [comment]
> 

Good point. User probably only choose one currency.
