### ISSUE TITLE
Close button does not escape from Search box

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2279]

**Comment by colourfreak** [comment]
![Screenshot_20211213-121905_AlphaWallet.jpg](https://user-images.githubusercontent.com/51817359/145803454-7903eb96-c069-48d4-af51-b803593c7502.jpg)

**Comment by colourfreak** [comment]
It prisons user in this screen, no way to escape

**Comment by JamesSmartCell** [comment]
Back button at top left. Yes, navigate back should also be coded to go back to the wallet.
