### ISSUE TITLE
The token symbol inside any ERC20 shows network icon - should be the same as in a wallet

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2280]

**Comment by colourfreak** [comment]
![Screenshot_20211213-122444_AlphaWallet.jpg](https://user-images.githubusercontent.com/51817359/145804355-9a08a4e5-c3de-4885-aa57-9c5a9aa2f7ee.jpg)

**Comment by JamesSmartCell** [comment]
Fixed in Samoa-Uprade branch.
