### ISSUE TITLE
Improve Segemented Controls and Token Groups

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2282]
This is corresponding to https://github.com/AlphaWallet/alpha-wallet-ios/issues/3546

Another issue related to the Wallet tab. We are very, very close to the end design I made while designing Samoa.
So based on Hu's recent work, we now have specified token groups.

- All (Assets, Defi, Governance but no Collectibles)
- Assets (ERC20)
- Collectibles (ERC721 and ERC1155),
- DeFi (all ctokens, atokens, ptokens, itokens, liquidity pools, etc...),
- Governance (DAO tokens like COMP, UNI, etc)

So we have to:
1. Update Scrollable Tabs (so they are horizontally scrollable) https://material.io/components/tabs
2. Add Token groups

**Zeplin:**
https://zpl.io/2ZRJvlE

**Prototype**
https://invis.io/6U125DXFWE2X

![Wallet-Long](https://user-images.githubusercontent.com/51817359/146032876-a7e79e6b-38a6-4e0d-84cb-fc772adaaec9.jpg)

**Comment by colourfreak** [comment]
Examples of scrollable tabshttps://user-images.githubusercontent.com/51817359/146033800-24e92cc5-684b-43e0-8bae-f553cc03ec90.mp4

**Comment by JamesSmartCell** [comment]
Do you know if there's a deterministic way to know if it's a DeFi or Governance? If not, we can create a common list of tokens that fall into these categories.

**Comment by colourfreak** [comment]
> Do you know if there's a deterministic way to know if it's a DeFi or Governance? If not, we can create a common list of tokens that fall into these categories.

I believed this was done while we are working on token-scrapper.

<img width="867" alt="Screenshot 2021-12-15 at 08 11 58" src="https://user-images.githubusercontent.com/51817359/146140276-69214de9-979a-44b2-ac15-6412358109eb.png">

**Comment by JamesSmartCell** [comment]
Ok perfect, thanks

**Comment by hboon** [comment]
@JamesSmartCell "group" is now populated in the `tokens` repo. If a token is not classified, consider it as as "Assets".

**Comment by colourfreak** [comment]
Well done!
