### ISSUE TITLE
Display token network's symbol of each token in the wallet tab (and other places where the token icon is displayed)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2294]
Refer to: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3542

As of writing, the `master` branch of iconassets (https://github.com/AlphaWallet/iconassets/tree/master) still contains the chain overlay.

A fork of the token icons without the preprocessed overlay icons in https://github.com/AlphaWallet/iconassets/tree/with-chain-overlay-removed has been created, which no longer have the chain overlay.

So best to modify the app to use `with-chain-overlay-removed` for now, implementing the overlay in-app.

The native tokens on each chain do not show the chain overlay.

Once both iOS and Android app implements this PR and have rolled out sufficiently, we can update iconassets repo's master branch with with-chain-overlay-removed and switch both apps back to accessing master.

**Comment by JamesSmartCell** [comment]
@hboon I have already implemented an overlay for the chain icon which overlays pixel perfect exactly on top using Tomek's standard placement. Would you like the % ratios from my implementation? If so you can look here: https://github.com/AlphaWallet/alpha-wallet-android/blob/master/app/src/main/res/layout/item_token_icon.xml

**Comment by hboon** [comment]
@JamesSmartCell wonderful! Do close this issue if you are ready (and use the branch suitable for you).

**Comment by JamesSmartCell** [comment]
@hboon If you can read Android's Constraint layout the file is here:

https://github.com/AlphaWallet/alpha-wallet-android/blob/master/app/src/main/res/layout/item_token_icon.xml

The key value is the `status_chain_icon`, which is a circle with the following percentage borders:

Top: 59%
RHS: 45%
LHS: 0%
Bottom: 96.5%

These are relative to the main (token) icon, although in our case that has a layout frame like this:
Top: 4%
RHS: 96%
LHS: 4%
Bottom: 96%

This may or may not be useful, but I found that with these values the network icon matched perfectly.

**Comment by hboon** [comment]
@JamesSmartCell thanks! If you are done with this (or don't need this anymore) in the Android code base, can you help to close this issue?

**Comment by JamesSmartCell** [comment]
Issue is complete on Android
