### ISSUE TITLE
Confirm transaction dialog not fully displayed, causes e2e test failure

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2295]
On `Pixel 5` it works perfectly, and it looks like below on `Nexus S` and `Pixel XL`.
![image](https://user-images.githubusercontent.com/735708/148000039-d0940580-1225-45a3-ae50-7494d9757fd0.png)

**Comment by seabornlee** [comment]
I am trying to fix this.

**Comment by JamesSmartCell** [comment]
Nice catch - It might be related to the code that raises the screen above the Navigation Bottom Bar. I don't see this issue because I use gesture navigation on all my hardware test phones, so I should switch that off on some phones.
