### ISSUE TITLE
How to show 1inch in assets

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2298]
I have 1inch, it is listed in MetaMask, but not in Alpha Wallet.
Shall we support 1inch?

**Comment by hboon** [comment]
@seabornlee are you referring to the `1INCH` token, or are you referring to supporting 1inch as a DEX?

**Comment by seabornlee** [comment]
@hboon I mean show `1INCH` in Wallet tab.

**Comment by hboon** [comment]
Ah ok. It should show up. Actually all tokens should show up in the Wallet tab [^1] except for rare exceptions. You do have Ethereum mainnet enabled, right? Probably @JamesSmartCell will have an idea why it isn't working or where to look.

[^1]: After loading completes

**Comment by seabornlee** [comment]
Sorry, I just tested again, 1INCH is listed correctly on Android emulator. But not shown on my iPhone.

**Comment by hboon** [comment]
Haha. My bad then. Would you help create an issue at https://github.com/AlphaWallet/alpha-wallet-ios/issues/new ? If it's possible, paste the wallet address somewhere (privately or in the issue) and the contract address (just to be sure)

**Comment by seabornlee** [comment]
Sure.
