### ISSUE TITLE
should allow screenshot for both backup-warning screens

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#2304]
|  backup legacy wallet (json-imported) | backup wallet with seed phrase  |
|---|---|
|![Screenshot_20220106-115841_AlphaWallet](https://user-images.githubusercontent.com/548435/148312135-92021728-9296-463b-a607-5a28a9b6cb80.jpg)| ![2022-01-06-120022](https://user-images.githubusercontent.com/548435/148311734-06b0e72a-25ea-4c98-a5aa-8681adec3bd3.jpg)  |

If screenshot is allowed in left, it should be allowed in right too.

**Comment by hboon** [comment]
Sounds like a bug. Both should allow screenshots. Only the one screen displaying the seed phrase should block or warn against them.

**Comment by JamesSmartCell** [comment]
@seabornlee This is a non trivial change, but low priority.

Check the path from "back up this wallet" in settings, it goes via BackupFlowActivity.
If you click 'Show Seed Phrase' however it goes straight to BackupKeyActivity.

Re-wire it so 'Show seed phrase" goes via BackupFlowActivity, and remove the corresponding code from BackupKeyActivity.

I notice there's code stubs left over from when we moved the "back up this wallet" code out of there (which you will see when you follow the path from 'Show seed phrase'), which need removing.

We originally did this to aid support - so users could screenshot pages to send to support to show what they were doing. I don't think anyone has ever sent those screen shots.

**Comment by seabornlee** [comment]
Noticed.

**Comment by colourful-land** [comment]
@seabornlee use master 81b19129e2e65ae80b003e82b90cc862e189bea1 (now) or older in trying to reproduce.

**Comment by seabornlee** [comment]
@JamesSmartCell 
When show seed phrase, it only shows the seed phrase then close, won't ask user to write down and then verify seed phrase.
I don't know why we need to enter backup flow when user want to just view seed phrase?
How about extract a ScammerWarningActivity out of BackupKeyActivity, then only prohibit screenshot when user enter BackupKeyActivity.

**Comment by seabornlee** [comment]
![image](https://user-images.githubusercontent.com/735708/148564706-d00e85a2-7b84-4739-b9a9-ba8d58c0ed6d.png)
I realized that, when pause and back, the seed phrase disappeared, I am not sure that is a feature or a bug?

**Comment by JamesSmartCell** [comment]
> ![image](https://user-images.githubusercontent.com/735708/148564706-d00e85a2-7b84-4739-b9a9-ba8d58c0ed6d.png) I realized that, when pause and back, the seed phrase disappeared, I am not sure that is a feature or a bug?

It should disappear. Any screen interruption when showing the seed phrase - switch off, page out etc, it should return back to the previous page.

**Comment by seabornlee** [comment]
Yes, according to the code it should return back to the previous page. But for this page, it doesn't go back to previous one, but just hide the seed phrase.

**Comment by JamesSmartCell** [comment]
> Yes, according to the code it should return back to the previous page. But for this page, it doesn't go back to previous one, but just hide the seed phrase.

That behaviour is also ok. Just as long as it removed the seed phrase. Ideally it should revert back to the settings page though, or at least the 'scammer' page.

**Comment by seabornlee** [comment]
Ok, I will it revert back to previous page.
