### ISSUE TITLE
Travis CI is crowded, consider using GitHub actions for Android

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2308]
![image](https://user-images.githubusercontent.com/735708/148340526-602d7ee5-7ca7-4085-8c85-9e44dbb0f3fb.png)

@hboon @JamesSmartCell 
Both iOS and Android build takes long time.
iOS project took 55 minutes for the last build.
Android project took 22 minutes.

As the team growing, CI server could be more and more crowded, so that it won't give quick feedback.
Consider migrate to `GitHub Actions` for Android side, already tested it on branch, the syntax is more intuitive and run emulator test is more like native feature.

**Comment by hboon** [comment]
@seabornlee if James doesn't mind, I don't :) Doesn't have to be the same for iOS and Android anyway. iOS is more picky with CI because it requires macOS on the server.

**Comment by colourful-land** [comment]
@hboon is the αW lead to decide. I recommend @abcfy2 to do this so as to avoid diverting @seabornlee 's attention on coding.

**Comment by JamesSmartCell** [comment]
Yep let's do it - I have no preference, if you can find a better service please do it. With @seabornlee's test suite coming on line, this will be more important.

Only thing, we need to set the Android environment to use Java 11, as Web3j 4.8.7+ only builds with Java 11.

**Comment by seabornlee** [comment]
> @seabornlee if James doesn't mind, I don't :) Doesn't have to be the same for iOS and Android anyway. iOS is more picky with CI because it requires macOS on the server.

That is great, thanks!

**Comment by seabornlee** [comment]
> @hboon is the αW lead to decide. I recommend @abcfy2 to do this so as to avoid diverting @seabornlee 's attention on coding.

Got that, I almost get it done. Will ask help from @abcfy2 if needed.

**Comment by seabornlee** [comment]
> h

Awesome! Noticed.

**Comment by seabornlee** [comment]
> Yep let's do it - I have no preference, if you can find a better service please do it. With @seabornlee's test suite coming on line, this will be more important.
> 
> Only thing, we need to set the Android environment to use Java 11, as Web3j 4.8.7+ only builds with Java 11.

Awesome! Noticed.

**Comment by hboon** [comment]
> As the team growing, CI server could be more and more crowded, so that it won't give quick feedback.
> Consider migrate to GitHub Actions for Android side, already tested it on branch, the syntax is more intuitive and run emulator test is more like native feature.

We have switch to running Travis builds concurrently. Let's open a separate issue for switching to GitHub actions if that's still useful.
