### ISSUE TITLE
Add option to rename wallet straight from the dotted menu in the top right

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2312]
https://zpl.io/VqMqYol
<img width="884" alt="Screenshot 2022-01-11 at 14 07 54" src="https://user-images.githubusercontent.com/51817359/148948228-82579a36-4877-49f9-b728-024f7f5682e6.png">

**Comment by seabornlee** [comment]
@JamesSmartCell I would like to pick this one.

**Comment by seabornlee** [comment]
@colourfreak I noticed that when rename wallet, the cursor is not at the end of text, but at the beginning, should we move it to the end?

**Comment by colourfreak** [comment]
> @colourfreak I noticed that when rename wallet, the cursor is not at the end of text, but at the beginning, should we move it to the end automatically?

Can you post a screenshot?

**Comment by seabornlee** [comment]
![image](https://user-images.githubusercontent.com/735708/149077965-7a397a30-6494-4dcc-8aa6-c8f808fc1fbb.png)
The cursor is at the beginning, so user need move to the end to delete or append text.

**Comment by colourfreak** [comment]
Yeah, please do. 
There is a corresponding issue. 

https://github.com/AlphaWallet/alpha-wallet-android/issues/2005

**Comment by seabornlee** [comment]
Ok, I just do it with this issue. Will handle #2005 later.
