### ISSUE TITLE
UI/UX cleanup task

### ISSUE THREAD

**Issue by justindg** [AlphaWallet/alpha-wallet-android#2336]
Creating this ticket to document several (minor) UI issues worth fixing

Wallet 
- Search panel is swipeable ✅
- Labels/headers are swipeable ✅
- Search panel background color is a little off ✅

WalletConnect
- Missing empty / no active sessions state ✅

Import Wallet
- Wrong button text format (must not be all caps) ✅

ERC20 Detail
- Tab elements not centered - wrong tab mode ✅

Activity
- List dividers not very visible ✅

Send ERC20
- Incorrect InputAmount layout margins #1682  ✅
- Bug: Token icon does not revert back to token symbol ✅
- 
Other
- Standardize tab styles across app ✅
- Fix inconsistent button styles across app ✅

**Comment by colourfreak** [comment]
let me know if you need anything

**Comment by JamesSmartCell** [comment]
I will also add one:

- Convert all dialog popups into ActionSheet popups (eg see the 'change chain' ActionSheet popup in the DappBrowser, which you can trigger by switching to Mainnet chain, then going to 'Quickswap' dapp on the main page).

The main culprit for this is WalletConnectActivity at the moment.

There is now a standard ```MESSAGE``` mode for ActionSheetDialog with a dedicated constructor.
