### ISSUE TITLE
Remove Currency Selection from alerts

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2346]
Currently, on this screen:

https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/6048de5cea4b5497a861c92c

pressing the down caret on the currency flag launches the currency selection; the caret was left in from a stock layout, and should be removed.

**Comment by seabornlee** [comment]
@JamesSmartCell 
Sorry James, I didn't quite get what do you mean.
What is a stock layout?
Can you kindly give some snapshots?

**Comment by JamesSmartCell** [comment]
Sure,
![currency](https://user-images.githubusercontent.com/12689544/150884381-a4a2dff7-6f64-4c93-b93c-121f96c163e2.jpg)

If I click the down caret after the 'AUD' here, it takes me to the currency selection screen. 

The down caret should be removed as currency selection should only be set from the settings menu.

**Comment by seabornlee** [comment]
Here it just selects the currency for new price alert, do not effect the system settings.
Every time open this page, it is the same as system currency set from settings menu.

So I think it's useful.
@colourfreak What's your opinion?

**Comment by JamesSmartCell** [comment]
It is useful, but a bit confusing - I clicked on it wondering what it would do in this context, and was confused why it popped up currency. After thinking about it, the ability to do this makes sense but maybe not on that UI component where we're used to using it to flip between crypto and fiat.

**Comment by colourfreak** [comment]
> It is useful, but a bit confusing - I clicked on it wondering what it would do in this context, and was confused why it popped up currency. After thinking about it, the ability to do this makes sense but maybe not on that UI component where we're used to using it to flip between crypto and fiat.

I agree. @seabornlee remove the down caret and it should be fine.

**Comment by seabornlee** [comment]
Ok, got it.
