### ISSUE TITLE
Critical Display issue

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-android#2356]
A user with a fresh install sends USDT to his account on a HUAWEI p30pro, but the wallet displays the '.' separator instead of the ',' and reads 1.5$ instead of 1,500$. Works properly as a watch wallet on my end (as seen on the screenshot), so I cannot replicate it. Etherscan shows the correct 1500+.

![IMG_20220127_011548_692](https://user-images.githubusercontent.com/84448420/151263605-ddc5132b-206b-4797-847c-1a0a9a6ddd65.jpg)
![IMG_20220127_011608_244](https://user-images.githubusercontent.com/84448420/151263607-7ccf941b-ee25-4c9c-8834-f4b15d5ae89e.jpg)
![Screenshot_20220127-011510_AlphaWallet](https://user-images.githubusercontent.com/84448420/151263608-5001bac5-6c07-4d76-824b-7afbdb36d68a.jpg)

The 'insufficient USDT' message itself might also come from the fact he has no ETH to perform the transaction, but the display issue still stands.

**Comment by hieronymus4826** [comment]
Wallet address: 0xf0f096F2Da9F7768B6F968fba970124fe18a89eE

**Comment by JamesSmartCell** [comment]
Got it, yes this should be standardised

**Comment by hboon** [comment]
> Got it, yes this should be standardised

Created #2358. Sorry missed it earlier. Should be relevant.

**Comment by JamesSmartCell** [comment]
Closing this issue as solved by #2358
