### ISSUE TITLE
Use , as thousands separator and . as decimal separator no matter the locale

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2358]
Refer https://github.com/AlphaWallet/alpha-wallet-ios/issues/3531

**Comment by JamesSmartCell** [comment]
Yes this makes it much easier.

How about for displaying values? Still show like this: €1.000.000,88 or like this €1,000,000.88

**Comment by hboon** [comment]
Always the latter.

But careful with user (and Etherscan) input parsing though.

**Comment by JamesSmartCell** [comment]
Yep, I'm going to regex it to ensure there's no misunderstandings
