### ISSUE TITLE
Unstoppable Domains name resolution deprecation/changes

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-android#2364]
There are some changes to name resolution or deprecation.

This:

We wanted to share an update regarding changes we are making to our API integration (https://unstoppabledomains.com/api/v1/). We will be deprecating this API next year in favor of resolution services hosted by our partners: Alchemy and Polygon. We will share details of these resolution services soon.

and this:

Also, we are dropping support for ENS domain name resolution from our API on Dec 31st.
If you have been using our APIs for ENS name resolution, we recommend you integrate with ENS directly by following their guide:
https://docs.ens.domains/dapp-developer-guide/resolving-names

There's also a separate integration doc. Will send you the link privately.

Would you help to check them, summarize what we need to do? And if it's obvious it needs to be done and simple enough, would you make the change?

Follow https://docs.alchemy.com/alchemy/enhanced-apis/unstoppable-domains-apis tutorial for implementation of *Get records for owner addresses* and *Get records for a domain*.

**Comment by hboon** [comment]
@oa-s can you help assign to James when you are done writing up?

**Comment by JamesSmartCell** [comment]
> Will send you the link privately.

Can you resend this?

**Comment by asif-finimble** [comment]
@JamesSmartCell can you guide me on this as what needs to be done. I cant find usage of unstoppable domains api. ```AWEnsResolver``` is resolving using ens.

**Comment by hboon** [comment]
@JamesSmartCell bump

**Comment by JamesSmartCell** [comment]
@hboon @oa-s we don't use unstoppable domains on Android, could you explain what it is and how it's different from ENS?

We use 3 name resolution services - ENS directly from chain, DAS (.bit) and the .crypto domains.

From reading the docs my assumption is that 'unstoppable domains' is an aggregator that resolves all the various crypto domains. Is this correct?

**Comment by JamesSmartCell** [comment]
Do we need an API key to query the Alchemy domain aggregator API? If indeed it is that.

**Comment by hboon** [comment]
Hmm.. I always thought Android supported Unstoppable domains first. In that case lowering priority since it's not going to cause problems. What we do in iOS is to go with ENS first and then fallback to Unstoppable. Name resolution could be an attack surface so we should try to keep the 2 resolutions separate and if need be disable one (or all of them).

> Do we need an API key to query the Alchemy domain aggregator API? If indeed it is that.

Yes we do.

Build a list of questions and buzz @oa-s?

**Comment by hboon** [comment]
Refer to #2929
