### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2369]
There are several rules which we have to follow, for quicker implementation
I will try to describe it as much as I can.

Dove #727272 to Dusty #999999
Azure #007fed to Dodge #0c84ff
White #ffffff bg to Cod #141414
Green remains the same
Alabaster #fbfbfb to Venus #232323
Mercury #e9e9e9 to Venus #232323
Mine #2f2f2f to White #ffffff

Dark mode:
https://zpl.io/09kMrOm
![Activity-Send-Opened-ETH-Dark](https://user-images.githubusercontent.com/51817359/151574967-f78284fd-a737-4c22-8eee-f2dd2b3d090b.jpg)
![Backup-Write-Down](https://user-images.githubusercontent.com/51817359/151574975-006f9618-52bb-468b-aa84-5b821bc63861.jpg)
![ETH-Activity](https://user-images.githubusercontent.com/51817359/151574977-e2ed7b16-e229-4432-98a2-075827df499e.jpg)
![ETH-Alert](https://user-images.githubusercontent.com/51817359/151574979-70e89d5f-c59d-4c5a-975f-16142fad593f.jpg)
![ETH-Info](https://user-images.githubusercontent.com/51817359/151574984-daaf5e5a-1c52-4db3-a143-06e98d26dd02.jpg)
![Import-Keystore-Password-Empty-Dark](https://user-images.githubusercontent.com/51817359/151574987-7d7d0ab6-3826-45cb-8355-67e7c6e30a7a.jpg)
![My-Wallet-Address](https://user-images.githubusercontent.com/51817359/151574990-75c1ec47-fdd7-4cc1-9315-52e9e2d6d015.jpg)
![Send-ETH-Confirm-Dark](https://user-images.githubusercontent.com/51817359/151574993-76c82259-3cdb-4132-9dcd-4770730af86b.jpg)
![Send-ETH-Illustration-Dark](https://user-images.githubusercontent.com/51817359/151574997-8b188be4-7a73-4a17-8109-e636ce02366d.jpg)
![Send-ETH-Recipient-Entered](https://user-images.githubusercontent.com/51817359/151575001-a8d0f4df-0670-4496-8f62-5e01fcdaa34f.jpg)
![Settings-Backup-Warning-Dark](https://user-images.githubusercontent.com/51817359/151575002-4048e5ca-4796-4807-965b-c1bfa5f19b07.jpg)
![Settings-Dark](https://user-images.githubusercontent.com/51817359/151575005-581a9841-fa7b-4ca7-b098-8ac32f8bc311.jpg)
![Settings-Support](https://user-images.githubusercontent.com/51817359/151575008-5e8d0d2c-6e61-4e64-91aa-2b902ab373f7.jpg)
![Wallet-Dark](https://user-images.githubusercontent.com/51817359/151575009-8184c355-e04a-4811-9d6a-1f957d6d58c2.jpg)
![Wallet-Summary-Dark](https://user-images.githubusercontent.com/51817359/151575014-a6c38ee7-32d8-49b8-8647-76f7414f8161.jpg)
![Welcome-Dark](https://user-images.githubusercontent.com/51817359/151575018-30356848-ca59-45f7-9f9a-196b10a4082d.jpg)
![Activity-Dark](https://user-images.githubusercontent.com/51817359/151574961-de626093-4407-4e08-8b9e-a643d8cbea15.jpg)

**Comment by colourfreak** [comment]
I am going to post more comments, cues on Monday.

**Comment by colourfreak** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/3483#issuecomment-980008604
I think you can follow cues from iOS. Apart from outdated buttons, they are all the same.

**Comment by JamesSmartCell** [comment]
Nice!

@justindg We'll probably need to sift through and do a minor refactor for all instances where we've used colours directly instead of using theme colours (eg R.color.white instead of R.color.colorTheme for backgrounds etc), what do you think?

Once that's done it should be pretty easy to change this.

**Comment by colourfreak** [comment]
@justindg Let me know if you need more info from me. I tried to describe every thing in [here](AlphaWallet/alpha-wallet-ios#3483 (comment))

**Comment by justindg** [comment]
Hey @colourfreak , thank you for the detailed overview. I will be in touch once I start the work on this feature

**Comment by justindg** [comment]
Hi @colourfreak , what is the preferred color of these showcase/onboarding dialogs for dark mode?

https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e21865083d02d7acbe394d9

My initial thought was that `cod`  lacked a bit of contrast with the background, but I'm no expert in this field. Let me know your thoughts.

This is the current iteration (will fix the corner radius soon):
![image](https://user-images.githubusercontent.com/17334718/155457125-98939093-78bd-4faf-a23a-6ff4b59988e0.png)

**Comment by justindg** [comment]
@colourfreak Also what is the preferred color for bottom sheets? Below is the default theme:

![image](https://user-images.githubusercontent.com/17334718/155459106-dac97371-00d3-4588-b9bd-7626a7bd6aed.png)

**Comment by colourfreak** [comment]
> Hi @colourfreak , what is the preferred color of these showcase/onboarding dialogs for dark mode?
> 
> https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e21865083d02d7acbe394d9
> 
> My initial thought was that `cod` lacked a bit of contrast with the background, but I'm no expert in this field. Let me know your thoughts.
> 
> This is the current iteration (will fix the corner radius soon): ![image](https://user-images.githubusercontent.com/17334718/155457125-98939093-78bd-4faf-a23a-6ff4b59988e0.png)

Set the background color of a bubble to `Mine`

![Wallet-Intro](https://user-images.githubusercontent.com/51817359/155548448-6a5a0b09-3135-4ae5-a358-2bc03dee086a.jpg)

**Comment by colourfreak** [comment]
> @colourfreak Also what is the preferred color for bottom sheets? Below is the default theme:
> 
> ![image](https://user-images.githubusercontent.com/17334718/155459106-dac97371-00d3-4588-b9bd-7626a7bd6aed.png)

Mine
