### ISSUE TITLE
Uncaught SyntaxError: Identifier '__addressHex' has already been declared

### ISSUE THREAD

**Issue by aliveli186** [AlphaWallet/alpha-wallet-android#2370]
When I start my app from AlphaWallet browser for the first time  or reload it this error message appears in the console.

![image](https://user-images.githubusercontent.com/8914034/151665118-33f30570-3ab1-4c2c-b7ae-9a128aae1b8b.png)

**Comment by JamesSmartCell** [comment]
This is already fixed, but the fix has not yet been released.

**Comment by JamesSmartCell** [comment]
This issue should now be resolved with the new release on the playStore

**Comment by JamesSmartCell** [comment]
Closing as appears to be fixed.
