### ISSUE TITLE
Fix background color in the bounding box of textbox's label

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2376]
Can't be sure and not captured accurately in the photo, but seems like the rectangular area (annotated with the red rectangle) has a slightly different color than the rest of the screen. Help verify first?

![IMG_9515 copy](https://user-images.githubusercontent.com/56189/151735653-e316e662-5fc2-4a5b-a991-3de30286620b.JPG)

**Comment by justindg** [comment]
I've checked the code and can confirm there is a color difference - will fix asap. Impressive attention to detail!
