### ISSUE TITLE
Show shortened address format under textboxes if ENS entered

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2378]
Should we be showing `0xbbce…a362` instead of the full address under address textboxes? (I thought we only display the full address in the Wallets/list of wallets screen)

![IMG_9515 copy 2](https://user-images.githubusercontent.com/56189/151735788-4143bed2-9c08-4ccf-b83d-116ac8df10e3.JPG)

**Comment by JamesSmartCell** [comment]
if @colourfreak can confirm this, please assign to @justindg if a change is required.
