### ISSUE TITLE
wallet connect only work for the first transaction (if phone goes to lock screen)

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#2382]
Repeatable on gnosis-safe.io.

1. wallet connect to gnosis-safe.io (on desktop)
2. do a transaction. -> success
3. wait for the mobile phone to timeout (black screen)
4. wake up the mobile phone
5. do another transaction. this time it will fail

We tried 5+ times. @zhangzhongnan928 was with me. this buggy behaviour result is 100% guaranteed. stable Internet.

**Comment by JamesSmartCell** [comment]
Thanks for the detailed report - I think the service gets terminated if the app goes to sleep - clearly this isn't how it should work.

**Comment by JamesSmartCell** [comment]
So far unable to reproduce. 

What model of phone is it, and what are your timeout settings? How long do you wait while timeout happens, before restoring the phone.

I will attempt to find where this could be happening 'blind'.
