### ISSUE TITLE
What's New says "17.12.21" and "v3.50" but Discord announcement says v3.51

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2396]
Also In Settings, Version says "3.51.0 (180)"

So:

* It's "3.50" in What's new, but "3.51.0" in Settings
* Should be the same number and same format i.e. "3.50.0" or "3.51.0"
* Is the "180" the build number? (then it shouldn't be "17.12.21"

**Comment by JamesSmartCell** [comment]
The GitHub tag hasn't been created yet, once it's created the What's New will render correctly.
