### ISSUE TITLE
Add DODO to Wallet Web page

### ISSUE THREAD

**Issue by lbk3530** [AlphaWallet/alpha-wallet-android#2401]
Title: DODO

Desc: Trade any asset with the best liquidity on multiple chains 

Website:  http://app.dodoex.io/?utm_source=AlphaWallet

Section: BSC/Ethereum/Exchanges/Polygon

Logo：
![Logo1-Y](https://user-images.githubusercontent.com/37101876/152912704-88a0d600-8021-457a-b79f-f4e01967b2cd.png)
n

**Comment by lbk3530** [comment]
Hi @colourfreak ，any update?

**Comment by colourfreak** [comment]
![Screenshot_20220301-171633_AlphaWallet.jpg](https://user-images.githubusercontent.com/51817359/156206371-874ee012-409f-42df-a062-2d87364e3576.jpg)
