### ISSUE TITLE
Can't go back from Camera. Camera should have a X/cancel button

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2403]
<img width='200' src='https://user-images.githubusercontent.com/56189/153332633-39c74b8f-6601-44a4-8372-af19bd915902.jpg'>

Should have a top bar with a X/cancel button like this:

<img width="366" alt="Screenshot 2022-02-10 at 11 40 11 AM" src="https://user-images.githubusercontent.com/56189/153332848-aa74d693-97a1-4748-b88c-ffce282821ec.png">

https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e6f647f9d20081669e6748d

**Comment by JamesSmartCell** [comment]
Do the Android navigation buttons not work? Like gesture or bottom bar button?

But, needs to go in.

**Comment by hboon** [comment]
No, bottom bar, but swiping right works.
