### ISSUE TITLE
Support both wallet_switchEthereumChainObject and wallet_addEthereumChain JSON-RPC methods in WalletConnect v1

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2404]
Context:

Pedro:
> This would depend on the wallet… walletconnect allows any JSON-RPC methods

https://canary.discord.com/channels/492410046307631105/833628540456140821/905050546904399892

Reproduce:

https://github.com/AlphaWallet/alpha-wallet-ios/issues/3887#issuecomment-1034527245

**Comment by JamesSmartCell** [comment]
Add in support for the switch and add Ethereum chain methods. See the 'Reproduce' above.

First, try it via the normal Dapp Browser with breakpoints at these two methods:

`onWalletAddEthereumChainObject`
`onWalletSwitchEthereumChain`

notice how when you are in the wrong chain these methods will be called, opening the relevant ActionSheet (`showChainChangeDialog`).

Implement these in WalletConnectActivity; you will need to debug the `handleRequest` method in `WCClient.kt`, the request should show up in there once it fires.

Pop open the dialog to get confirmation from the user. Note that hitting the 'x' or sliding the dialog down is rejection - no need for a reject button.

I think you can use `updateSession` similar to how it's done in WalletConnectService to change chains.

You will also need the infrastructure as per the code under the comment `// show add custom chain dialog` in DappBrowserFragment. The same dialog is fine to re-use (don't worry about implementing it via ActionSheet for now).

Have a look, let me know if you have any questions.

**Comment by asif-finimble** [comment]
Hi @JamesSmartCell , I tried replicating the behavior but the switch chain action sheet is sometimes shown & sometimes not shown.  Also I don't see the wallet connect request in ```handleRequest``` method or do we need to add a session update call in ```showChainChangeDialog```? sorry but I'm confused as I'm not able to fully understand.

**Comment by JamesSmartCell** [comment]
To see the switch chain action you have to set the wallet onto the "wrong" chain, eg Ethereum Classic.

I will check to see if I can see the WalletConnect call for switch chain.

**Comment by asif-finimble** [comment]
> To see the switch chain action you have to set the wallet onto the "wrong" chain, eg Ethereum Classic.

I did try that, and it doesn't work,  It still shows Polygon network and on clicking ```Connect wallet```, bottom dialog is opened but Wallet connect button is not provided.  But if I change the chain to ```Ethereum```, ```switchChainChangeDialog``` is shown.
     
   
![image](https://user-images.githubusercontent.com/92773051/158320912-b5434429-3266-429f-acac-6a65e89470b2.png)   
  
Also if I change chain from Uniswap interface, the switch dialog is shown twice and we are back to original chain.

**Comment by JamesSmartCell** [comment]
Yeah I'm not sure it works the way we thought it did. If the app needs eg Polygon, it asks for Polygon when it connects.

**Comment by JamesSmartCell** [comment]
Hi @hboon maybe you can help us here. I'm not sure when this would ever be relevant.

If the app needs Polygon (eg Quickswap, Pagaxies) then it asks for that at the time of WalletConnect init.

What circumstances are the 'change_chain' ever called for and is there any reproducible?

**Comment by JamesSmartCell** [comment]
For me, it works perfectly any way I try it. EG if the dapp wants Gnosis, when I click on the WC connect it will ask to open in Gnosis.

etc etc.

**Comment by hboon** [comment]
> Hi @hboon maybe you can help us here. I'm not sure when this would ever be relevant.
> 
> If the app needs Polygon (eg Quickswap, Pagaxies) then it asks for that at the time of WalletConnect init.
> 
> What circumstances are the 'change_chain' ever called for and is there any reproducible?

Not sure if it's still reproducible in Uniswap but see https://github.com/AlphaWallet/alpha-wallet-ios/issues/3887#issuecomment-1034527245

The use case:

1. User connect to dapp on chain X
2. User clicks *in* the dapp UI to change it to chain Y

I can think of another one, while bridging:

1. User connect to dapp on chain X
2. Bridges to chain Y
3. Dapp prompts used to switch to chain Y to poll for and show result

Another one, still for bridging. In li.fi's docs https://docs.li.finance/official-documentation/integrate-li.fi-natively/li.fi-sdk/advanced-features/handling-chain-switches

> Some routes require a network switch in the end-users wallet during execution. This need arises when the route first bridges a token to another chain and subsequently wants to swap it into the final output token using an exchange. 

So something like:

1. User connects to dapp on chain X
2. User select route: token T1 on chain X -> token T2 on chain Y
2. Dapp bridges T1 on chain X to T1 on chain Y
3. Dapp prompts to switch to chain Y in order to proceed to swap from T1 on chain Y to T2 on chain Y

**Comment by JamesSmartCell** [comment]
I couldn't reproduce in Uniswap; it works correctly when trying to connect with a different chain.

I didn't really understand when @hieronymus4826 was saying that the Android connection didn't really work. Android serves whichever chain the dapp asks for when starting a session, and since there's no reproducible where a dapp wants to change chains I can't see where the issue is.

**Comment by hboon** [comment]
@hieronymus4826 can you still reproduce this for Android? I can't do it for both Android and iOS now: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3887#issuecomment-1034527245

**Comment by asif-finimble** [comment]
So I found that the "wallet_switchEthereumChain" is called by DAPP/uniswap when connected via wallet connect on desktop(or any other browser except AW) by scanning QR. when we select other chain on desktop, the mobile app will receive the wallet connect method "wallet_switchEthereumChain". I show a dialog, if user approves, we send "wc_sessionUpdate" with new chain Id approved, return null as the RPC response and the dapp will change chain. If user rejects, we send error response in RPC and dapp will show normal error message.

**Comment by asif-finimble** [comment]
same for addEthereumChain, if user approves, we add the chain and update the session. The rpc request is returned null. If user rejects, then we respond with server error message: "rejected by user".
