### ISSUE TITLE
Move "Change Language" and "Change Currency" in the main Settings view

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2407]
Note that if you don't speak English, you will find it difficult to understand "Advanced". Therefore, you might not be able to locate where to change the language. 

![Settings_Full](https://user-images.githubusercontent.com/51817359/153616646-d4506af8-8a00-428e-a9e4-b89853a34ad5.jpg)
![Settings_Advanced](https://user-images.githubusercontent.com/51817359/153616703-545ece38-a2a3-4f45-947b-157a9bad470d.jpg)

### Zeplin
https://zpl.io/VY7JKYk
https://zpl.io/251gOEW

**Comment by hboon** [comment]
Is there not a way to detect the system setting and use it as the default, if that language is supported by the app?

**Comment by JamesSmartCell** [comment]
Yes, if you install the wallet in eg French locale, it should start in French.

**Comment by colourfreak** [comment]
What if you are from a country where crypto is banned and you have to use VPN?

**Comment by JamesSmartCell** [comment]
> What if you are from a country where crypto is banned and you have to use VPN?

Your phone would still be set up in the locale you like to use it in, wouldn't it? I don't really know how people would set up their phones. Do you have any idea if they would change their locale on their phone, and why?

**Comment by hboon** [comment]
@JamesSmartCell the edit is replying to me right?

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell the edit is replying to me right?

Yes, primarily. Since you asked

> Is there not a way to detect the system setting and use it as the default, if that language is supported by the app?

**Comment by hboon** [comment]
Yes, so if eg. the user speaks Chinese but not English, they should have their system setting set to Chinese and the app should have picked it up. And if they have configured it to a language that we have not localized for, say Hindi, then it falls back to English and that is probably the next best language besides Hindi.

So my point is, it sounds like the change isn't necessary? Or is there some other reason for it?

**Comment by JamesSmartCell** [comment]
> Yes, so if eg. the user speaks Chinese but not English, they should have their system setting set to Chinese and the app should have picked it up. And if they have configured it to a language that we have not localized for, say Hindi, then it falls back to English and that is probably the next best language besides Hindi.
> 

Yes, correct.

> So my point is, it sounds like the change isn't necessary? Or is there some other reason for it?

If you don't speak English and have say Italian locale, but speak a little French you might want French as the language. AW would default to English in this case. This could be a reason to move it.

**Comment by seabornlee** [comment]
> What if you are from a country where crypto is banned and you have to use VPN?

We detect the system language, not the IP address.
