### ISSUE TITLE
Burmese font clipping issue

### ISSUE THREAD

**Issue by gichiba** [AlphaWallet/alpha-wallet-android#2415]
This is a common problem for Burmese-language app developers that I alluded to in the original PR #2339 

![screenshot of Myanmar wallet](https://user-images.githubusercontent.com/9886144/154507965-e562bcab-e072-46bf-9490-c454bae1d082.png)

It can be solved by specifying the default font for Burmese language that is sized properly. "Pyidaungsu" is recommended.

**Comment by asif-finimble** [comment]
I have used the regular and bold fonts from here: https://myanmar.gov.mm/en/-/pyidaungsu-fonts-and-keyboards.   
Used this font for semibold : https://github.com/saturngod/myanmar-unicode-fonts/blob/master/other/Pyidaungsu.ttf    
@JamesSmartCell can you recommend a font for light version.
