### ISSUE TITLE
List of wallets screen should indicate which is the current wallet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2426]
@colourfreak Is there a Zeplin for Android for this?

<img width='200' src='https://user-images.githubusercontent.com/56189/155938639-17fe5376-2443-4bb4-ba00-843dbfcc0498.png'>

Little blue dot on iOS:

<img width="200" alt="Screenshot 2022-02-28 at 3 02 23 PM" src="https://user-images.githubusercontent.com/56189/155938716-c826a626-de9d-4a03-8009-6bff18fe0955.png">

**Comment by JamesSmartCell** [comment]
@asif-finimble can you copy the style of the iOS selection as above; you'll need to accommodate the extra vertical '...' we have on Android too, can you ensure the blue dot doesn't shift the positions of any of the current layout.

We'll update once again when an official UI is added to Zeplin.

**Comment by asif-finimble** [comment]
OK. will work on it.
