### ISSUE TITLE
What's New Formatting

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2432]
1st item. Not sure if it's intentional or just formatting at the source?

![image](https://user-images.githubusercontent.com/56189/156289337-e9ad01c0-9d48-41e8-b94d-69a1da6cd362.png)

**Comment by JamesSmartCell** [comment]
It's my fault, presumably at the source (github text). Well spotted

**Comment by justindg** [comment]
@JamesSmartCell I fixed this in the dark mode branch :)

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell I fixed this in the dark mode branch :) Also made it dark mode compliant

yay. Could you patch the current master with the fix? Or is that not able to be done without a lot of framework change?

**Comment by JamesSmartCell** [comment]
> > > @JamesSmartCell I fixed this in the dark mode branch :) Also made it dark mode compliant
> > 
> > 
> > yay. Could you patch the current master with the fix? Or is that not able to be done without a lot of framework change?
> 
> Unfortunately not, because I've been using new standard values/styles for it

Ok. Not possible to just force the first '-' to be a tick?
