### ISSUE TITLE
"Set Keystore Password" keeps looping through enter keystore password + lockscreen password

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2434]
Lockscreen password is set.

After tapping enter here and then entering the lock screen password, it loops back to this screen.

![IMG_9872](https://user-images.githubusercontent.com/56189/156289674-8cf83911-3320-4cca-88b3-25b1a461c228.JPG)

**Comment by seabornlee** [comment]
@hboon I tested on Android API 29, once enter password, it pops up a share dialog:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/735708/159603729-49620b63-4222-479a-a141-c6156eecf28d.png">

Then:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/735708/159603769-0a29fc16-203b-4a46-9e30-a018498c19e0.png">

Did you see the `Share via` dialog on your phone?
If not, can you share your Android version?

**Comment by hboon** [comment]
@seabornlee works now. Thanks.

**Comment by hboon** [comment]
@seabornlee but created #2434. In case you have the context since it's the same screen :)

**Comment by seabornlee** [comment]
> @seabornlee but created #2434. In case you have the context since it's the same screen :)
@hboon #2434 is this issue itself. Do you mean you created another issue?

**Comment by hboon** [comment]
@seabornlee sorry, it's #2463. Justin has fixed it.
