### ISSUE TITLE
Show more collection-level data from OpenSea #3730

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2437]
@oa-s would you help write up details and then assign to James?

https://github.com/AlphaWallet/alpha-wallet-ios/issues/3730#issuecomment-1034803414

**Comment by hboon** [comment]
@oa-s bump

**Comment by JamesSmartCell** [comment]
This is for displaying the financial data right?

If you post a few screenshots that should be sufficient to get us started.

**Comment by hboon** [comment]
Something like that:

x|x|x
-|-|-
<img width='200' src='https://user-images.githubusercontent.com/56189/160554827-2648551d-5456-4fcb-835f-2c86afab2788.PNG'>|<img width='200' src='https://user-images.githubusercontent.com/56189/160554920-63cbfb95-f7e8-459b-ad1e-5f88c1ac2e00.PNG'>|<img width='200' src='https://user-images.githubusercontent.com/56189/160554744-04286359-0399-41bf-b5ba-655bc1831b04.PNG'>

**Comment by oa-s** [comment]
here is the latest version of `properties` section view
<img width="461" alt="Screenshot 2022-03-29 at 13 23 01" src="https://user-images.githubusercontent.com/96283950/160591051-276acf45-8578-4c2f-9061-e25f8f4c49bf.png">

**Comment by JamesSmartCell** [comment]
Thanks; @justindg can you take it from here?

**Comment by JamesSmartCell** [comment]
@hboon @oa-s do you add the last sale value for the NFT to the global wallet value?

**Comment by hboon** [comment]
> @hboon @oa-s do you add the last sale value for the NFT to the global wallet value?

We haven't yet. But we will. So if you figure out which one's the best property to use, let us know :)

**Comment by JamesSmartCell** [comment]
> > @hboon @oa-s do you add the last sale value for the NFT to the global wallet value?
> 
> We haven't yet. But we will. So if you figure out which one's the best property to use, let us know :) Maybe in a separate issue/PR? Easier to track and "copy"

Thanks, was clarifying for @justindg's implementation. Perhaps to protect ourselves we could display a separate estimated value (with a big (*) NFTs may not be worth this amount now) when the 'collections' tab is selected.
