### ISSUE TITLE
Show Trait Rarity

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2440]
I have determined a way to easily calculate trait rarity for the majority of cases.

Opensea API gives us the trait frequency (`trait_count`):

```
 "traits": [
        {
            "trait_type": "Beard",
            "value": "None",
            "display_type": null,
            "max_value": null,
            "trait_count": 882,
            "order": null
        },
        {
            "trait_type": "Gender",
            "value": "Female",
            "display_type": null,
            "max_value": null,
            "trait_count": 797,
            "order": null
        },
        {
            "trait_type": "Clothes",
            "value": "Collared",
            "display_type": null,
            "max_value": null,
            "trait_count": 180,
            "order": null
        },
```

We can use the OpenSea API to determine the total supply.

First, get the `slug` from the normal API:

`        "payout_address": "0x6d089dd805a3851ab45db5367bd8e09306986f82",
        "require_email": false,
        "short_description": null,
        "slug": "punksv2",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,`

In this case, `punksv2`.

Use this in the opensea collection stats call:

`https://api.opensea.io/api/v1/collection/punksv2/stats`

This will provide the total_supply.

Now, the rarity for each trait can be easily computed.

Sometimes, the main OpenSea API won't show the traits eg:

`https://api.opensea.io/api/v2/assets/matic?owner_address=0x2c951aab9f83e2662b4e8b7337b3524d85436841`

See the cat doge NFTs. It appears they have no traits.

The traits can be reliably checked like this:

MATIC:

`https://api.opensea.io/api/v2/metadata/matic/<CONTRACT ADDRESS>/<TOKEN ID>`

eg

`https://api.opensea.io/api/v2/metadata/matic/0x2953399124F0cBB46d2CbACD8A89cF0599974963/20165209622670505449829174314126577455283915657757664200758758359457308082177`

ETHEREUM:

`https://api.opensea.io/api/v1/asset/<CONTRACT ADDRESS>/<TOKEN ID>`

eg

`https://api.opensea.io/api/v1/asset/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/1`
`https://api.opensea.io/api/v1/asset/0x300b896c8ce26395cd1aed16cbbd070a487c7c3c/6653`

etc

Rinkeby same format as ETHEREUM but with `https://rinkeby-api.opensea.io`

This should be done possibly within NFTAsset or Token, since it applies to 1155 and 721 alike.

**Comment by hboon** [comment]
@JamesSmartCell like I mentioned in https://github.com/AlphaWallet/alpha-wallet-ios/issues/3730#issuecomment-1062558300, use `count` instead of `total_supply`. Unless it's different for v2?

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell like I mentioned in [AlphaWallet/alpha-wallet-ios#3730 (comment)](https://github.com/AlphaWallet/alpha-wallet-ios/issues/3730#issuecomment-1062558300), use `count` instead of `total_supply`. Unless it's different for v2?

This method should work 100% of the time, I checked with the various types of contracts.

**Comment by hboon** [comment]
Ah I see. Great, thanks.

**Comment by JamesSmartCell** [comment]
@justindg can you also implement the heuristic for fetching traits? I was planning to do this but 1559 has priority. Here's my notes on how I was going to approach this:

First:

- Modify OpenSeaService to fetch and store the stats (eg https://api.opensea.io/api/v1/collection/punksv2/stats). You'll need to make a note of the slug, and use that in the stats call. We only need to store the `count` as Boon says above. I'm not sure but `total_count` and `count` seem to be the same for all cases I looked at, but this may not always be the case.

I'm not sure exactly what's going on but we need to follow something like this:

1. User clicks on NFT detail (only place in the app where traits are shown)
2. See if NFT has traits. Has: goto 4, has not: goto 3
3. Try to fetch traits using either OpenSea API (see above, if available) or directly with existing metadata method (maybe modify the metadata fetch method in class Token to include the OpenSea fetch if available).
4. Perform simple calculation to determine trait rarity %.

**Comment by justindg** [comment]
It seems like I can get this done through a single call to `/asset` api:

`https://api.opensea.io/api/v1/asset/<CONTRACT ADDRESS>/<TOKEN ID>`

From there I can obtain both stats (total_supply) and traits, and then calculate rarity from there.

**Comment by JamesSmartCell** [comment]
Ok I didn't notice that that route provides the stats too. That's really handy. Then you don't need to change the opensea service fetch.

**Comment by hboon** [comment]
But `/api.opensea.io/api/v1/asset/<CONTRACT ADDRESS>/<TOKEN ID>` is 1 call per token ID.

We'll always need:

* 1 (excluding pagination) call for `/api/v1/assets/?owner=0xb0b`/ to get the entire list of NFTs token IDs
* 1 for each collection `/api/v1/collection/\(slug)/stats` and/or `/api/v1/collections?asset_owner=0xb0b` for collection's level information, which will include the count

Doesn't sound like we need to make 1 call per token ID. Is there another reason?

**Comment by justindg** [comment]
`/api.opensea.io/api/v1/asset/<CONTRACT ADDRESS>/<TOKEN ID>` will not be called until the user visits the NFT Detail page. 
![rarity2](https://user-images.githubusercontent.com/17334718/158878240-eafa8317-808b-4670-bdc0-004b977c6e7f.jpg

Currently this is the only screen where the attributes are displayed. Is there a different way we should approach this? I prefer not to make the rarity calculation before visiting the screen, as this will affect the performance.

**Comment by hboon** [comment]
oa-s made updates recently so he will know better.

> Currently this is the only screen where the attributes are displayed. Is there a different way we should approach this? I prefer not to make the rarity calculation before visiting the screen, as this will affect the performance.

Ah I see. Yes, due to flow and performance, it might be different for Android and iOS, I think the API calls made for iOS is like this, and you can see if it helps:

1. 1 call (repeat until pagination is done) for `/api/v1/assets/?owner=0xb0b` to get the entire list of NFTs token IDs owned by the current wallet address — this includes traits for each token ID, but not the collection's count/total_supply
2. Compute the list of collections from the (1), including their collection slugs (eg 'blitmap')
3. 1 call (repeat until pagination is done) for `/api/v1/collections?asset_owner=0xb0b` for collection's level information.
4. For each collection from (2), 1 call for `/api/v1/collection/#{slug}/stats` [^1] — `/api/v1/collection/#{slug}/stats` contains `count`/`total_supply`

That's why I suggest we don't seem to need to make `/api/v1/asset/<CONTRACT ADDRESS>/<TOKEN ID>` which would be 1 call per token ID. (but I see you want to call this only when the screen is visited, so maybe that's fine too)

[^1]: I don't remember why we need both. But I suppose `/api/v1/collection/#{slug}/stats` is only embedded in `/api/v1/collection/#{slug}` (this one's unused. It's much bigger and embeds stats) but not in `/api/v1/collections?asset_owner=0xb0b`)
