### ISSUE TITLE
Update Play Store graphics

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2446]
[Graphics for Google Play.zip](https://github.com/AlphaWallet/alpha-wallet-android/files/8251618/Graphics.for.Google.Play.zip)
![1](https://user-images.githubusercontent.com/51817359/158341169-246c339f-5b2c-4d45-b55f-d98b34276b92.jpg)
![2](https://user-images.githubusercontent.com/51817359/158341185-77dfc1b0-7c73-412f-af3e-55068def7b54.jpg)
![3](https://user-images.githubusercontent.com/51817359/158341191-b8b70ec7-f561-4d51-9512-a6f108ae68c7.jpg)
![4](https://user-images.githubusercontent.com/51817359/158341193-586c96c0-d9c7-4e08-b3a9-de7f6dc97fb7.jpg)
![5](https://user-images.githubusercontent.com/51817359/158341197-96de77e0-7b0f-4053-84e9-a5bb34647b6a.jpg)
![6](https://user-images.githubusercontent.com/51817359/158341203-ad16da07-390b-40b7-b15c-da9ff96b1f6f.jpg)
![7](https://user-images.githubusercontent.com/51817359/158341209-59b6bdf2-9904-488b-9950-3b98ff0dbc82.jpg)
![8](https://user-images.githubusercontent.com/51817359/158341215-ec2c8d95-5bec-4c51-b37d-ffde4c9be662.jpg)
![9](https://user-images.githubusercontent.com/51817359/158341223-113afb12-454f-40c0-b333-3c0a130065f2.jpg)
![10](https://user-images.githubusercontent.com/51817359/158341228-b79a57e2-03f8-466a-b53f-3902f83f914d.jpg)

**Comment by colourfreak** [comment]
> The car is red : ) @colourfreak <img alt="image" width="491" src="https://user-images.githubusercontent.com/735708/159502889-ed26e32a-4ffe-4e16-af06-7b8c6899b49a.png">

Ignore this. Push this as it is.

**Comment by seabornlee** [comment]
Ok.
