### ISSUE TITLE
Update Android App Icon

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2447]
![hdpi](https://user-images.githubusercontent.com/51817359/158344408-edb331bc-9e45-453b-8d94-fe45d5d549a5.png)
![mdpi](https://user-images.githubusercontent.com/51817359/158344413-917b413d-0b23-4652-8bb5-e6050ad54ab9.png)
![play](https://user-images.githubusercontent.com/51817359/158344416-16fcf058-5ec8-487b-abc9-caa96aa20293.png)
![xhdpi](https://user-images.githubusercontent.com/51817359/158344417-465ee07d-406e-4a2b-aa9f-8c96a45f3a77.png)
![xxhdpi](https://user-images.githubusercontent.com/51817359/158344418-c0f2bd19-38bb-4e64-a1d5-25ceb099688a.png)
![xxxhdpi](https://user-images.githubusercontent.com/51817359/158344419-8359aa26-9f63-45e4-9541-3f22e197a6de.png)

**Comment by justindg** [comment]
Already updated in the Dark mode branch :)

**Comment by JamesSmartCell** [comment]
@colourfreak is there an SVG of the new icon?

**Comment by colourfreak** [comment]
[alphawallet.svg.zip](https://github.com/AlphaWallet/alpha-wallet-android/files/8314803/alphawallet.svg.zip)

**Comment by colourfreak** [comment]
Still not updated

**Comment by colourfreak** [comment]
<img width="942" alt="Screenshot 2022-04-01 at 12 56 22" src="https://user-images.githubusercontent.com/51817359/161250453-54f3b66c-dc1a-4d8a-bfcc-127c15aec583.png">

**Comment by JamesSmartCell** [comment]
@colourfreak I will update the icon at the same time as pushing the 3.53 release.

**Comment by JamesSmartCell** [comment]
@colourfreak Now updated in PlayStore along with the new release.

**Comment by JamesSmartCell** [comment]
Live:
![image](https://user-images.githubusercontent.com/12689544/163498973-eac38f00-b314-40e8-8fbd-fdb71b0e735e.png)

**Comment by colourfreak** [comment]
Awesome guys!
