### ISSUE TITLE
Is there a way to request an offline signature from the AW browser?

### ISSUE THREAD

**Issue by sintc0nery** [AlphaWallet/alpha-wallet-android#2450]
That is, working from a front-end, we know that we can request a call to a contract method from the wallet through something like:
```
this.Contract = await Contract.deployed()
this.Contract.buySomething('Parameters of the contract method');
```
The problem with this is that the transaction is sent  
front-end(raw) -> alphawallet(sign) -> infura(signed)  
which is fine, but if we wanted to do another itinerary from the front-end, like:  
front-end(raw) -> alphawallet(sign) -> front-end(signed) -> any type of transmission to an eth node (https for example)  
I don't know how to do it.
Is there any way to request the supplier, AW in this case, a signature of this type? I guess with metamask isn't possible.
Something that enable the front-end to process the transaction:   
```
this.Contract = await Contract.deployed()
var tx = this.Contract.buySomething('Parameters of the contract method', { type: 'raw_transaction');

//now doing whatever with var tx
```
I am trying to do this to enable crypto payments via NFC. Being able to verify that the tx has been carried out correctly before the transaction has been mined.
Thanks in advance, 
I look forward to hearing from you.

**Comment by JamesSmartCell** [comment]
Hi, are you asking to sign a transaction offline for later sending to a node?

This is possible within a dapp currently but I don't know exactly how to drive it; instead of 'sendTransaction' you need to use 'signTransaction'.

I will check through a dapp I wrote to see if I can update it to do what you're after.

What it'll give you is the signature for the transaction. You'll need to form the transaction and then form the transaction and signature package.

**Comment by sintc0nery** [comment]
Hi,
yes that is exactly what I want but from what I've researched so far, most wallets have discontinued support for the web3 `signTransaction` feature to prevent scams from making the user sign a malicious transaction.
Looking over the alphawallet code, I think there are methods to actually use `signTransaction` but I haven't been able to access its call like I would with `sendTransaction`:
```
ethereum.request({
              method: "eth_sendTransaction",
              params: [{rawTxObject}],
            });
```
It works by asking the user to accept the transaction in the alpha wallet app, but:
```
const signedTx = await ethereum.request({
              method: "eth_signTransaction",
              params: [{rawTxObject}],
            });
```
Does nothing, I don't know if there is no longer support to this function or is there another way to call it.

**Comment by hboon** [comment]
```
const signedTx = await ethereum.request({
              method: "eth_signTransaction",
              params: [{rawTxObject}],
            });
```

Yes, this is correct (vs `eth_sendTransaction` which signs and sends).

Yes you are right, it's not supported by AlphaWallet.

**Comment by JamesSmartCell** [comment]
Looks like we can't do this anymore as it's been flagged as unsafe.
