### ISSUE TITLE
QRScanner crashes on API23

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2451]
According to Zxing release notes, it requires API24+.
<img width="901" alt="image" src="https://user-images.githubusercontent.com/735708/159153551-505a68c8-c758-4e6b-b614-3055cfdcf152.png">

**Comment by JamesSmartCell** [comment]
I have been considering this update for a while now; I don't think we have many users still with phones at API23

**Comment by seabornlee** [comment]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/735708/159459407-62a0496a-c8b8-4942-a937-4738870e5fc1.png">

**Comment by JamesSmartCell** [comment]
Disable QRScanner for API23?

**Comment by JamesSmartCell** [comment]
Yes, for now let's just disable QR scanner with a toast, but leave the rest of the features running. Previously we had a different implementation which did support API23 but the results weren't very good.

**Comment by seabornlee** [comment]
Got it.
