### ISSUE TITLE
Lint on CI

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2455]
- [x] Config lint rules (including coding style)
- [x] Abort build when has lint warnings
- [x] Lint updated files on CI, create baseline
- [x] Comment on PR according to lint result

**How to use:**
1. Send PR as normal
2. Check the comments added by lint-bot
3. Fix issue locally and click 'Resolve conversation' under each comment
4. Commit and Push again
5. Back to step 2

**Comment by JamesSmartCell** [comment]
@seabornlee also we should add style check similar to web3j to enforce consistent project style eg:

```
if (a.equals(b))
{
    //do something
}
else
{
    //the other thing
}
```

rather than 
```
if (a.equals(b)) {
    //do something
} else {
    //the other thing
}
```

**Comment by seabornlee** [comment]
> @seabornlee also we should add style check similar to web3j to enforce consistent project style eg:
> 
> ```
> if (a.equals(b))
> {
>     //do something
> }
> else
> {
>     //the other thing
> }
> ```
> 
> rather than
> 
> ```
> if (a.equals(b)) {
>     //do something
> } else {
>     //the other thing
> }
> ```

Sure thing.

**Comment by JamesSmartCell** [comment]
Hi @seabornlee I created a 'AlphaWalletStyle.xml' which contains the coding style.

This is a great mod, looking forward to the merge.

**Comment by seabornlee** [comment]
Awesome!
