### ISSUE TITLE
Setup fastlane Google Play Store Credential

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2461]
As F-droid requires `metadata` created by `fastlane`.
We can download Google Play Store metadata by providing credentials to fastlane.
And later, we can benefit from fastlane to update changelogs, screenshots, descriptions, etc. And auto-increment build number and build apk, upload to Play store.

To do that, the first thing is to get the credentials to call Google Play API.
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/735708/159406357-4194dad2-032d-43ea-8758-b49f9b220f17.png">

https://docs.fastlane.tools/actions/supply/

**Comment by JamesSmartCell** [comment]
I think @weiwu-zhang is the sole owner of the Google PlayStore settings, in this case he is the only person that can do the above.

**Comment by weiwu-zhang** [comment]
@JamesSmartCell how do you determine that it's a permission issue? I couldn't do what @seabornlee asked me to do. I already have all permission:

![image](https://user-images.githubusercontent.com/548435/160306170-1b468c87-6a0a-471c-b289-6ec12911d5c9.png)

But I can't access API access
![image](https://user-images.githubusercontent.com/548435/160306189-6c94c387-fb6b-4b40-a751-4cf15685646f.png)

**Comment by weiwu-zhang** [comment]
@seabornlee research a bit, and we do a zoom session so you can control my account to do that. I don't think it's because my account is magically powerful, but doing so excludes the probability that "maybe xxx account isn't powerful enough" (@JamesSmartCell 's line)

**Comment by seabornlee** [comment]
@hboon Can you help with this?

**Comment by hboon** [comment]
> owner

I have no idea. Let me know if there's a way for me to transfer this.

I tried following the instructions and got the key. Will send it to you guys.

**Comment by weiwu-zhang** [comment]
@hboon you are the αW product manager it is 𝑐𝑜𝑟𝑟𝑒𝑐𝑡 that you own this product. No need to transfer to anyone. This issue is closed assuming @hboon will send the keys
