### ISSUE TITLE
Add TokenIcon to chain selection listing

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2468]
Here's how the Network Select for both Single Item (Radio button) and Multiple item select should look (although for single item it'll be a radio button instead of a checkbox).

![image](https://user-images.githubusercontent.com/12689544/159692812-2a67f331-3ac1-4b0e-ad63-54497e16b2c8.png)

Add the TokenIcon and Chain Id to the List in ```SelectNetworkFilterActivity``` and ```SelectNetworkActivity```.

See usage of TokenIcon to display the current chain in ```BalanceDisplayWidget```

(Keep the leftmost 'hamburger' network edit button for editing the network).

**Comment by JamesSmartCell** [comment]
Here's a link to the Zeplin design: https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/60b6299ce283f10c3f95453c

**Comment by JamesSmartCell** [comment]
You can pretty much just re-use the TokenHolder layout for this

**Comment by asif-finimble** [comment]
> You can pretty much just re-use the TokenHolder layout for this

There are other views in it and also the checkbox is at beginning in there. Don't you think we should just create new layout?

**Comment by asif-finimble** [comment]
@JamesSmartCell can't we just set the image from list? Using tokenIcon will require passing the token object. I tried doing that 
 using ```tokenService.getServiceToken(chainId)``` but Optimism token is not coming.

**Comment by JamesSmartCell** [comment]
> > You can pretty much just re-use the TokenHolder layout for this
> 
> There are other views in it and also the checkbox is at beginning in there. Don't you think we should just create new layout?

Yes use new layout but you can look at the tokenholder layout for inspriation
