### ISSUE TITLE
UI: button text not visible

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2471]
<img width="156" alt="image" src="https://user-images.githubusercontent.com/735708/160053518-c7ec8899-d9b9-4c07-b527-4445149d29ff.png">

<img width="153" alt="image" src="https://user-images.githubusercontent.com/735708/160053614-4a43c878-0040-49f3-9e33-48ea6e2d1d52.png">

**Version:**
master branch.

**Comment by justindg** [comment]
Will fix this
