### ISSUE TITLE
Support Cronos mainnet

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2475]
Cronos testnet exists, but mainnet is not listed under "Settings -> Select active network".
@hboon iOS neither.

**Network info here:**
https://cronos.org/docs/getting-started/metamask.html#connecting-to-the-cronos-mainnet-beta

**Comment by JamesSmartCell** [comment]
Excellent, Cronos mainnet wasn't available at the time.

Will you check and add it in? You need to touch three files:

EthereumNetworkBase x2 (both of them).
TickerService (to add the coingecko ticker ids if supported).

Also you will need to add the assets and pick a distinctive colour for the chain.

**Comment by hboon** [comment]
- [ ] Create iOS issue once parameters are known :)

**Comment by JamesSmartCell** [comment]
@asif-finimble can you complete the Cronos Mainnet addition?

Note that some items may have changed. I recently fixed the Testnet implementation (thanks to the new node health scanner :) ), the mainnet RPCs and tx explorer/API routes have been updated and should look similar to the testnet URLs.

See this page:

https://cronos.org/docs/getting-started/metamask.html#connecting-to-the-cronos-mainnet-beta

**Comment by JamesSmartCell** [comment]
Also create an issue with all the data that the iOS team will need on their repo, which is the 3 URLs for node connections (RPC, tx explorer and API) and the SVG. If there's a Cronos theme colour list that too. Looks like blue & white is their theme colours. Might need a little colour jiggling to fit in dark mode.

**Comment by asif-finimble** [comment]
Sure.

**Comment by asif-finimble** [comment]
Added Cronos mainnet 
RPC: https://evm.cronos.org  
Symbol: CRO  
Name: Cronos
SVG: https://cronoscan.com/images/svg/brands/mainbrand-1.svg?v=22.5.2.5 
Blockexplorer: https://cronoscan.com  
Tx URL: https://cronoscan.com/tx/   
Api URL: https://api.cronoscan.com/api?
Color: #1A90FF (from svg)

**Comment by asif-finimble** [comment]
@hboon , @JamesSmartCell  I have created issue for IOS: https://github.com/AlphaWallet/alpha-wallet-ios/issues/4661
