### ISSUE TITLE
Dark Mode collected issues

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2476]
Here's a list of minor artifacts I've seen (all while using Dark Mode):

- [x]  Two side by side buttons in a Dialog. For a good example go Settings/Advanced/Reload Token Data.
- [ ]  When switching chains using Change / Add Wallet in Settings, the AlphaWallet 'wait' screen should be in Dark Mode, as should the loading screen. It might be a bit jarring eg if you're looking at your moneybags in the dark, then suddenly the whole screen lights up.
- [x]  Background assets in TokenIcon for transparent icons. For Dark Mode these should switch to a darker background asset. For prime examples see 'Rinkeby' icon in the main wallet page, also try sending a transaction and see the circle asset underneath the 'pending' spinner. I think it's called 'drawable.greycircle'.
- [x]  Background asset for 'tick' that appears when a transaction is being sent. I originally created this to mask out the background as the tick appears; the circle behind the tick needs to match the background colour, not be white.
- [x]  Settings notification is a bit _skew-whiff_. To reproduce create a new wallet but don't back it up. It doesn't look too bad, but it seems like it should be higherup more in the corner.

![Screenshot_20220327-182914_AlphaWallet](https://user-images.githubusercontent.com/12689544/160271516-0a3fb62b-ecb2-4c16-b50c-a02e549a9eef.jpg)

A bunch of minor things; they only stand out because the rest looks awesome.

**Comment by justindg** [comment]
> When switching chains using Change / Add Wallet in Settings, the AlphaWallet 'wait' screen should be in Dark Mode, as should the loading screen. It might be a bit jarring eg if you're looking at your moneybags in the dark, then suddenly the whole screen lights up.

I tested this on my phone, and I found out that the wait/splash screen seems to follow the phone's (and not the app's) dark mode settings. We could compromise by having the splash screen always dark, but I am unsure if that's weird to the user.

**Comment by justindg** [comment]
Adjusted the notification badge a little bit, it should be perfectly aligned to the north west quadrant now

![image](https://user-images.githubusercontent.com/17334718/160306317-0ed5a9de-2f3f-4ffb-b3d9-7847f4971c9b.png)
