### ISSUE TITLE
For Rinkeby opensea testnet doing nothing when click on Buy Now for any NFT

### ISSUE THREAD

**Issue by HemangiVekaria** [AlphaWallet/alpha-wallet-android#2489]
@JamesSmartCell  can you please help me with this? When i add https://testnets.opensea.io in the browser and select Rinkeby from the test network at that time if I want to buy any NFT and click on  Buy now it's opening a screen like this.
![image](https://user-images.githubusercontent.com/17717369/160761797-af719420-6979-4f93-ae9b-b09cbafff77f.png)

Now when clicking on Confirm Checkout it's show the process for some time and then show message like this
![image](https://user-images.githubusercontent.com/17717369/160761903-dbf4381e-fdc9-424a-95c6-a5a2e65ab668.png)

We are not getting any callback from webview like onSignTransaction or onSendTransaction or any other... While i checked this same link in Chrome browser with Metamask and in there when click on Confirm Checkout it's redirected to metamask and showing confirmation there. 

Do you have any idea which method is called? Can you please do check for this and help me to figurinng out this? Thanks in advance.

**Comment by JamesSmartCell** [comment]
Thanks for reporting, I'll check it

**Comment by HemangiVekaria** [comment]
Thanks @JamesSmartCell

**Comment by HemangiVekaria** [comment]
Hello @JamesSmartCell Did you find anything? If then please guide me. i need solution ASAP. Could you please help?

**Comment by JamesSmartCell** [comment]
Thanks I replicated it, you are using WalletConnect to connect, right?

It is a bit hit and miss, sometimes if you 'log out' of the wallet, then log back in using WalletConnect, then try to buy again you'll get the correct pop-up. I'm not sure what's happening; trying to see if it's our fault, WalletConnect or Opensea.

**Comment by JamesSmartCell** [comment]
The fault appears to lie on OpenSea's or WalletConnect's side, but I have managed to add a filter that prevents the connection from shutting down when getting bad data. This let me purchase a few of the NFTs on OpenSea Rinkeby.

This fix will be in the next release due out today or tomorrow, or if you can't wait you can build from source code.

Thanks for reporting! It really helps.

**Comment by HemangiVekaria** [comment]
Thanks... I will take a look from source code and see if it works or not. Thanks for support

**Comment by JamesSmartCell** [comment]
> Thanks... I will take a look from source code and see if it works or not. Thanks for support

I haven't pushed the PR yet but you can build from the linked PR

**Comment by HemangiVekaria** [comment]
I build from fix-walletconnect-busy-connection  branch its showing like this... still cannot purchase nft

**Comment by JamesSmartCell** [comment]
It wasn't working before the fix, now I get this:

https://user-images.githubusercontent.com/12689544/161367470-05861774-2440-4ea8-a6b3-a8488085c953.mp4

You have to keep logging out until when you log in, you see the WalletConnect login.

Make sure, when the 'Connect to WalletConnect' prompt appears you are connecting to Rinkeby.

**Comment by JamesSmartCell** [comment]
@HemangiVekaria I watched your video, you need to log out, then connect via walletconnect, if you don't get the WalletConnect screen you need to log back out again, then log in with WalletConnect

**Comment by HemangiVekaria** [comment]
Yes i selected network as Rinkeby and try to connect using walletconnect then it's connected to mainnet.. Let me uninstall and install app and see if its work for me or not

**Comment by JamesSmartCell** [comment]
You can choose 'edit' and change the network to Rinkeby.

They didn't write the connector very well, if they did it properly it would always be Rinkeby.

No need to uninstall

**Comment by JamesSmartCell** [comment]
Let me know how you get on

**Comment by HemangiVekaria** [comment]
i am checking give me few minute i will check and let you know

**Comment by HemangiVekaria** [comment]
Yes it's working now. Thanks

**Comment by JamesSmartCell** [comment]
Nice, thanks :)

**Comment by JamesSmartCell** [comment]
Closed by #2514
