### ISSUE TITLE
Improve Switch Chain ActionSheet

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2504]
When switching chains with WalletConnect (and DappBrowser), the prompt is still the placeholder text message which was put in a while back.

Check Zeplin for an official design for this action sheet configuration: If it exists implement it, if not we can flag this as an issue for Tomek.

**Comment by asif-finimble** [comment]
@JamesSmartCell I checked and there are no designs for switch chain. Only the switching to testnet action sheet is present.

**Comment by JamesSmartCell** [comment]
@asif-finimble Thanks for checking. Let's create a placeholder design for this, as currently the text view doesn't look good.

It should be a layered design looking somewhat like the normal WalletConnect Approve sheet, showing a graphic of old chain logo/text ---> new chain logo/text in one widget, and the text asking to swap, and a title.

**Comment by asif-finimble** [comment]
@JamesSmartCell how about something like this?  
should we show name and chainID below the icon?  

![image](https://user-images.githubusercontent.com/92773051/161486861-f06915cf-720f-467c-9394-dfab48494a1d.png)

**Comment by JamesSmartCell** [comment]
As layers like the usual ActionSheet one, so yes, the top, then your eth > op, then a partition, then the usual text.

This works for a draft.

**Comment by asif-finimble** [comment]
@JamesSmartCell how does this look?

![image](https://user-images.githubusercontent.com/92773051/161523502-f3e5665d-b655-4cf5-88ba-cf9f32c1c64e.png)

**Comment by JamesSmartCell** [comment]
I like it :)

**Comment by asif-finimble** [comment]
OK. great. will generate a PR then.

**Comment by JamesSmartCell** [comment]
Looks good just one thing, can you move the element that shows the chain graphic, chevron and new chain graphic into its own widget?
