### ISSUE TITLE
Add Transaction to logs when NFT Transfer event is detected

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2506]
- Ensure the Transaction log is written to DB when Transfer event is detected.

Find where events are picked up in `ERC721Token` and `ERC1155Token`. When the event is picked up, trigger the corresponding transaction to be picked up by creating a pending transaction in Realm that the TransactionService will pick up and fully populate.

**Comment by asif-finimble** [comment]
@JamesSmartCell Can you please guide me on this. I'm not familiar with code. Where do I start?

**Comment by JamesSmartCell** [comment]
Start in ```class ERC721Token```. 

In the function ```processTransferEvents``` you'll see that when an ERC721 token is discovered we start pulling in events from that token contract that apply to the wallet being scanned for.

When one of these transfer events is discovered, currently all the function does is collect the TokenID for that NFT so it can subsequently be checked to see if the wallet still has it.

Each event recorded looks like this : ```event Transfer(address indexed from, address indexed to, uint256 indexed tokenId);```  in the Solidity code, so we can pull the from address, to address and tokenId from the ```getIndexedValues()``` event params.

The ```EthLog``` also has many other useful params like transaction hash, block etc.

However we have many of the data items we need to build a transfer record. 

The transfer records are stored like this (From ```TransactionNetworkClient```):

```
    private void writeEvents(Realm instance, EtherscanEvent[] events, String walletAddress,
                             @NonNull NetworkInfo networkInfo, final boolean isNFT) throws Exception
    {
        String TO_TOKEN = "[TO_ADDRESS]";
        String FROM_TOKEN = "[FROM_ADDRESS]";
        String AMOUNT_TOKEN = "[AMOUNT_TOKEN]";
        String VALUES = "from,address," + FROM_TOKEN + ",to,address," + TO_TOKEN + ",amount,uint256," + AMOUNT_TOKEN;

        Map<String, Transaction> txFetches = new HashMap<>();

        instance.executeTransaction(r -> {
            //write event list
            for (EtherscanEvent ev : events)
            {
                boolean scanAsNFT = isNFT || ((ev.tokenDecimal == null || ev.tokenDecimal.length() == 0 || ev.tokenDecimal.equals("0")) && (ev.tokenID != null && ev.tokenID.length() > 0));
                Transaction tx = scanAsNFT ? ev.createNFTTransaction(networkInfo) : ev.createTransaction(networkInfo);

                //find tx name
                String activityName = tx.getEventName(walletAddress);
                String valueList = VALUES.replace(TO_TOKEN, ev.to).replace(FROM_TOKEN, ev.from).replace(AMOUNT_TOKEN, scanAsNFT ? ev.tokenID : ev.value); //Etherscan sometimes interprets NFT transfers as FT's
                storeTransferData(r, tx.hash, valueList, activityName, ev.contractAddress);
                //ensure we have fetched the transaction for each hash
                writeTransaction(r, tx, ev.contractAddress, networkInfo.etherscanAPI.contains(COVALENT) ? null : txFetches);
            }
        });

        fetchRequiredTransactions(instance, networkInfo.chainId, txFetches);
    }
```

You can see there's two steps:

1) first build the transfer record:

- You need the Transaction Hash (Available from ```EthLog```), the from address (event params), to address (event params), tokenId (event params), activity name: either "Sent", "Received" or "Mint" depending on the "from" and "to" addresses, and contract address which we know from the Token itself.
- Store this as per ```storeTransferData``` above.
- Collect the TransactionHashes into a HashSet.

2) Fetch and write the transactions if required:

- iterate the HashSet you built above, see if the transaction has been fetched or not (is it in Realm?), if it hasn't then fetch it and write the TX as per ```fetchRequiredTransactions``` from the function above. Note that this could probably do with a refactor to avoid duplicate code and improve it. The TODO I wrote a while back is to move the transaction fetch to the transaction service and have that gradually resolve the required transactions in a similar way to how TokensService gradually resolves unknown tokens.


To complete the task, once this is working, you'll also need to filter for outgoing transfer events; currently the filter only catches incoming tokens, because that's all that's needed to build the token balance.

you'll need to update the ```getTransferFilter``` to receive outgoing transfers; which will probably have to be done in a separate call, as I don't think you can combine receiving outgoing and incoming calls because a filter doesn't work like that. If you remove the filters, and receive every Transfer event on the contract it would be overwhelming for contracts like the OpenSea collections.

**Comment by asif-finimble** [comment]
Thanks for the explanation. Will work on it.

**Comment by asif-finimble** [comment]
@JamesSmartCell  I understood the most of what you explained that how to get the events and create txn record. Now I need to know that how should I proceed with implementation? 
I see that TokenRepository calls the update balance and from there we reach here. Sorry but I'm not able to get the whole picture of what's happening. Like how what do we do from here and which classes and methods need to be updated?

**Comment by JamesSmartCell** [comment]
In addition, you probably only need to do this if the network doesn't have a etherscanAPI available, like Aurora and custom chains, or doesn't support the token discovery APIs that Etherscan has (I'm not sure how to detect this automatically).

Klaytn Baobab currently has no Etherscan API, so is a good example to use.

Watch this address: 0x82357f25aD0Db84d2E4CC1a2AE2803D88b178112

in Klayn Baobab Testnet. You should see the 9 NFTs appear, but there's no corresponding activity in the activity pane.

If you reset this wallet (in settings, advanced, reload token data) you'll see the NFT TokenIds being discovered in the ```processTransferEvents``` method, then it checks to see if the user still holds these tokens (because for pure balance we don't need to check when the user sends a token, only that they received a token, then check it's still in the wallet).

What we want to do is populate the mint events for this wallet, and the constructor transaction that created the token.

First get the mint events showing as I detailed above, then load the transaction and write it to Realm.

**Comment by JamesSmartCell** [comment]
If you create NFTs on a different testnet eg Rinkeby or Ropsten using the NFT faucet in my github (or yours) you'll see the mint events and the constructor transaction. The wallet knows it's a mint event because the 'from' address is the zero address 0x0000000...

**Comment by asif-finimble** [comment]
Thanks. Will go through the explanation and implement.

**Comment by asif-finimble** [comment]
> Watch this address: 0x82357f25aD0Db84d2E4CC1a2AE2803D88b178112     

@JamesSmartCell I watched this address and also did reset token data but the ```processTransferEvents()``` is not executed.

**Comment by JamesSmartCell** [comment]
Now complete
