### ISSUE TITLE
Tapping this token in Wallet tab seem to hang the app somewhat reliably

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2520]
Tapping this token in Wallet tab seem to freeze the app somewhat reliably

<img width='200' src='https://user-images.githubusercontent.com/56189/161464382-9c47063f-d4ec-44a8-b649-05a49f65f816.JPG'>

This is with: 0x0d590124d2faabbbdfa5561ccbf778914a50bcca

Final release candidate v3.53.3 available on 20220402

**Comment by justindg** [comment]
Found the cause, will attempt to fix
