### ISSUE TITLE
Add Aurora EVM Bridge

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2529]
Aurora is the EVM bridge for Near protocol which is gaining traction.

Name: ```Aurora```
Symbol: ```ETH```
ChainId: ```1313161554```
RPC: ```https://mainnet.aurora.dev```
Etherscan API: ```https://api.aurorascan.dev/api?```
Etherscan URL: ```https://aurorascan.dev/tx/```
Icon: ![aurora](https://user-images.githubusercontent.com/12689544/161689840-e3756579-d88e-4120-843b-6841aad8c47f.svg)
Coingecko chain ID: ```aurora```
Coingecko chainpair: ```aurora```

Name: ```Aurora (Test)```
Symbol: ```ETH```
ChainId: ```1313161556```
RPC: ```https://betanet.aurora.dev```
Etherscan API: ```https://api-testnet.aurorascan.dev/api?```
Etherscan URL: ```https://testnet.aurorascan.dev/tx/```
Icon: ![auroratest](https://user-images.githubusercontent.com/12689544/161689889-fea4ff91-e8a3-413e-b62b-789445c29654.svg)

usesSeparateNFTTransferQuery should be ```true```
Fixed Gas: Unknown (TBD, test it).
Gas Limit: ```6,721,975```

**Comment by JamesSmartCell** [comment]
@asif-finimble additionally can you see if there's a faucet for the Testnet coins and try a few transactions.

**Comment by asif-finimble** [comment]
Ok. Sure. I'll research on it.

**Comment by asif-finimble** [comment]
@JamesSmartCell there's a correction needed. testnet id ends in 5. Not 6.

**Comment by asif-finimble** [comment]
Faucet: https://aurora.dev/faucet

**Comment by asif-finimble** [comment]
@JamesSmartCell I added the chain and transferred 0.0005 ETH from Aurora faucet. The tx is available in Activity tab but the balance is not updated. Also Gas service throws exception for fetching gas history for Aurora.

**Comment by JamesSmartCell** [comment]
That's fine, it probably doesn't have EIP1559 gas.

That's interesting about the testnet ID, chainlists must be wrong.

**Comment by JamesSmartCell** [comment]
Network Name: Aurora Testnet
New RPC URL: https://testnet.aurora.dev/
Chain ID: 1313161555
Currency Symbol: ETH

Yep should be ending with a 5. Also the testnet RPC should be different - I couldn't get any response on the other one.

**Comment by asif-finimble** [comment]
Okay, will update the rpc. I got the chain ID from docs but missed the rpc..

**Comment by asif-finimble** [comment]
@JamesSmartCell balance and activity both are working as expected with the updated RPC. Can't send payment though, it says Gas price too low.

**Comment by JamesSmartCell** [comment]
Can you commit the branch? I will add the API key

**Comment by JamesSmartCell** [comment]
I have added the API key here: https://github.com/AlphaWallet/alpha-wallet-android/tree/add-aurora-key

**Comment by asif-finimble** [comment]
Ok. I'll add it.

**Comment by JamesSmartCell** [comment]
Thanks. I'm running into a few integration issues on the chain side - it's not as straightforward as most chains.

**Comment by asif-finimble** [comment]
Ok. Do I need to to do anything on that.?
