### ISSUE TITLE
Warn user about unsynced ENS send

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2544]
If the user's phone time is not synced correctly, the wallet can fail to validate the user's ENS.

see this code in EnsResolver:

```
    public String resolve(String ensName)
    {
        String contractAddress = ensName;
        if (isValidEnsName(ensName, addressLength))
        {
            try
            {
                if (!isSynced()) //ensure node is synced
                {
                    throw new EnsResolutionException("Node is not currently synced");
                }
```

The ```isSynced()``` call checks the blocktime against the phone's current time, and if the phone's current time is not correct it can result in ENS not working (which is correct as it's picking up a possible attack).

If this error is thrown, the user should be warned that the node doesn't appear to be synced but that it may be the phone's time is not synced (the most likely cause).

```ENS Lookup Warning```
```AlphaWallet has detected a discrepancy between ethereum's timestamp and your device's current time, or possibly the blockchain connection is not synchronized, please check your phone's time is correct, or ignore this warning.```

The dialog should have 'Cancel' as the main action, and 'Ignore' for the secondary.

If Ignore is chosen, re-run the ENS call but disable the ```isSynced()``` check.

**Comment by asif-finimble** [comment]
@JamesSmartCell should we show the warning dialog in all screens that use ENSResolver or any specific screens?

**Comment by JamesSmartCell** [comment]
Good question - only need it in SendActivity for now

**Comment by JamesSmartCell** [comment]
But, if there's a way to do it cleanly from InputAddress, this is better
