### ISSUE TITLE
eth_call might have value specified. Include if it does. Otherwise tapping Buy in OpenSea with non-zero eth will fail because an eth_call with value is made to estimate gas

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2549]
Refer to steps and explanation to reproduce in PR: https://github.com/AlphaWallet/alpha-wallet-ios/pull/4303

Video in original issue: https://github.com/AlphaWallet/alpha-wallet-ios/issues/4299

**Comment by JamesSmartCell** [comment]
This works correctly; I recently 'purchased' an NFT from OpenSea Rinkeby for 1ETH using AW: https://rinkeby.etherscan.io/tx/0xf9c52d2889daeed10e88a2ffb8a80699a94045107d84e5b8229fbfd9a6ed7ece

**Comment by hboon** [comment]
Huh. Interesting. Didn't work when I tried with the last test build. I made sure to reimport my key (and tried signing elsewhere) to eliminate any issue with my keystore.

But just to be sure, it's OpenSea doing that additional `eth_call` prior to posting the transaction to figure out the gas limit. That `eth_call` is the one we need to includes the `value` if the dapp provides it. Could you help verify it's included? Otherwise I'll would test again on my side to be sure too.

(the code snippet above looks like it's path of the 2nd step: posting the actual transaction)

**Comment by hboon** [comment]
@JamesSmartCell If I try to buy https://testnets.opensea.io/assets/0x35e294961973be5c2fea8cbbaa3e4ac9d43410c3/0, I see:

<img width='200' src='https://user-images.githubusercontent.com/56189/163098428-dd5b4e2e-ee74-47cc-bfc5-117c00dc3f2b.jpg'>

**Comment by JamesSmartCell** [comment]
Yes, this issue has been fixed (I presume you're using WalletConnect) - can you try the build I sent to you.

**Comment by hboon** [comment]
It's not WalletConnect, I'm using the dapp browser

**Comment by JamesSmartCell** [comment]
Ok it's not working --- the bug stands! It's been fixed in WalletConnect

**Comment by JamesSmartCell** [comment]
Fixed by [7c98bcd2beba952b5767ce7162cc9a9ec2ebef49](https://github.com/AlphaWallet/alpha-wallet-android/tree/7c98bcd2beba952b5767ce7162cc9a9ec2ebef49) - sorry for the direct commit point I committed straight to master by accident!
