### ISSUE TITLE
The landing page should assume the contract is ERC875 if the contract's behaviour isn't defined

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#255]
A page like this, created by the token factory, should work:

https://app.awallet.io/AAAAAFtD3qixNWJA9F9SnRqDC9JeeRK-WR8iHxJcZXwXyjl6KT62vHtfvsUU1_HcgcOZPpB1jFXfrh_FDTzPDbkFWHvM9HLZxxYk6EKAEFptCdPTvAQ7CCYtgouXHA==

the MagicLink is generated by AlphaWallet. Currently only 875 token can get MagicLink from AlphaWallet. The landing page is opened through a MagicLink.

**Comment by James-Sangalli** [comment]
@colourful-land bump

**Comment by colourful-land** [comment]
I'll check `dmz`'s behaviour for this.

**Comment by James-Sangalli** [comment]
Working now
