### ISSUE TITLE
Limit decimals of % to just two numbers after dot

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2553]
so for example we have **+ 0.008%** now 
let's limit to just two numbers so it will be **+ 0.01%**

Is there a reason why we have non-standard 3 letters there?
![2022-04-14 08 10 22](https://user-images.githubusercontent.com/51817359/163325058-39bb9c60-78f9-4b34-80c9-a286ffbd4da6.jpg)

**Comment by hboon** [comment]
@JamesSmartCell And crypto amounts should be 4 decimals, not 5. I can file a different issue if it's more appropriate.
