### ISSUE TITLE
APP crashes/ stops, if the User play around the APP while the Transaction is in pending state. Video with Voice attached below. 

### ISSUE THREAD

**Issue by aflahzake** [AlphaWallet/alpha-wallet-android#2562]
Video below. When the user sends balance to any other address & during the transaction if the user play around the app. The APP crashes/ stops.

https://user-images.githubusercontent.com/101316605/163765289-2a20fafc-eca5-4c3d-bd75-90ed6e74b20a.mp4

**Comment by JamesSmartCell** [comment]
Nice catch, thanks
