### ISSUE TITLE
ether scan reset my pass alone and now my password change confirmation is not going to my email even though it says ít is

### ISSUE THREAD

**Issue by docb12** [AlphaWallet/alpha-wallet-android#2578]

**Comment by JamesSmartCell** [comment]
@docb12 could you provide more information? Is this related to AlphaWallet or Etherscan?

We don't have any passwords or emails tied to accounts, the keys are held locally by the wallet on your phone and we have no access.

You probably want to contact Etherscan about this.

**Comment by docb12** [comment]
ether scan makes it possible to link live wallet to web why so hard to verify with all my codes and seeds this is bbull

**Comment by JamesSmartCell** [comment]
> ether scan makes it possible to link live wallet to web why so hard to verify with all my codes and seeds this is bbull

Yes, via Walletconnect. We use it often. Can you say what is the issue? What is the code which you're referring to (don't post it here or anywhere else)? Is this your private key? You can import that into AlphaWallet, then use it with Etherscan via Walletconnet, just follow the prompts.

**Comment by JamesSmartCell** [comment]
Closing issue as it's unclear if it's relevant.
