### ISSUE TITLE
Implement Swap using LI.FI's API

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2581]
LI.FI's APIs support both same-chain swap and multi-chain bridging. We are only implementing same-chain swap for now.

API usage is quite simple. First 3 steps involves the LI.FI API:

1. "Fetch Chains" — get supported chains. Use this to limit which chains the user can choose in the swap UI
2. "Fetch Tokens" — get supported swap "pairs" for selected chain. We can use this to populate the "to" tokens based on user's selection of the "from" token
3. "Swap" — fetch the transaction (in li.fi terminology the "quote") that will perform the swap functionality
4. Prior to swapping, we'll need to check if an ERC20 approval is needed and prompt the user
5. Post the transaction from (3)

Fetch chains
---
```
curl --url 'https://li.quest/v1/chains' --header 'Accept: application/json' --header 'Content-Type: application/json' | json_pp
```

Fetch Tokens
---
```
curl --url 'https://li.quest/v1/connections?fromChain=1&toChain=1' --header 'Accept: application/json' --header 'Content-Type: application/json' | json_pp
```

Swap (actually get the "quote")
---
```
curl --request GET --url 'https://li.quest/v1/quote?fromChain=137&toChain=137&fromToken=0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619&toToken=0x0000000000000000000000000000000000000000&fromAddress=0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362&fromAmount=1000000000000000&order=BEST_VALUE&slippage=0.05' --header 'Accept: application/json' | json_pp
```

The quote API returns 503 sometimes. Just drop or retry.

If the `from` amount is too small, this error might be returned:

```
"message": "Unable to find a quote for the requested transfer."
```

Docs
---
The API docs are at https://apidocs.li.finance/reference/welcome-to-the-lifinance-api

The JavaScript SDK examples are easy to read to understand how to use the APIs https://apidocs.li.finance/reference/how-to-transfer-tokens

Others
---
Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/3919#issue-1138520205 for UI design. Buzz Tomek if an Android version is needed.

iOS might not be implementing the GUI for fees, etc at the moment

**Comment by JamesSmartCell** [comment]
@justindg can you implement this as a new ActionSheet style interface (make up a name, it might be obvious what to call it later) - with a new interface different from ActionSheet since it doesn't sign anything.

Can you implement the view elements as widgets where it makes sense as this keeps the code a bit more modular and removes interdependencies which end up getting too complicated.
