### ISSUE TITLE
Use correct/updated tokens.json file

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2583]
Context: https://github.com/AlphaWallet/alpha-wallet-ios/issues/3546#issuecomment-1112302008

Android seems to be using the original file which includes a much longer list of tokens, many of which are mapped wrongly. Should use the filtered list instead. The updated one is included in this PR: https://github.com/AlphaWallet/alpha-wallet-ios/pull/4470/files

**Comment by JamesSmartCell** [comment]
Thanks, updated https://github.com/AlphaWallet/TokenTest, which will be removed once the managed list is ready for use.
