### ISSUE TITLE
Constant email notification request every the App opens (Android)

### ISSUE THREAD

**Issue by BastianAlpha** [AlphaWallet/alpha-wallet-android#2588]
the email notification request every time i am opening AlphaWallet ever since the last update. (Android)

![image](https://user-images.githubusercontent.com/91123102/166195021-fee970fe-d1dd-4352-a3fa-4fb2e1d567de.png)

**Comment by colourfreak** [comment]
@hboon @JamesSmartCell How many emails we have collected so far?

**Comment by hboon** [comment]
Answered privately. (for James' benefit)

**Comment by colourfreak** [comment]
> Answered privately. (for James' benefit)

Where can I look for this? Discord?

**Comment by hboon** [comment]
Yes, I Dm-ed you on Discord.

**Comment by JamesSmartCell** [comment]
@asif-finimble can you look into what might cause this pop-up to keep coming back even if user dismisses it?

**Comment by hboon** [comment]
If it's not too clear why, better to disable it and hotfix first.

**Comment by asif-finimble** [comment]
> @asif-finimble can you look into what might cause this pop-up to keep coming back even if user dismisses it?

sure.

**Comment by asif-finimble** [comment]
@JamesSmartCell the issue was caused due to "launchCount" not being incremented in new update, because we increment launchCount in Splash screen. Now in new update, SplashScreen is not the first screen which is called instead its the HomeScreen. And the homescreen will show Splash screen if its first start of app. Fixed it by moving the launchCount increment to HomeScreen.

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell the issue was caused due to "launchCount" not being incremented in new update, because we increment launchCount in Splash screen. Now in new update, SplashScreen is not the first screen which is called instead its the HomeScreen. And the homescreen will show Splash screen if its first start of app. Fixed it by moving the launchCount increment to HomeScreen.

Ah! Yeah after we switched HomeActivity to be the starting activity.
