### ISSUE TITLE
Can't add Contract Addresses of the Heco Network

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-android#2589]
Android app {version 3.54.0 (186)} doesn't allow add manually contract addresses of the Heco Network.

The contract address in test is HBTC: 0x66a79D23E58475D2738179Ca52cd0b41d73f0BEa

**Comment by JamesSmartCell** [comment]
Thanks I'll check it.

**Comment by Hoanib** [comment]
👍🙏
