### ISSUE TITLE
Add node checks in the 'Select Active Networks' Activity

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2601]
Add an extra menu icon to the left of the (+) so that appears like (new icon) (+) that opens a new activity that tests the network status of the nodes.

Use this initially for the icon, we can replace later:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
<g><g transform="translate(0.000000,511.000000) scale(0.100000,-0.100000)"><path d="M8550.8,5092.8c-213.5-36-445-146.1-606.9-292.2c-406.8-366.4-507.9-955.3-245-1445.2l65.2-121.4l-696.8-699l-696.8-696.8l-128.1,71.9c-494.5,269.7-1065.4,263-1544.1-20.2l-155.1-89.9l-490,490L3561,2782.2l58.4,143.8c51.7,130.4,58.4,168.6,49.4,359.6c-6.7,179.8-20.2,238.3-74.2,350.6c-83.2,170.8-254,343.9-427.1,429.3c-123.6,60.7-155.1,65.2-382.1,65.2c-233.8,0-256.2-4.5-393.3-71.9c-481-236-658.6-820.4-391.1-1278.9c78.7-132.6,258.5-294.5,409.1-364.1c112.4-53.9,155.1-60.7,364.1-60.7c200,0,254,9,355.1,53.9l121.4,53.9l492.2-492.2l492.2-492.2l-101.1-202.3c-56.2-112.4-119.1-276.5-141.6-366.4l-36-161.8l-762,4.5l-759.7,6.7l-49.4,146.1c-236,696.8-984.5,1006.9-1654.3,683.3c-164.1-80.9-424.8-339.4-503.5-503.5C-102.7,397.5,232.2-373.5,951.5-587c139.4-40.5,454-47.2,609.1-11.2c364.1,83.1,692.3,386.6,822.6,759.7l51.7,148.3l766.5,6.7c600.1,4.5,766.4,0,773.2-22.5c125.9-424.8,206.8-570.9,440.5-804.6c193.3-193.3,431.6-328.2,692.3-395.6l161.8-40.5v-802.4v-802.4l-103.4-24.7c-179.8-45-373.1-159.6-517-303.4c-570.9-573.2-413.6-1521.6,312.4-1879c748.5-366.4,1586.9,103.4,1688,946.3c62.9,510.2-301.2,1056.4-811.4,1222.7l-119.1,38.2v806.9v806.9l62.9,13.5c312.4,69.7,561.9,204.5,791.2,436.1c294.4,294.4,436.1,642.8,436.1,1067.6c0,332.7-76.4,593.4-258.5,856.4l-63,92.1l705.8,703.5c692.3,692.3,705.8,703.5,757.5,669.8c105.6-67.4,321.4-132.6,487.8-146.1c926-67.4,1557.6,908.1,1119.3,1732.9c-96.6,184.3-310.2,393.3-490,483.2C9047.5,5079.3,8759.8,5128.8,8550.8,5092.8z M5766,1611.2c314.7-94.4,550.6-292.2,687.8-584.4c74.2-155.1,83.2-195.5,92.1-400.1c6.7-191.1,2.3-249.5-40.5-373.1c-121.4-361.9-409.1-629.3-773.2-721.5c-62.9-15.7-188.8-22.5-316.9-15.7c-182.1,9-233.8,22.5-382.1,92.1c-472,224.8-714.7,739.5-584.4,1240.7c96.6,364.1,393.3,665.3,755.2,762C5368.1,1656.1,5615.4,1656.1,5766,1611.2z"/></g></g>
</svg>
```

The Activity would list all the nodes, main-net then testnet, would appear very similar to the 'Select Active Networks' dialog, without the hamburger edit menu and the checkbox on the right. Instead of the checkbox we want a node status icon, green, yellow or red:

Use this page for inspiration:

https://chainlist.org/
and
https://rpclist.info/ 

It looks like they use green for under 1 second, yellow for over 1 second, and red for not responding.

No need to add the latency figures.

You could perform the check by pinging for the client version like this:

```
        final Web3j web3j = TokenRepository.getWeb3jService(chainId);
        try
        {
            Web3ClientVersion web3ClientVersion = mWeb3.web3ClientVersion().sendAsync().get();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
```

Or it might be more applicable in this case to simply call directly:

```
    NetworkInfo networkInfo = networkInteract.getNetworkInfo(chainId);
    MediaType mediaType = MediaType.parse("application/json");
    RequestBody body = RequestBody.create(mediaType, "{\"jsonrpc\":\"2.0\",\"method\":\"web3_clientVersion\",\"params\":[],\"id\":1}");
    Request request = new Request.Builder()
     .url(networkInfo.rpcServerUrl)
     .method("POST", body)
     .addHeader("Content-Type", "application/json")
     .build();
    Response response = client.newCall(request).execute();
```

This would be a great sanity check for all our node status. We can also point devs who fork our wallet to this, so they can check their node status.

We can expand on it later.

This is in response to this issue: https://github.com/AlphaWallet/alpha-wallet-android/issues/2589 which is a result of Huobi changing the RPC for their main-net. Having a dialog like this would be useful for our testing and also for devs who are forking our wallet.

Also check the ```backupNodeUrl``` endpoint if it's present. Check the Primary RPC first, then check the backup nodes. Backup node can be displayed alongside the Primary node result.

There's no spec for this yet, but I think it's critical to have on a multi-chain wallet.

**Comment by colourfreak** [comment]
@JamesSmartCell Can we work on the design here?

<img width="914" alt="Screen Shot 2022-06-06 at 15 00 50" src="https://user-images.githubusercontent.com/51817359/172165833-0f6b9ce8-289d-41cc-bb4f-e240333a235a.png">

- Add status icons with smiles (for color blindness)
- We add a Question mark that prompts the explainer
- We could add one more item inside the Settings tab (maybe Advanced) as I prefer to avoid going deeper inside Select Active Networks screen - but

**Comment by colourfreak** [comment]
https://zpl.io/Dl6nZrO
https://zpl.io/p1zBAYo
https://zpl.io/251gOEW

**Comment by JamesSmartCell** [comment]
Nice, yes this makes it easier to read.

@colourfreak the icon I used might need replacing too; I used one that seemed to fit.
