### ISSUE TITLE
Wallet Connect Is Not Working Properly

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-android#2604]
One of my jobs is to check how AW interacts with dApps and Wallet Connect is making it very difficult for me. The currently dApp on testing is https://app.symbiosis.finance/swap and although I can say that on iOS it runs smoothly without issues at all, on Android it doesn't. Of course I had to do some tricks to be able to connect the dApp directly to AlphaWallet on iOS but those tricks have not worked for Android. And even if you manage to connect the dApp to AW the balances are not shown. If there aren't balances you can't perform transactions of any kind. 

One thing, when you access to Wallet Connect even your wallet is connected to Polygon Network (it's where I have assets for the testings) the dApp automatically will be connected to Ethereum Mainnet however you can switch to Polygon editing first the pop up approval. 

I also tried to connect the dApp through the Trust Wallet, Onto and Coin98 direct connections but even if you manage connect your wallet, you will not see your balances...

**Comment by Devjohn12** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by JamesSmartCell** [comment]
Thanks, I have noticed that many dapps aren't driving the WalletConnect API correctly with regards to ChainID. 

However, like you say, if you're in the dapp browser and connect to WC directly it should copy the current ChainID.

Can you say what the 'tricks' to connect on WC in iOS are? I will try to get those working on Android.

Also, if you have an existing example of dapp which connects easily on iOS but is problematic on Android that would also be helpful.

The dapp here: https://app.symbiosis.finance/swap does that illustrate the current problems?

**Comment by Hoanib** [comment]
Yes, Simbiosis dApp is the best example. This dApp doesn't work properly being connected through Wallet Connect on iOS too. However doing this little trick it works well: just connect the dApp trough Wallet Connect then disconnect the Wallet Connect approval for that dApp, do a hard refresh or reload the page, or close/open AW app. The dApp would be connected through Web 3. Having said that it only works using AW in-browser.

**Comment by justindg** [comment]
Tested with the current version of the app, and can confirm WalletConnect is working.
