### ISSUE TITLE
La Prairie NFT title not showing

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2621]
**In the list, see the last one:**
![Screenshot_20220525_100505_io stormbird wallet](https://user-images.githubusercontent.com/735708/170165953-86297637-51bf-43bf-b606-b9dfa62ce798.jpg)

**Click to view the detail:**
![image](https://user-images.githubusercontent.com/735708/170166054-02ee70ee-b8eb-4c8c-abaa-fc4e506abb9f.png)

Test wallet, watch `gtd.eth`.

**Comment by hboon** [comment]
@seabornlee would you help paste the contract? Easier to discover :)

**Comment by JamesSmartCell** [comment]
Removed the bug label because it's not actually a bug, the wallet is working correctly; there's no name() for the token (see etherscan).

The real solution is to check if the contract has metadata, and if so use the contract metadata name.

**Comment by seabornlee** [comment]
> @seabornlee would you help paste (粘贴) the contract? Easier to discover :)

0x28d5B2E6f30A9b54DCBE8792543fB0232F4f3658
