### ISSUE TITLE
DeFi & Goverance tabs are empty

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2622]
![image](https://user-images.githubusercontent.com/735708/170166479-fdb39e05-2794-43be-b99f-ebce7875b2b3.png)

![image](https://user-images.githubusercontent.com/735708/170166492-ae351627-0fa7-4ff2-841a-cdba245062e9.png)

**Comment by JamesSmartCell** [comment]
Yes ... this is expected if you don't have any defi or governance tokens.

Previously we used a rich tokenlist but I think we removed all the governance and defi markers from the list, due to there being some that may not be accurate.

@hboon do you know if there's a further update to the list we can use that has restored the data?

**Comment by hboon** [comment]
@JamesSmartCell use the copy mentioned in https://canary.discord.com/channels/548357107267928064/978834485598629898/978843163634569286. I'll always remember to buzz you guys when there's an update for this (or when the repo is finally in sync).

**Comment by hboon** [comment]
The actual link mentioned in that Discord link above (pasted that for context), but actual link to tokens.json:

https://github.com/AlphaWallet/alpha-wallet-ios/blob/18d98f9b929ceffc52218d580c152fe25a9a4426/AlphaWallet/Tokens/JSON/tokens.json#L14

**Comment by JamesSmartCell** [comment]
> The actual link mentioned in that Discord link above (pasted that for context), but actual link to tokens.json:
> 
> https://github.com/AlphaWallet/alpha-wallet-ios/blob/18d98f9b929ceffc52218d580c152fe25a9a4426/AlphaWallet/Tokens/JSON/tokens.json#L14

Thanks :) yeah this is definitely different from the cut-down one which we currently are shipping with.

**Comment by colourfreak** [comment]
> Yes ... this is expected if you don't have any defi or governance tokens.
> 
> Previously we used a rich tokenlist but I think we removed all the governance and defi markers from the list, due to there being some that may not be accurate.
> 
> @hboon do you know if there's a further update to the list we can use that has restored the data?

Note that it was great before on Android and it was bad on iOS. Now, both platforms unified bad solution.

**Comment by colourfreak** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/3546#issuecomment-1112154035
