### ISSUE TITLE
Remove mutually exclusive mainnet and testnet modes so testnets can be selected once they are enabled

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2631]
**Zeplin:**
https://zpl.io/5E6NR33

**Changes:**

- Change the headline to "Select Active Networks"
- Update the network icons https://zpl.io/2ZAKYQX
- When you toggle Testnet on, you will see a warning about the Monopoly money
- When you hit OK on the warning screen, the list of networks expands by testnet networks
- We cancel Testnet mode where you only see Mainnet or Testnet at a time. They can be both displayed, so we are coming back to the same flow as previously
- At the bottom of the list you have a Browse More button, it takes you to the same screen as plus button at the top - browse all other networks
- Add placeholder network icons for all remaining networks - 

**Prototype:**
https://invis.io/MW1220T36ET3

**Comment by colourfreak** [comment]
https://user-images.githubusercontent.com/51817359/170235287-63bf1a64-60bf-4e31-9d8a-40fb85245765.mov

**Comment by hboon** [comment]
Let’s hold off doing this. Cutting down unnecessary work in phase 1

**Comment by justindg** [comment]
Resolved via #3052
