### ISSUE TITLE
stage.attestation.id in the AW internal browser

### ISSUE THREAD

**Issue by oleggrib** [AlphaWallet/alpha-wallet-android#2632]
I am trying to create attestation with http://stage.attestation.id/ using AlphaWallet internal browser.

I discovered that background is dark somehow, but in Metamask and Chrome it looks correct. Maybe its because of dark theme?

AlphaWallet:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/18176173/171051257-a9acaf2c-1aa2-46a1-8c4e-02fbd910b66d.png">

Chrome Devtools Mobile View:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/18176173/171051735-087e8cf0-bfa9-478c-bc10-4820737b7cb6.png">

AlphaWallet:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/18176173/171051309-c77c3308-c759-49e5-bb41-3fb7c22aa7e8.png">

And another issue: it breaks when I try to connect ti the wallet with walletconnect.
@JamesSmartCell , can you help me to use AW correctly?

**Comment by micwallace** [comment]
This issue stems from com/alphawallet/app/web3/Web3View.java:236:

`/WebSettingsCompat.setForceDark(getSettings(), FORCE_DARK_ON);`

**Comment by oleggrib** [comment]
> This issue stems from com/alphawallet/app/web3/Web3View.java:236:
> 
> `WebSettingsCompat.setForceDark(getSettings(), FORCE_DARK_ON);`

great finding. is any option to update this seting from the browser? @JamesSmartCell

**Comment by micwallace** [comment]
No unfortunately it's hardcoded into the webview settings. I think it should probably be removed, as I suspect it would cause issues with a lot of websites. But let's wait until James is back to confirm its ok.

**Comment by hboon** [comment]
Bump @justindg in case it's a bug.

**Comment by justindg** [comment]
Will remove webview dark mode for now. It will cause high contrast for most websites, maybe let's revisit in the future.

**Comment by oleggrib** [comment]
@JamesSmartCell , can you tell me when new wallet version will be deployed, so we can make sure it works good?
