### ISSUE TITLE
Change font family to Circular Std

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2637]
I have just updated all screens with a new font. I am going to check if we need a license for this font (paid).
[Circular.zip](https://github.com/AlphaWallet/alpha-wallet-android/files/8831924/Circular.zip)

**Comment by hboon** [comment]
Since we aren't going with Circular Std, we should either confirm that we switch to another font or revert to Source Sans Pro. Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/4741#issuecomment-1159621515

**Comment by hboon** [comment]
@justindg remember, no matter whether we ship with a new font (or revert to Source Sans Pro), we can't commit Circular to `master` on GitHub due to licensing.

**Comment by hboon** [comment]
@justindg let's revert/stick to Sources Sans Pro for now.

**Comment by hboon** [comment]
> @justindg let's revert/stick to Sources Sans Pro for now.

This done yet?

**Comment by justindg** [comment]
> > @justindg let's revert/stick to Sources Sans Pro for now.
> 
> This done yet?

Yes it has been reverted long ako👌

**Comment by hboon** [comment]
Thanks!
