### ISSUE TITLE
Make one version of the app without gray lines

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2638]
I recently removed almost all gray separators. You can check in Zeplin. 

Removed on:
- Activity
- Wallet
- Settings
- Transactions (send erc20, send erc1155, send erc721)
- ERC20 tokens
- ERC721 & ERC1155 tokens

You can keep it for action sheets.
<img width="782" alt="Screen Shot 2022-06-03 at 13 31 17" src="https://user-images.githubusercontent.com/51817359/171845767-74bd1c53-5450-458a-92bd-598df3ab8729.png">
<img width="662" alt="Screen Shot 2022-06-03 at 13 31 34" src="https://user-images.githubusercontent.com/51817359/171845770-3362bbf1-9f51-4b5c-96cd-e53ce4e91cb3.png">
<img width="712" alt="Screen Shot 2022-06-03 at 13 31 48" src="https://user-images.githubusercontent.com/51817359/171845773-8194859b-2682-4400-ab2f-ce48f5cba5f2.png">
<img width="704" alt="Screen Shot 2022-06-03 at 13 31 03" src="https://user-images.githubusercontent.com/51817359/171845756-9370bbc2-8423-4cc2-80aa-3c2f92f9694b.png">

**Comment by justindg** [comment]
@seabornlee do you want me to work on this issue?

**Comment by hboon** [comment]
Out of phase 1
