### ISSUE TITLE
Improve the design of Backup warning 

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2639]
https://zpl.io/VD0lGAJ
https://zpl.io/3X6v68N

**Back up Your Wallet**
You have not backed up your wallet yet.
Your funds are at risk. Act now.

(Back up Now)

<img width="943" alt="Screen Shot 2022-06-03 at 14 14 49" src="https://user-images.githubusercontent.com/51817359/171851542-67f486ae-93b7-45b3-84ae-a5e78c321f22.png">

**Comment by hboon** [comment]
Out of phase 1
