### ISSUE TITLE
Update segmented controls tabs with the new design

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#2647]
You can get inspired with [Google Travel ](https://www.google.com/travel/)

So the blue selection indicator has rounded corners on the top part.
<img width="646" alt="Screen Shot 2022-06-06 at 14 08 46" src="https://user-images.githubusercontent.com/51817359/172158188-1f1ce80d-4a23-43b7-9346-26d42a24e359.png">
<img width="575" alt="Screen Shot 2022-06-06 at 14 08 54" src="https://user-images.githubusercontent.com/51817359/172158198-255e4062-4661-492f-b338-1e744843e545.png">
<img width="559" alt="Screen Shot 2022-06-06 at 14 08 57" src="https://user-images.githubusercontent.com/51817359/172158202-0a3be957-571d-4267-b41d-55758dfa8751.png">
j
<img width="537" alt="Screen Shot 2022-06-06 at 14 09 02" src="https://user-images.githubusercontent.com/51817359/172158206-446954f2-5ab3-4d67-a4c5-bcdb50ab764f.png">
<img width="768" alt="Screen Shot 2022-06-06 at 14 09 34" src="https://user-images.githubusercontent.com/51817359/172158210-e3254bfe-4655-46ef-9e38-d29d81ba18e0.png">
j

**Zeplin:**
https://zpl.io/z89WxGM
https://zpl.io/9q6Zd8z
https://zpl.io/Em6A8Zl

**Comment by hboon** [comment]
Out of phase 1
