### ISSUE TITLE
BINANCE_TEST_ID and  BINANCE_MAIN_ID is reversed in EthereumNetworkBase

### ISSUE THREAD

**Issue by xinyou-app** [AlphaWallet/alpha-wallet-android#2651]
the code line 113 to 116 in /master/lib/src/main/java/com/alphawallet/ethereum)/EthereumNetworkBase.java
BINANCE_TEST_ID and  BINANCE_MAIN_ID is reversed
is the will effect BINANCE Token?

put(BINANCE_TEST_ID, new NetworkInfo("BSC TestNet (Test)", "T-BSC", BINANCE_TEST_RPC_URL, "https://explorer.binance.org/smart-testnet/tx/",
                    BINANCE_MAIN_ID, false));
            put(BINANCE_MAIN_ID, new NetworkInfo("Binance (BSC)", "BSC", BINANCE_MAIN_RPC_URL, "https://explorer.binance.org/smart/tx/",
                    BINANCE_TEST_ID, false));

**Comment by JamesSmartCell** [comment]
```public static final long BINANCE_TEST_ID = 97;```
```public static final long BINANCE_MAIN_ID = 56;```

Checking on chainlists.org:

Mainnet ID is 56, and testnet is 97.

Are you concerned about the order they are added in? Since it's a Java Map, it doesn't matter. The display order is controlled from a list above, see:

```private static final List<Long> hasValue```

**Comment by seabornlee** [comment]
@JamesSmartCell See the parameter passed to new NetworkInfo() constructor, the chainId is wrong.
