### ISSUE TITLE
Can not show seed phrase

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2659]
v3.56.7

1. Open Android app
2. Create new wallet
3. Goto `Settings` -> `Show Seed Phrase`
4. Input phone password

Expected:
I can see seed phrase.

Actual:
Back to `Settings` page.

**Comment by JamesSmartCell** [comment]
As a note, I was not able to reproduce this with v3.56.7 (it works correctly as expected).

**Comment by JamesSmartCell** [comment]
@seabornlee is this affecting PIN unlock only? If so we should update this issue to reflect this?
