### ISSUE TITLE
Mode Testnet Shows Balance Erroneously on Summary

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-android#2666]
Being on mode Testnet the app shows the summary balance of Mainnet. Also you can see that the app does not make a difference between Mainnet and Testnet as iOS does on the Wallets section. 

Android: 
![image](https://user-images.githubusercontent.com/100842739/174415607-af3dedcd-d5e0-4d38-953a-c65dcdd08213.jpeg)

iOS:
![image](https://user-images.githubusercontent.com/100842739/174415772-a5d2b3c7-74ec-4f20-a97b-b186dc4079f1.png)

**Comment by seabornlee** [comment]
@Hoanib Thanks for open this, very helpful

**Comment by Hoanib** [comment]
You are welcome @seabornlee

**Comment by seabornlee** [comment]
@Hoanib Will be included in the next release. Thanks again!

**Comment by Hoanib** [comment]
Glad to hear that! @seabornlee
