### ISSUE TITLE
Deeplink-based wallet API

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2668]
Deeplink-based wallet API

This is analogous to offering an WalletConnect SDK that other (client) apps can implement to sign messages with AlphaWallet. For ByteBrew to implement and sign messages in their (client) apps (games actually). We do not need to sign transactions at the moment.

Refer to:

* For context and UI design: https://github.com/AlphaWallet/alpha-wallet-ios/issues/4659
* For the final word on the API (parameters etc. The issue above might be outdated): https://www.notion.so/stormbirdlabs/Deep-link-based-wallet-SDK-3a8a124b54754452b9623615a8ac8e2b
* iOS PR for more context/gotchas: https://github.com/AlphaWallet/alpha-wallet-ios/pull/4829
* Test links: https://wallet-deeplink-api.hboon.repl.co

**Comment by hboon** [comment]
Or @seabornlee @justindg, if you folks can sort out who/how to implement it before James is active

**Comment by justindg** [comment]
I'll do it

**Comment by hboon** [comment]
Forgot to mention a page with test link (have edited the first comment to include it)
