### ISSUE TITLE
Display PHI NETWORK Price

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-android#2670]
Need To set up Price API For PHI Network API Can Be found here https://phiswap-api.herokuapp.com/api/ticker?filter=WPHI 

pulls data from subgraph https://graph.phiswap.com/subgraphs/name/exchange/graphql

from these analytics https://info.phiswap.com 

Thanks

**Comment by JamesSmartCell** [comment]
Hi @Phinetwork can you direct us to a consumable API feed for the token prices? The heroku above is offline.

**Comment by Phinetwork** [comment]
Yes thanks for letting me know it did work checking with dev of api. I'm getting one for you. Sorry about that. I'll have a consumable api for you within the next day or two.

**Comment by Phinetwork** [comment]
hello update 

https://phiswap-api.herokuapp.com/api/ticker?filter=WPHI this is currently online and working 

and will also be live shortly at https://price.phi.network/api/ticker?filter=WPHI

**Comment by Phinetwork** [comment]
@JamesSmartCell are we able to get this done for next update?

**Comment by Phinetwork** [comment]
Are we working on this @JamesSmartCell

**Comment by Phinetwork** [comment]
How's this going @JamesSmartCell @hboon
