### ISSUE TITLE
Cant connect WalletConnect through Alphawallet to the Rinkeby(Android)

### ISSUE THREAD

**Issue by oleggrib** [AlphaWallet/alpha-wallet-android#2693]
Steps to reproduce:
1. Open https://rinkeby.etherscan.io/token/0x3f9b11E2877Cb7411c2bA2401b3ef099dE6eeceB?a=369862206488372798118489#writeContract
2. Click "Connect to Web3"
3. Select WalletConnect
4. Open Alphawallet Android, allow network Rinkeby only
5. Scan rinkeby.etherscan.io QR code
6. Alphawallet will ask you to connect to the Ethereum(mainnet)
7. You can click "Edit", will see that only Rinkeby in the list
8. Click Back
9. Ethereum replaced with Rinkeby
10. Click "Aprove" and nothin happens, popup still visible.
11. When you close popup then WalletConnect disconnected

**Comment by JamesSmartCell** [comment]
Hi @oleggrib It's still connected (online) when you close the popup, but yes that seems to be a new issue.
