### ISSUE TITLE
Android hangs when scanning a non-wallet-connect qr code

### ISSUE THREAD

**Issue by weiwu-zhang** [AlphaWallet/alpha-wallet-android#2695]
1. Go to scan QR code in Android
2. Scan this: ![image](https://user-images.githubusercontent.com/548435/176839213-6182890e-e289-40e9-a546-9ce56e0c94b3.png)
3. The Android app hangs.

Expected:

3. The android app flashes red or shows some text to let users know it doesn't recognise this type of QR code.

**Comment by JamesSmartCell** [comment]
@seabornlee if you tackle this one, it looks like it needs a token scan timeout.
