### ISSUE TITLE
Remove manual sorting functionality in "Add / Hide Tokens" screen

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-android#2709]
Ref: https://github.com/AlphaWallet/alpha-wallet-ios/issues/4948#issuecomment-1178541658

**Comment by seabornlee** [comment]
@justindg Do you want to take this?

**Comment by JamesSmartCell** [comment]
I don't believe there's any sorting ability for Add/Hide Tokens.

Can be closed.
