### ISSUE TITLE
PHI Network Gas Price is Too High

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-android#2711]
Gas price for PHI Network at most needs to be 2000 Wei it is currently defaulting at 1gwei and this is far too expensive for chains tokenomics. Can we please adjust the gas fees to be 2000 Wei on phi chain and not 1 gwei thank you @JamesSmartCell @hboon

**Comment by Phinetwork** [comment]
Any update on this? @JamesSmartCell 🙏

**Comment by JamesSmartCell** [comment]
On it

**Comment by Phinetwork** [comment]
Thank you 🙏

**Comment by Phinetwork** [comment]
> On it

How it's going @JamesSmartCell do you think this will be ready before next update?
