### ISSUE TITLE
Remove the permission or declare

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2718]
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/735708/178229189-87b6347b-8b10-4d92-b11e-743b7f4dcd98.png">

@JamesSmartCell Has the auto updating feature been outdated?
The url https://1x.alphawallet.com/dl/latest.apk is 404 now.

**Comment by JamesSmartCell** [comment]
I think this is to allow auto-update if you installed from the website. It's OK to lose this feature, although it will be inconvenient for some. We don't know how many people are using AW in China because we can't include analytics.

Let's see if we can get it though.

**Comment by seabornlee** [comment]
Can we get the download click event from the website Google Analytics?
And put this feature in noAnalytics flavor.

**Comment by seabornlee** [comment]
> Not sure --- I understand it's not advisable to have any usage of Google Analytics API in an app installed on a phone running a China build of Android (安卓) OS. Perhaps you would know a lot more about this than any of us though?

I mean add GA to the website, then we know how many users download app from our official website.
