### ISSUE TITLE
Add option to delete WalletConnect history

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2722]
Settings -> WalletConnect

Add a 'recycle bin' icon at top, when clicked have these options:

Delete Empty
Delete All
Cancel

If Delete Empty is called, delete all Historic Walletconnect sessions with no transaction or signing activity.
If Delete All is called - do that.

Don't delete any connection that's active.
Reset the view when deletion callback comes back (maybe try using the realm success callback like eg ```public void updateWalletItem(Wallet wallet, WalletItem item, Realm.Transaction.OnSuccess onSuccess)```

**Comment by asif-finimble** [comment]
How do we decide if a session has transaction/signing activity?
