### ISSUE TITLE
When we show the (list of) Wallets screen, it should automatically scroll to reveal the current wallet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2734]
Refer https://github.com/AlphaWallet/alpha-wallet-ios/issues/3649

**Comment by seabornlee** [comment]
@hboon How about just putting the current wallet on the top of the list?

**Comment by hboon** [comment]
I don't mind, but 2 reasons not to:

* might be confusing for users
* it wouldn't always be at the top because we have HD wallets, "raw primary key/traditional" wallets, watch-only wallets. Unless we move the sections around too

**Comment by seabornlee** [comment]
Got that, thanks for the clarification.
