### ISSUE TITLE
Error while switching networks in WalletConnect

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#2743]
Sharing feedback from one user.

> When switching networks in the Alphawallet: 1) Once you approve the transaction, the approve msg stays on the screen until you click the X to close it. Also, if you repeat the t4ransaction, the network defaults back the Ethereum and you have to change it back to the testnet once again. The asset does eventually drop in but the msg box stays.

![image](https://user-images.githubusercontent.com/61957841/180368494-504b60b6-fd5c-4e31-b5e0-097d64f9b0bb.png)

I also tested and was able to replicate:
https://www.loom.com/share/66909345cd4b4def83248692b4525cd1

**Comment by JamesSmartCell** [comment]
I'll pick this up since it's the legacy WC

**Comment by JamesSmartCell** [comment]
Could reproduce this with an old build but after the refactor it's fixed. I'll do another test.

**Comment by JamesSmartCell** [comment]
This has now been fixed.
