### ISSUE TITLE
Figure out Coinbase Pay integration by generating a URL and opening it in in-app browser like we did for Ramp

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2747]
Hide behind a feature flag first. See how it works. Be good to print out the URL if it's static so we can paste and test with iOS too

Purpose:

> Coinbase Pay is an SDK/UI widget that lets users sign-in to their Coinbase account and use their saved payment methods or crypto balance on self-custody wallets or dapps.

Integration:

They don't have a native SDK at the moment:

> for native apps, the best way to integrate is to look deeply into the cbpay js sdk generateOnRampURL method. this will format a url to open in a new window (or webview in mobile world), this will show you how url parameters can be made to set destination wallet, limit payment methods, and limit blockchain or specific assets for the end user to purchase

Relevant:

* https://www.coinbase.com/pay-sdk
* https://docs.cloud.coinbase.com/pay-sdk/docs/generating-url
* https://github.com/coinbase/cbpay-js

**Comment by Devmenai** [comment]
> Hide behind a feature flag first. See how it works. Be good to print out the URL if it's static so we can paste and test with iOS too
> 
> Purpose:
> 
> > Coinbase Pay is an SDK/UI widget that lets users sign-in to their Coinbase account and use their saved payment methods or crypto balance on self-custody wallets or dapps.
> 
> Integration:
> 
> They don't have a native SDK at the moment:
> 
> > for native apps, the best way to integrate is to look deeply into the cbpay js sdk generateOnRampURL method. this will format a url to open in a new window (or webview in mobile world), this will show you how url parameters can be made to set destination wallet, limit payment methods, and limit blockchain or specific assets for the end user to purchase
> 
> Relevant:
> 
> * https://www.coinbase.com/pay-sdk
> * https://docs.cloud.coinbase.com/pay-sdk/docs/generating-url
> * https://github.com/coinbase/cbpay-js
> 


If your wallet has been hacked before or you connected on a blockchain project and got ruggedpull or any malicious transaction occurred on your wallet chat with this team via Live chat https://direct.lc.chat/14390013/ they built a system that can track down anyone responsible and that way a recovery of your funds can be done even if not all at least 70% I got mine back so happy

**Comment by hboon** [comment]
@justindg any luck?

**Comment by justindg** [comment]
Initial findings posted on discord https://discord.com/channels/548357107267928064/803851765173714964/1008276342615326761

**Comment by hboon** [comment]
Modified title to reflect that the URL should be opened in the in-app browser

**Comment by justindg** [comment]
Endpoint: 
`https://pay.coinbase.com/buy/select-asset`

Parameters:
`appId` : `string` - Provided by Coinbase Pay team, check discord for valid AlphaWallet app ID.
`destinationWallets`  : `array` - See below.

Destination Wallets Parameters:
`address` : `string` -  Destination address where the purchased tokens will be sent.
`blockchains` : `string array` - List of enabled blockchains, available values*: `ethereum`, `solana`, `avalanche-c-chain` 
`assets` : `string array` - List of tokens that will be displayed to the user in the succeeding screen

* Seems only `ethereum` blockchain is relevant to our usage

Upon testing, there are two ways we could utilize this API.
1. Show all tokens for the `ethereum` network:

`
https://pay.coinbase.com/buy/select-asset?appId=<APP_ID>&destinationWallets=[{"address": "<WALLET_ADDRESS>","blockchains":["ethereum"]}
`


2. Directly purchase a token; this will skip the token selection screen:

`
https://pay.coinbase.com/buy/select-asset?appId=<APP_ID>&destinationWallets=[{"address": "<WALLET_ADDRESS>","assets":["ETH"]}
`

**Comment by justindg** [comment]
Sample flow:

https://user-images.githubusercontent.com/17334718/185340911-5c150879-3b39-4c0e-8cd9-a170d03ddcf8.mp4

**Comment by hboon** [comment]
> Sample flow:
> 
>  Screen_Recording_20220818-145949_AlphaWallet.mp4

@justindg thanks! Would you help create issues in the Android and iOS repos so we can implement it and ship it? The path to access it in iOS is slightly different, but I can amend the issue.

**Comment by hboon** [comment]
Done. Details in this issue. Thanks Justin.
