### ISSUE TITLE
Verify Klaytn + Covalent detecting of NFT token IDs is still correct

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2755]
A little different from what is described in https://github.com/AlphaWallet/alpha-wallet-ios/issues/4191:

> `ev.tokenID = logParams.values().iterator().next().valueBI.toString();`

It can be read from `tokenId` instead of `value` *and* this comment in the iOS PR https://github.com/AlphaWallet/alpha-wallet-ios/pull/5094/files#diff-5b743bac24c0d35ba865cb65b26472d247e6b6132c2d2360f9293bd6bd34c9daR160 :

```
//`tokenId`s in Covalent don't start with 0x, but `value`s does
```

**Comment by Devmenai** [comment]
> A little different from what is described in https://github.com/AlphaWallet/alpha-wallet-ios/issues/4191:
> 
> > `ev.tokenID = logParams.values().iterator().next().valueBI.toString();`
> 
> It can be read from `tokenId` instead of `value` *and* this comment in the iOS PR https://github.com/AlphaWallet/alpha-wallet-ios/pull/5094/files#diff-5b743bac24c0d35ba865cb65b26472d247e6b6132c2d2360f9293bd6bd34c9daR160 :
> 
> ```
> //`tokenId`s in Covalent don't start with 0x, but `value`s does
> ```


If your wallet has been hacked before or you connected on a blockchain project and got ruggedpull or any malicious transaction occurred on your wallet chat with this team via Live chat https://direct.lc.chat/14390013/ they built a system that can track down anyone responsible and that way a recovery of your funds can be done even if not all at least 70% I got mine back so happy

**Comment by JamesSmartCell** [comment]
Nice, thanks for spotting this, have seen some Klaytn NFT weirdness over the past couple of weeks but didn't investigate further.
