### ISSUE TITLE
Reverse resolution for 0x561b0145d8f5221995bc6a787d8d70db0604b7b8 should fail and not return ethereumfoundation.eth

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2759]
Because calling 0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e.resolver() with params [node]: 0x9188349584b7e1a147d72e1ca58e2952e8c560e1c4b679847824d8b1749c45cf results in 0x0

<img width='300' src='https://user-images.githubusercontent.com/56189/183843158-edb996e4-35d0-4223-a555-19dadea4afa2.png'>

It should however reverse resolve for these 2 addresses:

```
0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362
0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63
```

Compare https://etherscan.io/address/0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63 and https://etherscan.io/address/0x561b0145d8f5221995bc6a787d8d70db0604b7b8. The ENS shows up for the former only

But forward resolution for ethereumfoundation.eth should return 0x561b0145d8f5221995bc6a787d8d70db0604b7b8

**Comment by JamesSmartCell** [comment]
I think it's using a fallback system - it knows that ENS is associated with that address, and checks that ethereumfoundation.eth still resolves to 0x561b0145d8f5221995bc6a787d8d70db0604b7b8, if it does then it displays the address.

Technically, it's correct to do so - if you previously sent to that address, it notes that and performs the validation.

What reason would we *not* want to show this association, providing it's valid? I would like to see it because when I send eth I like as many validations I haven't made a mistake as possible.

**Comment by JamesSmartCell** [comment]
Could we show that it links to this address but doesn't resolve to it?

**Comment by hboon** [comment]
> Could we show that it links to this address but doesn't resolve to it?

I think if we want to show it (as it is now in Android), then just keep it that way.

> I think it's using a fallback system - it knows that ENS is associated with that address, and checks that ethereumfoundation.eth still resolves to 0x561b0145d8f5221995bc6a787d8d70db0604b7b8, if it does then it displays the address.
> Technically, it's correct to do so - if you previously sent to that address, it notes that and performs the validation.
> What reason would we not want to show this association, providing it's valid? I would like to see it because when I send eth I like as many validations I haven't made a mistake as possible.

Are we showing 0x561b0145d8f5221995bc6a787d8d70db0604b7b8 -> ethereumfoundation.eth because we have previously verified that ethereumfoundation.eth -> 0x561b0145d8f5221995bc6a787d8d70db0604b7b8?

If so, then yeah, let's keep it.

**Comment by JamesSmartCell** [comment]
> > Could we show that it links to this address but doesn't resolve to it?
> 
> I think if we want to show it (as it is now in Android), then just keep it that way.
> 
> > I think it's using a fallback system - it knows that ENS is associated with that address, and checks that ethereumfoundation.eth still resolves to 0x561b0145d8f5221995bc6a787d8d70db0604b7b8, if it does then it displays the address.
> > Technically, it's correct to do so - if you previously sent to that address, it notes that and performs the validation.
> > What reason would we not want to show this association, providing it's valid? I would like to see it because when I send eth I like as many validations I haven't made a mistake as possible.
> 
> Are we showing 0x561b0145d8f5221995bc6a787d8d70db0604b7b8 -> ethereumfoundation.eth because we have previously verified that ethereumfoundation.eth -> 0x561b0145d8f5221995bc6a787d8d70db0604b7b8?
> 
> If so, then yeah, let's keep it.

Yes that's exactly how it's working. It always performs the validation if it's checking from a previously used address (even if it knows that previously it resolved to that address).

**Comment by hboon** [comment]
👍
