### ISSUE TITLE
Mark up ERC71.setApprovalForAll transactions in confirmation actionsheet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2780]
It can be a potentially dangerous call. Currently actionsheet doesn't provide a good hint of what it is.

Refer to https://github.com/AlphaWallet/alpha-wallet-ios/pull/5217

This is how it looks like currently for ERC71's `setApprovalForAll()`:

<img width='200' src='https://user-images.githubusercontent.com/56189/186587653-ff9c90de-f54d-4abf-9ef0-1020ba185eb3.jpg'>

This is how it looks like for ERC20 `approve()`:

<img width='200' src='https://user-images.githubusercontent.com/56189/186587669-686e1c74-0365-4f0d-a6df-f40859a48db1.jpg'>

The last row ("Token" = "#1") is also wrong. The "1" is probably from the bool arg = `true`.

Would be desirable to make something similar for `setApprovalForAll()`

You can reproduce with https://streetfighters.fun/ (as of writing) in dapp browser. Tap "Mint" button, but don't sign the transaction. (seems like you'll need Blitmap token in the wallet for the request to show up. If you can 0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362 and make the app pretend it has the key, it could be useful)

**Comment by JamesSmartCell** [comment]
Hi @hboon we should already be detecting this function; I think I need to add extra param types in case they're using different parameters from the way the spec was when I originally wrote the decoder class in 2018.

Should it alert the user or do you think just displaying 'setApprovalForAll()' is sufficient warning?

**Comment by hboon** [comment]
Might save you some time: `setApprovalForAll(address,bool)` with hash "a22cb465".

> Should it alert the user or do you think just displaying 'setApprovalForAll()' is sufficient warning?

Just display the function name and the address like we do for `approve()` in the other screenshot will do for now.

Longer term, we'll beef up the display.

**Comment by JamesSmartCell** [comment]
> Might save you some time: `setApprovalForAll(address,bool)` with hash "a22cb465".
> 
> > Should it alert the user or do you think just displaying 'setApprovalForAll()' is sufficient warning?
> 
> Just display the function name and the address like we do for `approve()` in the other screenshot will do for now.
> 
> Longer term, we'll beef up the display.

It's already in our tx decoder, just needs a quick debug to see why it's not picking it up as it should.
