### ISSUE TITLE
Testnet 'Where are my tokens' should only appear on the wallet page

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2799]
Reproduce:

1. Open AW
2. Switch to testnet mode
3. On wallet page, click hamburger->add/hide tokens->(+)

See this screen:

![image](https://user-images.githubusercontent.com/12689544/188038948-a2be2f27-8b6e-4b69-98cb-51d185af3a09.png)

Should not see the 'Testnet where are my tokens' entry.

**Comment by seabornlee** [comment]
Was fixed.
