### ISSUE TITLE
Fix 'Go To Token' button

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2818]
Reproduce:

1. Have any wallet with NFTs (or watch 0xA20efc4B9537d27acfD052003e311f762620642D and switch on Rinkeby)
2. Click on Activity pane.
3. Click on NFT transfer.
4. See this screen (or one like it):

![ctor](https://user-images.githubusercontent.com/12689544/189047990-00354f7a-62a2-45bd-9ab5-d788d8ce8169.jpg)

5. Click on 'Go To Token'. 

Expected: Goes to NFT Token page ```class NFTActivity```. If Token is known to ```TokensService```.

**Comment by Thisdick69** [comment]
Need help

**Comment by seabornlee** [comment]
> Need help

Hi @Thisdick69 , you can create an issue to describe what problem you are facing, we are willing to provide any help as we can.

**Comment by justindg** [comment]
Seems to be working fine, albeit the limited information displayed

![306581932_1221511905076843_5558450149703736913_n](https://user-images.githubusercontent.com/17334718/191650939-bfb13816-02e9-4fbf-bd12-0adb0301454f.jpg)
