### ISSUE TITLE
Use third party crash analytics 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#282]
https://www.captechconsulting.com/blogs/a-comparison-of-android-crash-reporting-tools mentioned Firebase, Crashlytics, Apteligent, Bugsnag

**Comment by colourful-land** [comment]
@justindg  do you have practical experience with any 3rd party crash analytics tool?

**Comment by justindg** [comment]
I've had a nice time with Firebase Crashlytics! Easy to setup too.

**Comment by miang719** [comment]
@justindg just do it then. thanks

**Comment by miang719** [comment]
@justindg how long does it take to setup? so i can follow up the progress

**Comment by justindg** [comment]
@miang719 done. PR can be found here https://github.com/AlphaWallet/alpha-wallet-android/pull/361

I would need a list of Google accounts so I could add new members/owners for dashboard access. Thanks!

**Comment by colourful-land** [comment]
Thanks a lot. I'll hold off for a day or two until I figure out our main domain name for google accounts.

**Comment by colourful-land** [comment]
@bootingman @zhangzhongnan928 

Tell a friend in China to download this:

https://github.com/AlphaWallet/alpha-wallet-android/releases/tag/1.0.11

Manipulate the basic functions (e.g. restore from a backup key and check its balance, send an ether to or back).

If it crashes, let us know. If it does not crash, force a crash with the following:

Settings > Help & FAQ > Click anywhere on the blank space below the FAQs (it will mysteriously crash)

**Comment by hboon** [comment]
@colourful-land does it need to be launched one more time so the app can report the crash to the server?

**Comment by bootingman** [comment]
@colourful-land @hboon I'm sure, several crash happened in Zhejiang province, China

**Comment by colourful-land** [comment]
I didn't see any crash reports in firebase, so I believe the crash report might have been sent to  Fabric Crashlytics. Please have a look @justindg if there are new crash reports of today and note down their IP addresses. If it has worked as expected we still can release it today.

† https://console.firebase.google.com/project/alpha-wallet-android-186eb/overview

**Comment by colourful-land** [comment]
Fits the profile. Problem solved. (I'll ask for login credential separately by email.)
