### ISSUE TITLE
Add PHI Network v2 chain

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-android#2822]
Already in process for IOS  needs to be added for android. 

https://chainlist.org/chain/144 

Phi network v2 chain

https://phiscan.com

https://connect.phi.network 

Chain ID: 144

**Comment by JamesSmartCell** [comment]
Note: API for transactions is:

https://phiscan.com/api

@Phinetwork is the chain icon for Phi v2 network different from the original Phi network?

**Comment by Phinetwork** [comment]
> Note: API for transactions is:
> 
> 
> 
> https://phiscan.com/api
> 
> 
> 
> @Phinetwork is the chain icon for Phi v2 network different from the original Phi network?
> 
> 
> 
> 

Icon is the same. V2 has some upgraded features and v1 chain is more private but logos are the same.

**Comment by Phinetwork** [comment]
How's this going

**Comment by Phinetwork** [comment]
> Note: API for transactions is:
> 
> 
> 
> https://phiscan.com/api
> 
> 
> 
> @Phinetwork is the chain icon for Phi v2 network different from the original Phi network?
> 
> 
> 
> 

@JamesSmartCell hows this coming along?

**Comment by JamesSmartCell** [comment]
We haven't added it yet

**Comment by JamesSmartCell** [comment]
@Phinetwork Do you have any price ticker for the Phi network? I see it's an algorithmic stable coin, is it safe to peg the value to 1 USD? It would be preferable if it's listed in an exchange somewhere.

**Comment by Phinetwork** [comment]
> @Phinetwork Do you have any price ticker for the Phi network? I see it's an algorithmic stable coin, is it safe to peg the value to 1 USD? It would be preferable if it's listed in an exchange somewhere.

https://price.phi.network/api/ticker?filter=WPHI



Just saw this. Thanks for the question.

This is the price api also phi is not an algorithm stable coin phi cash is an algo stable coin. 

Please use this price api for phi this is what was used on the iOS version thank you
