### ISSUE TITLE
Check out chains supported by OpenSea API and let's 

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2842]
These are supported on the site, let's see if they are supported by the API too and if we need to go to v2 (iOS is still on v1):

* Arbitrum
* Klaytn
* Polygon
* Solana
* Which testnet. Rinkeby or Goerli?

iOS only supports Ethereum and Rinkeby at the moment.

- [x] Check
- [x] Create iOS issue
- [x] Implement Android

**Comment by JamesSmartCell** [comment]
Rinkeby will be switched off soon. Yes Android also supports (supported?) Rinkeby too.

We should check Goerli support.

**Comment by hboon** [comment]
https://docs.opensea.io/reference/testnets-api-overview suggest testnets https://testnets-api.opensea.io/api/v1 is connecting to Goerli now, so should verify that and update our app if necessary (on iOS we hit that on Rinkeby so tokens would show up on the wrong chain)
