### ISSUE TITLE
Implement displaying NFT rarity (not attribute rarity) from  OpenSea API

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2843]
Keywords to look for: [OpenSea OpenRarity]

If so, let's figure out how to get it in

**Comment by justindg** [comment]
@hboon openrarity data can be found on some NFTs like Cool Cats NFT:

```
    "rarity_data": {
        "strategy_id": "openrarity",
        "strategy_version": "0.4.3b0",
        "rank": 9125,
        "score": 0.901504573157466,
        "calculated_at": "2022-09-26T18:11:50.340242",
        "max_rank": 9955,
        "tokens_scored": 9955
    }
```

Should we implement it? Could simply add another line in the Details section

**Comment by hboon** [comment]
@justindg yeah definitely! Would you help write up an issue for iOS? Thanks.

**Comment by hboon** [comment]
@justindg BTW, I noticed Android uses v2 for Polygon, would you see if it includes rarity with the same schema, if you haven't?

**Comment by justindg** [comment]
> @justindg BTW, I noticed Android uses v2 for Polygon, would you see if it includes rarity with the same schema, if you haven't?

The API response doesn't have the `rarity_data` field if the collection owner has not opted in the feature, but I will try to find a Polygon collection that has it enabled :)

**Comment by hboon** [comment]
You can try calling it on mainnet with v2 too. Probably supported.

**Comment by justindg** [comment]
> You can try calling it on mainnet with v2 too. Probably supported.

API v2 seems to have different functionalities? Can't seem to find how to retrieve asset data using v2

https://docs.opensea.io/v2.0/reference/retrieve-listings
