### ISSUE TITLE
Add Arbitrum Goerli and Optimism Goerli support

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2853]
- [x] Write issue for iOS

**Comment by JamesSmartCell** [comment]
IDs:

Optimism Goerli:  420    Currency Symbol:  ETH
Arbitrum Goerli:  421613  Currency Symbol:  AGOR
 
RPC:

Arbitrum Goerli:

https://arbitrum-goerli.infura.io/v3/

Optimism Goerli:

https://optimism-goerli.infura.io/v3/

Transaction Viewer:

https://goerli-rollup-explorer.arbitrum.io/tx/
https://blockscout.com/optimism/goerli/tx/

APIs:

https://goerli-rollup-explorer.arbitrum.io/api?
https://blockscout.com/optimism/goerli/api?

Logos would stay the same as current testnet logos.

Backup RPC nodes:

https://goerli-rollup.arbitrum.io/rpc
https://goerli.optimism.io


This should be enough info for a full implementation. Let me know if you need any more info.
