### ISSUE TITLE
Fix Gnosis gas price: default gas price should be 2 gwei instead of 1 gwei

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2862]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/5495

**Comment by JamesSmartCell** [comment]
Can we get the gas price from the node?

**Comment by hboon** [comment]
Good point.

```
curl -H 'accept: application/json' -H 'content-type: application/json' -H 'user-agent: AlphaWallet/395 CFNetwork/1237 Darwin/20.5.0' -H 'accept-language: en-us' --data-binary '{"id":1,"method":"eth_gasPrice","jsonrpc":"2.0","params":[]}' --compressed "https://rpc.ankr.com/gnosis" -s
```

{"jsonrpc":"2.0","result":"0x77359400","id":1}

which is 2gwei.

I think you can use EIP1559. Good to verify in case the amount is much bigger than what is needed in practice (because they seem to want more)

**Comment by JamesSmartCell** [comment]
Then we'll do it that way. It won't need updating again

**Comment by JamesSmartCell** [comment]
@hboon it already works this way :)

**Comment by hboon** [comment]
@JamesSmartCell woohoo!
