### ISSUE TITLE
Price ticker api for phi

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-android#2863]
> @Phinetwork Do you have any price ticker for the Phi network? I see it's an algorithmic stable coin, is it safe to peg the value to 1 USD? It would be preferable if it's listed in an exchange somewhere.

https://price.phi.network/api/ticker?filter=WPHI

Just saw this. Thanks for the question.

This is the price api also phi is not an algorithm stable coin phi cash is an algo stable coin. 

Please use this price api for phi this is what was used on the iOS version thank you 

@JamesSmartCell 

__Originally posted by @Phinetwork in https://github.com/AlphaWallet/alpha-wallet-android/issues/2822#issuecomment-1268495918__

**Comment by Phinetwork** [comment]
@JamesSmartCell just following up did we add the api for PHI

**Comment by JamesSmartCell** [comment]
Yes, added. I'm pushing another release - our previous release was stalled by the playstore.
