### ISSUE TITLE
 Price API For PHI Network 

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-android#2865]
Can we set up Price API For PHI Network API Can Be found here https://price.phi.network/api/ticker?filter=WPHI

Thanks 

__Originally posted by @Phinetwork in https://github.com/AlphaWallet/alpha-wallet-android/issues/2670__

**Comment by JamesSmartCell** [comment]
Yes, will be in the next release.

**Comment by Phinetwork** [comment]
> Yes, will be in the next release.

Perfect thank you what is the ETA for the android version for the  next update?

**Comment by Phinetwork** [comment]
When will android update be live lots of users asking about this hasn't updated since September 4th. Do we have an estimate of when do update will be live on android?

**Comment by Phinetwork** [comment]
> We have a release pending for over 2 weeks now --- we are attempting to contact the PlayStore to resolve this but getting through the automated deflection bot is tricky!

Thanks for the update figured it was google not doing their job. Thanks for the heads up. It Will get approved soon.

**Comment by Phinetwork** [comment]
If users download the APK directly off the alpha wallet website does this work with the newest features? @JamesSmartCell

**Comment by JamesSmartCell** [comment]
No it hasn't been updated. We found the issue with the PlayStore, should be fixed today.

**Comment by Phinetwork** [comment]
> No it hasn't been updated. We found the issue with the PlayStore, should be fixed today.

Great news thanks for the update

**Comment by Phinetwork** [comment]
> We have a release pending for over 2 weeks now --- we are attempting to contact the PlayStore to resolve this but getting through the automated deflection bot is tricky!

Hey @JamesSmartCell great job with the v2 integration. Can we please integrate the price API for the v1 chain as well. Only the price is showing up for the v2 chain it should show up for both the v1 & v2 chains thank you.

**Comment by JamesSmartCell** [comment]
Is it just a straight duplicate?

**Comment by Phinetwork** [comment]
> Is it just a straight duplicate?

Yes you got it. it's a straight duplicate same price api as the v2 chain is used for the v1 chain.
