### ISSUE TITLE
Show full Ethereum address in transaction confirmation actionsheet not "0xabcd…cdef"

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2873]
Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/5576

Careful to do it for when there's an ENS too. Both contracts and recipients. Too easy to fake them. Improve UX + safety for users

from|to
-|-
<img width="200" alt="Screenshot 2022-10-14 at 10 50 22 AM" src="https://user-images.githubusercontent.com/56189/195751342-84642d7a-3e4b-4b59-9640-98fc87427328.png">| <img width="200" alt="Screenshot 2022-10-14 at 10 47 18 AM" src="https://user-images.githubusercontent.com/56189/195751325-8e3867ec-c854-4742-91a1-f602a6d42259.png">

**Comment by JamesSmartCell** [comment]
Good call, in fact we should do this in other places too. The only place where we should abbreviate is on the Change/Add wallets activity (IMO). I have noticed it's inconsistent across the wallet.

**Comment by hboon** [comment]
We used to intentionally show the abbreviated version except in the Change/Add Wallet screen and when we an ENS is around.

I think that's still OK, except we should always show the full version in the transaction confirmation actionsheet. For the rest, it is less critical which one, so we can abbreviate for a more tidier look (or switch if it's more appropriate)
