### ISSUE TITLE
Java debug error

### ISSUE THREAD

**Issue by elishaakyaw** [AlphaWallet/alpha-wallet-android#2876]
i cloned the app and followed the steps stated but i run into this error. Any help will be appreciated
 Task :app:compileAnalyticsDebugJavaWithJavac FAILED

**Comment by JamesSmartCell** [comment]
Hi @elishaakyaw can you try setting the app flavour :- like this:

![image](https://user-images.githubusercontent.com/12689544/196482764-924e64fc-211c-4ae6-8545-eab5fe8486dc.png)

then do a full rebuild:

![image](https://user-images.githubusercontent.com/12689544/196484372-f5db39bf-9dd9-4f90-a7bc-dca1555e6750.png)

If this doesn't work can you let me know the full error message, I will try to diagnose with you.

**Comment by elishaakyaw** [comment]
Thanks alot.  Went out to get some groceries so will do that when I get
home and give you my feedback

**Comment by elishaakyaw** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/52818647/196560533-20a2fb8a-f177-4d53-b674-f559b8413e8c.png)
![Screenshot (22)](https://user-images.githubusercontent.com/52818647/196560548-339cdb09-b76c-43c4-877e-b17f656d46b7.png)

**Comment by elishaakyaw** [comment]
i did what you recommended. ended up with the above errors.

**Comment by JamesSmartCell** [comment]
Ok I think I know what the problem is:

can you do:

![image](https://user-images.githubusercontent.com/12689544/197005176-938c1429-ac1b-49f1-9e32-058cdba86b86.png)


I think it's the Java JDK version. We're using verion 11. Try changing your Java version. Please let me know if you get it working I'll ensure the docs are up to date.

**Comment by elishaakyaw** [comment]
ok sure. will try that now. thanks

**Comment by elishaakyaw** [comment]
is it necessary to build in android studio. Is it possible to do this in vs code. running into a lot of errors.

**Comment by elishaakyaw** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/52818647/197028569-c9ebc84c-0816-4d4b-bad8-00afea24a06d.png)
![Screenshot (30)](https://user-images.githubusercontent.com/52818647/197028599-c8bdc62c-bd3f-4b9f-9948-f950b3f0198e.png)

**Comment by elishaakyaw** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/52818647/197029051-bc6096be-c5ed-4033-96c5-081ecdd884d0.png)

**Comment by elishaakyaw** [comment]
i also get this window often, i just click yes without clicking anything

**Comment by elishaakyaw** [comment]
i also get this window often, i just click yes without typing anything
