### ISSUE TITLE
Error: there is no registered task type 'Java'. Did you miss installing an extension that provides a corresponding task provider?

### ISSUE THREAD

**Issue by elishaakyaw** [AlphaWallet/alpha-wallet-android#2882]
![Screenshot (34)](https://user-images.githubusercontent.com/52818647/197605556-5d5e90dc-5b2d-4b28-9ddc-592b2e2213e8.png)
![Screenshot (33)](https://user-images.githubusercontent.com/52818647/197605098-a0566996-3fbd-4a10-ac39-ea4f23004afd.png)

**Comment by seabornlee** [comment]
We haven't tested VS Code, can you try Android Studio?

**Comment by JamesSmartCell** [comment]
> We haven't tested VS Code, can you try Android Studio?

We only test with Android Studio / Gradle. If you get it working with VS Code please post some instructions!
