### ISSUE TITLE
Could not resolve all dependencies for configuration ':app:analyticsDebugRuntimeClasspath'.

### ISSUE THREAD

**Issue by elishaakyaw** [AlphaWallet/alpha-wallet-android#2884]
![Screenshot (2)](https://user-images.githubusercontent.com/52818647/198025563-973999fb-894d-407f-937f-b0d94d0ec5ae.png)
![Screenshot (3)](https://user-images.githubusercontent.com/52818647/198025574-17cdb96e-511a-45ba-96dd-b0037091be64.png)

**Comment by seabornlee** [comment]
It probably network issue. Retry may fix this or try using VPN.
