### ISSUE TITLE
Error after clonning

### ISSUE THREAD

**Issue by elishaakyaw** [AlphaWallet/alpha-wallet-android#2885]
![Screenshot (5)](https://user-images.githubusercontent.com/52818647/198100398-210b4788-e3d3-4060-9787-1e0a82e75f49.png)
any help here please. i cloned the app, setup jdk 11 but i am geting this error here.

**Comment by seabornlee** [comment]
hi, can you show a full screenshot of the Event Log panel?
![image](https://user-images.githubusercontent.com/735708/198208096-027a7cb9-7020-4589-abe6-e909d26e09c9.png)

**Comment by elishaakyaw** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/52818647/198230099-c63f7687-bbc2-43b5-a6cf-496c927cdc2d.png)
this is my eventlog

**Comment by elishaakyaw** [comment]
i also get a compile sdk error

**Comment by JamesSmartCell** [comment]
You need to select an Android project - from the picture it looks like you're attempting to compile this as a project. It should look like this:

![image](https://user-images.githubusercontent.com/12689544/198540572-72152349-dc4b-4a32-bd2c-b484d62010cc.png)

Also, be sure to click on the Build Variants tab on the left and pick analyticsDebug/x86
