### ISSUE TITLE
Gradle:Configure Project

### ISSUE THREAD

**Issue by elishaakyaw** [AlphaWallet/alpha-wallet-android#2889]
i got the app to build yesterday. woke up today and decided to fire up android studio and work on the app, but it hangs at gradle configure project

**Comment by seabornlee** [comment]
We are debugging this. Can you help check the settings?
![image](https://user-images.githubusercontent.com/735708/198751846-3c0d9842-d122-428f-ac5f-41c1a97a59ab.png)

**Comment by elishaakyaw** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/52818647/198752551-d4dd5729-a411-4d86-ae62-55321d935d3a.png)
already done that

**Comment by elishaakyaw** [comment]
i was able to build the app before and even build an apk which i ran on my physical device. i closed my pc and went to bed only to get this error the next time i decided to run it again

**Comment by elishaakyaw** [comment]
its not an error but the configure gradle project takes forever, even after cloning

**Comment by seabornlee** [comment]
We introduced CheckStyle gradle plugin, it hangs the build under some condition, we are trying to fix it.
A walk around is uncomment the line `apply from: rootProject.file("codestyle.gradle")` in `projectRoot/build.gradle`.

I am so sorry to bother you.

**Comment by elishaakyaw** [comment]
ok tanks a lot. will try that now

**Comment by elishaakyaw** [comment]
still hangs for some wired reason
![Screenshot (16)](https://user-images.githubusercontent.com/52818647/198754009-097fd306-eac5-475c-8207-17a04fa4596c.png)

**Comment by elishaakyaw** [comment]
and that line of code has already been uncommented

**Comment by elishaakyaw** [comment]
![Uploading Screenshot (19).png…]()

**Comment by elishaakyaw** [comment]
here is another control project i built just to check if it want from my end. it built succesful
![Uploading Screenshot (20).png…]()
ly and i generated an apk for my physical device

**Comment by elishaakyaw** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/52818647/198822657-0608b584-273c-414c-b289-622967d53fd3.png)
i created a control project in java to be sure it wasnt caused at my end. Everything builds easily and i even generate apk for my physical device.

**Comment by seabornlee** [comment]
> and that line of code has already been uncommented

Oh, sorry my fault. That line should be commented.

**Comment by JamesSmartCell** [comment]
Closing as now fixed
