### ISSUE TITLE
Gradle:Configure Project hangs for hours until i stop the process

### ISSUE THREAD

**Issue by clutchnetwork** [AlphaWallet/alpha-wallet-android#2890]
anytime i clone the app , it hangs at gradle configure project. Havent found a solution yet.

**Comment by seabornlee** [comment]
Sorry about that. I am trying to fix this. Before that, you can comment `apply from: rootProject.file("codestyle.gradle")` in `build.gradle` for a temporary solution.

**Comment by JamesSmartCell** [comment]
Closing as fixed
