### ISSUE TITLE
Gradle configure Project takes forever

### ISSUE THREAD

**Issue by LiQiang-code** [AlphaWallet/alpha-wallet-android#2891]
looking to add my own tokens and rebuild, but after cloning, gradle configure takes forever. Any help would be greatly appreciated.

**Comment by seabornlee** [comment]
Sorry about that, please see #2890

**Comment by JamesSmartCell** [comment]
Try again now, the line that causes this has been commented out. We're currently investigating this issue as the related feature we're implementing is of great benefit for the codebase.

**Comment by LiQiang-code** [comment]
thanks alot. i recloned but and gradlebuild works just fine. I run into other problem with
> Task :app:javaPreCompileAnalyticsDebug FAILED

**Comment by seabornlee** [comment]
> thanks alot. i recloned but and gradlebuild works just fine. I run into other problem with
> 
> > Task :app:javaPreCompileAnalyticsDebug FAILED
We need more detailed info to investigate the issue.
Can you kindly provide a screenshot and also your OS version and JDK version?

**Comment by JamesSmartCell** [comment]
Should be fixed now. Please re-open if this is not the case
