### ISSUE TITLE
Modify or change logo and splash screen

### ISSUE THREAD

**Issue by LiQiang-code** [AlphaWallet/alpha-wallet-android#2896]
looking to make some changes with the splash screen and app logo. Cant seem to find the exact files.

**Comment by seabornlee** [comment]
Splash layout: `app/src/main/res/layout/activity_splash.xml`
Logo: `ic_launcher`
![image](https://user-images.githubusercontent.com/735708/199378197-99f9938a-a658-4416-917a-42a1702e6cec.png)
