### ISSUE TITLE
Check Update notifications are working and implement as required

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2906]
Check the current status of the app update notification.

- For PlayStore installed apps; the user should get a notification in the Settings page there's a new version available, and implement the native PlayStore update control to allow user to update from within the app (if possible).
- For downloaded / manually installed app, check the version update (using github - I believe the code is still in the app, but may be archived out so check github history), and if an update is available give user a link (within the update notification) for a browser intent to the download page.

**Comment by seabornlee** [comment]
https://developer.android.com/guide/playcore/in-app-updates
