### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by LiQiang-code** [AlphaWallet/alpha-wallet-android#2910]
Hi, looking forward to rebrand alpha-wallet for a small company. I want to change the splash screen, app name, app logo to that of the project. Want to know the exact files to change. i want to rebrand and make it open source

**Comment by seabornlee** [comment]
Reference: https://github.com/AlphaWallet/alpha-wallet-android/wiki/How-to-customize-splash-screen-and-app-logo%3F

**Comment by LiQiang-code** [comment]
thanks

**Comment by seabornlee** [comment]
My pleasure.

**Comment by LiQiang-code** [comment]
i want to add binance and polygon networks as locked chains. I know how to go about that but im a bit confused about the name i should add to the locked chains section. i tried Binance (BSC) but it didnt work

**Comment by LiQiang-code** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/116978261/199981828-e07e7348-2764-4799-a923-29911b584a4f.png)
I know about it, wat i want to know is the type of string i should input. Cos i tried Binance (BSC) , BINANCE_MAIN_ID etc but its not working

**Comment by LiQiang-code** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/116978261/199982384-a4bf6f16-6ec1-4353-9274-13457b59f9b1.png)
i know about that. what i want to know is the name i should input, cos i tried Binance(BSC), BINANCE_MAIN_ID etc..

**Comment by seabornlee** [comment]
![image](https://user-images.githubusercontent.com/735708/199983098-9b2120b7-858b-4b36-ba07-4edab2e1c88b.png)
The ids are constants, need class name to reference them.

**Comment by LiQiang-code** [comment]
ok i got it now thanks

**Comment by seabornlee** [comment]
You are welcome!
