### ISSUE TITLE
Rebrand 

### ISSUE THREAD

**Issue by Mantisrei** [AlphaWallet/alpha-wallet-android#2914]
![Screenshot_20221105-231945_Vinufolio](https://user-images.githubusercontent.com/117015485/200146669-2bff6718-bddb-4852-ad82-bb4f02de557b.jpg)
![Screenshot_20221105-231633_Vinufolio](https://user-images.githubusercontent.com/117015485/200146674-a98250b5-5570-41fa-a6d0-5699a1a166d4.jpg)
I'm looking forward to rebrand for a small project,  but I want to change these two. Cant seem to find the specific files. Any one to point me in the right direction.

**Comment by Mantisrei** [comment]
Looked through all the image files but didn't find them.

**Comment by seabornlee** [comment]
hi, thx for using AlphaWallet, you can checkout this: https://github.com/AlphaWallet/alpha-wallet-android/issues/2910

**Comment by JamesSmartCell** [comment]
Closing, thanks for sorting @seabornlee
