### ISSUE TITLE
Splash screen issue

### ISSUE THREAD

**Issue by LiQiang-code** [AlphaWallet/alpha-wallet-android#2921]
@seabornlee @JamesSmartCell  i tried changing the splash screen, i read through the other issues, but im new to java and have been building with   react native and flutter for most of my dev life. Would be very appreciative if you could take me through or give me a detailed explanation with on how to change it. Thanks.

**Comment by seabornlee** [comment]
Hi, you can just replace two files:
![image](https://user-images.githubusercontent.com/735708/200454287-271bf19c-6e37-4e97-8a3d-fde024aca874.png)

**Comment by LiQiang-code** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/116978261/200655721-f42dd90e-8f4e-4ae9-acf4-4e1f09df4f77.png)

**Comment by LiQiang-code** [comment]
ok sure. can i just copy and paste the image

**Comment by LiQiang-code** [comment]
tanks alot i understand now..
