### ISSUE TITLE
Swap issues

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2935]
## For watch only wallet
**Now**: It does nothing when confirm transaction.
**Expected**: It shows can't do swap with watch only wallet.

## Edit from token balance
**Now**: It opens `Select Route` page when editing balance.
**Expected**: It automatically selects the recommended route and user can open `Select Route` page by clicking button. Such as 1inch does.

**Comment by justindg** [comment]
> ## For watch only wallet
> **Now**: It does nothing when confirm transaction. **Expected**: It shows can't do swap with watch only wallet.

In this case, should we allow user to bring up confirmation dialog? Or can we just show alert them when they press continue?

**Comment by seabornlee** [comment]
> > ## For watch only wallet
> > **Now**: It does nothing when confirm transaction. **Expected**: It shows can't do swap with watch only wallet.
> 
> In this case, should we allow user to bring up confirmation dialog? Or can we just alert them when they press `Continue`?

I prefer the former so that later other transactions will automatically have the same check.

**Comment by justindg** [comment]
> > > ## For watch only wallet
> > > **Now**: It does nothing when confirm transaction. **Expected**: It shows can't do swap with watch only wallet.
> > 
> > 
> > In this case, should we allow user to bring up confirmation dialog? Or can we just alert them when they press `Continue`?
> 
> I prefer the former so that later other transactions will automatically have the same check.

I only implemented it in the Activity where the transaction, since a reference to the `Wallet` object is needed. I can create new tickets/PRs for other scenarios that need this.
