### ISSUE TITLE
PlayStore DeepLink Issue

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2938]
**Some deep links may be failing because your web domains aren't associated with your app**
This means that on Android 12 and above, your app can't accept traffic from some web URLs. To fix issues and make sure that users go directly to your app, go to the Deep links page.

**Details:** 
https://play.google.com/console/u/1/developers/8548546370386799497/app/4973272515950350768/deeplinks?selectedVersionCode=215

- [ ] Put assetlinks JSON file on sever
- [ ] Fix <data> tag failed
  Add a "/" to the beginning of the android:path attribute in the <data> tag. The attribute might also be android:pathPrefix or android:pathPattern.

**Comment by JamesSmartCell** [comment]
Hi @seabornlee I independently did this work, it does require an update that I don't have permission to push to the 
DMZ site (aw.app), I will get that actioned by the current owner(s).
