### ISSUE TITLE
UI: Activity details page not show full NFT video

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2957]
Height is not enough. 

![71668838022_ pic](https://user-images.githubusercontent.com/735708/202837167-a8388b3b-f8b9-4b58-b27f-7183fa6fa527.jpg)

**Comment by justindg** [comment]
@seabornlee may I know the wallet address so I can watch the wallet for testing?

**Comment by seabornlee** [comment]
> @seabornlee may I know the wallet address so I can watch the wallet for testing?

DM you.

**Comment by justindg** [comment]
Closed via #2994
