### ISSUE TITLE
Transaction Dialog normalisation

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2959]
Visit this site for WalletConnect v2 test:

https://react-app.walletconnect.com/

Send a transaction in (eg) Goerli and notice the hex hash that appears looks different from a normal transaction hash.

Fix: use the transaction hash here or if it is; work out why it's different from dappbrowser and walletconnect v1

**Comment by JamesSmartCell** [comment]
@justindg Transaction dialog:

![Screenshot_20221122-224519_AlphaWallet](https://user-images.githubusercontent.com/12689544/203306193-7f3555ee-8c9e-46fc-bb40-a6373da8feb4.jpg)

Click on the 'eth_sendTransaction' box.

I can see a few issues with centering also the transaction hash displayed is wrong too (I think). Compare with transaction sent, account to account or NFT send etc.

**Comment by justindg** [comment]
Solved via #2983
