### ISSUE TITLE
WalletConnect v2 issue list

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2963]
All of these are pretty much superficial - the core works amazingly well :)

Essential:

- [x] Warn user if WalletRequest sign/TX send is for a different wallet than the current default wallet.
- [x] When connecting WalletConnect dialog should not show watch wallets
- [x] When connecting WalletConnect dialog should only show default wallet (?) and ask for connection permission. This permission, once granted should be remembered.
- [x] If addresses are shown, use ```Utils.formatAddress(...)```
~~- [ ] If WalletConnect message is received while user is not on the home pages (wallet/activity/browser/settings) use the notification - add the numbering (or see what that looks like).~~ (Moved to #2985)

Optional (but great if they can be done):

~~- [ ] If user cancels the signing dialog in the browser, close the open ActionSheet on the app~~ (Moved to #2986 )
~~- [ ] I got this crash occasionally when disconnecting a WC2 session from the desktop end:~~  (Moved to #2987)

```java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 2(offset:-1).state:19 androidx.recyclerview.widget.RecyclerView{5fed730 VFED..... ......ID 0,0-1080,2085 #7f0a029e app:id/list}, adapter:com.alphawallet.app.ui.widget.adapter.TokensAdapter@b7dda7f, layout:androidx.recyclerview.widget.LinearLayoutManager@a62ea4c, context:dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper@a5120b4```

**Comment by justindg** [comment]
Checked items are fixed in branch `2963-fix-wc-v2-issues` https://github.com/AlphaWallet/alpha-wallet-android/tree/2963-fix-wc-v2-issues

**Comment by justindg** [comment]
Moved other issues to separate tickets as they may be unrelated or too big for a single PR
