### ISSUE TITLE
sell link with ETH 0.00001 ..... will show as ETH 0.0001

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#297]
sell link with ETH 0.00001 ..... will show as ETH 0.0001 on Andriod AlphaWallet
sell link with ETH 0.00001 ..... will show as 1.0E-5 ETH on landing page

**Comment by JamesSmartCell** [comment]
Fixed in PR #312

**Comment by James-Sangalli** [comment]
@JamesSmartCell if this is fixed in the PR then please close the issue.
