### ISSUE TITLE
The "First Wallet Action" event should always include the property "type"

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3024]
The "First Wallet Action" event should always include the property "type" with one of these values (code in Swift):

```
public enum FirstWalletAction: String {
        case create
        case `import`
        case watch
    }
```

**Comment by JamesSmartCell** [comment]
@hboon Is this for Mixpanel, or just for reference/display? How is this value used?

**Comment by hboon** [comment]
Yes, Mixpanel
