### ISSUE TITLE
The "Scan QR Code Completed" event should always include the property "resultType"

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3027]
The "Scan QR Code Completed" event should always include the property "resultType" with one of these values (eg. "sendFungibleScreen" verbatim):

```
public enum ScanQRCodeResultType: String {
    case addressOrEip681
    case walletConnect
    case string
    case url
    case privateKey
    case seedPhase
    case json
    case address
}
```

Not sure if they are all applicable for Android?

**Comment by justindg** [comment]
@hboon seems like `seedPhase` is misspelled?

**Comment by hboon** [comment]
@justindg Oh my :sob:, one of the worst place to have a typo. I'll fix it for iOS. Thanks for the heads-up.

**Comment by hboon** [comment]
> Oh my 😭, one of the worst place to have a typo. I'll fix it for iOS. Thanks for the heads-up.

Done: https://github.com/AlphaWallet/alpha-wallet-ios/pull/6153
