### ISSUE TITLE
Change the title of the Wallet tab to show the truncated wallet address if ENS/wallet name is not available

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3029]
Refer https://github.com/AlphaWallet/alpha-wallet-ios/issues/6042

**Comment by seabornlee** [comment]
**Acceptance Criteria:**

1. Show formatted address by default
2. Show custom name instead of address
3. Show ENS name instead of address
4. Show custom name instead of ENS name

**Tasks:**

- [ ] Add test to cover the ACs
- [ ] Implement the change

**Comment by hboon** [comment]
What does "AC" mean?

**Comment by hboon** [comment]
Oh, acceptance criteria :)
