### ISSUE TITLE
Add OKEx chain which is an evm chain

### ISSUE THREAD

**Issue by Mantisrei** [AlphaWallet/alpha-wallet-android#3030]
i want to add okex chain but after making changes, home screen is blank and app keeps crashing

**Comment by JamesSmartCell** [comment]
How are you adding it?

See this commit, and duplicate:

https://github.com/AlphaWallet/alpha-wallet-android/commit/44df65f7d864bd57222758dafa9c04b0fc2b5c07

**Comment by Mantisrei** [comment]
I want to add it to the main code and later display it in the custom view.

**Comment by JamesSmartCell** [comment]
Yes, just following the 44df65f commit (just change the Ids and find the OKX API calls) will allow you to do that. If you try to do it in a different way it'll probably crash - as you found out.

**Comment by JamesSmartCell** [comment]
Hi @Mantisrei did you get anywhere with this one? In particular did you find:

- Working and stable RPC node
- Etherscan/Blockscout/Covalent equivalent
- Transaction API (Etherscan/Blockscout compatible preferred)
- SVG logo for OKX
- Exchange listing prices for OKX chain tokens

**Comment by JamesSmartCell** [comment]
@Mantisrei I looked into it, but couldn't find any Etherscan/Blockscout API. There is a custom API - oklink - but this provides a different style of query. Were you able to find anything better?

I found these instructions which give a very basic interface, but not a good experience as it won't discover an NFT/Tokens etc.

https://decentralizedcreator.com/add-okt-to-metamask/

**Comment by JamesSmartCell** [comment]
Ok I have got the API routes from the OKX team.

**Comment by JamesSmartCell** [comment]
Closing as we are handling this internally.

@Mantisrei it'll be in a release which will be out later this month.
