### ISSUE TITLE
bad character in base64 value; build failed line: 240

### ISSUE THREAD

**Issue by muchaartur** [AlphaWallet/alpha-wallet-android#3041]
Please help me solve this problem. After download I build project ad everything was fine. I build project and its ok. When I changed for my Keyes with infra and GitHub token access I have build failed with this error on screen . Can you please help me solve this issue?

![Screenshot 2023-01-13 at 01 26 41](https://user-images.githubusercontent.com/25831645/212209304-75334889-c0a9-4307-9a25-0b15e6682da1.png)

![Screenshot 2023-01-13 at 01 26 48](https://user-images.githubusercontent.com/25831645/212209324-94931284-6ccd-443c-b3ee-428fbf087139.png)

![Screenshot 2023-01-13 at 01 26 58](https://user-images.githubusercontent.com/25831645/212209330-93edeb24-40e2-4886-be19-b683dc839890.png)

![Screenshot 2023-01-13 at 01 27 03](https://user-images.githubusercontent.com/25831645/212209345-5f066643-e07a-4f70-a2a7-87bd2d625549.png)

![Screenshot 2023-01-13 at 01 27 05](https://user-images.githubusercontent.com/25831645/212209361-c4ef6d28-3fdd-4e46-8f7d-e43b459d5ca6.png)

**Comment by seabornlee** [comment]
hi @muchaartur 
Did you encode your GPR key with Base64, because once the original key appears in code, GitHub revoke the key immediately, so we encoded it.

**Comment by muchaartur** [comment]
yes I did it as in tutorial

**Comment by muchaartur** [comment]
ok it works thank you I made little mistake
