### ISSUE TITLE
[RPC] Update RPC node endpoint for Fantom testnet. https://rpc.testnet.fantom.network/ has been down for a while

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3042]
Refer https://github.com/AlphaWallet/alpha-wallet-ios/pull/6132

**Comment by JamesSmartCell** [comment]
Is it back up again?

![image](https://user-images.githubusercontent.com/12689544/212581045-82e0a057-2dd5-4a63-8582-086392c4a7b6.png)

**Comment by hboon** [comment]
Seems like it's up ocassionally, but it's been down on #monitoring almost all the time.
