### ISSUE TITLE
Execution failed for task ':app:processAnalyticsReleaseGoogleServices'. > No matching client found for package name 

### ISSUE THREAD

**Issue by muchaartur** [AlphaWallet/alpha-wallet-android#3053]
Hello I tried to change package name and I have error. Please can you help me solve this?

![Screenshot 2023-01-18 at 21 14 04](https://user-images.githubusercontent.com/25831645/213285326-7a35af83-33bb-4b47-883a-6c1faa08a951.png)

**Comment by JamesSmartCell** [comment]
Hi @muchaartur try the following:

- edit the applicationId in `app/src/debug/google-services.json`
- click on 'Build Variants' (Build -> Select Build Variants) and pick 'noAnalyticsDebug'.

Of course, if you just edit the applicationId in google-services.json you won't get crashlytics, all those will go to our crashlytics console - you'll need to create a Play developer account and pull the google-services ID from there.

**Comment by abhinawtech** [comment]
How to change the package name?
