### ISSUE TITLE
Sign Request not Popping Up on Wallet Connect Page

### ISSUE THREAD

**Issue by JustinFeng** [AlphaWallet/alpha-wallet-android#3080]
https://user-images.githubusercontent.com/1527902/218005259-40e51816-2ba8-471c-9fc6-8550e78c0f68.mp4

This happens when I use AW to connect WalletConnect V2 on attestation.id page

Once connected, attestation.id will request a signature, but the request is not popping up on AW

It only pops up when I go back to the Setting screen and re-trigger the sign request on attestation.id

Please feel free to reach me on discord (Jia#0289) if you have other questions, cheers

**Comment by seabornlee** [comment]
It was designed to pop up from anywhere. After refactoring, it only pops up from HomeActivity.

**Comment by JamesSmartCell** [comment]
Hi @seabornlee I think I broke this as I wasn't sure people would want the popup if they were in a different process; eg signing a transaction separately. What should happen if they are already in a transaction signing action, and a WC2 request comes?

**Comment by hboon** [comment]
I think the best way currently is for it to just show it and hide an existing one temporarily, if that’s reasonably convenient to do.

Longer term, we have to queue them up and use notifications or toast-like UI. Generally, I am keen on changing all kinds of notifications/error message to that model. At least on iOS, some of the error messages are unnecessarily modal.

**Comment by seabornlee** [comment]
> Hi @seabornlee I think I broke this as I wasn't sure people would want the popup if they were in a different process; eg signing a transaction separately. What should happen if they are already in a transaction signing action, and a WC2 request comes?

I hadn't tested this case previously. The easiest solution is to reject the WC sign request with "User is in signing process.”

**Comment by hboon** [comment]
@seabornlee is this still happening?

**Comment by seabornlee** [comment]
@hboon Yes, I am working on this.
