### ISSUE TITLE
error "pairUri.query must not be null" before poping "WalletConnect" window and  "Confirm Transaction" window

### ISSUE THREAD

**Issue by diyism** [AlphaWallet/alpha-wallet-android#3082]
When I swap token in  the alpahwallet Browser tab (tested both on "https://app.1inch.io" and "https://app.paraswap.io" with polygon network),
an error shows and hides: "pairUri.query must not be null"
then the "WalletConnect" window and  "Confirm Transaction" window can pop out,
and the transaction can be executed successfully,
but the upper error seems noisy.

alphawallet (android) version 3.61.0(237) from the google playstore

**Comment by seabornlee** [comment]
Thank you for bringing this to our attention. We have fixed the issue and will be shipping it soon.
