### ISSUE TITLE
Unable to initiate a transaction in polygon in Dapp browser and/or WalletConnect

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3087]
* A. AlphaWallet dapp browser only

Direct injection within alpha wallet browser gives the same error

* B. AlphaWallet WalletConnect + external browser

It doesn't show any error but simply gets into wallet connect and no prompt is shown.. the website loads forever waiting for the sign

* C. AlphaWallet dapp browser + WalletConnect

Same as A

Example dapp: https://app.thesmurfssociety.com/ + Polygon Chain

Could be same issue as #3082

v3.61.0 (237)

**Comment by JamesSmartCell** [comment]
@hboon Reproduced on 3.61 and fixed in master. Should be good to close.

**Comment by hboon** [comment]
Thanks! 👍

**Comment by hboon** [comment]
Re-opening as user said:

> Not solved yet.. EIP 712 transaction in polygon chain is not popping out is what the dev says

—
https://discord.com/channels/548357107267928064/548358111669256192/1076531651141697726

**Comment by justindg** [comment]
Almost certain #3141 closes this
