### ISSUE TITLE
Can't scan WalletConnect v2 QR code in dark mode

### ISSUE THREAD

**Issue by KevinLu** [AlphaWallet/alpha-wallet-android#3089]
Reproduction:

1. Go to https://web3modal.com/ click on Connect Wallet button
2. Try to scan the QR code with AlphaWallet
3. Nothing happens, the QR code just does not get scanned no matter how long I hold the camera to the code

Dark mode QR code example:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/18564130/218582183-e7a8c98f-35cd-4902-bcab-77177a4888f7.png">

**Comment by seabornlee** [comment]
Thank you for bringing this to our attention! We will investigate it promptly.

**Comment by chadyj** [comment]
Fixed in Web3Modal 2.4.7.

This issue was caused by some android apps having issues scanning a reversed QR code (white dots on black background).

Web3Modal 2.4.7 now only shows a regular QR (black dots on white background) which completely fixes the issue.

**Comment by KevinLu** [comment]
Awesome, thanks for updating. Will close this issue.
