### ISSUE TITLE
Executing transactions instantly fails with WalletConnect 2

### ISSUE THREAD

**Issue by KevinLu** [AlphaWallet/alpha-wallet-android#3094]
Usage:
- Android AlphaWallet client [v3.62.0](https://github.com/AlphaWallet/alpha-wallet-android/releases/tag/v3.62.0)
- WalletConnect v2 protocol

Reproduction:
- Go to https://react-app.walletconnect.com/
- Connect by scanning QR code (I tried with Goerli test net)
- Click on "eth_sendTransaction"
- Use the default gas values (Average)
- Click on "Confirm" button in AlphaWallet
- AlphaWallet instantly sends RPC failed message "JSON-RPC Request Failed", result: "
Rejected by the user"

**Comment by JamesSmartCell** [comment]
@KevinLu Thanks for reporting this! It was causing issues.
