### ISSUE TITLE
Switch network not working with WalletConnect v1

### ISSUE THREAD

**Issue by KevinLu** [AlphaWallet/alpha-wallet-android#3095]
Usage:
- Android AlphaWallet client [v3.62.0](https://github.com/AlphaWallet/alpha-wallet-android/releases/tag/v3.62.0)
- WalletConnect v1 protocol

Reproduction:
- Go to https://wagmi.sh/examples/contract-write-dynamic or https://wagmi.sh/examples/contract-write
- Connect by scanning QR code, select Ethereum mainnet as the chain
- Click on "Connect to Testnet (Goerli)" to try to switch networks
- Nothing happens, AlphaWallet app does not prompt me to switch to Goerli network

Diff:
- Works when trying above steps with MetaMask mobile app

**Comment by JamesSmartCell** [comment]
Hi @KevinLu I have checked the site - I know it's a programmer cliche but I think the error is on the wagmi site. I did try debugging the site to double check but they've used a framework that excessively obfuscates the sourcecode so it goes beyond my very limited JavaScript skills to check.

Try this correctly implemented WC test site (yes it's mine):

https://jamessmartcell.github.io/

You can see the network change request popups happen when you click on the 'change to Klaytn/change to Aurora' buttons.

**Comment by KevinLu** [comment]
Thanks for looking into this @JamesSmartCell ! I'm unable to test on the site you've linked unfortunately. After I scan the QR code with AlphaWallet the site and AlphaWallet shows connected, but no extra buttons appear. This is the state the site is in after scanning with the QR code.
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/18564130/220977633-d383f7d6-5f6c-4ea9-9a41-c6aad323968a.png">

However, I can confirm the wagmi site has issues and I was able to get network switching working using my own implementation of wagmi. I'll close this issue now.
