### ISSUE TITLE
alphawallet failed to use comma , as decimal separator in Spanish

### ISSUE THREAD

**Issue by weiwu-zhang** [AlphaWallet/alpha-wallet-android#3099]
Reference: Read this first
https://www.reddit.com/r/ethdev/comments/1178d5p/how_do_you_deal_with_european_number_notation_in/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

1. The left side shows that a UK bank (wise) in Spanish language mode, where the user types with a decimal point, and the screen confirms with a decimal comma. This is the desired behaviour.
2. The right side shows that alphawallet use decimal point during input (acceptable) as well as display (not okay)

(Of course we are not supposed to hard code the correct behaviour like how numbers are displayed 𝑖𝑓 Android has a system way to do that, since we never have the full knowledge of which locale uses decimal comma which uses decimal points.

device is Samsung S21 Ultra Thin
|  Correct behaviour | AlphaWallet behaviour |
|---|---|
|  ![Screen_Recording_20230220_134755_Wise mp4](https://user-images.githubusercontent.com/548435/220112605-fe31209c-3d5b-422f-bd22-3dfdfb2d1054.gif)|  ![Screen_Recording_20230220_123359_AlphaWallet mp4](https://user-images.githubusercontent.com/548435/220095720-db3988e0-6658-4db4-bc9a-12cfe7005f64.gif)|

**Comment by JamesSmartCell** [comment]
@weiwu-zhang we came to a conclusion some time ago to simply force the input to always use decimal, no matter what locale as this is safest.

The above issue applies to an old version of AlphaWallet.

**Comment by hboon** [comment]
Yes, we decided to always use `,` as thousands separator and `.` as decimal separator no matter the locale more than a year ago.

* https://github.com/AlphaWallet/alpha-wallet-ios/issues/3531
* https://github.com/AlphaWallet/alpha-wallet-android/issues/2358

There were a few reasons:

* some sites in the blockchain like Coinmarketcap does this so users are used to it
* keyboard doesn't always provide the correct buttons for the separators
* copy and paste from elsewhere
* we didn't get it to work, this way was much simpler and consistent

So let's keep this unless there's a very solid reason to change it and we are really confident there is no issue making the change. We have far too many regressions already.

**Comment by weiwu-zhang** [comment]
I'm accepting the decision because it was a thought-over process by the team (I disagree with the decision because we should aim to be better than banks instead of better than dapps, but I can't overrule a decision without being in the UX role). In the meanwhile, yearly review on this decision is needed to avoid we fall behind other wallets when they progress to cover larger userbase instead of focusing on crypto native.

**Comment by hboon** [comment]
#3104 to set a reminder to follow up in a year
