### ISSUE TITLE
Ether balance not showing after successful transaction

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-android#310]
Stumbled upon this bug during user testing so they're new users.

When user receives ether, they can't see the successful transaction immediately (while they're still on the app). They can see in the history of transactions that they have received the ether but they have to restart the AlphaWallet app to see the ether balance appear on the currency card.

The screenshot shows that after 20 confirmation the balance still doesn't update, despite the transaction history says that it was done.

![screenshot_20181128-160449_alphawallet](https://user-images.githubusercontent.com/548435/49137450-6c3cd400-f327-11e8-97ff-3c51960a9b98.jpg)
![screenshot_20181128-160453_alphawallet](https://user-images.githubusercontent.com/548435/49137451-6cd56a80-f327-11e8-8ba8-f5b7906a69df.jpg)

**Comment by JamesSmartCell** [comment]
This can be fixed but we need to have our own main net node to check the memory pool. 

We have our own Ropsten testnet node so it can be implemented for Ropsten. @James-Sangalli is there any progress on this?

**Comment by miang719** [comment]
@James-Sangalli have a look.

**Comment by James-Sangalli** [comment]
New node is irrelevant and won't fix this issue, we need a service like Mark's.

**Comment by colourful-land** [comment]
@James-Sangalli she referred to ETHER BALANCE not updating, Ξ.

ΞΞΞΞΞΞΞ

Ether balance

ΞΞΞΞΞΞΞ

Ether balance should update even if we don't have Mark's service.
