### ISSUE TITLE
logo of our token in cloned app

### ISSUE THREAD

**Issue by ravi19821982** [AlphaWallet/alpha-wallet-android#3117]
hello we cloned the app and locked our token to show as info given on page  but i dont know how to add our token logo  in that can any one help

**Comment by justindg** [comment]
> hello we cloned the app and locked our token to show as info given on page but i dont know how to add our token logo in that can any one help

Hi @ravi19821982, check this repo out: https://github.com/AlphaWallet/iconassets

**Comment by JamesSmartCell** [comment]
Hi @ravi19821982 did you manage to submit your icon update PR to our repo? Remember to lowercase your address directory.

**Comment by ravi19821982** [comment]
@JamesSmartCell  bro we clone this repo and change our repo address in code and now its working fine i am able to update or token even any token logo now .

thanks for help

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell bro we clone this repo and change our repo address in code and now its working fine i am able to update or token even any token logo now .
> 
> thanks for help

Nice, if you want your token in our repo just submit PR.
