### ISSUE TITLE
Update `tokens` repo's list of spam tokens

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3129]
- [x] Look at `iconassets` repo and build a list of the tokens (i.e. image files) that are images of spam tokens, X
- [x] Update the Spam Group in `tokens` repo (use `adjustment.json`) so that those spam tokens (X) are included in `tokens.json` (no editing might be needed)
- [ ] Update app to use them

**Comment by eviltofu** [comment]
How do I assign the channel id? @hboon

**Comment by hboon** [comment]
@eviltofu do you mean "chain ID"? Can you elaborate either way?

**Comment by eviltofu** [comment]
Doh I keep typing in the wrong thing. 

I mean in the step _update the spam group in tokens repo (use adjustment.json)_ if I find a token that has a spam token but is not in adjustment.json what should the chain ID be?

**Comment by hboon** [comment]
You'll have to figure it by checking it against each blockchain explorer site by entering the contract and see if that's the contract + chain ID

1. Open `modules/AlphaWalletFoundation/AlphaWalletFoundation/Settings/Types/RPCServers.swift`
2. Look for `return 137`, that gives you the whereabouts of all the chain IDs and the matching server (the enum-case)
3. For each of the chain IDs supported in the `tokens` repo that we have data for (there is just a handful, not all the ~30 we support in AlphaWallet), figure out the enum-case with the help of step (2)
4. Repeat step (2) but search for `return "https://cn.etherscan.com"`, this gives you the blockchain explorer site for each chain (enum-case) that you want.
5. Look to the list with the help of (4) and try searching for the contract and see if it looks like it's the one

**Comment by eviltofu** [comment]
There is a duplicate `0xfcb5df42e06a39e233dc707bb3a80311efd11576` in adjustment.json. There are two chain ID `56`s. I will remove the duplicate.

**Comment by eviltofu** [comment]
Is ![image](https://user-images.githubusercontent.com/1050309/224653314-c041944e-1d50-427a-970d-4424dab4f0d8.png) a spam token? I've been only counting ![image](https://user-images.githubusercontent.com/1050309/224653521-4a0e126c-1b18-47f8-9eaf-aa29954938f7.png).

**Comment by hboon** [comment]
Only the latter (the one with the "SPAM" image). At least for now

**Comment by eviltofu** [comment]
@hboon can't seem to find any chain id from cn.etherscan.com

**Comment by hboon** [comment]
From https://github.com/AlphaWallet/alpha-wallet-android/issues/3129#issuecomment-1465630577. eg. Look for 137, so we have:

```
case .polygon: return 137
```

and:

```
case .polygon: return "https://polygonscan.com"
```

**Comment by eviltofu** [comment]
This isn't the problem I was able to eventually get to polygonscan.com. After entering the contract address, how do I find the chain id? There is no attribute named chain id. https://polygonscan.com/address/0x7da85e8592b45dc0811cdca4e5b8267e7833a87d @hboon

**Comment by hboon** [comment]
That’s what I meant. polygonscan.com means a specific chain ID -> 137

**Comment by eviltofu** [comment]
Can I use these search results to determine the chain IDs? Using https://etherscan.io/ @hboon Then I just take the chain IDs from RPCServers.swift.

<img width="873" alt="Screenshot 2023-03-15 at 9 56 18 PM" src="https://user-images.githubusercontent.com/1050309/225331194-28204d13-6aa1-4945-9e5b-4f91b58730d8.png">
<img width="857" alt="Screenshot 2023-03-15 at 9 56 21 PM" src="https://user-images.githubusercontent.com/1050309/225331228-36e7a2fd-dd62-4087-8eb4-d0001ede112d.png">
<img width="831" alt="Screenshot 2023-03-15 at 9 56 14 PM" src="https://user-images.githubusercontent.com/1050309/225331235-43b4e817-c9b4-4b97-b2db-ec82e98562a0.png">

**Comment by hboon** [comment]
As long as it’s accurate :)

**Comment by eviltofu** [comment]
@hboon do I have to do task 3 (update the android app) or can this be sent to someone on the android team?

**Comment by hboon** [comment]
@eviltofu up to you. If it's simple and you are confident, contribute a PR.

**Comment by justindg** [comment]
I'm currently working on this for Android :)

> @hboon do I have to do task 3 (update the android app) or can this be sent to someone on the android team?

**Comment by hboon** [comment]
Ok. Coordinate and assign yourself to avoid duplicate work :)
