### ISSUE TITLE
Issue signing off-chain transactions with wallet-connect

### ISSUE THREAD

**Issue by nenadV91** [AlphaWallet/alpha-wallet-android#3139]
Hello Alpha team,

We are trying to implement a custom Alpha wallet button in our DAPP called CaWSwap.
This button is using [web3-react wallet-connect](https://github.com/Uniswap/web3-react/tree/main/packages/walletconnect) connector for connecting to your wallet.

We can connect to wallet and do approve/wrap/unwrap transactions
But off-chain transactions such as our swap/limit orders are not working and once these orders are created on the CoWSwap nothing is shown in the wallet and we can't sign them in the wallet.

[Here is a PR](https://github.com/cowprotocol/cowswap/pull/2099) with the [demo link ](https://swap-dev-git-wallet-alpha-cowswap.vercel.app/#/1/swap/WETH)

Could you help us fix this issue so we can proceed with this implementation.
Thank you in advance 🙏

**Comment by nenadV91** [comment]
Hey @hboon, thank you for such a fast response.
Our QA Elena tested this again today and seems that this issue is no longer there on IOS with the new Alpha wallet update but its still there for Android devices.

**Comment by justindg** [comment]
> Hey @hboon, thank you for such a fast response. Our QA Elena tested this again today and seems that this issue is no longer there on IOS with the new Alpha wallet update but its still there for Android devices.

Hi @nenadV91 , can you elaborate the steps you did to reproduce the issue for Android? I tried to do a ETH > COW swap in the Gorli network, and I was prompted to sign without issues.  

We also had an update for Android (around 15 hours ago) which contains a few WalletConnect fixes, let us know if you have tried that one out.

**Comment by nenadV91** [comment]
Hey @justindg, ETH -> some token transaction will work because it's a on-chain transaction.

To reproduce the issue try
1. Go to the [demo](https://swap-dev-git-wallet-alpha-cowswap.vercel.app/#/5/swap/WETH) 
2. Connect alpha wallet
3. If you don't have WETH, wrap some ETH->WETH
4. Try to trade WETH->some token and you should see the issue because nothing pops up in the wallet to sign.

The reason for this is that for those other tokens we use off-chain signing, that uses either [EIP712 (_signTypedData) or ETHSIGN (signMessage)](https://github.com/cowprotocol/contracts/blob/7efd5b43fbf46fe40bac9e6de1b6bab05d27c20b/src/ts/sign.ts#L134)

**Comment by justindg** [comment]
> Hey @justindg, ETH -> some token transaction will work because it's a on-chain transaction.
> 
> To reproduce the issue try
> 
> 1. Go to the [demo](https://swap-dev-git-wallet-alpha-cowswap.vercel.app/#/5/swap/WETH)
> 2. Connect alpha wallet
> 3. If you don't have WETH, wrap some ETH->WETH
> 4. Try to trade WETH->some token and you should see the issue because nothing pops up in the wallet to sign.
> 
> The reason for this is that for those other tokens we use off-chain signing, that uses either [EIP712 (_signTypedData) or ETHSIGN (signMessage)](https://github.com/cowprotocol/contracts/blob/7efd5b43fbf46fe40bac9e6de1b6bab05d27c20b/src/ts/sign.ts#L134)

Thanks for the detailed info. I found the issue and fixed it via #3141

**Comment by nenadV91** [comment]
@justindg That is awesome, can we merge it?
We also have the similar issue with ledger-live on Android and Desktop, so I've shared your solution with them, maybe its the same problem.
