### ISSUE TITLE
Switch to BlockPI RPC node for Klaytn

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3142]
We don't have an account yet (do we need one?)

Watch https://discord.com/channels/548357107267928064/801312516554096690/1084720856573411368 for confirmation

- [ ] Create iOS issue with details once confirmed and known

**Comment by JamesSmartCell** [comment]
This would help a lot - the current RPC is limited to 1 call per second which in one instance is causing issues.

**Comment by hboon** [comment]
No, we have a paid account with KAS which doesn't have the global limit — the free KAS node has a limit for everyone (not just AlphaWallet). But we are giving that up for reasons.

**Comment by hboon** [comment]
Yes, @justindg, let's go with BlockPI,

i.e. Switch away from using these for mainnet and testnet Klaytn. I don't know if BlockPI supports testnet:

* https://public-node-api.klaytnapi.com/v1/cypress
* https://node-api.klaytnapi.com/v1/klaytn
* https://api.baobab.klaytn.net:8651
* https://node-api.klaytnapi.com/v1/klaytn

**Comment by JamesSmartCell** [comment]
Hi @justindg I signed up for KAS. Let me create a new keys.secrets and pass to you - would you be able to connect it up via the key manager? Remember to update the dummy harnesses in the test harness.

**Comment by hboon** [comment]
Remember :) —

- [ ] Create iOS issue with details once confirmed and known

**Comment by hboon** [comment]
Done (with creating the iOS issue a while ago)
