### ISSUE TITLE
WalletConnect: sign from anywhere 

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#3155]
Currently, the sign-in dialog is only appearing on the HomeActivity page. 
If the user is on another page, such as the WalletConnect session list, the sign-in dialog will not be displayed.

**Comment by JamesSmartCell** [comment]
Is it possible to implement this as a service?

**Comment by seabornlee** [comment]
Do you want to receive notification event AW running in background?
If so, as I know, it's not possible on Android.

**Comment by hboon** [comment]
@seabornlee are you referring to the WalletConnect dapp/SDK asking AlphaWallet user to sign? If so, isn't this done by the SDK opening the deeplink?

**Comment by seabornlee** [comment]
No, I am closing this one since it's duplicated with #3080
