### ISSUE TITLE
"AMOUNT TO TRANSFER" in transfer eth screen remains in english after switching language in in-app settings

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#317]
![img_0210](https://user-images.githubusercontent.com/56189/45251203-c8b9d400-b374-11e8-820f-1279c96797ce.jpg)

* "AMOUNT TO TRANSFER"
* Additional "S" after "MY ADDRESS" in chinese.
* Also "Invalid Address" and "Invalid amount"

**Comment by JamesSmartCell** [comment]
fixed in commit e6abdbdb8c872baa292faf5b015767e8223633cf

**Comment by hboon** [comment]
Also this:

* Additional "S" after "MY ADDRESS" in chinese.
* Also "Invalid Address" and "Invalid amount"

(My bad. Should have put it above the screenshot)

**Comment by miang719** [comment]
@James-Sangalli pending for your translation strings

**Comment by James-Sangalli** [comment]
@JamesSmartCell bump @bootingman bump

**Comment by James-Sangalli** [comment]
These will be included in the translation service which will happen in clumps. closing all these issues.
