### ISSUE TITLE
Delay in wallet click

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#3173]
This is an oldie but it's a goldie.

On the 'Change / Add wallets page ("Wallets")' if you have a lot of wallets, only the right caret '>' of each wallet item can be selected for the first couple of seconds, then after a delay the whole item becomes selectable. Sometimes you just have to click twice. It's been like this for quite a while but haven't tried to diagnose it.

**Comment by justindg** [comment]
Likely caused by `android:descendantFocusability="blocksDescendants"` in the parent layout (`@id/container`)

**Comment by JamesSmartCell** [comment]
> Likely caused by `android:descendantFocusability="blocksDescendants"` in the parent layout (`@id/container`)

Sounds quite likely. Could you try it?
