### ISSUE TITLE
InputAddress does not display ProgressBar after entering ens

### ISSUE THREAD

**Issue by xiaohan445336816** [AlphaWallet/alpha-wallet-android#3189]
It should be caused by updating item_asset_image.xml

avatar_progress_spinner is placed in RelativeLayout and RelativeLayout is hidden by default

But the setWaiting and finishWaiting methods in UserAvatar have not been updated, and only show and hide the avatar_progress_spinner

**Comment by JamesSmartCell** [comment]
Thanks @xiaohan445336816 nice hide and explanation. I suspect that design changes rendered the progress not showing, as it was working correctly when first implemented. Should be an easy fix. If you like you could submit a PR :)
