### ISSUE TITLE
Add custom token screen error messages are not localized

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#319]
![img_0218](https://user-images.githubusercontent.com/56189/45261283-80142080-b431-11e8-8818-57e4b30f52ff.JPG)

**Comment by miang719** [comment]
@James-Sangalli pending for your translation strings

**Comment by James-Sangalli** [comment]
@hboon these will be included in the translation service which will happen in clumps. closing all these issues.
