### ISSUE TITLE
Add/Import wallet prompt is not localised

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#320]
![img_0216](https://user-images.githubusercontent.com/56189/45261291-a9cd4780-b431-11e8-9c18-726c8c9adbfe.JPG)

**Comment by miang719** [comment]
@James-Sangalli pending for your translation strings

**Comment by James-Sangalli** [comment]
@JamesSmartCell Chinese is not included in the localisation service as Chinese and English were the first two languages of the app

**Comment by James-Sangalli** [comment]
These will be included in the translation service which will happen in clumps. closing all these issues.
