### ISSUE TITLE
Backup wallet screen is not completely localized

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#321]
![img_0217](https://user-images.githubusercontent.com/56189/45261299-db461300-b431-11e8-92d6-d4f035b0e0c4.JPG)

**Comment by miang719** [comment]
@James-Sangalli pending for your translation strings

**Comment by James-Sangalli** [comment]
@miang719  up to @bootingman

**Comment by bootingman** [comment]
PR sent 
https://github.com/AlphaWallet/alpha-wallet-android/pull/483
