### ISSUE TITLE
Redeploy DMZ service

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3219]
To include #3217 . `master` branch (at anytime from now for simplicity, the Android code changes that is more active is unlikely to affect the DMZ service)

Similar to how it was done for #2679

---

Can verify deployment success by visiting https://aw.app/wc and comparing with the before/after screenshots in first comment of #3217

**Comment by abcfy2** [comment]
Should be done. Please check it.

**Comment by hboon** [comment]
Works for me. Thanks!
