### ISSUE TITLE
Switch locale prompt's title is not localized

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#322]
![img_0215](https://user-images.githubusercontent.com/56189/45261304-ea2cc580-b431-11e8-9fa3-4259410a9cf6.JPG)

**Comment by miang719** [comment]
@James-Sangalli pending for your translation strings

**Comment by bootingman** [comment]
PR sent
https://github.com/AlphaWallet/alpha-wallet-android/pull/483
