### ISSUE TITLE
Override XML confirmation dialog is not completely localized

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#323]
![img_0212](https://user-images.githubusercontent.com/56189/45261307-fca6ff00-b431-11e8-8fb2-ad2939d8322e.JPG)

**Comment by miang719** [comment]
@James-Sangalli pending for your translation strings

**Comment by bootingman** [comment]
PR sent
https://github.com/AlphaWallet/alpha-wallet-android/pull/483
