### ISSUE TITLE
Settings screen is not completely localized

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#324]
![img_0214](https://user-images.githubusercontent.com/56189/45261308-06306700-b432-11e8-974a-98b0b6962e2d.JPG)

**Comment by miang719** [comment]
@James-Sangalli pending for your translation strings

**Comment by bootingman** [comment]
translated, some strings missing in values-zh/strings.xml, I just add from values/strings.xml
