### ISSUE TITLE
Trying to run the project is a hell (Execution failed for task ':app:compileAnalyticsDebugJavaWithJavac'. > java.lang.IllegalAccessError: class io.realm.processor.Utils (in unnamed module @0x5015b8c7) cannot access class com.sun.tools.javac.code.Symbol$ClassSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x5015b8c7)

### ISSUE THREAD

**Issue by EAG-es** [AlphaWallet/alpha-wallet-android#3245]
2023-06-07 I try to clone this project
- 3 hours later Android Strudio seem to be reade to Make the project
- I got an error: Execution failed for task ':app:compileAnalyticsDebugJavaWithJavac'.
> java.lang.IllegalAccessError: class io.realm.processor.Utils (in unnamed module @0x5015b8c7) cannot access class com.sun.tools.javac.code.Symbol$ClassSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x5015b8c7
 -  I downgrade Java to Version SDK 8 
 - I try to upgrade Gradle to v8.0.1
 - I got another error....
 - I try to upgrade Gradle to v8.0.0
 - I got another error... Revert project
 - I am using 
Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- I got a Make fail: A problem occurred configuring project ':app'.
> org.codehaus.groovy.runtime.metaclass.MissingMethodExecutionFailed: No signature of method: org.gradle.api.reporting.internal.TaskGeneratedSingleFileReport.enabled() is applicable for argument types: (Boolean) values: [false]
 - And I resign to keep trying...
Project failure for me....
Hope others the best luck!!!

**Comment by JamesSmartCell** [comment]
Try using this JVM: File/Settings/Build, Execution, Deployment/Build Tools/Gradle

Gradle JDK: corretto-11 11.0.19

**Comment by JamesSmartCell** [comment]
I have upgraded the build to Corretto JVM 17:

JBR 17.0.6.
