### ISSUE TITLE
WalletConnect v2 + EIP-712 signing

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3258]
> AlphaWallet‘s EIP712 signing on WalletConnect v2 is broken everywhere (on v1 it works).

https://twitter.com/timdaub/status/1673591412045103104?s=20

**Comment by ravi19821982** [comment]
hello 

is there any update for wallet connect v2  bcoz in our wallet dapp are not working

**Comment by JamesSmartCell** [comment]
Yes, this has now been fixed. The release will be out very soon

**Comment by JamesSmartCell** [comment]
Release is out. v3.67
