### ISSUE TITLE
Wallet connect v2 is not working

### ISSUE THREAD

**Issue by vineetaparodkar** [AlphaWallet/alpha-wallet-android#3259]
We are trying to integrate wallet connect v2 with Alpha wallet. Our react native dapp redirects to web browser even though updated alpha wallet is installed on device.

Error message on web browser:
If you are using AlphaWallet with WalletConnect and facing issues please take the following steps:

Try using WalletConnect V2 (or latest version)
Try launching the application from within AlphaWallet app's Browser tab.

**Comment by ravi19821982** [comment]
hello vineeta 

i am also from india how can we connect  if possible text me on defilover2021 telegram

as we have not updated wallet but issue you can solve by update your react page i think.

**Comment by JamesSmartCell** [comment]
This should be fixed when the release goes out.

**Comment by JamesSmartCell** [comment]
Ok let me check - I missed the subtlety that it's launched from within the browser (sorry about that!).

**Comment by JamesSmartCell** [comment]
@vineetaparodkar Can you let me know your website, as I tested with this:

https://react-app.walletconnect.com/

and it works correctly from within the browser.

**Comment by vineetaparodkar** [comment]
We are trying this dapp example with Alpha wallet https://github.com/WalletConnect/react-native-examples

**Comment by JamesSmartCell** [comment]
Can you test against the reference dapp: https://react-app.walletconnect.com/

Yes you can also use normal web3 in the AlphaWallet browser as per metamask.

Alphawallet has full WalletConnect v2 support as far as we know. If you have an actual sample where it doesn't work can you share it?

**Comment by JamesSmartCell** [comment]
Hi @vineetaparodkar we worked out the issue - the wallet should work between two apps now.
