### ISSUE TITLE
Browser scroll lagging

### ISSUE THREAD

**Issue by abyuwono** [AlphaWallet/alpha-wallet-android#3263]
Why we tested several phones and we experienced lagging slow when scrolling inside the browser? We tested multiple website yahoo.com and other sites and still showing same issue. Thank you

**Comment by techyroots** [comment]
I am facing the same issues, is there any solution for this?

**Comment by JamesSmartCell** [comment]
Hi, this should be closed now, have you found the browser experience to be greatly improved with the last 2 releases?

**Comment by JamesSmartCell** [comment]
Closing, as browser experience is now much better. Thanks for reporting this, it inspired us to have a serious look at why it was slow and to solve it.
