### ISSUE TITLE
Alpha wallet issue with wallet connect 

### ISSUE THREAD

**Issue by arbaz-meo** [AlphaWallet/alpha-wallet-android#3267]
hello Guys 

i m trying to connect alpha wallet with wallect connect , my code let me connect with metamask and trust wallet but its not allow me to connect with alpha  wallet .

pop open when we click on approve then its says all event must approve 

![MicrosoftTeams-image (3)](https://github.com/AlphaWallet/alpha-wallet-android/assets/74611973/1f57424e-4b29-4dd1-85eb-cf9bf711fd19)
![MicrosoftTeams-image (5)](https://github.com/AlphaWallet/alpha-wallet-android/assets/74611973/3341d113-d239-41dd-8e22-db9aff3f1056)

![MicrosoftTeams-image (4)](https://github.com/AlphaWallet/alpha-wallet-android/assets/74611973/9c6695fb-fd5e-4cd2-aade-3207c8279d69)

**Comment by JamesSmartCell** [comment]
This has been fixed in v3.68
