### ISSUE TITLE
Search bar requires a full http url

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#329]
![screenshot_20180913-141827_alphawallet 1](https://user-images.githubusercontent.com/16630514/45471847-ee741e00-b764-11e8-86f5-9f9cd2161524.jpg)

**Comment by James-Sangalli** [comment]
@JamesSmartCell on browsers like chrome you do not need enter google.com, you can type a search term directly in the bar

**Comment by JamesSmartCell** [comment]
OK

**Comment by James-Sangalli** [comment]
@JamesSmartCell @justindg bump

**Comment by James-Sangalli** [comment]
@JamesSmartCell @justindg could we get this in? It is nice for the user
