### ISSUE TITLE
Token transfer transaction details shows wrong destination

### ISSUE THREAD

**Issue by tab00** [AlphaWallet/alpha-wallet-android#3291]
"To" shows the token contract address instead of the recipient.

You can fix it by changing
https://github.com/AlphaWallet/alpha-wallet-android/blob/1f4f698012f0f919b84260aebf202e39649d5a72/app/src/main/java/com/alphawallet/app/ui/TransactionDetailActivity.java#L206-L207
to
```java
String to = transaction.getDestination(token); 
 toValue.setText(to != null ? to : "");
```
and move it to after https://github.com/AlphaWallet/alpha-wallet-android/blob/1f4f698012f0f919b84260aebf202e39649d5a72/app/src/main/java/com/alphawallet/app/ui/TransactionDetailActivity.java#L219

**Comment by JamesSmartCell** [comment]
Thanks, will do
