### ISSUE TITLE
Show essential token details somewhere

### ISSUE THREAD

**Issue by tab00** [AlphaWallet/alpha-wallet-android#3292]
Details like contract address are important for the user to see, e.g. in case they  want to deposit them into an exchange.

Exchanges show what the contract address is of a token that they handle on their deposit screen. This allows a user to check that the address matches the address of the contract of the token that they want to deposit. So there should be an easy way to check the contract address of a token in the wallet app.

I've been clicking around but couldn't find the contract address of a token in the app.

The "Info" tab just shows *market* info, but not the essential information of a token.

**Comment by JamesSmartCell** [comment]
Yes, agree - for NFT we show contract address but to find the address of token you need to go to activity and then check the activity in the transaction list.
