### ISSUE TITLE
Make address on main screen copyable

### ISSUE THREAD

**Issue by tab00** [AlphaWallet/alpha-wallet-android#3308]
The main screen shows the address at the top. It'd be convenient if the address gets copied to the clipboard when clicked, as the user may need to send it to someone e.g. via WhatsApp.

**Comment by JamesSmartCell** [comment]
Good idea! Currently you can click on the hamburger menu and choose 'copy wallet address', but if you didn't see that and wanted to copy it then your idea is a better approach
