### ISSUE TITLE
ERC-1155 NFT image and metadata not showing

### ISSUE THREAD

**Issue by tab00** [AlphaWallet/alpha-wallet-android#3309]
Images for ERC-1155 NFTs aren't appearing - just a plain square shows with the symbol characters.

When you call `uri` in an ERC-1155 NFT contract it returns something like:

https://game.example/api/item/{id}.json

You must replace the `{id}` string with the actual token ID, in lowercase hexadecimal (with no 0x prefix) and leading zero padded to 64 hexadecimal characters, as specified in the [ERC-1155: Multi Token Standard](https://eips.ethereum.org/EIPS/eip-1155).

e.g. for token ID 2 you would replace {id} with 0000000000000000000000000000000000000000000000000000000000000002 to get the JSON metadata at https://game.example/api/item/0000000000000000000000000000000000000000000000000000000000000002.json

**Comment by JamesSmartCell** [comment]
Thanks, I wasn't aware of that nuance.

**Comment by tab00** [comment]
Thanks @JamesSmartCell , it works now when viewing the NFTs of a collection.

Though in the wallet "Collectibles" pane it still just shows a square with the symbol characters as the collection image. Maybe it should show the image of the first NFT found instead of just a plain square.

**Comment by JamesSmartCell** [comment]
> Thanks @JamesSmartCell , it works now when viewing the NFTs of a collection.
> 
> Though in the wallet "Collectibles" pane it still just shows a square with the symbol characters as the collection image. Maybe it should show the image of the first NFT found instead of just a plain square.

Yes that's something I've been intending to add for a while.
