### ISSUE TITLE
Inconsistency in the UI for the Dapp browser

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-android#331]
We need to make the UI for Android and iOS to be consistent.

I've designed the UI for Android's Dapp browser and put them up on InVision: https://invis.io/PYO5X20X87N#/321071520_1 and Zeplin for handover https://zpl.io/V00ow9m

Main concern in the UI for Android:

<img width="386" alt="screen shot 2018-09-20 at 9 54 48 pm" src="https://user-images.githubusercontent.com/20555752/45823241-daf62380-bd1f-11e8-9e11-5732192c769a.png">

The icons need to be consistent

<img width="389" alt="screen shot 2018-09-20 at 9 54 59 pm" src="https://user-images.githubusercontent.com/20555752/45823275-ed705d00-bd1f-11e8-82c7-7d593b3cf84e.png">
<img width="382" alt="screen shot 2018-09-20 at 9 56 25 pm" src="https://user-images.githubusercontent.com/20555752/45823346-0ed14900-bd20-11e8-841a-bf8cdc55a54e.png">

The browser needs to be consistent as well

**Comment by colourful-land** [comment]
@farrahfazirah I believe by "browser needs to be consistent" you mean the "more options icon" behaviour right?

**Comment by farrahfazirah** [comment]
@colourful-land Yes, the more options icon

**Comment by JamesSmartCell** [comment]
I will be tasking Justin with the UI upgrade next week, he'll need the graphic assets for the tabs

**Comment by farrahfazirah** [comment]
@JamesSmartCell I need Justin's e-mail to invite him to the Zeplin asset board. Do you have his e-mail?

**Comment by JamesSmartCell** [comment]
jrbdeguzman@gmail.com

**Comment by JamesSmartCell** [comment]
Justin de Guzman
