### ISSUE TITLE
Splash screen is dim

### ISSUE THREAD

**Issue by tab00** [AlphaWallet/alpha-wallet-android#3319]
The startup splash screen appears dim, as if it has a semi-transparent dark overlay. How can we make it appear without a dark overlay?

**Comment by tab00** [comment]
Where in the code can the dark overlay be removed?

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell where in the code can the dark overlay be removed?

https://github.com/AlphaWallet/alpha-wallet-android/blob/master/app/src/main/res/drawable/background_splash.xml

I don't know why it appears dim you could try changing the colours in the xml

**Comment by tab00** [comment]
> https://github.com/AlphaWallet/alpha-wallet-android/blob/master/app/src/main/res/drawable/background_splash.xml

Yes, I've already played around with that a lot, but haven't solved it yet.

**Comment by tab00** [comment]
I've found the cause. If you enable Dark Mode in Android settings then there will be a dark overlay:
![splash-screen-lime-dark-mode](https://github.com/AlphaWallet/alpha-wallet-android/assets/12715448/7ff277fb-b0b2-4ad4-99fb-479d155d8029)

If you disable Dark Mode then there'll be no dark overlay:
 ![splash-screen-lime-light-mode](https://github.com/AlphaWallet/alpha-wallet-android/assets/12715448/949294da-61e9-47c6-af9d-6a44811d8338)

So how can we have the dark overlay disabled regardless of lightness mode?
Would it be possible to force light mode in the app just during the splash screen so that the dark overlay will never appear?

**Comment by JamesSmartCell** [comment]
> I've found the cause. If you enable Dark Mode in Android settings then there will be a dark overlay: ![splash-screen-lime-dark-mode](https://user-images.githubusercontent.com/12715448/273320034-7ff277fb-b0b2-4ad4-99fb-479d155d8029.png)
> 
> If you disable Dark Mode then there'll be no dark overlay: ![splash-screen-lime-light-mode](https://user-images.githubusercontent.com/12715448/273320046-949294da-61e9-47c6-af9d-6a44811d8338.png)
> 
> So how can we have the dark overlay disabled regardless of lightness mode? Would it be possible to force light mode in the app just during the splash screen so that the dark overlay will never appear?

sounds like an Android rabbithole to spend a long time searching for a solution! If you find a way please let me know.

You can't just remove the overlay in the vector splash? Or brighten the colours in the logo a little?

**Comment by tab00** [comment]
> You can't just remove the overlay in the vector splash?

Where is the overlay?

Is it the app somehow placing the overlay when Android is in light mode, or is the OS doing that?

**Comment by JamesSmartCell** [comment]
Hi @tab00 fixed in this PR: #3332

**Comment by tab00** [comment]
Thanks @JamesSmartCell . So it's now using the new Splash Screens API, which is good. Though it doesn't seem to allow customizations like gradient or image background, or a fullscreen foreground image.
