### ISSUE TITLE
Issue with Maven Dependency from trustwallet/wallet-core Repository

### ISSUE THREAD

**Issue by dp77** [AlphaWallet/alpha-wallet-android#3322]
I am facing the same issue as mentioned in GitHub Issue [#3286](https://github.com/AlphaWallet/alpha-wallet-android/issues/3286) The error message I am receiving is:

'Could not GET 'https://maven.pkg.github.com/trustwallet/wallet-core/com/trustwallet/wallet-core/2.6.16/wallet-core-2.6.16.pom'. Received status code 401 from server: Unauthorized'

any guidance or solutions on how to fix this problem.

**Comment by JamesSmartCell** [comment]
Yes - I have bundled a public token in the gradle.properties but I guess it doesn't work for everyone.

You need to roll your own access token. 

Check out this: https://github.com/AlphaWallet/alpha-wallet-android#getting-started

you need to have:

```
gpr.user=Your GitHub Email
gpr.key=The GitHub Personal Access Token you created in previous step
```

then it should work. I don't like this style of locking access to the library but that's what they've gone with. We would prefer to move away from this dependency, maybe we can use the Trezor C library and compile with NDK.

**Comment by JamesSmartCell** [comment]
The one I added says it's still active, but perhaps they added an exclusion? 

To generate the token you just need to click on your github photo (NOT the settings in the top menu! as they say in the docs). Then 'Settings', then you should see 'Developer Settings' right at the bottom. Then you need to base64 encode the access token twice, so you go to https://www.base64encoder.io/ paste your key in there, then copy the result back into https://www.base64encoder.io/ and encode again.

The reason I have to do this twice is so github don't invalidate the access token when I check it in!

**Comment by dp77** [comment]
thanks its worked

**Comment by JamesSmartCell** [comment]
> thanks its worked

great
