### ISSUE TITLE
bad character in base64 value

### ISSUE THREAD

**Issue by puomlion** [AlphaWallet/alpha-wallet-android#3343]
when I tried to run  ./gradle build, I got the error feedback:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Sam\Desktop\alpha-wallet-android\build.gradle' line: 74

* What went wrong:
A problem occurred evaluating root project 'alpha-wallet-android'.
> bad character in base64 value

* Try:
> Run with --stacktrace option to get the stack trace.
PS C:\Users\Sam\Desktop\alpha-wallet-android> ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Sam\Desktop\alpha-wallet-android\build.gradle' line: 74

* What went wrong:
A problem occurred evaluating root project 'alpha-wallet-android'.
> bad character in base64 value

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by seabornlee** [comment]
`gpr.user` and `gpr.key` are required, read [more](https://github.com/AlphaWallet/alpha-wallet-android?tab=readme-ov-file#getting-started)

**Comment by puomlion** [comment]
I had to encode it twice before it worked.
Encoding it only once gives the error message 
"bad character in base64 value".
Thanks

**Comment by seabornlee** [comment]
Oh, sorry for didn't mention that. It's a simple trick to avoid GitHub security check.

**Comment by puomlion** [comment]
Hello Team

Please how I get Coinbase Pay ID ?
I created the api on the Coinbase commerce site and I pasted the keys in
the keys.c file.
I get an internal server error message when I click on Coinbase Pay button
on the app.

Any help?

R,
Samuel
