### ISSUE TITLE
Remove Telegram and Use Discord as the support channel

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#3373]
about: Need to remove and only have DIscord Smart Token Labs Channel as the way to support. Please consider this as urgent as there are some requests still coming through which are not looked after in timely manner. If its on Discord we can use our mod team to extend support.

Discord Invite: https://discord.gg/nbb9VSF85A

**Comment by JamesSmartCell** [comment]
Fixed in https://github.com/AlphaWallet/alpha-wallet-android/commit/26e15c62c583c831160afb35cfbe34ff722316b6
