### ISSUE TITLE
Verify if quicknode is accessible from China

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#342]
Can you do the following?

Contact the team, ask for a trial access to their Ethereum nodes.

Obtain a temporary credential to access their node directly - note that Ethereum node doesn't use http/https so it perhaps isn't blocked. Also the node may run on a different server than the website itself.

Run a test connection. If you are unsure how to reach an Ethereum node, google or ask Sangalli.

**Comment by James-Sangalli** [comment]
@colourful-land Can't see how this could even be banned in china but @bootingman can you please test this soon?

**Comment by colourful-land** [comment]
#336 will address this issue so this is closed. If Mark's Akiolabs can't do this for us, reopen this.
