### ISSUE TITLE
Standardise Icons

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#346]
Standardise icons on Android build.

Resources in Zeplin, there is a guide for how iOS appears. Do not copy this directly as it's iOS native but use the same assets. The existing layout is sufficient but ensure the width adjusts correctly and the bookmark and favourite icons move into the triple-dot expand-menu appropriately with screen width.

**Comment by James-Sangalli** [comment]
Obsolete
