### ISSUE TITLE
Show CryptoKitty thumbnail + attributes on tokens detail page

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#348]
Show CryptoKitty thumbnail + attributes on tokens detail page (AssetDisplayActivity).

**Comment by James-Sangalli** [comment]
@JamesSmartCell @justindg I guess this is done? If so, please reference to the PR

**Comment by justindg** [comment]
@James-Sangalli yup! It was included in https://github.com/AlphaWallet/alpha-wallet-android/pull/360

**Comment by James-Sangalli** [comment]
@justindg these commits were not merged? If they are please reference and close this issue

**Comment by justindg** [comment]
@James-Sangalli my bad - it's in https://github.com/AlphaWallet/alpha-wallet-android/pull/374 :)
