### ISSUE TITLE
Enable SNS notifications 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#357]
This has already been setup on iOS and has the control panel setup for SNS in general. The android version is not implemented in this repository yet.

Requires the following:
- Be able to register the device token to SNS
- Be able to get a notification from the control panel
- Enable the appropriate permissions
- Work with Baidu cloud (can be pursued after GCM or Firebase) 

I have credentials for SNS and firebase which I can provide on demand.

**Comment by James-Sangalli** [comment]
@justindg this boilerplate code might help you: https://github.com/AlphaWallet/alpha-wallet-android/tree/with-amazon-sns

**Comment by miang719** [comment]
@justindg, any follow up on this issue?

**Comment by justindg** [comment]
Hi all, sincere apologies for the delay - I am able to send Push Notifications via Firebase already but I'm running into issues integrating with SNS.

Some concern though: a few weeks back we've talked about the issue with Google Play Services and China. Firebase Messaging requires Google Play Services for it to work. @James-Sangalli, what did you use for iOS?

**Comment by James-Sangalli** [comment]
@justindg the firewall problems are not an issue for iOS because iOS has it's own notification centre. 

could you be more specific about your issues with SNS?

**Comment by justindg** [comment]
@James-Sangalli I am now able to register device tokens and publish notifications to SNS. 

Just wondering - how/where did you store AWS credentials? Figured they're needed to register the device tokens automatically through the app.
