### ISSUE TITLE
Three kitties not displayed

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#358]
Reproduce:

1. Import the private key in #200  and make sure mainnet is selected.

2. Scan the QR code for the crypto kitties contract.

3. mobile shows 0 CryptoKitties.

This is the proof that the wallet has 3 kitties:

 http://api.akiolabs.com/alpha-wallet/v1/assets?address=0xe188e8e7fca9e5d09b5a66148b072ecca936266b 
(search for "token_id")

@JamesSmartCell @justindg  If Justing de Guzman's update has a fix with this, be sure to mention the bug so it's closed by the PR>

**Comment by JamesSmartCell** [comment]
Not a bug.

Kitties/ERC721 not yet supported in Android ... ETA later this week.

**Comment by JamesSmartCell** [comment]
See #346, #347, #348, #349 and also the overall project concerning the UI overhaul project in the project tab. 

https://github.com/AlphaWallet/alpha-wallet-android/projects

**Comment by colourful-land** [comment]
You forgot to close this one!
