### ISSUE TITLE
Upgrade ERC875 spec to replace bytes32 and uint16 with uint256

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#370]
This breaks backward compatibility...

**Comment by miang719** [comment]
@hboon take a look

**Comment by hboon** [comment]
@miang719 this is for Android though. iOS's done with https://github.com/AlphaWallet/alpha-wallet-ios/issues/812

**Comment by James-Sangalli** [comment]
@JamesSmartCell is this ready?

**Comment by James-Sangalli** [comment]
Done in here #388 @JamesSmartCell please reference issues in PRs from now on.
