### ISSUE TITLE
(Android) support the dynamic fields in standard meetup contract

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#375]
In the standard Peter's contract (the spawnable contract)'s XML there are some fields whose value is obtained through smart contract calls, not embedded in the `tokenID`. These must be displayed correctly and refreshed at a suitable frequency lest the contract changes its internal state.

The standard xml is MeetupContract.xml

 https://github.com/AlphaWallet/contracts/blob/master/spawnable-contract/schema1/MeetupContract.xml

The parts that need to be displayed on the UI are the following (observe closely the `<function>` calls)

    <attribute-type id="expired" syntax="1.3.6.1.4.1.1466.115.121.1.7">
      <origin contract="holding-contract">
        <function>isExpired</function>
      </origin>
    </attribute-type>
    <attribute-type id="street" syntax="1.3.6.1.4.1.1466.115.121.1.7">
      <origin contract="holding-contract">
        <function>getStreet</function>
        <parameter>TokenID</parameter>
      </origin>
    </attribute-type>
    <attribute-type id="building" syntax="1.3.6.1.4.1.1466.115.121.1.7">
      <origin contract="holding-contract">
        <function>getBuildingName</function>
        <parameter>TokenID</parameter>
      </origin>
    </attribute-type>
    <attribute-type id="state" syntax="1.3.6.1.4.1.1466.115.121.1.7">
      <origin contract="holding-contract">
        <function>getState</function>
        <parameter>TokenID</parameter>
      </origin>
    </attribute-type>

Refer to iOS development progress at
https://github.com/AlphaWallet/alpha-wallet-ios/issues/869

**Comment by colourful-land** [comment]
This issue is a duplicate of https://github.com/lyhistory/Peter-s-Tool/issues/4 which is assigned to me. I'll handle it.

**Comment by colourful-land** [comment]
Keenly observe that the data structure around `getState` has changed.

    <tb:attribute-type id="state" syntax="1.3.6.1.4.1.1466.115.121.1.15" as="utf8"> 
      <tb:origin contract="holding-contract">
        <tb:function name="getState">
          <tb:inputs>
            <tb:uint256 ref="tokenID"/>
          </tb:inputs>
        </tb:function>
      </tb:origin>
    </tb:attribute-type>

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/alpha-wallet-android/pull/552
