### ISSUE TITLE
Support collectibles' images that changes, eg. Chibi Fighters grow from baby to adult 

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#387]
Not sure if this affects Android [1]

Basically, the image URLs below can serve different image content as time goes by. eg. for Chibi Fighters, it might start out as a baby and switch to an adult:

    {
        "external_link" : "https://chibifighters.io/chibi/2213",
        "image_thumbnail_url" : "https://storage.googleapis.com/opensea-prod.appspot.com/0x71c118b00759b0851785642541ceb0f4ceea0bd5-thumbnail/2213.png",
        "permalink" : "https://opensea.io/assets/0x71c118b00759b0851785642541ceb0f4ceea0bd5/2213",
        "image_preview_url" : "https://storage.googleapis.com/opensea-prod.appspot.com/0x71c118b00759b0851785642541ceb0f4ceea0bd5-preview/2213.png",
        "image_url" : "https://storage.googleapis.com/opensea-prod.appspot.com/0x71c118b00759b0851785642541ceb0f4ceea0bd5/2213.png",
        ...
    }

I only know about https://chibifighters.io/ for now. Victor might know about more. For Chibi Fighters, it needs to be a baby. Those you buy directly from them are babies. Not sure if you can get any from the open market.

[1] https://github.com/AlphaWallet/alpha-wallet-ios/issues/865

**Comment by JamesSmartCell** [comment]
ok thanks. Does the URL change when the image changes or does it just update the image at the same URL?

**Comment by hboon** [comment]
Same URL.

**Comment by jzaki** [comment]
Resurfaced with POAP erc721 event images. Still related to iOS#865

**Comment by JamesSmartCell** [comment]
Tested by replacing the image the metadata points to, identical URL but different image.

Result: Image updated correctly.
