### ISSUE TITLE
(Android) XML to have TBML namespace

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#394]
1. Switch to  `recognises-xml-namespace` branch

https://github.com/AlphaWallet/alpha-wallet-android/tree/recognises-xml-namespace

This branch has all the code tested after namespace change, tested against the testcases;

2. Observe the new XML format in the new repo (link provided in a comment below)

3. Change the android code to use the new repo server repo.aw.app

4. adjust these lines in `lib/src/main/java/io/stormbird/token/tools/TokenDefinition.java` to get the function returned correctly following the new XML format

                    switch(origin.getAttribute("contract").toLowerCase()) {
                        case "holding-contract":
                            as = As.Mapping;
                            // TODO: Syntax is not checked
                            getFunctions(origin);
                            break;
                        default:
                            break;
                    }

5. Make a pull request of the entire thing if the app works as you expected.

**Comment by colourful-land** [comment]
repo.aw.app is online now. Its XML, however, has not been fully updated to allow ABI embedded in XML, see https://github.com/AlphaWallet/contracts/issues/70

Example: https://repo.aw.app/0xA66A3F08068174e8F005112A8b2c7A507a822335

**Comment by JamesSmartCell** [comment]
Check out the update I made. With this update the app can start.

When parsing the new format (namespace) meetup XML check for "*** Developer warning - error in XML format at tag ... ***" output, there is an issue with reading the file.

**Comment by colourful-land** [comment]
A reminder: It's not desirable to be compatible with the legacy and the namespaced version at the same time thanks to the cases like `<option>` appearing in two namespaces. it will be too confusing if the code is guessing what `<option>` is about. 

Every single XML file that was in the legacy format was modified to use namespace in the new repo. We can only do such thing ones, before the user submitting their own signed XML, and that's why we should not be open about new TBML unless the namespace change dust is settled.

The new Android app should detect a legacy version and refuse to use it and download the corresponding XML instead. If a token doesn't have a namespace TBML (404 or 406 from repo.aw.app), it should be considered as if no XML has been written for that token. If an XML file was found existing and not have namespace, it should be deleted from the mobile phone even if there is no upstream repo equivalent to fill in the blank.

**Comment by JamesSmartCell** [comment]
This is now complete and integrated. Legacy is not parsed.

**Comment by James-Sangalli** [comment]
@JamesSmartCell please reference where it was merged
