### ISSUE TITLE
Include HTTP headers in the GET request for asset definition file

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#395]
1. The headers:

```
curl -H "Accept: text/xml; charset=UTF-8" -H "IF-Modified-Since: Mon, 02 Jul 2018 13:23:00 GMT" -H "X-Client-Name: AlphaWallet" -H "X-Client-Version: 1.0.3" -H "X-Platform-Name: iOS" -H "X-Platform-Version: 11.1.2" https://repo.awallet.io/0xd8e5f58de3933e1e35f9c65eb72cb188674624f3
```

Accept — "text/xml; charset=UTF-8"
X-Client-Name — "AlphaWallet"
X-Client-Version — the app version number
X-Platform-Name — "iOS" or "Android"
X-Platform-Version - OS version number

and

IF-Modified-Since — timestamp the file was last saved. Only include if the file is already cached

2. Should also check for the HTTP status code `304` (if and when the repo supports it) which means the content is unchanged and the body will not be in the response

3. Let's also standardize standardise the app version number format for iOS and Android. Maybe not as far as applying https://semver.org (though would be good, but maybe later), but at least we can agree that it's in the format `x.y(.z)?`? e.g. `1.2`, `1.2.3`, `2.0` but not `1`. Helps with parsing on the server side for the short term.

**Comment by JamesSmartCell** [comment]
Fixed in PR #399
