### ISSUE TITLE
Github releases not updated -- why?

### ISSUE THREAD

**Issue by leafcutterant** [AlphaWallet/alpha-wallet-android#396]
The latest [APK release](https://github.com/AlphaWallet/alpha-wallet-android/releases) on Github is 1.0.11 (pre-release, experimental), while the current stable on [Google play](https://play.google.com/store/apps/details?id=io.stormbird.wallet) is 1.0.14.

Why do you force your users to go though Google to be able to use the latest version?

**Comment by zhangzhongnan928** [comment]
@JamesSmartCell

**Comment by James-Sangalli** [comment]
@leafcutterant sorry for that! We have created a new release to match this. Cheers.
