### ISSUE TITLE
hiding twitter, facebook and forum into one "Contact us" label

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#401]
hiding twitter, facebook and community into one contact us label

**Comment by James-Sangalli** [comment]
@justindg feel free to take this up

**Comment by ronakdave195** [comment]
@James-Sangalli May I kindly request you to confirm if the word community refers to Telegram and Reddit options in Settings.

**Comment by James-Sangalli** [comment]
@tomekalphawallet please comment on this as I believe you had removed this from the design

**Comment by tomekalphawallet** [comment]
Yes, this is correct. I moved this to Support.

Sketch Cloud:
https://sketch.cloud/s/jDODG/a/4nLd9d
https://sketch.cloud/s/jDODG/a/0MqWx2

Zeplin:
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e21dbe52d0e9457c9e2823c/
https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e21dbe3444ae12ba600c510/

<img width="646" alt="Screenshot 2020-02-12 00 29 11" src="https://user-images.githubusercontent.com/51817359/74289428-57334180-4d2f-11ea-9ca6-d0b1a89903fa.png">
<img width="691" alt="Screenshot 2020-02-12 00 28 59" src="https://user-images.githubusercontent.com/51817359/74289435-5a2e3200-4d2f-11ea-8779-afa05c978d4f.png">

**Comment by ChintanRathod** [comment]
@tomekalphawallet Design of whole Setting page is different then existing one. While implementing this "Support" page, do you wish to change whole design of Setting page or not? 

For time being, I can only add "Support' button in existing list and move shown social buttons to next page without changing the icons, style/design. 

Kindly share your opinion.

**Comment by jzaki** [comment]
> add "Support' button in existing list and move shown social buttons to next page without changing the icons, style/design.
@ChintanRathod yes, this makes sense. The redesign is a separate set of tickets.

**Comment by JamesSmartCell** [comment]
closing as no longer relevant
