### ISSUE TITLE
Is there some debug methods when use alpha-wallet-android?

### ISSUE THREAD

**Issue by duncanwang** [AlphaWallet/alpha-wallet-android#404]
Is there some debug methods when use alpha-wallet-android? Because I want to find some code bugs.

**Comment by JamesSmartCell** [comment]
Yes there is a good way to debug natively on the Android.

First you need to go to the dapp site on the android like this:

![target](https://user-images.githubusercontent.com/12689544/48654672-15034d80-ea63-11e8-8485-61ca495b9da7.jpg)

then open the debugger on Chrome (F12).

Click on the debugger control button on Chrome - 

![remote1-](https://user-images.githubusercontent.com/12689544/48654761-aecafa80-ea63-11e8-810e-25bb5c3921b8.png)

And then click 'more tools' and 'remote devices':

![remote2-](https://user-images.githubusercontent.com/12689544/48654798-f3569600-ea63-11e8-8d56-64aaf72d5321.png)

If you connected your phone you should see it in the list of phones in the remote window:

![remote4](https://user-images.githubusercontent.com/12689544/48654821-0f5a3780-ea64-11e8-8841-21cdc9d57881.PNG)

Then click on the name of the phone you're debugging, in my case the Mi MIX 2, you should see your last chrome search on the main debugger. Scroll down the list and you'll see 'WebView in io.stormbird.wallet' and your current dapp page:

![remote5-](https://user-images.githubusercontent.com/12689544/48654857-7546bf00-ea64-11e8-8886-0fef075eb3f9.png)

Click on Inspect:

![remote6](https://user-images.githubusercontent.com/12689544/48654848-58aa8700-ea64-11e8-8e80-09d2f727b8a9.PNG)

You can now debug the JS as you would a normal website, using the Chrome tools.

Hope this helps,

if you can think of any useful features we can add to make app debugging better please let us know.

**Comment by James-Sangalli** [comment]
@duncanwang are you satisfied with this answer?

**Comment by pertsev** [comment]
@JamesSmartCell It seems the debugging is disabled now. (I see webviews from other apps like trustwallet e.g.)

**Comment by James-Sangalli** [comment]
@pertsev should still be working as I tested this with Chrome recently, is it still an issue on your end with the latest build from the play store?

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell It seems the debugging is disabled now. (I see webviews from other apps like trustwallet e.g.)

Yes you would see those in the debug window as any webview is visible. When you say debugging do you mean debugging the app itself or debugging dapps? I presumed you mean debugging dapps because we're open source.

**Comment by nosovk** [comment]
Hello

> Yes there is a good way to debug natively on the Android.
> 
> First you need to go to the dapp site on the android like this:
> 
> ![target](https://user-images.githubusercontent.com/12689544/48654672-15034d80-ea63-11e8-8485-61ca495b9da7.jpg)
> 
> then open the debugger on Chrome (F12).
> 
> Click on the debugger control button on Chrome -
> 
> ![remote1-](https://user-images.githubusercontent.com/12689544/48654761-aecafa80-ea63-11e8-810e-25bb5c3921b8.png)
> 
> And then click 'more tools' and 'remote devices':
> 
> ![remote2-](https://user-images.githubusercontent.com/12689544/48654798-f3569600-ea63-11e8-8d56-64aaf72d5321.png)
> 
> If you connected your phone you should see it in the list of phones in the remote window:
> 
> ![remote4](https://user-images.githubusercontent.com/12689544/48654821-0f5a3780-ea64-11e8-8841-21cdc9d57881.PNG)
> 
> Then click on the name of the phone you're debugging, in my case the Mi MIX 2, you should see your last chrome search on the Google Chrome App. Scroll down the list and you'll see 'WebView in io.stormbird.wallet' and your current dapp page:
> 
> ![remote5-](https://user-images.githubusercontent.com/12689544/48654857-7546bf00-ea64-11e8-8886-0fef075eb3f9.png)
> 
> Click on Inspect:
> 
> ![remote6](https://user-images.githubusercontent.com/12689544/48654848-58aa8700-ea64-11e8-8e80-09d2f727b8a9.PNG)
> 
> You can now debug the JS as you would a normal website, using the Chrome tools.
> 
> Hope this helps,
> 
> if you can think of any useful features we can add to make app debugging better please let us know.

This debug method is not working now, probably in play store build there was disabled webview debuging. Now you can't debug errors that apper with embedded web3 provider.

**Comment by nosovk** [comment]
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews
webview debug need to be explict enabled in alphawallet code.

**Comment by JamesSmartCell** [comment]
@nosovk Thanks, I'll add this in.

**Comment by nosovk** [comment]
https://github.com/AlphaWallet/alpha-wallet-android/commit/f5b7694de94c3300c43151447e4260f5e26187d5
I see it in muster, will try to build app now.

**Comment by nosovk** [comment]
is there any release plan?
Latest update in market was 7 days ago, just before accepted fix. Is there some release map?
