### ISSUE TITLE
Can you adopt a pet dog success?

### ISSUE THREAD

**Issue by duncanwang** [AlphaWallet/alpha-wallet-android#405]
Please open the websitehttp://112.124.104.209:3000/ in alpha-wallet-android DAPP browser with selecting the network of the ropsten test network.
Click "Adopt" Button when to adopt a dog. Can it be success?
I can't get sucess, and I want to know how to debug in alpha-wallet-android DAPP browser ?

**Comment by zhangzhongnan928** [comment]
Works on iOS DApp browser @JamesSmartCell

**Comment by JamesSmartCell** [comment]
@duncanwang I was able to access the website yesterday but today I get ERR_CONNECTION_REFUSED.

Could you make the site available again so I can fix the issue?

**Comment by JamesSmartCell** [comment]
Fixed in PR #409
