### ISSUE TITLE
Support EIP1102 aka. Privacy Mode or at least test to verify it doesn't break dapp browser

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#416]
https://eips.ethereum.org/EIPS/eip-1102

https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

**Comment by James-Sangalli** [comment]
@hboon our web3.js dist supports this and it is up to the dapp to decide whether this is enabled or not. Closing.
