### ISSUE TITLE
Web3.js should come from gradle not be included in source code 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#427]

**Comment by JamesSmartCell** [comment]
Do you mean gradle should pull it from the web? There is a danger here that changing the web3.js will result in incompatibilities with existing code. This would have to be done with great care in order not to release a broken build.

**Comment by JamesSmartCell** [comment]
Also, can you explain why you labelled this as a bug?

**Comment by James-Sangalli** [comment]
@JamesSmartCell no, can pull from the repo provider etc. It has versioning to prevent such an attack.

**Comment by James-Sangalli** [comment]
Duplicate.
