### ISSUE TITLE
Sign message return incorrect result

### ISSUE THREAD

**Issue by emn178** [AlphaWallet/alpha-wallet-android#438]
You have the same bug I reported to Trust, Please refer to
https://github.com/TrustWallet/TrustSDK-Android/issues/9#issuecomment-423478284

![image](https://user-images.githubusercontent.com/3477613/48818430-442cfe00-ed86-11e8-8fbb-454167d7a5c5.png)

**Comment by miang719** [comment]
bump @JamesSmartCell

**Comment by JamesSmartCell** [comment]
This is fixed in PR #448 , will be in release 1.30.1 which should be out today or tomorrow.
