### ISSUE TITLE
Use AlphaWallet-web3-provider

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#444]
Can replace the nervos dist and be brought in via a dependency rather than being in the source. 

As for the worries about being sent bad web3.js code, you can usually source it from a particular commit.

**Comment by JamesSmartCell** [comment]
this is already done in a branch before the issue was raised. No need for issue, closing.

**Comment by James-Sangalli** [comment]
@JamesSmartCell web3.js is still a file in the source, this is probably ok tho
