### ISSUE TITLE
Address is not checksumed

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#445]
0xe188e8e7fca9e5d09b5a66148b072ecca936266b is my address on Android. everything is in lowercase. It remains so after being copied in to a clipboard.

Many services refuses to accept such Ethereum addresses with the concern that the user might have mistyped a character.

P.S. Consider storing checksummed address internally in the wallet (i.e. not only as a Big Integer) just in case.

**Comment by colourful-land** [comment]
@JamesSmartCell bump

**Comment by James-Sangalli** [comment]
This is solved now
