### ISSUE TITLE
Move DApp browser icon on the navigation bar to the third position

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-android#465]
The DApp browser icon on the navigation bar should be the third icon on the navigation bar. It should be placed to the right of the transaction history icon. This issue is brought up to maintain the same UI for both iOS and Android.

![rsz_dappbrowsricon](https://user-images.githubusercontent.com/20555752/49709166-0416b800-fc6e-11e8-83e1-10c69f4ce5c9.png)

**Comment by James-Sangalli** [comment]
Outdated.
