### ISSUE TITLE
XML Display issue

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#479]
Same XML, different display on iOS and Andriod

0x3F02F7629998B8022730f3822c994fA4610897cb
on ropsten
![img_2281](https://user-images.githubusercontent.com/33795543/50394216-1416b780-0797-11e9-9fd7-ecaefb0a4f91.PNG)
![2018-12-24 16 10 45](https://user-images.githubusercontent.com/33795543/50394251-458f8300-0797-11e9-8b77-4bda6c48400f.jpg)

0x87F57dc07073C0166072bBaD36406c3C290deF65
on mainnet
![img_2280](https://user-images.githubusercontent.com/33795543/50394250-44f6ec80-0797-11e9-90b1-518ff2348ebc.PNG)
![2018-12-24 16 09 40](https://user-images.githubusercontent.com/33795543/50394217-1416b780-0797-11e9-8a04-a347359f2409.jpg)

XML as attached
[Archive.zip](https://github.com/AlphaWallet/alpha-wallet-android/files/2706865/Archive.zip)

**Comment by JamesSmartCell** [comment]
First issue is not a bug, Android is displaying the XML correctly. 

'introduction' tag is displayed when user has 0 tokens, 'instruction' tag is displayed when user has balance. In the XML the 'Instruction' tag contains exactly the information displayed. A page with overlapping graphic and text with a mix of office door instruction and edcon info. With a zero balance the ticket displays correctly.

Here is the instruction tag, displayed when there is positive balance:

<t:instruction xml:lang="en">
      <h1>Instructions to open the office door</h1>
      <iframe src="https://google.com.sg/"></iframe>
      <img alt="A numeric pad with 10 digits, with asterisk on the lower-left corner and number sign on the lower-right corner."
           src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGoAAABUAQMAAABQnzAJAAAABlBMVEX///8AAABVwtN+AAAACXBI
WXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4goXCAQH5D1msQAAAUdJREFUOMvVkzFSwzAQRf/KArtg
gulTaHICH4AZFCofipmo8AE4AkfREXKEHMElnfkryQ4xDE0oQONi32il3f+1Bn5c1TSNeJqmHOBO
vwjEFKBjQsWsTgPAAWKIrQaAR8CALRpfjwy9KO6IaInBBPTYwwaeY6pVFEWfTioaxbigXZITNopt
SR8YlZszOqJ1DF09sqsDu6qifOl5pWil95p1nXWeEg6UIKekKBI9kTkUL57yPeXb5LK5RKv4QrxJ
1jW+OHmbrLs/FZ9ttk4LiXqVrVN81kLJOj6awSO7kj9sXXrfzdykzsCAh1mCpwgOQygCVVPP3SJf
93uetcF0C+quHJcxc6GM2QrzmGkhuGXqNsQqpjIXD/pPpg7lh5Wzot2Mwb6WH1bSIJm3gvW7osTv
dzMuZ1Nyvnl/LoTPhXJXW31Q96vWfQA1zLLR3ye5DwAAAABJRU5ErkJggg==" style="float: left;"/>
      <ol>
        <li>The EDCON 2019 (Community Ethereum Development Conference) is the non-profit global conference which will happen in Sydney, Australia in April 2019. The purpose of the conference is to improve communication among the various communities and to promote Ethereum ecosystem development on a global scale. EDCON is organized as a conference series, once a year in different countries. The previous EDCONs were held successfully in ESCP Europe, Paris 2017, and Ryerson University, Toronto 2018 (both were oganized by LinkTime, a Chinese community representative). The Ethereum Foundation and various Ethereum communities have been showing their strongly supports to our high quality community conferences.</li>
      </ol>
    </t:instruction>

If IOS is displaying correctly then there must be a different version of XML, or iphone is not using the schema agreed during the week. The display you showed with iphone is displaying the 'introduction' tag when there is a balance, which is incorrect unless there's a different version of XML.

I will check the other contract.

**Comment by James-Sangalli** [comment]
@JamesSmartCell sounds good, please reference and close when it's fixed
