### ISSUE TITLE
aw.app as an app directory

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#484]
need to read this issue together with Victor's email "A small improved version........."

Victor had a vision of a website for DApp reviewing and sharing. After having talked to him on the phone I inscribe for him the following.

Suppose we have a website, let's say the future version of aw.app, which serves the purpose of.

Let aw.app be a directory of all dapps, akin to Yahoo before Google forced it into a search engine, or akin to AppStore nowadays. It is a Dapp itself, so that people can leave signed messages on it.

It allows Dapp owners to publish their Dapp on the website, write a title and a description and potentially some screenshots. It also allows the users to leave a comment from 1 star to 5 stars about each Dapp, digitally signed. It allows the Dapp author to reply to these comments, again digitally signed and verifiably from the issuers of the contracts.

Let's start with an example of a Dapp entry on it.

http://aw.app/www.kingoftheether.com is an entry for a Dapp called King of The Ether.

It has the following content:

> Title: King of the Ether.

> Description: An Ethereum contract, living on the blockchain, that will make you a King or Queen, might grant you riches, and will immortalize your name

> [optional] preview image.

> Data of the Dapp. For example, what tokens are usable in this Dapp. how many Ethers have been wasted on it)

> - Comment section with the first 3 comments, must be digitally signed. A check mark is displayed if the digital signature recovers an Ethereum address that had actual interaction with the Dapp's corresponding smart-contract.

If opened on a device with web3 objects (e.g. Metamask enabled browser), there is

> an action button to enter the Dapp

Otherwise, there is

> (potentially animated) Instruction on how to install AlphaWallet on the mobile phone.

If the link is opened on a device which already has AlphaWallet installed, then AlphaWallet opens the Dapp with the same view as it would open on the web, except handled natively in the app.

That's the vision how it would work per Victor.

Procedure-wise, I hope @zhangzhongnan928  and @farrahfazirah can build a storyboard of it before he actually ask @James-Sangalli or peter to produce the code. Then, we need a managing editor to keep things running, e.g. publishing app title and description in a signed way, deleting bad comments for a fee^h^h^h^h^h spam deterring. @bootingman can be that person. If @bootingman is the manager, he should be involved in early stage.

I'll provide some technical comments.

- The basic data (the title of the Dapp, the description in each lingo and so like) can be cryptographically signed or unsigned, but it's simpler technically to always sign it, by default by ourselves using an editor key. It can be stored in a traditional SQL database. Victor and I discussed inventing a new descriptive language akin to TBML to describe Dapps, e.g. Dapp Behaviour Language, to embed this information, but I conclude that it would be over-designed.

- When designing a database table, for every text field remember to have a relational database to localise it and a separate digital signature field to store its signature. If not sure how this should be done, make sure a master is involved (I can guide @James-Sangalli or Peter on this if needed.).

- There is no need for a corresponding smart contract in the beginning but we might use one for key management or donation.

- I think it can still reside on DMZ project which currently handles aw.app domain because the web service does not need to hold any key.

- The link used in the example, http://aw.app/www.kingoftheether.com is not a signed link like our previous Magic Link for atomic swap. Therefore please refrain from calling every link magic link since nothing magical can happen (when there is no signature). Just call it **share link**.

**Comment by James-Sangalli** [comment]
@colourful-land perhaps you are thinking of a more advanced version of this: https://www.stateofthedapps.com/

**Comment by zhangzhongnan928** [comment]
@James-Sangalli 

> @colourful-land perhaps you are thinking of a more advanced version of this: https://www.stateofthedapps.com/

@

**Comment by zhangzhongnan928** [comment]
Close by mistake.



> @colourful-land perhaps you are thinking of a more advanced version of this: https://www.stateofthedapps.com/

@James-Sangalli you need to read this issue together with my email "A small improved version........."

**Comment by zhangzhongnan928** [comment]
@farrahfazirah based on Weiwu's description and Apple App Store's UX. 
Can we draw 2 store boards:
1. a non-crypto user read some articles about an interesting DApp, they search the google and find our DApp review site, he read the information on our site and decide to use the DApp, he clicks the open DApp button, then pops up a landing page to teach him install AlphaWallet page and click the open button again.

2. a regular user open DApp Review website to search new DApp and leave a review for the Dapp he used before.

**Comment by zhangzhongnan928** [comment]
move to https://github.com/AlphaWallet/App-Directory/issues/1



> @colourful-land perhaps you are thinking of a more advanced version of this: https://www.stateofthedapps.com/
