### ISSUE TITLE
The display area for iFrame is slightly biased to the right

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#502]
the below screenshots based on the same TBML for both ERC875 and ERC20 tokens.

ERC20
![erc20](https://user-images.githubusercontent.com/33795543/50331404-7a9e9a00-0539-11e9-91c2-cbf071fb9f4e.jpeg)

ERC875
![erc875](https://user-images.githubusercontent.com/33795543/50331405-7a9e9a00-0539-11e9-83fd-88c5268d9291.jpg)

TBML
[TBML.zip](https://github.com/AlphaWallet/contracts/files/2701988/TBML.zip)

**Comment by colourful-land** [comment]
@farrahfazirah   do you think this is an issue of android rendering or bug in the HTML code in IFRAME?

**Comment by zhangzhongnan928** [comment]
@colourful-land it is from iOS

**Comment by farrahfazirah** [comment]
For reference, this is how the HTML looks on web browser and mobile browser respectively

<img width="500" alt="screen shot 2019-01-15 at 11 50 14 am" src="https://user-images.githubusercontent.com/20555752/51157674-f4693f80-18bb-11e9-94f2-8743f664d5d0.png">

<img width="312" alt="screen shot 2019-01-15 at 11 55 32 am" src="https://user-images.githubusercontent.com/20555752/51157807-81ac9400-18bc-11e9-8202-58384e301742.png">


### On iOS
I used a ruler (the red line) and pit the asset card against the iFrame to see the width difference. For better clarity, I removed the border-radius in the iFrame design for iOS:

_Left side of iFrame and asset card on iOS_
<img width="526" alt="screen shot 2019-01-15 at 11 57 02 am" src="https://user-images.githubusercontent.com/20555752/51158967-c7b82680-18c1-11e9-9b43-63a5f5bef859.png">


_Right side of iFrame and asset card on iOS_
<img width="206" alt="screen shot 2019-01-15 at 11 58 16 am" src="https://user-images.githubusercontent.com/20555752/51157891-d94aff80-18bc-11e9-80c6-9c5fbf539465.png">

As you can see, the width of the iFrame is slightly smaller than the asset card on both sides.

#### Suggestions for iOS
- Make width of iFrame the same as asset card

### On Android

The iFrame UI on Android is not the same as iOS. It is "enclosed" with the same grey rectangular design as the asset card:

<img width="700" alt="screen shot 2019-01-15 at 12 04 06 pm" src="https://user-images.githubusercontent.com/20555752/51158063-ad7c4980-18bd-11e9-8633-7daec8bbd783.png">

I pit the asset card against the iFrame and the width of the iFrame is much smaller than the asset card on both sides:

_Left side of iFrame and asset card on Android_
<img width="239" alt="screen shot 2019-01-15 at 12 34 19 pm" src="https://user-images.githubusercontent.com/20555752/51159009-ed453000-18c1-11e9-8db3-0c36af240e03.png">


_Right side of iFrame and asset card on Android_
<img width="156" alt="screen shot 2019-01-15 at 12 34 27 pm" src="https://user-images.githubusercontent.com/20555752/51159017-f6360180-18c1-11e9-8176-e8411313c0e2.png">


#### Suggestions for Android
- Remove rectangular grey border
- Make width of iFrame the same as asset card
