### ISSUE TITLE
failed to import magiclink for spawnable token

### ISSUE THREAD

**Issue by lyhistory** [AlphaWallet/alpha-wallet-android#505]
network: ropsten
meetup contract address: 0xa2918727EBD4B6c16cA3Bd25Becb0C739b70339d
organizer address: 0xEda3c41535ae147BD10d7B18884C7340b893cbDc
magic link: https://app.awallet.io/AgAAAABcx9Y4opGHJ-vUtsFso70lvssMc5twM51DTjIwMTkwNDMwMTI1OTM2KzA4MDAAAQAAAAAAAAAAQWG96vQO--XkIKyrC4QOSFZP__pZEEm-YMyxWov3L3LiOGpM23xgFtW1bq8Cc6213GdfBYtbbqi6YxKCkMzXmfsb

I can redeem it with my mockup tool using web3j:
![image](https://user-images.githubusercontent.com/1522513/51422959-47603100-1bf3-11e9-99f5-6af182356553.png)
https://ropsten.etherscan.io/tx/0x7f574894afd632c6943b5dcb9d87724fcc95c972a273fd483d0636b1a3d9b36f

while I open the magic link with the latest android client, it shows:
![image](https://user-images.githubusercontent.com/1522513/51423025-00bf0680-1bf4-11e9-955f-62c6d24f1e01.png)
but the client can display it nicely:
![image](https://user-images.githubusercontent.com/1522513/51423073-b427fb00-1bf4-11e9-9f81-b0801bc3916c.png)

please note that currently there's no validation on whether the magic link has been redeemed(in the meetup contract: spawnPassTo in https://github.com/AlphaWallet/contracts/blob/master/spawnable-contract/schema1/MeetupContract.sol), so we can redeem it multiple times (maybe we should add validation for this later on)

and this is how I extract tickets from the magic link for your reference:
![image](https://user-images.githubusercontent.com/1522513/51423110-72e41b00-1bf5-11e9-9bbc-fb25ccd5d767.png)

**Comment by James-Sangalli** [comment]
@lyhistory is the signer address 0x52b590123a81a22f08acf05598fec68c636b4797?

**Comment by James-Sangalli** [comment]
@lyhistory isn't your code using the same code as in android? @JamesSmartCell please take a look also

**Comment by lyhistory** [comment]
hi, @James-Sangalli previously we have a discussion here: https://github.com/lyhistory/Peter-s-Tool/issues/15

linkdata = leading byte(0x02)| price in microeth 4 byte| expiry in 4 byte| contract address| tickes array
and the data to sign is:
signature = sign(price convert to eth (32 bytes)| expiry(32 bytes)| contract address| tickes array)

according to https://github.com/AlphaWallet/alpha-wallet-android/issues/294 the leading byte I'm using is 0x02,  quote from @JamesSmartCell 

> 0x01: Standard magic link.
> 0x02: Spawn token magic link.
> 0x03: Customisable spawn token link.

**Comment by James-Sangalli** [comment]
<img width="1139" alt="screen shot 2018-11-14 at 7 05 33 pm" src="https://user-images.githubusercontent.com/16630514/51437929-fabb4980-1d09-11e9-9405-41ad5461880b.png">
@JamesSmartCell looks proper, might have something to do with how it is submitted to the network as on iOS an extra 32 bytes is added somewhere...

**Comment by James-Sangalli** [comment]
@lyhistory problem has been fixed in iOS here: https://github.com/AlphaWallet/alpha-wallet-ios/pull/1028 was taking the wrong byte positions for the token ids

**Comment by James-Sangalli** [comment]
@JamesSmartCell added a branch here for you to complete spawnable compatibility as it has not yet been implemented in android. https://github.com/AlphaWallet/alpha-wallet-android/tree/compatible-with-spawnable-links

I added the finals for the formats and put a method to retrieve the tokenIds, let me know if you need anything else.

**Comment by James-Sangalli** [comment]
Solved https://github.com/AlphaWallet/alpha-wallet-android/pull/552
