### ISSUE TITLE
Network page should be an activity not a dialog 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#513]

**Comment by JamesSmartCell** [comment]
It does seem like other wallets also implement this as an activity. Wonder why we designed it as a dialog in the first place or is it just a hangover from the inherited source?

**Comment by JamesSmartCell** [comment]
Added @James-Sangalli to the assignee list so you may make the change.

**Comment by colourful-land** [comment]
1. Why is such a need?
2. What network page? In dapp browser or in wallet?

**Comment by James-Sangalli** [comment]
> 1. Why is such a need?
> 2. What network page? In dapp browser or in wallet?

Again, this was created before we had the dapp browser network setting.

It was intended to be for the settings page only, when you select the network.
