### ISSUE TITLE
xDai don't pick up the transection records

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#515]
![image](https://user-images.githubusercontent.com/33795543/51664713-fedeb400-1ff4-11e9-9c8c-f04d6b440346.png)

**Comment by hboon** [comment]
@JamesSmartCell this might help:

The format for https://blockscout.com/poa/dai/api is compatible with https://api.etherscan.io, but supports xDai

**Comment by zhangzhongnan928** [comment]
ENS only works on mainnet
What is your address?


Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>
