### ISSUE TITLE
app doesn't show errror message when attempting to create impossible universal links

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#52]
Every occurrence of
TODO: Display appropriate error to user
should be fixed (search the source code for it)

Situations: creating an order of higher value than 4,300Eth, creating orders with indices higher than 32768.

I noticed this in the pull request but decided to approve it anyway and put the issues aside.

**Comment by James-Sangalli** [comment]
Believe this was done a long time ago.
