### ISSUE TITLE
Automatically switch network when importing through MagicLink 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#521]
Switch to the right network automatically when importing through MagicLink 
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1050

**Comment by colourful-land** [comment]
Please don't make it automatic without overall design change that @farrahfazirah is working on.

Be sure to talk to Farrah (hopefully me too) before doing anything about it. If you design a smart-phone, you can't add a call button and say it is call-ready. You also need to display signal bar, handle incoming call when busy, put the call on hold, have a queue of incoming unanswered calls etc. We can't just add dialogue and it becomes usable to the users - at least 4 places have to change.

**Comment by James-Sangalli** [comment]
Solved with host
