### ISSUE TITLE
Some parts still display xDai as ETH on xDai Chain

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#527]
![photo_2019-01-28 15 47 22](https://user-images.githubusercontent.com/33795543/51821406-0ca57980-2314-11e9-8e35-f42dbb50f204.jpeg)
![photo_2019-01-28 15 47 14](https://user-images.githubusercontent.com/33795543/51821407-0d3e1000-2314-11e9-8e54-3120495a1f3b.jpeg)

Should display xDai, instead of ETH

**Comment by JamesSmartCell** [comment]
Fixed in PR #552 , waiting for paymaster network API for merge.

**Comment by James-Sangalli** [comment]
Already up.
