### ISSUE TITLE
Can't open pdf in alpha-wallet-android

### ISSUE THREAD

**Issue by duncanwang** [AlphaWallet/alpha-wallet-android#528]
http://test.dingheng.xyz/upload/works//20190103/attorn.pdf

It couldn't be opened or downloaded in   alpha-wallet-android dappp browser.  
DEVICE: HUAWEI MATE9

Is it a bug?

**Comment by bootingman** [comment]
Issue Title: Garbled character/code displayed when open a pdf URL in DApp browser
Reporter: Denghui & Wen
Device info: HTC Exodus (Android 8.0)
APP version: [1.32.0-RC2](https://0x.alphawallet.com/dl/AlphaWallet-0x8B40U.apk)
Reappear rate: 100%

Steps:         
1. Run AlphaWallet App
2. Click the tab of "DApp Browser"
3. Paste the URL of " htts://alphawallet.com/blockchain-tickets-report-en/ "
4. Garbled character/code displayed

Screenshot:
![screenshot_20190128-163430](https://user-images.githubusercontent.com/943683/51824593-a4f42c00-231d-11e9-93c9-6377d2d9c6e7.png)

**Comment by JamesSmartCell** [comment]
We are investigating methods of being able to do this and also telegram connect, however care has to be taken with allowing extra permissions to the dapp browser.

**Comment by duncanwang** [comment]
http://test.dingheng.xyz/upload/works//20190103/attorn.pdf 
This bug doesn't be solved.
