### ISSUE TITLE
DAPP Browser can link to telegram

### ISSUE THREAD

**Issue by duncanwang** [AlphaWallet/alpha-wallet-android#530]
when I address the telegram address（https://t.me/joinchat/K4zC2RUSydjaE87Skqa6VA），I'll soon jump to error address（tg:join?invite=K4zC2RUSydjaE87Skqa6VA）.

![_20190129151100](https://user-images.githubusercontent.com/15844058/51890841-2b6d4400-23d8-11e9-9565-db52a1668596.jpg)

**Comment by bootingman** [comment]
Issue Title: Error when open a telegram group URL in DApp browser
Reporter: Denghui & Wen
Device info: HTC Exodus (Android 8.0, Google serivce built-in)
APP version: [1.32.0-RC2](https://0x.alphawallet.com/dl/AlphaWallet-0x8B40U.apk)
Reappear rate: 100%

Steps:
 - Run AlphaWallet App
 - Click the tab of "DApp Browser"
 - Paste the URL of " [htts://t.me/AlphaWalletGroup](htts://t.me/AlphaWalletGroup) " or any Telegram Link
 - Error with net::ERR_UNKNOWN_URL_SCHEME

Screenshot:
![screenshot_20190129-190558](https://user-images.githubusercontent.com/943683/51904308-48fed580-23f9-11e9-8e23-10cd284dfa87.png)
