### ISSUE TITLE
Network can't be changed in setting configuration.

### ISSUE THREAD

**Issue by duncanwang** [AlphaWallet/alpha-wallet-android#533]
There's no OK button in version v1.34. So network can't be changed in setting configuration.
![image](https://user-images.githubusercontent.com/15844058/51953022-ac2e4d80-2475-11e9-87e1-4b641f9a8399.png)

**Comment by JamesSmartCell** [comment]
Can you try the updated version that just went out an hour ago?

**Comment by JamesSmartCell** [comment]
Mark as resolved.
