### ISSUE TITLE
Need the Scan QR from Dapp Browser function back

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#556]
Can put it here before we have a better design.
![img_3170](https://user-images.githubusercontent.com/33795543/52391821-37dd5500-2ada-11e9-93df-93f0705a86c8.PNG)

**Comment by JamesSmartCell** [comment]
I don't understand the request. Where would the scan QR go? On the URL bar? Currently scan QR is only used with addresses.

**Comment by zhangzhongnan928** [comment]
Scan QR code to URL, which was available in previous iOS.
It is a good function.

		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i

**Comment by zhangzhongnan928** [comment]
And can be used with many DApps, since they are all website based. 

		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i
