### ISSUE TITLE
Change namespace to aw.app from awallet.io

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#562]
See also https://github.com/AlphaWallet/alpha-wallet-ios/issues/1086

Currently, magic links are generated on app.awallet.io domain which will be abandoned by Jan 2020. We should stop producing such links least we have to keep awallet.io forever. 

aw.app was originally intended for magic links (all such links should be 5-letters total) so we should use it.

**Comment by colourful-land** [comment]
This is actually not trivial because the current domain is hosted on wordpress.com which doesn't allow pare domain names (aw.app) to be directed anywhere other than wordpress.com. Ultimately we need to switch domain name provider. I'll work on this.

**Comment by JamesSmartCell** [comment]
this is now complete.
