### ISSUE TITLE
Add ability to choose a photo from photo library/album in QR scanner

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#569]
From 
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1083#issuecomment-462133788

**Comment by jzaki** [comment]
iOS design, `Photos` text button top-right. @tomekalphawallet to provide clearer design.
<img src="https://user-images.githubusercontent.com/939603/74286682-65f41580-4d7c-11ea-8e03-d03d51f1c3e7.PNG" width="300">

**Comment by JamesSmartCell** [comment]
Good call. Will add.
