### ISSUE TITLE
Link shown under step 2 in MagicLink webpage should show correct subdomain

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#583]
Related to supporting MagicLinks on different chains via different subdomains https://github.com/AlphaWallet/alpha-wallet-ios/issues/1050

1. Click https://ropsten.aw.app/AQAPQkBcZQgL2OX1jeOTPh41-cZetyyxiGdGJPOA4ZqD_8GKo1jVfPDEdlGCg64rlZGQ5lrL0m4VTXsyeI9CZ-r0mqk6zGpa51yiKV_W53lgszYs4cMQVidmuEpaXD4b
2. Look at Step 2

Expect
---
https://ropsten.aw.app/AQAPQkBcZQgL2OX1jeOTPh41-cZetyyxiGdGJPOA4ZqD_8GKo1jVfPDEdlGCg64rlZGQ5lrL0m4VTXsyeI9CZ-r0mqk6zGpa51yiKV_W53lgszYs4cMQVidmuEpaXD4b

Observed
---
https://app.awallet.io/AQAPQkBcZQgL2OX1jeOTPh41-cZetyyxiGdGJPOA4ZqD_8GKo1jVfPDEdlGCg64rlZGQ5lrL0m4VTXsyeI9CZ-r0mqk6zGpa51yiKV_W53lgszYs4cMQVidmuEpaXD4b

PS: Possibly the Javascript that shows the banner at the top needs to be updated too.

**Comment by JamesSmartCell** [comment]
Fixed in #615
