### ISSUE TITLE
dmz website bails out ugly with some magic links

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#584]
Open the following links on a browser:

This old link works correctly:

https://app.awallet.io/AAAAAFxORgCDDhZQqHp1TjfKftdrcAOVp8YWFICZIUHgFR0DJGCz8WENnKlX_1MNrOXDXmFR8dLvJhbb8g9e2oLhLi9tliU44J4huN5DPR66LX19uanvtOlJn8LTShs=

This bails out with an exception:

https://app.awallet.io/AgAAAABcd683oWtw6PrYOeYqu6LZYuTKWiivnnZVUzIwMTkwMjE1MDgwMDAwKzA4MDAADkJVSURMAAAAMd7C6X3UPn6_eEmk09nwjBMiBBCZKbRcXq-NMH0LVSJ_WOFtp9oWGjLjgnJ3sJTD-UwBgnNDY-IaUCkP9Dq3fRQb

The latter link was created by @zhangzhongnan928 

Either @zhangzhongnan928 's link is correct, then the website should handle it properly (an earlier message from Sangalli suggested that @hboon's iOS handles the link correctly), or if the link is incorrect, it should bail out a lot nicer, pointing out what is wrong with the link.

**Comment by JamesSmartCell** [comment]
This is fixed in draft in PR #587 

@farrahfazirah can you have a look and suggest improvement? After new website is updated so the above link works.

**Comment by JamesSmartCell** [comment]
use this link now:

https://xdai.aw.app/AgAAAABcd683oWtw6PrYOeYqu6LZYuTKWiivnnZVUzIwMTkwMjE1MDgwMDAwKzA4MDAADkJVSURMAAAAMd7C6X3UPn6_eEmk09nwjBMiBBCZKbRcXq-NMH0LVSJ_WOFtp9oWGjLjgnJ3sJTD-UwBgnNDY-IaUCkP9Dq3fRQb

**Comment by JamesSmartCell** [comment]
https://xdai.aw.app/AQAPQkBcuuPboWtw6PrYOeYqu6LZYuTKWiivnnYM-dW0Wt8gLSa73G14-t7ROUOvQCmED1JZDEVsyTCsAmYsoFVfMtam7N5OyOLfE1y6s1RHZU3C6WwcxwdKm-XGsRs=

**Comment by James-Sangalli** [comment]
This has been solved with various fixes.
