### ISSUE TITLE
Detect AlphaWallet in web3

### ISSUE THREAD

**Issue by mqklin** [AlphaWallet/alpha-wallet-android#588]
How can one detect this wallet inside dApp? Something like `web3.currentProvider.isAlphaWallet` ?

**Comment by hboon** [comment]
@mqklin Correct. Check the flag `isAlphaWallet`.

**Comment by mqklin** [comment]
@hboon hmm, it returns `undefined`

**Comment by mqklin** [comment]
It works, thank you

**Comment by mqklin** [comment]
For me it works only if I use VPN =/

**Comment by hboon** [comment]
@JamesSmartCell do you have any idea why or how to troubleshoot?

**Comment by mqklin** [comment]
I'm from Russia btw, I have to use VPN to access Telegram, LinkedIn, etc

**Comment by JamesSmartCell** [comment]
The injection should occur before the VPN has any effect. Can try to reproduce this, does it still happen?

**Comment by mqklin** [comment]
Now it works without problems!
