### ISSUE TITLE
Add Telegram in Settings under 'Contact Us' section

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-android#589]
AlphaWallet telegram group link: https://t.me/AlphaWalletGroup
Logo for Telegram:
![telegram-1x](https://user-images.githubusercontent.com/20555752/52846828-8f686a00-3145-11e9-9263-195ba26e4403.png)
![telegram-2x](https://user-images.githubusercontent.com/20555752/52846831-90010080-3145-11e9-8f79-e1abafd616b4.png)
![telegram-3x](https://user-images.githubusercontent.com/20555752/52846833-90010080-3145-11e9-9725-edbe1e6b3e89.png)

**Comment by hboon** [comment]
Let's be consistent on both apps and add it as the first item, above Twitter. (Buzz https://github.com/AlphaWallet/alpha-wallet-ios/issues/1105 if there's a better place)

**Comment by farrahfazirah** [comment]
@hboon @JamesSmartCell @justindg Yes, let's put Telegram above Twitter.
