### ISSUE TITLE
xDai network MagicLink landing page in browser display issues 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#594]
https://xdai.aw.app/AQAAAABcashXoWtw6PrYOeYqu6LZYuTKWiivnnYIew5R9LjnmTi4PeKjt_Ndon-nY1WR59qr-Awi686yf_IgaqraGyXDyG_Qiw6WRmdPKhUSNhSBDWluc-ZqAzCjdRw=   

![b95329cf-ebb2-40e8-98fa-59056cb98cb5](https://user-images.githubusercontent.com/33795543/52914910-c8047100-3308-11e9-9f5f-d152d76da63c.jpeg)

**Comment by hboon** [comment]
@zhangzhongnan928 transferred to android repo (which also hosts the MagicLink webpages)

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 the magic links on xdai are working for me when i create a new NFT token on xdai, are you sure this link hasn't been claimed?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 the magic links on xdai are working for me when i create a new NFT token on xdai, are you sure this link hasn't been claimed?

I create one more, try yourself.
https://xdai.aw.app/AQAAAABcashXoWtw6PrYOeYqu6LZYuTKWiivnnYIew5R9LjnmTi4PeKjt_Ndon-nY1WR59qr-Awi686yf_IgaqraGyXDyG_Qiw6WRmdPKhUSNhSBDWluc-ZqAzCjdRw=

All other contracts display available, only this ETHDenver contract display as unavailable(this is the one we have TBML file)

**Comment by James-Sangalli** [comment]
It may well be this: https://github.com/AlphaWallet/contracts/pull/125 Please send me a current link so I can test again.

**Comment by zhangzhongnan928** [comment]
https://xdai.aw.app/AQAPQkBcuuPboWtw6PrYOeYqu6LZYuTKWiivnnYM-dW0Wt8gLSa73G14-t7ROUOvQCmED1JZDEVsyTCsAmYsoFVfMtam7N5OyOLfE1y6s1RHZU3C6WwcxwdKm-XGsRs=

![img_3440](https://user-images.githubusercontent.com/33795543/53003790-ba66fc80-346a-11e9-91bb-93bbc136bc97.jpg)

**Comment by JamesSmartCell** [comment]
This is now fixed with PR #615
