### ISSUE TITLE
Add Custom Token function broken

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#598]
Android cannot auto load the right information, 
![photo_2019-02-19 10 45 02](https://user-images.githubusercontent.com/33795543/52986700-6f7dc280-3433-11e9-88a8-96b982bb1c92.jpeg)

**Comment by JamesSmartCell** [comment]
Unable to reproduce - is this contract on a different network to the one you're set to?

If so - then should add custom token try different networks and show the result(s)? This would be a good modification

**Comment by zhangzhongnan928** [comment]
strange, it works all fine now. I tested with multi contracts on different networks before
