### ISSUE TITLE
Scan EIP 681 QR code while in Send screen and fill in address + amount

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#601]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md

It seems on the line with many stable coins use cases. @colourful-land

**Comment by hboon** [comment]
* Check function_name empty or not available, prompt not supported.
* Check chain_id empty or not available or the same as current chain's -> Use current chain.
* If chain_id is available but doesn't match, prompt wrong network.
