### ISSUE TITLE
Handle magic links with network specification, prevent user from importing on the wrong network

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-android#602]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1050 for reference

**Invision**
Switch Network Mode for Payment
https://invis.io/58QLV7F6EA2

Browser v1.1 Switch Network
https://invis.io/SCQLWQA9F27

**Zeplin**
Switch Network Mode for Payment https://app.zeplin.io/project/5ba3a438abd22908b916fa9a/dashboard?seid=5c6d27d687bfc29a5149f691

Browser v1.1 Switch Network
https://app.zeplin.io/project/5ba3a438abd22908b916fa9a/dashboard?seid=5c6d28775e1ba59a694f5afd

The following is a summary of what the feature entails:

**Features for Switch Network Mode for Payment**
1. User is prompted by a dialog to switch network if they're not on the right network for the payment e.g. Bob sends MagicLink to Alice asking for 1 xDAI for his cryptokitties but Alice is on Ethereum network, thus she is prompted to switch to xDAI chain
- Actions users can take: continue to switch network or cancel and go back (abort import)
2. If it's user's first time switching network, a tooltip appears on how the user can switch networks
- Tooltip will disappear if user clicks onto other screens/undertakes any other action on the app, even if it's not Settings
3. The title "Wallet" on wallet screen is changed to the name of the current network user is on

**Features/Modification for Browser v1.1 with Switch Network**
1. Home icon has been replaced by network icons/network picker
2. User can click on the network icons to switch to a different network

**Comment by JamesSmartCell** [comment]
Completed with PR #612
