### ISSUE TITLE
Customise each wallet name on the Wallets page

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#603]
See https://github.com/AlphaWallet/alpha-wallet-ios/issues/1108

**Comment by JamesSmartCell** [comment]
I have tasked Justin to build this, should be ready within 2 weeks.

**Comment by farrahfazirah** [comment]
Below is a modification by Justin for the reworked wallets 

<img src="https://user-images.githubusercontent.com/20555752/53800770-700c7200-3f78-11e9-9bff-817ea6d4f645.jpg" height="550px"> <img src="https://user-images.githubusercontent.com/20555752/53800780-74d12600-3f78-11e9-8eb9-26fa155b8502.jpg" height="550px">

@hboon has mentioned that, I quote, "the ETH amount is going to be “wrong” with multi-chain support in the first screenshot. Easy way out is for it to display just the ether balance for mainnet? Or to squeeze and display 2-3 balances from the chains that has the largest balance?"

The proposed solution is to remove the balance for now OR just display mainnet's balance (if we are implementing it now).

@zhangzhongnan928 What is the urgency of this particular modification? I think Justin did a good job. It just needs a little tweaking and we're good. However, it would still need modifications for multi-chain support. 

Do we implement it now or only after multi-chain support?

**Comment by zhangzhongnan928** [comment]
Display ETH with customised wallet name is fine, even for muti-network(all eth based networks).
But better to have customised wallet name first with bigger text, then eth balance and wallet address with same size text.

**Comment by justindg** [comment]
Added the name to the page as suggested by @zhangzhongnan928 
![screenshot_1551796897](https://user-images.githubusercontent.com/17334718/53813476-b671c900-3f98-11e9-96c7-8f7b3352edc9.png)

Max length of wallet name is currently set to 30 characters

I'll leave the PR in #623 open until the requirements are finalised. :)

**Comment by JamesSmartCell** [comment]
Once Plasma goes live this is going to get more complex too.

How about a current solution to only display main-net ETH and leave the rest to the wallet view for now until we work it out. 

In the network list we can tag chains with value (ie currently ETH, ETC and XDAI) and display those in the wallet summary if they are non-zero?

**Comment by zhangzhongnan928** [comment]
> Once Plasma goes live this is going to get more complex too.
> 
> How about a current solution to only display main-net ETH and leave the rest to the wallet view for now until we work it out.
Agreed
> 
> In the network list we can tag chains with value (ie currently ETH, ETC and XDAI) and display those in the wallet summary if they are non-zero?
Nice, agreed

**Comment by hboon** [comment]
@JamesSmartCell are you referring to the 2 screenshots in https://github.com/AlphaWallet/alpha-wallet-android/issues/603#issuecomment-469639377 ? And "network list" refers to the first screenshot and "wallet view" refers to the second screenshot?

If so, are you suggesting this (for the 1st screenshot)? :

> Or to squeeze and display 2-3 balances from the chains that has the largest balance?
