### ISSUE TITLE
Add link to community forum

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#634]
From https://github.com/AlphaWallet/TokenScript/issues/57, change link in app from https://community.alphawallet.com/c/feedback/android-feedback to the corresponding http://www.tokenscript.org/c/AlphaWallet/android-feedback

Android might not have this link as it was something that was left over in iOS from the earlier days and we just updated the link to point somewhere.

**Comment by James-Sangalli** [comment]
No longer used, stick with Telegram
