### ISSUE TITLE
Adding Zerion to Alpha wallet

### ISSUE THREAD

**Issue by rockfridrich** [AlphaWallet/alpha-wallet-android#637]
Hey Alpha Wallet team, 

We added support of Alpha wallet to our interface. Do you mind adding us to the Finance section of DApps exploration tab?
You could use this logo — https://drive.google.com/file/d/1qv0-kc1BKbJoO12LYCxxKkk3n7ISsXCR/view?usp=sharing
Description: Trade and manage your digital assets across different wallets in one interface.

Regards,
Vadim

**Comment by hboon** [comment]
@rockfridrich Yes, we'll add it in.

1. We pull the logo using https://api.faviconkit.com/zerion.io/144. Would you be able to update your site so that there is a higher res logo available there?
2. Thanks for adding support for AlphaWallet! The wallet name displayed should be "AlphaWallet" though.

**Comment by rockfridrich** [comment]
@hboon we did it.

**Comment by hboon** [comment]
@rockfridrich thanks!
