### ISSUE TITLE
Switching network in DApp Browser

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#638]
1. Should keep the same website open instead of going back the home page.
2. Need to auto refresh after switching like changing network in metamask.

**Comment by hboon** [comment]
- [x] iOS. Done. Will be in a future build. (Didn't create a separate issue because everything multi-chain is still a single PR).

**Comment by James-Sangalli** [comment]
Done in android too. @JamesSmartCell Please close and reference issues.
