### ISSUE TITLE
Disable test net on filtered networks

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-android#643]
Currently all the networks are enabled for Android. As suggested by Victor, the test networks should be disabled on initial.

**Comment by hboon** [comment]
Partly so I know if I need to fix iOS :) :

![Simulator Screen Shot - iPhone X - 2019-03-25 at 16 59 33](https://user-images.githubusercontent.com/56189/54898192-647ced00-4f1f-11e9-9145-5c24c02c4788.png)

**Comment by JamesSmartCell** [comment]
This is fixed in the latest chain source.
