### ISSUE TITLE
Replace home button on dapp browser with network label

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-android#644]
<img src="https://user-images.githubusercontent.com/20555752/54899135-ca5e7a00-4f09-11e9-91a6-5cd1173a43b5.png" height="500px">

**Comment by justindg** [comment]
Hi @farrahfazirah, where does the home button go? Or do we completely eliminate the function?

**Comment by farrahfazirah** [comment]
> Hi @farrahfazirah, where does the home button go? Or do we completely eliminate the function?

Yup it's eliminated. The "home" function is through the dapp icon on navigations now.

**Comment by justindg** [comment]
@farrahfazirah Done. Included in branch Multi-Chain-Support. @JamesSmartCell
