### ISSUE TITLE
Currency market value has a disruptive flashing animation when refreshing

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-android#645]
Can be seen in this video:

<img src="https://user-images.githubusercontent.com/20555752/55305677-0ce10300-5484-11e9-96c1-fcd2612ecbf7.gif" height="450px">

I propose we remove the animation and just have it static.

**Comment by justindg** [comment]
Noted, will revert asap

**Comment by justindg** [comment]
Addressed in #647 :)
