### ISSUE TITLE
MagicLink landing page should be able to identify different network.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#646]
Currently, it displays all as Ethereum mainnet

https://xdai.aw.app/AQAPQkBdGxiV8uDV_Ed2HKwO7e5ssa9fMYQ6ChgSf3yqIOGnodoeZF2Eth-1i_Rh5KEO4_ipCvo_d3v3wYsaFIXzMqJu1H4kCes19ixJxeGo4fEJOUUnsm91FKHIKRw=

**Comment by JamesSmartCell** [comment]
Fixed
