### ISSUE TITLE
Tokenscript generates web view for "Enter" action with a single word: none

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#656]
As you can see in the screenshot, the webview has a single element with single value "none"

![Screenshot_20190407-203142](https://user-images.githubusercontent.com/548435/55682270-8ee59600-5974-11e9-8c40-6121b4fffa36.png)
![devtoolapp](https://user-images.githubusercontent.com/548435/55682274-9dcc4880-5974-11e9-97f7-3674d9adc3db.png)

**Comment by James-Sangalli** [comment]
No longer an issue
