### ISSUE TITLE
prompt users to update their wallet when unrecognised namespace show up

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#658]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1171
pseudo code:

    let supported_namespaces = ["http://tokenscript.org/2019/04/tokenscript"]
    when (new XML is downloaded) {
        if (! xml.namespace in supported_namespace) { // namespace unsupported
            if (xml.namespace.substring(0,23) == "http://tokenscript.org/") {
                alert("upgrade your wallet. There is some change in the air.");
            } else {
                alert("please do not through stole into this IQ testing machine.");
            }
     }

**Comment by JamesSmartCell** [comment]
Yes this is implemented.
