### ISSUE TITLE
Wrong URL for Uniswap in discover dapp

### ISSUE THREAD

**Issue by leckylao** [AlphaWallet/alpha-wallet-android#663]
Need to remove swap at the end after the /. Otherwise it shows not connected to wallet.

**Comment by hboon** [comment]
@leckylao can you please help to post a screenshot of what you see on Android?

I did a quick test on iOS and it looks like visit "https://uniswap.exchange" will redirect you to "https://uniswap.exchange/swap" anyway:

<img src="https://user-images.githubusercontent.com/56189/56081462-2a2cae80-5e40-11e9-8da9-67fe2a2f4e79.png" width=400>

**Comment by leckylao** [comment]
Test

**Comment by JamesSmartCell** [comment]
I see it, yeah if you remove 'swap' then it works.
