### ISSUE TITLE
Host goerli.aw.app domain to support Görli MagicLinks

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#668]

**Comment by JamesSmartCell** [comment]
Already handled in DMZ server code - only needs the goerli.aw.app domain pointed at DMZ and a rebuild/redeploy of server, once #665 is accepted into master.

**Comment by hboon** [comment]
@JamesSmartCell it's added `goerli.aw.io`, I think it should be `goerli.aw.app`.

**Comment by JamesSmartCell** [comment]
oops quite right. Fixed

**Comment by hboon** [comment]
- [ ] Close issue when deployed
