### ISSUE TITLE
find a way to avoid writing your own entity parser

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#677]
HI if you ℎ𝑎𝑣𝑒 to write your own entity parser, be aware of these:

- avoid looping system entity references 
e.g. `&haha;` is used in `&token.en;` which uses `&token.en;`

- not to forget to resolve entity references in a referred file
e.g. `&haha;` is used in `&token.en;`

- make sure new entities are not mistaken as system entity (think emoji)

- make sure entities in CDATA is 𝑛𝑜𝑡 resolved.

- make sure entity injection attack isn't possible
One probable way to do so is `&ent<![CDATA[Haha now I escaped prison]]>;`

- make sure you don't break normal entity references like 'author'
e.g. `<!ENTITY author "James Brown">`

In general, I suggest to let c10n (canonicalization) work out the way and your code should work with a canonicalized copy, not the original. Please avoid writing your own parser and only do so if it's completely not feasible to use a library to canonicalize the XML file dropped on Android. Please bear in mind that **regexp will not do it**.

**Comment by colourful-land** [comment]
we have two major enemies.

- fireman thinking (the first plausible cause must be the cause of the problem; the first solution we can think of must be the best solution).

- gateway assumption: to make the area inaccessible, we don't need to go through the trouble to defend the area; we just need to remove the gateway to that area.

Kindly not lower your guard in developer mode. Developer mode might be triggered by another bug or the user might be coerced to run it. That is, although normally we run signed code which is already 
canonicalized, we shouldn't assume that because developer mode is turned on, the uncanonicalized code isn't intended to breach the system.

**Comment by JamesSmartCell** [comment]
I tried the Google recommended Xerces-For-Android source, which does work correctly but because it uses internal versions of the XML structure (eg NodeList, Node, Element etc) it can't be used with the DMZ and peter's tool code. 

One solution is to spend time to port a universal implementation of the javax Apache code so one body of code works on both native Java and Android Java. This means we need to maintain another module, but once the project is done it shouldn't need to be touched again for a while.

**Comment by colourful-land** [comment]
> One solution is to spend time to port a universal implementation of the javax Apache code so one body of code works on both native Java and Android Java. This means we need to maintain another module, but once the project is done it shouldn't need to be touched again for a while.

If the way these objects are used is the same, there might be a duck typing method, perhaps even provided by Gradle so we don't have to use 3rd party modules. Do you feel the android internal NodeList, Node, Element etc quark like a duck?

**Comment by James-Sangalli** [comment]
@colourful-land @JamesSmartCell bump
