### ISSUE TITLE
Support hardware based keystore, Android

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#678]
Source: https://source.android.com/security/keystore

Will any of you @JamesSmartCell do some experiment - maybe make a skeleton android app that does nothing but store keys? I'm interested to learn if S10 has support for secp256k1

According to https://source.android.com/reference/hidl/android/hardware/keymaster/4.0/IKeymasterDevice secp256k1 is not a mandatory requirement (expectedly - which security software want to support blockchain anyway)

**Comment by colourful-land** [comment]
https://www.ozbargain.com.au/node/446269 -> does Mary have an account as Australia government employee? We can get that 30 % off S10 device.

**Comment by James-Sangalli** [comment]
Not a priority for now
