### ISSUE TITLE
balance is zero when disconnected

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#692]
Reproduce:

1. Disconnect the Internet connection of the phone. Run AlphaWallet.
2. Observe a non-zero Ether balance
3. Go to Settings -> My wallets
observe that the balance displayed there is 0.00 Eth.

**Comment by ronakdave195** [comment]
This issue seems to have been resolved. @JamesSmartCell May I request you to confirm.
![aew-no-internet](https://user-images.githubusercontent.com/54934848/73340723-47345000-42a1-11ea-870f-a6a245b1efb8.jpg)

**Comment by James-Sangalli** [comment]
Can confirm this is no longer an issue
