### ISSUE TITLE
a wallet is created before the user confirms it

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#694]
Reproduce.

1. go to settings, wallet.
2. click 'add'
3. create a new wallet. 
4. at this stage, the user is asked for the wallet name. Choose 'back' or 'cancel'.
5. now go to settings, wallet again, notice that the wallet is created despite the user cancelled in the middle.

**Comment by James-Sangalli** [comment]
@colourful-land mitigated by keystore release whereby a user can see a 'Lose this wallet' button
