### ISSUE TITLE
Need to Support EIP-1193

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#698]
Ref https://github.com/AlphaWallet/alpha-wallet-ios/issues/1215#issuecomment-494156670

Note: the issue with Uniswap was actually caused by enable() but it is still a good idea to initiate the window.ethereum object.

**Comment by James-Sangalli** [comment]
@JamesSmartCell please remember to close the issues that are solved in PRs!
