### ISSUE TITLE
A few problems discoverred when helping a user to install αWallet

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#708]
1. The user sees an incoming transaction with a red number with plus sign, but when she switch from the Ether view to the wallet view, the plus sign and the red number is gone; so she hurrily switched back and the plus sign disappeared as well (showing no incoming transactions). this worried her a lot.

2. When the user choose to backup the key store, typed the password and confirmed, she is prompted to choose from one of the 16 apps (like Telegram etc) and she stopped there out of confusion (what does backup has anything to do with Telegram). I instructed her to use Gmail.

3. When the user finished backing up, she clicked "Yes I managed to back up the keystore" then she sees a big "Save" button, and confused and asked if she didn't successfully save her key, worrying the gmail client didn't save it for her.

4. She also failed to reach out to the backup in the first place because she clicked the address in preferences not the three dots to the right of the addresses.

**Comment by JamesSmartCell** [comment]
Could this be addressed in the UX redesign?
