### ISSUE TITLE
Provide a Clear Browser Cache function in the setting page

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#722]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1244

**Comment by ChintanRathod** [comment]
Started working on this issue, yet stuck at below points. 
1) Image for clear browser 
2) Translation. What is your approach for translations? If it is Google translations, I can do that, else I need translated strings from relevant person.

**Comment by ronakdave195** [comment]
@James-Sangalli We await to receive your feedback on @ChintanRathod's above query

**Comment by justindg** [comment]
Hi @ronakdave195  and @ChintanRathod , I'm currently working on the revamped Settings page. The new page will include the section for the "Clear Browser Cache" function, so no need to worry about the layout and icon. I will leave a corresponding TODO tag in the source for you to write the actual implementation of the cache clear function. I will update this ticket once the PR is up. :)

**Comment by justindg** [comment]
Update: You can now add the implementation in **`AdvancedSettingsActivity`** under `onClearBrowserCacheClicked()`

**Comment by ChintanRathod** [comment]
@justindg Sure. I will add the logic in AdvancedSettingsActivity and push the code in "Fiji" branch.
