### ISSUE TITLE
Implement blended HD and Standard keys in Wallet

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#723]
Need to add HD key functionality. Relates to ios:
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1265

The best way is going to be a compromise, as seen in the Trust wallet. See how the HD keys sit side by side with the legacy keys in the wallet?

![trust1](https://user-images.githubusercontent.com/12689544/59735241-241bd980-9298-11e9-920d-fb475ef7b0d1.jpg)

When you click on an HD key you see the backup options:

![trustmw](https://user-images.githubusercontent.com/12689544/59735320-74933700-9298-11e9-9d42-558df67ec715.jpg)

Backup of the HD key is via seed, which looks something like this:

![seed](https://user-images.githubusercontent.com/12689544/59735347-8f65ab80-9298-11e9-9bb5-dc11d1625c63.jpg)

Backup of the legacy keys is already handled in Alphawallet so this functionality doesn't need to change.

**Comment by colourful-land** [comment]
We enforce the use of English seed phrases. Despite that seed phrases are [polyglot](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md
). Reason:

- We assume that Chinese input methods always send the combination to the server (e.g. when the user writes an ideograph in a drawing area)
- we are concerned putting the keyboard to password mode prevents typing of umlauts like ë

Tomek is going to develop a safe seed phrase recovery tool which will allow non-English. But it will be a separate task.

**Comment by JamesSmartCell** [comment]
Note: there are official bip39 seed phrase lists for Chinese and Spanish

**Comment by James-Sangalli** [comment]
Obsolete
