### ISSUE TITLE
Xiaomi Mi8 phone crash on launch

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#729]
This is on a China version. The owner mentioned that there could be a difference between China builds of the hardware and international releases, if that's why we can't reproduce it.

**Comment by JamesSmartCell** [comment]
Thanks, I didn't get a crash notification, so I can't say why it's happening. Did you get his wechat or anything like that? If not, maybe we can try asking in the Alphawallet wechat group. I still haven't recovered my wechat :( The one I created the other night got closed, don't know why.

**Comment by hboon** [comment]
I might have. What’s our WeChat group? I was going to ask them to join our Telegram group if they are on Telegram. WeChat would be better.
