### ISSUE TITLE
Harden pull request #683

### ISSUE THREAD

**Issue by jot2re** [AlphaWallet/alpha-wallet-android#734]
Since pull request #683 considers security critical checks it would be good to ensure full documentation along with lots of negative tests. For example the following. 

- [x] Add method signatures including which security critical the given method checks for.
- [x] Add more negative test: by including certs in the chain that are not yet valid and that has expired. If possible also try to include a revoked certificate. 
- [x] Try to stress the implementation by having the certificate chain in an unexpected order. 
- [x] Try to stress the implementation by having more than expected KeyInfo (and others) elements in the xml files. 
- [x] Ensure that there are positive tests for both RSA and ECDSA.

**Comment by James-Sangalli** [comment]
@colourful-land could you try this on your computer? Mine has a botched ca setup

`openssl ca -config /private/etc/ssl/openssl.cnf -selfsign -keyfile cakey.pem -startdate 20890214120000Z -enddate 20990214120000Z
Using configuration from /private/etc/ssl/openssl.cnf`
