### ISSUE TITLE
Implement Navbar numeric button badges

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#755]
See the small red circled value at top left corner of settings icon:

![Capture](https://user-images.githubusercontent.com/12689544/61197522-bf2d9500-a718-11e9-8b13-becebc4a95ac.PNG)

Implement this as a method in class AWalletBottomNavigationView.

See Tinashe's answer here:
https://stackoverflow.com/questions/42682855/display-badge-on-top-of-bottom-navigation-bars-icon

This method is best as it avoids adding another library (creating another set of display issues). DO NOT use the library bottom navigation as suggested by the first answer. It should be straightforward to create a white number in a red circle and display it. Need to have a method that decrements and removes the red circle too.

**Comment by JamesSmartCell** [comment]
@justindg please implement this, thanks :)

**Comment by JamesSmartCell** [comment]
![Capture](https://user-images.githubusercontent.com/12689544/61291451-e5832b80-a811-11e9-9381-43b8f1a8faeb.PNG)

also a 'focus mode' where a popup dialog box focusses on the highlighted box, when the box is clicked.

**Comment by James-Sangalli** [comment]
@justindg perhaps you would like to take this on?

**Comment by justindg** [comment]
Sure I'll take this on. May I know more about the flow of 'focus mode'? Is that for onboarding only? I'm assuming this is like a 'tour' for new users

**Comment by JamesSmartCell** [comment]
Yes I think so; I don't think it would show up more than once, although the little numeric circle will show up whenever there's a wallet that hasn't been backed up.

I'll ask the UX guy for clarification at the next meeting.

**Comment by JamesSmartCell** [comment]
![image](https://user-images.githubusercontent.com/12689544/61347451-6557d700-a8a0-11e9-98c4-e4b264fb245f.png)

Here's another popup that I think will only happen once.

You can get the colour asset from the 'Implement-HD-Keys' branch, it's called 'nasty_green'

**Comment by JamesSmartCell** [comment]
Completed.
