### ISSUE TITLE
Implement slide-away warnings

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#762]
![image](https://user-images.githubusercontent.com/12689544/61350574-5b87a100-a8ab-11e9-936e-ebb3951264af.png)

In this frame a warning is displayed; it should be possible for the user to either:
- click on the backup button.
- swipe the warning away.

If the user swipes the warning away then It will display a notice 'remind me later' as per this frame: The 'remind me later' is a floating button that when clicked will call a currently empty function remindLater() (not currently in the source).

![image](https://user-images.githubusercontent.com/12689544/61350650-a4d7f080-a8ab-11e9-9ae8-786abda0227a.png)

Work from the 'Implement-HD-Keys' branch.

Logic for postponing hasn't been written yet but will probably be in the sharedprefs (stored in the notbackedup entry, in a double entry list with address then backup warning time in UTC).

Currently the postpone warning is not tokenised in the 'TokensAdapter' class but it does appear in the settings page. To see it, create a new wallet (Wallet now only creates HD key wallets), then you'll get the notice to back up. It's described in the newsettings class layout file.

**Comment by JamesSmartCell** [comment]
Notice that the displayed UI is slightly inconsistent above - after the user swipes away then the red box is gone but the screen will be dark with the 'Remind me later' message.

**Comment by James-Sangalli** [comment]
@justindg this one too, if you have questions you can ask me.

**Comment by ronakdave195** [comment]
@JamesSmartCell @James-Sangalli On trying to replicate the above issue, I’m not able to slide the red “Back my wallet” warning box. I can use the “Remind me later” option by clicking on the 3 dots on the top right corner of the box.

**Comment by JamesSmartCell** [comment]
Checked and this is working correctly as per the design specs. It's superseded by the new UX design so this issue is now irrelevant. Closing.
