### ISSUE TITLE
Better error handling of non standard QR codes

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#765]
Enjin wallets QR causes strange JSON output to be placed inside the input amount field. While enjin is not following protocol, the wallet should be able to safely take the address and nothing else.

**Comment by zhangzhongnan928** [comment]
![IMAGE 2019-07-19 17:38:21](https://user-images.githubusercontent.com/33795543/61518030-03d46b80-aa4c-11e9-9396-55e2f5ca17e3.jpg)

**Comment by ronakdave195** [comment]
@JamesSmartCell May I request you to provide test steps and more description here so that we can try to reproduce this at our end to suggest any fixes.

**Comment by ronakdave195** [comment]
@JamesSmartCell @James-Sangalli We await your inputs on the above query.
