### ISSUE TITLE
Create updated icons in Settings

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#768]
Referring to the Settings screen design in https://community.tokenscript.org/t/design-backup-alerts-import/233/6

Here's a list of additional icons that are needed:

- [ ] Passcode / Face ID
- [x] TokenScript Overrides
- [x] Console
- [x] Clear Dapp Browser Cache
- [x] Twitter
- [x] Reddit
- [x] Facebook

**Comment by James-Sangalli** [comment]
Android has these icons already but no passcode or ability to see your overridden files @JamesSmartCell
