### ISSUE TITLE
Tabernacle API services for express-of-trust and XML validation for iOS

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#772]
Tabernacle api services are temporary services set up between the time Android can handle certain operations til when iOS can do the same. The concept is that swift is less standardized to do some XML stuff or public-key-derived-public-key operations and will need server support to do some

**Comment by James-Sangalli** [comment]
@colourful-land is this still an issue given the current setup?

**Comment by James-Sangalli** [comment]
Dropped
