### ISSUE TITLE
Show the sequence number of the seed phrase in back up screen (not for current sprint as of 20190803)

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#780]
(Not for current sprint)

@tomekalphawallet: A slight tweak to the screen for the users by adding the sequence number of the seed phrase words in a lower contrast color.

<img src="https://user-images.githubusercontent.com/56189/62354422-66933000-b53f-11e9-97dd-9ebd8132139c.PNG" width=400>

- [x] Confirm design
- [x] Rename this issue and create issue for iOS

**Comment by tomekalphawallet** [comment]
drop "in a" to the next line. Other than that I like it.

**Comment by hboon** [comment]
> Other than that I like it.

Thanks!

> drop "in a" to the next line.

@tomekalphawallet I don't think we should do it. It's unfortunately really tedious and costly for a few reasons to make it not worth it.

1. Different screen sizes
2. Font sizes are fixed now, but they wouldn't be in an accessible system, so it might not be in the future — iOS Dynamic Type and Android's font size preferences. (I hope to quietly sneak it in when we get a breather).
3. Localization
4. Very fragile, i.e. if we even change just one word, it might break

There are places where it might be easier or worth spending extra effort and incurring maintenance costs to do it though. Example in this screen, the "Making a backup is very simple and safe:" is always on a separate line. (It's easy). It might be wrapped on a smaller screen though.

File another issue if you want to convince me otherwise.

**Comment by JamesSmartCell** [comment]
Has been done in update

**Comment by James-Sangalli** [comment]
> Has been done in update

@JamesSmartCell please reference PR
