### ISSUE TITLE
unexpected behaviour when hitting back button on backup wizard

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#781]
A. reproduce.

1. Go to backup this wallet.
2. see the welcome screen `activity_backup_seed`
3. Hit next;
4. Hit next;
5. Hit back
6. Hit back.
7. observe the backup failed message

expected:
7. see the welcome screen `activity_backup_seed`

**Comment by JamesSmartCell** [comment]
Fixed
