### ISSUE TITLE
Create new wallet wizard's Continue button doesn't work if the user dismiss it quickly

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#782]
many user dismiss the wizard instantly. I tried to dismiss "continue" button quickly then the second prompt doesn't show up automatically.

**Comment by JamesSmartCell** [comment]
Can you clarify this? Which screen is the 'continue' button button on. Is this the 'backup your seed phrase' screen or the main wallet screen after you first install the app? Which is the second prompt you refer to?

**Comment by JamesSmartCell** [comment]
Seems to be working as expected. The debugging values may have been interfering with this; please re pull and try it.

**Comment by JamesSmartCell** [comment]
Fixed by removing second dialog to match iOS implementation.
