### ISSUE TITLE
Rendering of Verify Seed screen is slightly broken in shorter devices

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#786]
<img src="https://user-images.githubusercontent.com/56189/62690977-4dd3c000-ba00-11e9-9952-9931c6c1603f.jpg" width=250>

**Comment by JamesSmartCell** [comment]
Thanks! I hope you're not going to put any crypto into that account after posting the seed here!

**Comment by hboon** [comment]
I’ll try not to :p

**Comment by hboon** [comment]
Working now. Thanks.
