### ISSUE TITLE
Crashes after "entering" swipe PIN to make seed go to "green bar"

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#788]
Launching the app again and the wallet is shown to be "green bar"

**Comment by JamesSmartCell** [comment]
This crash was logged in crashlytics and fixed, thanks for testing :)

**Comment by hboon** [comment]
Noticed this in the newest build.

**Comment by James-Sangalli** [comment]
Tried with master, not an issue anymore
