### ISSUE TITLE
Signing on Xiaomi device with only swipe PIN and green bar wallet doesn't prompt for user presence

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#789]
This is the wallet after https://github.com/AlphaWallet/alpha-wallet-android/issues/788.

**Comment by JamesSmartCell** [comment]
User authentication event is valid for 30 seconds; if you sign within 30 seconds of a previous authentication event you don't need another event. Can you try again after 30 seconds and see if the authentication is required?

Perhaps UX should indicate somehow that authentication event is not required? Or reduce the valid time.

**Comment by hboon** [comment]
With the new build:

1. Tried to upgrade to "green bar"
2. Was prompted for swipe to unlock. Proceed.
3. "Green bar" shown
4. Went to app browser and sign a transaction

Expect:

Prompted for swipe to unlock

Observe:

Was not prompted. Signing failed. Was xcontract. The signature box remains empty.

Re-tried after waiting > 30 seconds after the prompt to swipe to unlock (from making it green bar) as well as killing the app. Not prompted.

**Comment by hboon** [comment]
This. I do get prompted when I try to back up, so it looks like the API is working. It only doesn't prompt when I try to sign from the dapp browser.

**Comment by JamesSmartCell** [comment]
Got it! OK I hadn't wrapped dapp browser class with the new KeyService class. This would account for this. Again good catch.
