### ISSUE TITLE
The prompt "Unlock Private Key" is a bit out of context for user right after importing a private key

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#801]
The other situation where the user gets prompted to do this, to go from yellow -> green is right after back up, verification. We show an additional screen to prepare the user.

(On iOS, we just import the key as yellow bar and let the user initiate back up themselves, if they want to elevate to the wallet to green bar. Saves work :) )

Alternatively, maybe change the prompt (text) or add that additional explanation screen?

<img src="https://user-images.githubusercontent.com/56189/62846219-c8525780-bd00-11e9-8ec9-c75a5ce9bc10.jpg" width=220>

**Comment by JamesSmartCell** [comment]
AFAIK this is correct behaviour.

**Comment by JamesSmartCell** [comment]
Good point. Updated
