### ISSUE TITLE
Name from TokenScript not shown on token card

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#805]
Shows the contract name but it should show the localised name in the TokenScript.

**Comment by ronakdave195** [comment]
@JamesSmartCell May I request you to provide test steps and more description here so that we can try to reproduce this at our end to suggest any fixes.

**Comment by James-Sangalli** [comment]
@ronakdave195 look at all the token cards which have TokenScript files. Notice that they use the name from the node rather than the name set inside the TokenScript

**Comment by James-Sangalli** [comment]
Duplicate https://github.com/AlphaWallet/alpha-wallet-android/issues/914
