### ISSUE TITLE
Kovan magic link during workshop was malformed

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#823]
you sent me this on telegram: https://kovan.aw.app/AQAAAABdXmK02RXIrTJB9FmkWty7-K9CyqVhoVQAMDAwMA==

Did you truncate it by accident?

**Comment by JamesSmartCell** [comment]
Was probably a debug issue - at that time we were half way through the key refactor. It's fixed now, here's the same token link:

https://kovan.aw.app/AQAAAABdaxrg2RXIrTJB9FmkWty7K9CyqVhoVQCMAe4UMQtjBB9dhWtFHD7kx5cbkmSiZHHh7rKZtUIOE4TkrREcY0aeC8xrB9H-KyQ5pupengHLPZ1dwTfctzuRs=

**Comment by hboon** [comment]
@JamesSmartCell tapping on that link shows “
error: io.stormbird.token.entity.SalesOrderMalformed”. Is that expected?

**Comment by JamesSmartCell** [comment]
Yes because I thought telegram had mangled it so I mistakenly unmangled it, thus breaking it. Try this one. 
https://kovan.aw.app/AQAAAABda18U2RXIrTJB9FmkWty7-K9CyqVhoVQCmCSGVN478Us0tDsqlp-lX6WfArno77FibujWUtsrJoIbYF8Ex4EFHmVvVV-hkpoDe_cePMbhx-V2JV0nARI5yxw=

**Comment by hboon** [comment]
Looks good for me too. Thanks :)
