### ISSUE TITLE
Move the logo higher in Welcome Screen

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#827]
Move the logo higher so it will be in between “Create a new Wallet” and the status bar. The one with black status bar is what you developed. The one with “x” is how I imagine this.

<img width="410" alt="Screen Shot 2019-08-26 at 10 48 33 AM" src="https://user-images.githubusercontent.com/51817359/63666895-f0ab7d00-c7fb-11e9-9242-40f5e3060f30.png">

![2019-08-26 12 48 45](https://user-images.githubusercontent.com/51817359/63666966-454ef800-c7fc-11e9-919c-25bbd59f324e.png)

**Comment by JamesSmartCell** [comment]
Moved.
