### ISSUE TITLE
Add an arrow to tooltips, align the text to center

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#828]
I would add the arrow right below the tooltip white screen. I know it might be difficult to implement, but this is necessary. Otherwise it’s like pointing out something without using a finger. 

![2019-08-26 12 54 34](https://user-images.githubusercontent.com/51817359/63667019-80e9c200-c7fc-11e9-89d0-fc186ca124d5.png)

Please align the text to the centre.

<img width="399" alt="Screen Shot 2019-08-26 at 11 01 35 AM" src="https://user-images.githubusercontent.com/51817359/63667029-89da9380-c7fc-11e9-881c-c7b24c0eaefc.png">

The semi-transparent dark background is set to 40% opacity.

---

This is the one worth discussing. I would prefer to keep “Back up your wallet” tooltip more than “Find your address here”. I have an assumption that it might be confusing to be prompt to see the address in “Settings” and then welcomed by big red warning about backup.

<img width="412" alt="Screen Shot 2019-08-26 at 11 13 06 AM" src="https://user-images.githubusercontent.com/51817359/63667094-b8586e80-c7fc-11e9-981f-a4d2575f93af.png">

**Comment by hboon** [comment]
@JamesSmartCell https://github.com/AlphaWallet/alpha-wallet-ios/issues/1405

**Comment by JamesSmartCell** [comment]
Fixed.
