### ISSUE TITLE
Remove Top App Bar text and background for backup flow

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#829]
The text on Top App Bar is duplicated. If you look at my designs you will find that some screens drop the blue Top App Bar. It has just the back icon (arrow) left. Also, please adjust elements vertically. 

<img width="201" alt="Screen Shot 2019-08-26 at 11 19 14 AM" src="https://user-images.githubusercontent.com/51817359/63667189-08373580-c7fd-11e9-90d5-bb5876faf2ad.png">

![2019-08-26 11 18 40](https://user-images.githubusercontent.com/51817359/63667255-403e7880-c7fd-11e9-9966-939e63cc10ad.jpg)

Please increase “line-spacing” for the “Making backup is very simple… “ text. I set this up to 24 pt.

**Comment by tomekalphawallet** [comment]
Same here, we don’t need Top App Bar here. It is confusing to have two action text at the top. 

![2019-08-26 11 29 45](https://user-images.githubusercontent.com/51817359/63667279-6237fb00-c7fd-11e9-80b2-57382ea837c6.jpg)

**Comment by JamesSmartCell** [comment]
Removed as directed.
