### ISSUE TITLE
Add an option to delete a word from a seed phrase

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#830]
When you make a mistake, and by accident tap the wrong word, you should be able to tap the input field to activate the keyboard and delete the wrong word. 

https://www.dropbox.com/s/27y48380t8i5t26/2019-08-26%2011.32.16.mov?dl=0

**Comment by hellolucas** [comment]
@all-contributors please add @tomekalphawallet for design
