### ISSUE TITLE
Add a feedback after completing the Seed Phrase verification

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#831]
After you enter the last word successfully we also need a feedback (this green checkmark). Then it animates to the next screen where we prompt to upgrade the security.

Right now the transition is too quick. You tap the last word from a seed phrase and you see a completely new screen without any feedback. So you are not sure if you verify the phrase correctly. 

https://www.dropbox.com/s/7r5pc5owxew6bc4/2019-08-26%2011.49.42.mov?dl=0

**Comment by JamesSmartCell** [comment]
Added.
