### ISSUE TITLE
Kill the landscape mode switch when asking for fingerprint

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#832]
When I agreed to “Upgrade my security” I was prompt to use fingerprint sensor. Then, while trying to lift up phone to do so, it switches from portrait mode to landscape and caused an error. The app crashed and I had to start the backup process again.

https://www.dropbox.com/s/tv15b2itakq4n6c/2019-08-26%2011.45.04.mov?dl=0

**Comment by JamesSmartCell** [comment]
Fixed by locking landscape/portrait during signing and fixing the orphaned window view.
