### ISSUE TITLE
Change the copy when requesting for security upgrade

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#833]
Any reason why we change the copy here? I would dropped the Top App Bar and stay with “Lock seed phrase”

<img width="412" alt="Screen Shot 2019-08-26 at 11 39 59 AM" src="https://user-images.githubusercontent.com/51817359/63667591-a4157100-c7fe-11e9-8280-a04a4be2ed6a.png">

![2019-08-26 11 40 11](https://user-images.githubusercontent.com/51817359/63667615-bbecf500-c7fe-11e9-8fe4-3aebb08d620a.jpg)

**Comment by JamesSmartCell** [comment]
The key press text is probably from an older version which hasn't been upgraded yet. I'll update the text. The top bar has been removed too. I'll leave 'Upgrade key security' for upgrading legacy keys.
