### ISSUE TITLE
Input field for account import via seed phrase hidden by keyboard

### ISSUE THREAD

**Issue by d10r** [AlphaWallet/alpha-wallet-android#849]
![Screenshot_20190910-105044](https://user-images.githubusercontent.com/5479136/64599746-3a7a9280-d3ba-11e9-8a51-e439845f7ccf.jpg)

Only if I close the keyboard, the input field becomes visible. Meaning I have to type the seed phrase blindly.

Device: Huawei P10 Lite, 5.1" screen with 1920x1080 px.
OS: Android 8.0

**Comment by JamesSmartCell** [comment]
Closing as fixed.
