### ISSUE TITLE
Account import via seed phrase: should auto-convert to lower-case

### ISSUE THREAD

**Issue by d10r** [AlphaWallet/alpha-wallet-android#850]
When entering a seed phrase for account import, the keyboard is initially set to uppercase (for the first character).  
Also, dictionary based autocomplete for individual words may put words in capitalized forms. This is more likely for languages which use uppercase for nouns. E.g. when entering "arena" on a phone with the keyboard set to German, it's recognized as noun and inserted as "Arena".  

Problem: BIP-39 allows only lowercase characters. The input field for seed phrase should thus auto-convert all chars to lowercase on entry.

**Comment by James-Sangalli** [comment]
@JamesSmartCell this was solved but never tagged in the PR...
