### ISSUE TITLE
Scanning QR code of Metamask account switches network to mainnet

### ISSUE THREAD

**Issue by d10r** [AlphaWallet/alpha-wallet-android#851]
How to reproduce:
In the Wallet tab, choose any network which is not Ethereum mainnet, e.g. Kovan testnet.
Then tap "Send".
In the Send screen, tap the camera icon for scanning a QR code. Now scan the QR code of a Metamask account, e.g. this one:
![image](https://user-images.githubusercontent.com/5479136/64601844-fa1d1380-d3bd-11e9-88df-88b1aad2a032.png)
As soon as the QR code reader returns, the badge at the top right has changed from the selected one (e.g. "Kovan") to "Ethereum":
![image](https://user-images.githubusercontent.com/5479136/64601991-38b2ce00-d3be-11e9-922a-33f6da112e15.png)
This happens silently, without any notice.
After tapping "Next" and then confirming with "Send", the transaction is reported as having failed (Transaction error: insufficient funds...) - in case the account had enough funds on Ethereum mainnet, it would probably execute the transaction on mainnet. I haven't tried that.

The cause here is likely that Metamask formats the QR codes like this: `ethereum:<address>` - no matter which network is selected in Metamask.

In my opinion AlphaWallet should either ignore the network (since the user explicitly made a choice before) or at least warn before switching.

**Comment by hboon** [comment]
FWIW, EIP681 says:

> "chain_id is optional and contains the decimal chain ID, such that transactions on various test- and private networks can be requested. If no chain_id is present, the client's current network setting remains effective."

**Comment by JamesSmartCell** [comment]
The original implementation honoured the EIP681 chain_id, but there appears to be a bug in metamask where it doesn't change the network id in the EIP681 even if you change the chain. Therefore, to avoid user losing funds I will ignore the chainId if the address is scanned from within the send page, since they already selected the network they want to send from using the wallet.
