### ISSUE TITLE
Json keystore can't be imported if it contained a carrier return

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#856]
Since messengers like Singal always adds a carrier return, JSON keystores can't be imported if it is copied from Signal.

**Comment by ronakdave195** [comment]
@James-Sangalli May I kindly request you to provide test steps or more information on the issue so that we can replicate it at our end and provide suggestions for fixes.

**Comment by James-Sangalli** [comment]
@ronakdave195 download signal, export a JSON keystore to a signal message, copy and paste this signal message and use it to import.

**Comment by ronakdave195** [comment]
@James-Sangalli I'm able to import a wallet whose JSON keystore was shared through a Signal messaging app.

**Comment by James-Sangalli** [comment]
@colourful-land please update
