### ISSUE TITLE
Stop serving TokenScript files at `https://repo.aw.app/<contract>`

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#863]
`curl https://repo.aw.app/0xf5dce57282a584d2746faf1593d3121fcac444dc`

returns

```
Network: Ethereum<?xml version="1.0" encoding="UTF-8" standalone="no"?><ts:token xmlns:ts="http://tokenscript.org/2019/05/tokenscript" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" custodian="false" xsi:schemaLocation="http://tokenscript.org/2019/05/tokenscript">
    <ts:name>
```

Notice the spurious leading "Network: Ethereum".

Affects the few files I tried.

**Comment by hboon** [comment]
Ah. It should be `repo.tokenscript.org` instead, which doesn't have this problem. We don't use `repo.aw.app` in our apps anymore. So maybe this issue can be closed.

**Comment by James-Sangalli** [comment]
@colourful-land I deleted the load balancer routing for this but it still works for some reason...

Is it being served elsewhere as well?
