### ISSUE TITLE
Re: Wallet Signing Issues

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#864]
It is currently impossible to produce a valid signature for a 0x protocol order using the Android version of the app.

For whatever reason the iOS version does work using personal_sign but does not on Android.

You can check this at - https://staging.bamboorelay.com/signing.html

In the current state this means users using the Android version of the wallet will be unable to create new 0x orders and unable to fill coordinated 0x orders.

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/alpha-wallet-android/pull/900
