### ISSUE TITLE
Server returns error inside Discovery token card

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#871]
To reproduce, add 0x8C0Edb69eBF038BA0c7a4873E40fC09725064c2e

Code which displays the message: https://github.com/AlphaWallet/TokenScript/blob/master/examples/erc20/AlphaWallet-Discovery-Token/discover.en.shtml#L15

![Screenshot_20190922-160314_AlphaWallet](https://user-images.githubusercontent.com/16630514/65384255-78d16380-dd63-11e9-9c78-e47134d6cce9.jpg)
![Screenshot_20190922-160302_AlphaWallet](https://user-images.githubusercontent.com/16630514/65384257-7a029080-dd63-11e9-9e48-60ef18440b59.jpg)

**Comment by JamesSmartCell** [comment]
Can you clarify what you mean by 'add xxxx'? I tried adding as account and token but both don't give any results. There was an issue with some badly formed script which I've fixed so that's good.

**Comment by JamesSmartCell** [comment]
OK never mind I got it working and reproduce the server error

**Comment by JamesSmartCell** [comment]
It's because of the multiple 'ownerAddress' that's been added. Previously we used this:
```
web3.tokens.data.currentInstance.ownerAddress
```
The one that the script is trying to use is this new one:
```
let suffix = "claimed?userAddress=" + this.props.ownerAddress;
```

I don't have any objection to either, but the same data shouldn't be in two places. If you change it to the new one, then older scripts will break, but providing they're updated then it should be ok to migrate.

**Comment by JamesSmartCell** [comment]
Can we resolve this here rather than a lengthy meeting about it? Much quicker and it's not important enough for discussion.
@hboon @colourful-land

**Comment by James-Sangalli** [comment]
@JamesSmartCell it's supposed to be loaded into props

**Comment by JamesSmartCell** [comment]
Yes, but the point is it should only go in once not twice. Using this works on iOS: 

```
web3.tokens.data.currentInstance.ownerAddress
```

Therefore it must be placed in two areas if both this code and the code in the new script work. It should only be put in one place for consistency.

**Comment by James-Sangalli** [comment]
> Yes, but the point is it should only go in once not twice. Using this works on iOS:
> 
> ```
> web3.tokens.data.currentInstance.ownerAddress
> ```
> 
> Therefore it must be placed in two areas if both this code and the code in the new script work. It should only be put in one place for consistency.

@hboon @colourful-land any thoughts?

**Comment by James-Sangalli** [comment]
@JamesSmartCell its loaded in the constructor:

web3.tokens.dataChanged = (oldTokens, updatedTokens) => {
    const currentTokenInstance = web3.tokens.data.currentInstance;
    document.getElementById('root').innerHTML = new Token(currentTokenInstance).render();
};

constructor(tokenInstance) {
        this.props = tokenInstance;
        this.getStatus();
        this.setOnConfirm();
        this.props.claimed = false;
    }

Cannot see how there is anything wrong with this

**Comment by JamesSmartCell** [comment]
@hboon , we talked about this about a week ago. In the end I used the common value between Android and iOS which is

```
web3.tokens.data.currentInstance.ownerAddress
```

**Comment by James-Sangalli** [comment]
@JamesSmartCell does this mean that a developer cannot create the following

var ownerAddress = "0x00...."
or 
let obj = {}
obj.ownerAddress = "0x00...."?

**Comment by hboon** [comment]
> > Yes, but the point is it should only go in once not twice. Using this works on iOS:
> > ```
> > web3.tokens.data.currentInstance.ownerAddress
> > ```
> > 
> > 
> > Therefore it must be placed in two areas if both this code and the code in the new script work. It should only be put in one place for consistency.
> 
> @hboon @colourful-land any thoughts?

Can you try this: Insert a check for whether it's accessible here:

```
web3.tokens.dataChanged = (oldTokens, updatedTokens) => {
    console.log(web3.tokens.data.currentInstance);// check web3.tokens.data.currentInstance
    const currentTokenInstance = web3.tokens.data.currentInstance;
    document.getElementById('root').innerHTML = new Token(currentTokenInstance).render();
};
```

Note that `dataChanged` might be called several times. If `web3.tokens.data.currentInstance` in the line added above includes `ownerAddress`, then `this.props.ownerAddress` should work.

**Comment by James-Sangalli** [comment]
@JamesSmartCell interestingly, ownerAddress is not defined in the token object either

{name: "AlphaWallet Discovery Token", symbol: "ALP", _count: "1", contractAddress: "0x8c0edb69ebf038ba0c7a4873e40fc09725064c2e", chainId: "1", …}
chainId: "1"
claimed: false
contractAddress: "0x8c0edb69ebf038ba0c7a4873e40fc09725064c2e"
name: "AlphaWallet Discovery Token"
symbol: "ALP"
tokenId: "0"
_count: "1"
__proto__: Object

**Comment by James-Sangalli** [comment]
Fixed in: https://github.com/AlphaWallet/alpha-wallet-android/pull/879
