### ISSUE TITLE
display "server error" on click "Discover DeFi, ETH and DAI"

### ISSUE THREAD

**Issue by lyhistory** [AlphaWallet/alpha-wallet-android#880]
App Version: 2.12.0
Phone model: Huawei P20 Pro
Android version: 9
Reproduce:
> Add contract "0x8C0Edb69eBF038BA0c7a4873E40fC09725064c2e "
> click 1 AlphaWallet Discover(ALP)
> click "Discover DeFi, ETH and DAI"
![image](https://user-images.githubusercontent.com/1522513/65504566-dc8d9500-def9-11e9-91e3-902529fa7ab3.png)
![image](https://user-images.githubusercontent.com/1522513/65504574-e0211c00-def9-11e9-80c5-16a0b9d4c352.png)

**Comment by James-Sangalli** [comment]
@JamesSmartCell this is solved with #879 right? has this been released?
