### ISSUE TITLE
Asking user the PIN when user secured the phone with Pattern

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#889]
On this test phone, the device is secured with a Pattern. The UI is asking for a PIN. When the user click "use pin" he is shown a pattern dialogue.

Should display "use pattern" in this case.

![Screenshot_20190926-171640](https://user-images.githubusercontent.com/548435/65666962-21dcce80-e082-11e9-9121-f489eeb2dd62.png)

**Comment by JamesSmartCell** [comment]
We don't know if it is PIN or Pattern at that stage. Requires a more generic term.
