### ISSUE TITLE
Crash when click the "My Wallet Address"

### ISSUE THREAD

**Issue by bootingman** [AlphaWallet/alpha-wallet-android#899]
Brand: Huawei Device
Model: unknow
Source: collect from WeChat wechat group on Oct 1
Description: runs well with "wallet", "transactions" and "browser", but crashed once click "settings" -> "my wallet address".
Recurrence rate: 100%
Video:
https://1x.alphawallet.com/dl/20191001.mp4

**Comment by James-Sangalli** [comment]
@bootingman could you please try this with the current master branch?

**Comment by James-Sangalli** [comment]
Assuming this is resolved as we haven't hit it
