### ISSUE TITLE
After signing the message for the discovery token, the prompt remains

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#905]
And I cannot leave the screen after the prompt shows up, forcing me to kill the app.

**Comment by justindg** [comment]
Didn't get authorisation due to an error, hence the prompt did not dismiss.

> I/chromium: [INFO:CONSOLE(122)] "Uncaught TypeError: window.web3CallBacks[id] is not a function"

**Comment by James-Sangalli** [comment]
Solved in #912
