### ISSUE TITLE
After doing the "enable" action in compound DAI card, the withdraw/supply screens haven't recognized the change

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#906]
To use Compound tokens you must "approve" the compound contract to move the underlying asset.

E.g. to use compound dai, you must send a transaction to the dai contract to allow you to move the funds.

The tokenscripts I wrote for compound require the user do this first and if they have done so, the screen will refresh and allow them to deposit/withdraw from compound.

The app does not do this refresh however, meaning users can never use compound tokens even if they have approved the contract.

Example: https://etherscan.io/address/0x6ef06a30B895bA2f7407028D99ad7C2dD4B330a7#

**Comment by justindg** [comment]
Seems to be fixed in the current master branch

**Comment by James-Sangalli** [comment]
Solved in #912
