### ISSUE TITLE
Pricing for ETH not working at all 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#907]

**Comment by justindg** [comment]
Any more info?

**Comment by James-Sangalli** [comment]
@justindg open the app and you will see the USD figures are not available for any eth conversions. Probably related #903

**Comment by JamesSmartCell** [comment]
I've been watching this issue for a while - it's caused by the API I was using doing throttling because we're using it without any token.  Fixing this by using a different oracle.
