### ISSUE TITLE
Balance updates then regresses on token cards

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#913]
To reproduce:

1. Call the discovery token and see the proceeds
2. Click on cDAI and enable
3. After enable is confirmed, withdraw the balance.
4. after confirmation, check the balance card in DAI, the main card view will not update but when you click on the card it will, going back and clicking it again will revert back to the old balance rather than the new one which was briefly glimpsed.

**Comment by ronakdave195** [comment]
@JamesSmartCell May I request you to provide more test steps and description here so that we can try to reproduce this at our end to suggest any fixes.

**Comment by James-Sangalli** [comment]
Seems to be solved in #1021 as it now works
