### ISSUE TITLE
TokenScript cards should take the localised name defined in the TokenScript

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#914]
At the moment it is taking the name from the smart contract, instead it should take the name defined in the tokenscript file and fallback to english if the user's language is not there. 

Useful for Devcon because we renamed the discovery card to devcon5 goodies but not a show stopper.

**Comment by ronakdave195** [comment]
@JamesSmartCell May I kindly request you to provide us more information on the working mechanism or workflow about TokenScript.
