### ISSUE TITLE
Travis doesn't build dmz?

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#943]
Seems it doesn't because it didn't spot the bug present in #942 whereby a param was missing in the ParseMagicLink instance

**Comment by JamesSmartCell** [comment]
I forgot to merge the DMZ updates back into the main repo ...

I updated the travis build file to build the alphawallet flavour on the android - you may need to explicitly add each project in.

**Comment by James-Sangalli** [comment]
@JamesSmartCell I believe we never had any travis configurations for either lib or dmz. 

lib should have a travis file on it's own, at least with DMZ it must build before we put it into production otherwise the dmz.jar would be created to begin with...

**Comment by ronakdave195** [comment]
@JamesSmartCell May I request you to confirm if this bug is resolved or is it still open?
