### ISSUE TITLE
Problem bookmarking with mydapps in browser

### ISSUE THREAD

**Issue by jzaki** [AlphaWallet/alpha-wallet-android#947]
- Go to browser tab
- Navigate to any page (eg twitter.com)
- Tap "..." in top right corner, then "Add to My DApps"
  - Title: "Twitter. It's what's happening / Twitter"
  - Address: "https://mobile.twitter.com/"
- Change Title and/or URL, tap done
- Tap "Add" (returns to twitter)
- Tap Browser tab, shows original text. Expect: changed title
- Tap twitter icon, goes to original URL. Expect: changed URL

**Comment by ronakdave195** [comment]
Thanks @jzaki, we were able to reproduce this at our end.

**Comment by JamesSmartCell** [comment]
It's actually a feature not a bug - but if necessary we can remove the restriction of only being able to bookmark dapps.

**Comment by JamesSmartCell** [comment]
I read it wrongly - it is definitely a bug!
