### ISSUE TITLE
able to get to transaction confirmation page with erc721/erc875 assets in watch account

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#951]

**Comment by ronakdave195** [comment]
@JamesSmartCell May I request you to provide test steps and more description here so that we can try to reproduce this at our end to suggest any fixes.

**Comment by James-Sangalli** [comment]
@ronakdave195 watch this account: 0x08D0d733b65321A1e28bD8b6045E59aa11F6Bbe3 and then go to the UEFA tickets (or any other ticket, you must enable xDAI to do this or you can simply try with a starwars ticket) and try to transfer one, it will let you get all the way to the transaction confirmation page and then it will fail as you don't have the corresponding Private key.

To see what it should be like, try it on iOS with the same key.

**Comment by ronakdave195** [comment]
> 0x08D0d733b65321A1e28bD8b6045E59aa11F6Bbe3

Thanks @James-Sangalli for sharing the steps. I tried the same and came across the attached screenshot as the last screen, post that I wasn't able to click on the "Transfer Tickets" button and had to compulsorily "Cancel and Go Back.
![transfer-tickets-failure](https://user-images.githubusercontent.com/54934848/73720418-e943b480-4747-11ea-82cc-a96eebc192b1.jpg)

**Comment by James-Sangalli** [comment]
@ronakdave195 yes, so we need to copy iOS here

**Comment by ronakdave195** [comment]
Ok

**Comment by ronakdave195** [comment]
@James-Sangalli In the iOS version when I go to any of the Star Wars tickets, the Transfer / Redeem button is disabled so I'm able to proceed further.

**Comment by James-Sangalli** [comment]
> @James-Sangalli In the iOS version when I go to any of the Star Wars tickets, the Transfer / Redeem button is disabled so I'm able to proceed further.

As intended, you should only be able to browse the tickets not do anything with them.

**Comment by ronakdave195** [comment]
Thank you for the feedback, @James-Sangalli!
