### ISSUE TITLE
Flip arrows in Transactions Tab

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#969]
**Transaction tab**
 "Sent" with an arrow pointing up on iOS
"Received" with an arrow pointing down on iOS

 "Sent" with an arrow pointing down on Android
"Received" with an arrow pointing up on Android

Suggestion: @JamesSmartCell please align with iOS (Sent with an arrow up, Received with an arrow down)

<img width="952" alt="Screenshot 2019-11-12 at 13 06 20" src="https://user-images.githubusercontent.com/51817359/68635652-5aab0700-054d-11ea-8062-00f8c3aff3ed.png">

**Comment by hboon** [comment]
@tomekalphawallet also appears in a similar manner when viewing native crypto and ERC 20 tokens if those are to be changed for Android or/and iOS.

**Comment by James-Sangalli** [comment]
This is actually done but I don't know where @JamesSmartCell please reference
