### ISSUE TITLE
Inconsistency iOS & Android (All in one)

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-android#970]
AlphaWallet/alpha-wallet-android#969

**Comment by tomekalphawallet** [comment]
https://github.com/AlphaWallet/alpha-wallet-android/issues/971

**Comment by tomekalphawallet** [comment]
https://github.com/AlphaWallet/alpha-wallet-ios/issues/1552

**Comment by colourful-land** [comment]
@JamesSmartCell attention.
