### ISSUE TITLE
Show address under My Wallet Address, hide under Change Wallet

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-android#971]
Show address under My Wallet Address, hide under Change Wallet

Suggestion: @JamesSmartCell please align with iOS. This is where users are looking for their wallet address, so "0x932423432..." under "Change Wallet" might suggest a place where to look for an address. 

<img width="933" alt="Screenshot 2019-11-12 at 13 46 53" src="https://user-images.githubusercontent.com/51817359/68637647-600b5000-0553-11ea-881c-64079107314c.png">

**Comment by hboon** [comment]
Nothing to change
